### ISSUE TITLE
Running via Azure Container Instance

### ISSUE THREAD

**Issue by RezaRahmati** [juice-shop/juice-shop#1055]
Hi

I just created an Azure container instance to run juice shop, the issue is it will start and stop and will be Terminated. 

What I am doing wrong?

I see these in the logs

```
> juice-shop@8.6.0 start /juice-shop
> node app

info: All dependencies in [1m./package.json[22m are satisfied ([32mOK[39m)
info: Detected Node.js version [1mv10.15.3[22m ([32mOK[39m)
info: Required file [1mindex.html[22m is present ([32mOK[39m)
info: Required file [1mmain.js[22m is present ([32mOK[39m)
info: Required file [1mpolyfills.js[22m is present ([32mOK[39m)
info: Required file [1mruntime.js[22m is present ([32mOK[39m)
info: Required file [1mvendor.js[22m is present ([32mOK[39m)
info: Configuration [1mdefault[22m validated ([32mOK[39m)
warn: Dependencies in [1m./frontend/package.json[22m are not rightly satisfied ([31mNOT OK[39m)
warn: @angular-devkit/build-angular: not installed!
warn: @angular/animations: not installed!
warn: @angular/cdk: not installed!
warn: @angular/cli: not installed!
warn: @angular/common: not installed!
warn: @angular/compiler: not installed!
warn: @angular/compiler-cli: not installed!
warn: @angular/core: not installed!
warn: @angular/flex-layout: not installed!
warn: @angular/forms: not installed!
warn: @angular/http: not installed!
warn: @angular/material: not installed!
warn: @angular/platform-browser: not installed!
warn: @angular/platform-browser-dynamic: not installed!
warn: @angular/router: not installed!
warn: @fortawesome/fontawesome-svg-core: not installed!
warn: @fortawesome/free-brands-svg-icons: not installed!
warn: @fortawesome/free-regular-svg-icons: not installed!
warn: @fortawesome/free-solid-svg-icons: not installed!
warn: @nguniversal/express-engine: not installed!
warn: @ngx-translate/core: not installed!
warn: @ngx-translate/http-loader: not installed!
warn: angularx-qrcode: not installed!
warn: core-js: not installed!
warn: flag-icon-css: not installed!
warn: hammerjs: not installed!
warn: ng-simple-slideshow: not installed!
warn: ng2-bar-rating: not installed!
warn: ng2-file-upload: not installed!
warn: ngx-clipboard: not installed!
warn: ngx-cookie: not installed!
warn: ngx-spinner: not installed!
warn: rxjs: not installed!
warn: socket.io-client: not installed!
warn: typescript: not installed!
warn: zone.js: not installed!
warn: Invoke npm install to install missing packages
error: [31mExiting due to unsatisfied dependencies![39m
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! juice-shop@8.6.0 start: `node app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the juice-shop@8.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/juicer/.npm/_logs/2019-05-27T18_43_11_958Z-debug.log 
```

![image](https://user-images.githubusercontent.com/10086092/58435410-69c8f600-808e-11e9-8ded-2b66abc810d3.png)

![image](https://user-images.githubusercontent.com/10086092/58435432-911fc300-808e-11e9-8f4e-49e44ea15d94.png)

**Comment by bkimminich** [comment]
You did not run `npm install` before starting the application. I recommend to use the Docker @ Azure approach described in the README if you keep having issues with manual installation.

**Comment by J12934** [comment]
Same thing happens when the docker image is run locally...

**Comment by J12934** [comment]
@bkimminich I think we should stop trying to stop validating frontend dependencies...

Validating that the `html` & `js` bundle should be enough.

**Comment by RezaRahmati** [comment]
> You did not run `npm install` before starting the application. I recommend to use the Docker @ Azure approach described in the README if you keep having issues with manual installation.

No, (I am new to docker) I thought it will do it by it self or it comes with installed packages

**Comment by bkimminich** [comment]
Yeah, I just tried locally with Docker and ran into the same trap. I'll fix this asap and release v8.6.1 which should be fine on Docker again.

**Comment by bkimminich** [comment]
Fix build is on the way... If DroidEdit didn't mess up the code style, then all should be fine now! 😉

**Comment by RezaRahmati** [comment]
@bkimminich FYI, I am able to host the juice shop docker with "App Services" in Azure and no issue

**Comment by RezaRahmati** [comment]
> Fix build is on the way... If DroidEdit didn't mess up the code style, then all should be fine now! 😉

Incredibly fast

**Comment by RezaRahmati** [comment]
> Fix build is on the way... If DroidEdit didn't mess up the code style, then all should be fine now! 😉

I confirm the issue is solved

![image](https://user-images.githubusercontent.com/10086092/58438746-71909680-809e-11e9-9d5e-a52d459d9f5b.png)
