### ISSUE TITLE
v8.6.2 Darwin_x64, ValidateDependencies.js Unexpected Token

### ISSUE THREAD

**Issue by monokle** [juice-shop/juice-shop#1057]
Hi, thank you for publishing the [latest version](https://github.com/bkimminich/juice-shop/releases/tag/v8.6.2). 
I attempted to intialize the app using `npm start` method on a Mac, and received a js error: "Unexpected token."

`/Users/juiceShop/.Trash/juice-shop_8.6.2/lib/startup/validateDependencies.js:11`
`const validateDependencies = async ({ packageDir = '.', exitOnFailure = true} = {}) => {`
                                                               ` ^`
`SyntaxError: Unexpected token (`
    `at Object.exports.runInThisContext (vm.js:76:16)`
    `at Module._compile (module.js:542:28)`
    `at Object.Module._extensions..js (module.js:579:10)`
    `at Module.load (module.js:487:32)`
    `at tryModuleLoad (module.js:446:12)`
    `at Function.Module._load (module.js:438:3)`
    `at Module.require (module.js:497:17)`
    `at require (internal/module.js:20:19)`
    `at Object.<anonymous> (/Users/juiceShop/.Trash/juice-shop_8.6.2/app.js:1:63)`
    `at Module._compile (module.js:570:32)`

All parentheses and brackets seem to be balanced, but if I can provide anything by way of logs or other information, to help this issue, please let me know.

Any advice appreciated!

**Comment by J12934** [comment]
Hi 👋
Which node version are you using?

**Comment by bkimminich** [comment]
I strongly suspect you have an outdated Node.js version that doesn't allow newer JavaScript syntax. You need the matching Node.js for the ZIP you downloaded (8, 10 or 11).

**Comment by monokle** [comment]
Apologies if I misunderstand the question; on my machine I am using v6.9.2. I went to update it to the latest node version and received a different error but I believe the issue is a version issue on my part. Closing this request since it seems the issue on my end. Thank you for the response!
