### ISSUE TITLE
config > recycle page > product image issue [🐛]

### ISSUE THREAD

**Issue by RezaRahmati** [juice-shop/juice-shop#1068]
# :bug: Bug report

## Description
In the config file if you set url as recycle page images, it won't render correctly

A clear and concise description of the problem...

### Is this a regression?

Not sure

## :microscope: Minimal Reproduction

set the config file like below

```
  recyclePage:
    topProductImage: 'https://securityaccount59.blob.core.windows.net/images/did-you-know.png'
    bottomProductImage: 'https://securityaccount59.blob.core.windows.net/images/recycle.jpg'

```

run the juice shop
navigate to recycle page

## :fire: Exception or Error

the image has source is 
`src="assets/public/images/products/https://securityaccount59.blob.core.windows.net/images/did-you-know.png"`
<pre><code>

</code></pre>

## :deciduous_tree: Your Environment

<pre><code>

</code></pre>

**Comment by bkimminich** [comment]
This is intentional as two of the product images are supposed to be displayed on that page:

![image](https://user-images.githubusercontent.com/3531020/58704136-4c0bd180-83ab-11e9-9370-6c4590e5fa1f.png)

see https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part1/customization.html

**Comment by RezaRahmati** [comment]
@bkimminich 
Thanks for answer, 
so if I customized all of my products and images still it should show that specific images? if it's configurable and hosting via docker how can I replace the images when images are coming from an http link?

**Comment by bkimminich** [comment]
It downloads the product images if you put in a link. So you can then use the file name for the recycling page and it will reuse the downloaded image.

**Comment by RezaRahmati** [comment]
so in my case I only have to set it to `did-you-know.png`?
