### ISSUE TITLE
Although gitHubRibbon is false It shows link to github page in the bottom of score-board [🐛]

### ISSUE THREAD

**Issue by RezaRahmati** [juice-shop/juice-shop#1070]
# :bug: Bug report

## Description
Although gitHubRibbon is false It shows link to github page in the bottom of score-board [🐛]

A clear and concise description of the problem...

### Is this a regression?

Yes, the previous version in which this bug was not present was: `x.y.z`

## :fire: Exception or Error

![image](https://user-images.githubusercontent.com/10086092/58680888-d31f6200-8337-11e9-911d-f8590033a20f.png)

<pre><code>

</code></pre>

## :deciduous_tree: Your Environment

<pre><code>

</code></pre>

**Comment by bkimminich** [comment]
That is intentional. Hiding the GitHub button from the main navbar makes sense for some awareness training settings, but in those the trainer would typically not visit the score board at all.

**Comment by bkimminich** [comment]
On the other hand, we hide the ribbon in the `ctf` theme, and there the score board is part of the setup, so maybe hiding the info box would be better after all... 👍

**Comment by rockydevnet** [comment]
I'll take this on
