### ISSUE TITLE
XSS Vulnerability in register user [🐛]

### ISSUE THREAD

**Issue by rockydevnet** [juice-shop/juice-shop#1081]
# :bug: Bug report

## Description

The register new user page is vulnerable to a persisted XSS injection by setting the email address of a user to a script.

## :microscope: Minimal Reproduction

1. Click Login
1. Click Not yet a customer to go to the registration page
1. Set the email field to `<iframe src="javascript:alert(`xss`)">`
1. Set a valid password
1. Using browser tools, remove the `disabled` attribute from the submit button
1. Submit the new user
1. Login as an admin (via whatever admin login you've found)
1. Go to the administration page
1. When the user list loads, you'll get a JS alert, demonstrating the reflected XSS issue.

Alternatively, just post directly to `http://localhost:3000/api/Users/` with body

```json
  {
    "email":"<iframe src=\"javascript:alert(`xss`)\">",
    "password":"1234567",
    "passwordRepeat":"1234567",
    "securityQuestion":{"id":5,"question":"Maternal grandmother's first name?","createdAt":"2019-06-04T08:51:28.497Z","updatedAt":"2019-06-04T08:51:28.497Z"},
    "securityAnswer":"stdsfg"
  }
```

## :deciduous_tree: Your Environment

Found on the `develop` branch.

**Comment by bkimminich** [comment]
![image](https://user-images.githubusercontent.com/3531020/58893813-1dfef800-86f1-11e9-8e60-52b52e2943d6.png)

**Comment by bkimminich** [comment]
Just reproduced step by step what you wrote and it triggered the _XSS Tier 2_ challenge.
