### ISSUE TITLE
 [🚀] Add a welcome banner

### ISSUE THREAD

**Issue by nilp0inter** [juice-shop/juice-shop#1085]
As a new user entering the Juice Shop front page it is difficult to understand the purpose of the project.

I propose to add a welcome banner to the front page with the following features:

- [x] A brief description of the project.
- [x] A link to the documentation.
- [x] A link to the github page.

Additionally it would be nice to have:

- [x] A "Dismiss" button to make the banner disappear (with that decision reflected in a cookie).
- [ ] An entry in the configuration to allow the user changing the banner text.

**Comment by rockydevnet** [comment]
I'll give this a go...

**Comment by rockydevnet** [comment]
Basic welcome banner now complete. The welcome shows on first load of the site, and will remain until closed at which point it sets a cookie.

<img width="1185" alt="Screenshot 2019-06-06 at 19 35 50" src="https://user-images.githubusercontent.com/4063056/59057466-5b4ebb80-8892-11e9-9ebd-69581281feb4.png">

The content is loaded from translations and allows for customisation of the app name. The description is full innerHtml, so allows for links and paragraphs.

- [ ] Still remaining todo is the option to fully customise the text in config. The idea here would be that the default config would be `null/undefined/emptyString/falsey`, and thus the banner would load content from translations. However, if the config is set, it would load that value. This would allow companies who are customising the app to provide their own introduction content.

**Comment by bkimminich** [comment]
@MarcRler as the welcome banner is part of the navbar, and that changes significantly in `facelift`, would you mind taking a look at the merge conflicts? Also I am failing to apply any background color from the Material theme to the banner, maybe you can figure that out too?

**Comment by bkimminich** [comment]
Remaining work on Welcome Banner to be postponed until _after_ re-merge of `facelift` into main branches to avoid unnecessary merge conflicts.

**Comment by bkimminich** [comment]
Banner text customization will be dropped. When run with a custom theme, it is highly unlikely that someone will accidentally stumble over that application instance and ask themselves "What might this be?" - it should suffice to have the banner in the default theme and turn it off in all other delivered themes. In the eBook it will also be recommended to turn it off in individual themes where hiding the ties to Juice Shop is a goal.
