### ISSUE TITLE
Re-triggering challenge notifications in CTF mode not consistent [🐛]

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1088]
# :bug: Bug report

## Description

Running in `NODE_ENV=ctf` mode and clicking the "Solved"-button for a challenge to re-trigger its notification box, doesn't work consistently:

1. Re-triggering the same notification that was last shown does not show the notification until the next `F5` refresh
2. Flipping between two or more challenges when re-triggering notifications makes them immediately appear

**Comment by J12934** [comment]
Closed by #1089
