### ISSUE TITLE
Challenge Refactoring [🚀]

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1093]
* [x] Remove all "Tier ..." parts from challenge names and rename appropriately, e.g.
  * "XSS Tier 0" will become "Reflected XSS"
  * "XSS Tier 1" will become "DOM XSS"
  * "XSS Tier 1.5" will become "Legacy XSS" etc.
* [x] Change name/description/hint to be more consistent regarding usefulness, e.g.
  * "Wherever you go, there you are" will become "Enforce a redirect to a page you are not supposed to redirect to"
* [x] Remove labels for :star: to :star::star::star::star::star::star: completely
* [x] Merge the 6 tables back into 1 and add :star:-rating as column "Difficulty"

💡 Introduce new categories trying to remove/reduce no. of challenges in vague categories like "Roll your own Security", e.g.
  * Insecure Redirects
  * Policy stuff (GDPR, security.txt etc.)

:information_source: Keep separate filtering by stars and category
:book: Follow-up: Update eBook to reflect changes in Score Board and in categorization

**Comment by bkimminich** [comment]
@MarcRler if you did not touch the Score Board yet in `facelift`, should I do the mentioned changes in `develop` so you can base any design improvements on top of the changes mentioned in this ticket?

**Comment by bkimminich** [comment]
Tables are merged back into one. This unfortunately didn't exactly make the render performance any better... 😞 ... I can confidently say that the culprit for the sluggishness is the `status` column with its crazy show/hide conditions for buttons and tooltips. When I switched the column to just display the solved status as text, the Score Board loaded in 1 - 1.5sec with all difficulties and categories displayed.

![image](https://user-images.githubusercontent.com/3531020/59372168-2f767e80-8d47-11e9-9727-7cf46067e255.png)

**Comment by bkimminich** [comment]
You can find a proposal for the new challenge descriptions, names and categories here:
 http://juice-shop-staging.herokuapp.com

Any feedback is welcome! Personally I'm not so happy with _Feeble Policies_ but couldn't come up with anything better... Ideas welcome!

**Comment by MarcRler** [comment]
Would it actually be conceivable to implement the scoreboard with tabs. So per severity 1 tab. The filters would then have to be implemented somehow differently or perhaps also omitted.

**Comment by bkimminich** [comment]
We actually try to reduce the importance of the difficulty levels down to "just another column that can be filtered" - as it is somewhat subjective how difficulty challenges are perceived. Tabs would make difficulty again a more central aspect, like the old 6 collapsible tables did.
