### ISSUE TITLE
 [🐛] Redirects Tier 2 HTTP Parameter Pollution

### ISSUE THREAD

**Issue by tomwalton78** [juice-shop/juice-shop#1101]
# :bug: Bug report

## Description

I have found that the Redirects Tier 2 challenge can be completed via HTTP parameter pollution as follows:
GET http://localhost:3000/redirect?to=http://www.example.com/&to=https://gratipay.com/juice-shop HTTP/1.1

Since I did not see this mentioned in the solutions I thought I would mention it in case this is not supposed to be possible.

### Is this a regression?

N/A

## :microscope: Minimal Reproduction

GET http://localhost:3000/redirect?to=http://www.example.com/&to=https://gratipay.com/juice-shop HTTP/1.1

## :fire: Exception or Error

<pre><code>

</code></pre>

## :deciduous_tree: Your Environment

Docker

<pre><code>

docker run -d -p 3000:3000 bkimminich/juice-sho
</code></pre>

**Comment by bkimminich** [comment]
It looks like HPP being the underlying vuln, but it's not. It's totally okay to work for solving though, as it coincidentally also triggers the mistake in the URL validation the developers made.

I suppose if you flip the order of the params you don't get the challenge solved and are redirected to the allowed page, right?

**Comment by tomwalton78** [comment]
When I flip the order:
http://localhost:3000/redirect?to=https://gratipay.com/juice-shop&to=http://www.example.com/
the URL becomes this: https://gratipay.com/juice-shop,http://www.example.com/
and I get 404 File Not Found error

**Comment by bkimminich** [comment]
Gratipay is out of business. The corresponding Redirect Tier 1 challenge was actually changed recently for that reason.

**Comment by bkimminich** [comment]
So far I see no unexpected behavior in anything you described.
