### ISSUE TITLE
Error In Browser Console on facelift branch[🐛]

### ISSUE THREAD

**Issue by agrawalarpit14** [juice-shop/juice-shop#1109]
# :bug: Bug report

## Description

Error in console
<img width="402" alt="Screenshot 2019-06-11 at 5 27 28 PM" src="https://user-images.githubusercontent.com/35000671/59270331-d76c4900-8c6e-11e9-8f54-8b40110ed420.png">

### Is this a regression?

Yes

## :microscope: Minimal Reproduction

This error can be observed in the browser console by following steps:
- Go to `http://localhost:4200/#/`
- Login to the app.
- Refresh the page.(Try the step more than once if error is not observed)

**Comment by agrawalarpit14** [comment]
The error also persists in `gsoc2019` branch. Post facelift merge, I suspect.😛

**Comment by MarcRler** [comment]
The bug should be fixed with the next PullRequest in the Facelift Branch. The problem was that the dialog was always opened independently of the cookie and then closed in the next step after checking the cookie.

`welcome.component.ts`

```
ngOnInit (): void {
    this.configurationService.getApplicationConfiguration().subscribe((config: any) => {
      if (config && config.application && !config.application.welcomeBanner) {
        return
      }
      this.dialog.open(WelcomeBannerComponent, {
        minWidth: '320px',
        width: '35%',
        position: {
          top: '50px'
        }
      })
    }, (err) => console.log(err))
  }
```
&&

`welcome-banner-component.ts`
```
ngOnInit (): void {
    let welcomeBannerStatus = this.cookieService.get(this.welcomeBannerStatusCookieKey)
    if (welcomeBannerStatus === 'dismiss') {
      this.dialogRef.close()
    } else {
      this.configurationService.getApplicationConfiguration().subscribe((config) => {
        if (config && config.application) {
          if (config.application.name !== null) {
            this.applicationName = config.application.name
          }
        }
      }, (err) => console.log(err))
    }
  }
```

The problem has been fixed by now checking the cookie before opening the dialog.

`welcome.component.ts`
```
ngOnInit (): void {
    let welcomeBannerStatus = this.cookieService.get(this.welcomeBannerStatusCookieKey)
    if (welcomeBannerStatus === 'dismiss') {
      return
    } else {
      this.configurationService.getApplicationConfiguration().subscribe((config: any) => {
        if (config && config.application && !config.application.welcomeBanner) {
          return
        }
        this.dialog.open(WelcomeBannerComponent, {
          minWidth: '320px',
          width: '35%',
          position: {
            top: '50px'
          }
        })
      }, (err) => console.log(err))
    }
  }
```
