### ISSUE TITLE
Refactor Hacking Instructor for Facelift [🔧]

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1110]
Due to some renamed/changed UI elements (e.g. search mechanism working differently now) the two Hacking Instructor scripts (`localXss.ts` and `loginAdmin.ts`) do not work as intended on branch `facelift`.

> ~The branch `facelift` should soon be merged back into `develop` to avoid permanent back-and-forth merges as well as fixes for soon-gone UI elements on the Score Board.~ _Done!_

**Comment by bkimminich** [comment]
Marked as _Critical_ now that the `facelift` branch was merged into `develop`.

**Comment by J12934** [comment]
Can take a look at it tommorow
