### ISSUE TITLE
Alternation solution for XSS Tier 1.5

### ISSUE THREAD

**Issue by snarque** [juice-shop/juice-shop#1124]
Being a novice regex-er, I triggered the XSS warning (but not the flag) with the following:
<script>X<<script>Xs<script>Xc<script>Xr<script>Xi<script>Xp<script>Xt<script>X>alert(`xss`)</script>

Shouldn't that count?

**Comment by bkimminich** [comment]
There's probably a million possible attack payloads that will cause successful XSS, but it's impossible for the application to recognize which ones work and which ones don't. This is why we have to prescribe a single specific payload for solving the challenge on the Score Board.
