### ISSUE TITLE
Welcome message displays link to juice-shop in ctf mode [🐛]

### ISSUE THREAD

**Issue by RezaRahmati** [juice-shop/juice-shop#1155]
# :bug: Bug report

## Description

The new version display a welcome message containing link to juice-shop even when it's running in ctf mode

![image](https://user-images.githubusercontent.com/10086092/60854859-afb9c380-a1cf-11e9-9143-2be5a74969cb.png)

### Is this a regression?

Yes, in the previous versions this bug was not present 

## :microscope: Minimal Reproduction

run a new instance from docker hub

## :fire: Exception or Error

<pre><code>

</code></pre>

## :deciduous_tree: Your Environment

<pre><code>

</code></pre>

**Comment by RezaRahmati** [comment]
I found new "hideWelcome" in the config file, and issue is solved, please close this bug

**Comment by J12934** [comment]
Oh good catch 👍
I think the `hideWelcome` option should have been set to false in the ctf config files. 
Do you want to send a small pr setting these configs to false in the ctf config files?

**Comment by bkimminich** [comment]
`hideWelcome` should be `showWelcome` and set to `false` in CTF mode, that's true.

**Comment by bkimminich** [comment]
Ah, just realized the banner needs fundamental changes. The way the app name is configured would need similar rewording as on the basket screen.

@RezaRahmati you should turn off the banner completely for your use case, I guess.

**Comment by RezaRahmati** [comment]
@bkimminich thanks, by "banner" do you mean "Welcome"?

**Comment by bkimminich** [comment]
Yeah, best set `hideWelcome: true` in your config for now.

**Comment by bkimminich** [comment]
Welcome banner was refactored for v9.0.0 so its text can now be configured completely. It cannot be translated any more, though. Turning it off completely is still possible: `application.welcomeBanner.showOnFirstStart: false`
