### ISSUE TITLE
MIME Type problems of scripts

### ISSUE THREAD

**Issue by DinoJay** [juice-shop/juice-shop#117]
Hey Björn,

first of all, thank you for crafting this really helpful problems. Unfortunately, I run into problems when I try execute the app.
This is my error log given by chrome:

---

Refused to execute script from 'http://localhost:3000/bower_components/underscore/underscore.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:3000/bower_components/string/lib/string.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:3000/bower_components/moment/min/moment.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:3000/bower_components/jquery/dist/jquery.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:3000/bower_components/bootstrap/dist/js/bootstrap.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:3000/bower_components/angular/angular.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:3000/bower_components/angular-route/angular-route.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:3000/bower_components/angular-cookies/angular-cookies.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:3000/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:3000/bower_components/angular-touch/angular-touch.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:3000/dist/juice-shop.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

---

Can you tell me what I have to change in the code to make it run?

Thank You and best regards!
Jan

**Comment by bkimminich** [comment]
Hi Jan! Can you tell me when this exception actually happens? Immediately when you open `localhost:3000` after doing `npm install` and `npm start`? Or when you open a specific URL?

**Comment by DinoJay** [comment]
it happens exactly after I did 'npm start' and try to open 'localhost:3000'.

**Comment by bkimminich** [comment]
Looks like your browser is trying to apply the `nosniff` header. Strange thing is, that those Bower modules should not return HTML. Maybe they do, because they are _missing_? You did definitely have a successful `npm install` run before you start the server? Could you try using the latest ZIP release (on Windows) instead and see if the problem persists? Just unzip it and run `npm start` because it has everything pre-installed.

**Comment by DinoJay** [comment]
mmh, unfortunately, I'm not a windows user (Ubuntu 12.10), so I can't test the other version. I cloned again the repo and reinstalled the node modules but the errors persist. Any other hint?

**Comment by bkimminich** [comment]
Sorry, I cannot reproduce this problem. If you are sure that `npm install` went through without any issues, then it should run. It does in fact work on Ubuntu and other Linux distros. My best guess now would be some overzealous Chrome plugin like NoScript? If you try the Docker image instead and get the same issue, it definitely is your system or browser that's causing the issue.

**Comment by scull06** [comment]
I have the same problem with 2.0.2 version
