### ISSUE TITLE
 ⭐ Using SQL Injection, Generate a Signed JWT Token for a Non-Existent User with Admin Privileges

### ISSUE THREAD

**Issue by ShepardToTheStars** [juice-shop/juice-shop#1194]
# :star: Challenge Idea
I stumbled upon this while solving another challenge. I didn't get credit for any challenge so it might be cool to add this. A link to my write up is in the [Possible Attack Flow](#possible-attack-flow).

### Description
Using SQL injection, get a signed JWT token for a non-existent user with admin privileges.

*This differs from all of the other SQL injection challenges because instead of logging in as a user, you are creating a 'faux' user that doesn't actually exist in the database at all. It also differs from the JWT challenges because it actually is a properly signed token that you get from the application itself.*

Challenge could be complete if a token is generated via SQL injection for an email like the other ones in the JWT challenges, and that user does not exist in the database.

### Underlying Vulnerability/ies
SQL Injection - using UNIONs and schema exposure techniques
Debug Information Exposure

### Expected difficulty
I was working through level 3 challenges when I stumbled upon this. It does require knowledge of some SQL things that you don't usually see in injection payloads (common ones anyways). It's definitely more complicated that level 3 is, and seems like the amount of work you would use for a level 4 challenge. I haven't attempted any level 5 challenges yet, so I don't have the best baseline for their difficulty.

:star::star::star::star:

### Possible Attack Flow
I have written up how I my method in my personal repos. You can [find it here](https://github.com/vlouwagie/ctf/tree/master/owasp-juice/bonus/nonexistent-user-admin-token).

Let me know what you think!

**Comment by bkimminich** [comment]
Thanks for your idea! By conicidence, in the soon-to-be-released v9.0.0 there'll be a new :star::star::star: challenge asking to retrieve the DB schema from the DB via SQL Injection! 👍 ... It expects you to load the right column of the schema table that all SQLite DBs use to save their `CREATE TABLE` statements and essentially bootstrap themselves. You can find the corresponding step-by-step guide here: https://github.com/bkimminich/pwning-juice-shop/blob/develop/appendix/solutions.md#exfiltrate-the-entire-db-schema-definition-via-sql-injection

As we do have a challenge asking to register a new admin user already and both JWT challenges demand to use user emails which do not exist in the database, I'd find it hard to formulate and _programmatically verify_ another challenge which combines both of these requirements.

**Comment by ShepardToTheStars** [comment]
No problem. You could also drop the admin privileges part if that would make it easier to check for. The challenge would just be '*Generate a signed JWT token for a non-existent user using SQL injection*' or something like that.

Either way, I just thought I'd post what I found, in case you did want to incorporate it. No worries if you end up just closing this issue.

**Comment by bkimminich** [comment]
No, I really like the challenge, I'm just not sure I could enforce the SQLi path in verifying the solution. Look, this is how the JWT challenges get validated:

```javascript
exports.jwtChallenges = () => (req, res, next) => {
  if (utils.notSolved(challenges.jwtUnsignedChallenge)) {
    jwtChallenge(challenges.jwtUnsignedChallenge, req, 'none', /jwtn3d@/)
  }
  if (utils.notSolved(challenges.jwtForgedChallenge)) {
    jwtChallenge(challenges.jwtForgedChallenge, req, 'HS256', /rsa_lord@/)
  }
  next()
}

function jwtChallenge (challenge, req, algorithm, email) {
  const decoded = jwt.decode(utils.jwtFrom(req), { complete: true, json: true })
  if (hasAlgorithm(decoded, algorithm) && hasEmail(decoded, email)) {
    utils.solve(challenge)
  }
}
```

_JWT Tier 2_ is all about changing the algorithm, so in your hack the algo would be the normal `RS256`. I guess if I also check that no user with the expected email (e.g. `inj3ct0r@juice-sh.op`) exists in the DB but the JWT is `RS256` signed, this would match your attack scenario, right?

**Comment by bkimminich** [comment]
~~I think this might be more of a :star::star::star::star::star: if we don't spoiler the SQLi approach in the mouseover-hint. Maybe just: "Try to make up a user record out of thin air." And then "Try to make SQL Injection do all of the work for you" could be a hint in the ebook?~~

Probably better to go with :star::star::star::star: and put the challenge into the _Injection_ category right away. I can't think of any other way to solve this witout having the actual private RSA key used for the tokens, and as that is hard-coded on the server side and not exposed anywhere, we maybe don't want to mislead anyone into other approaches than SQLi...

**Comment by ShepardToTheStars** [comment]
Woah! Spoilers! 😛 (just kidding)

Would it make sense to add it to the [login challenge checks](https://github.com/bkimminich/juice-shop/blob/9cf7373b6fd75483fa106595b506a8f9be97adb4/routes/login.js#L77)?

```
  function verifyPostLoginChallenges (user) {
    if (utils.notSolved(challenges.loginAdminChallenge) && user.data.id === users.admin.id) {
      utils.solve(challenges.loginAdminChallenge)
    } else if (utils.notSolved(challenges.loginJimChallenge) && user.data.id === users.jim.id) {
      utils.solve(challenges.loginJimChallenge)
    } else if (utils.notSolved(challenges.loginBenderChallenge) && user.data.id === users.bender.id) {
      utils.solve(challenges.loginBenderChallenge)
    } else if (utils.notSolved(challenges.ghostLoginChallenge) && user.data.id === users.chris.id) {
      utils.solve(challenges.ghostLoginChallenge)
    }
```

You could add another `else if` in there that checks for

- If the challenge is not yet complete
- Re-query the SQLite database for the user's `id`/`email` in the user object. If the `email`/`id` does not exist, then the challenge would be complete (since the PostLogin happens after a successful login).
- (optional) Could even check for if the `user.data.isAdmin === true` if you want to include that in this.

**Comment by bkimminich** [comment]
Yeah, you're right, that's much easier as the whole JWT part is not really a "challenge" but just happens by accident as the application normally issues the token. I'll make this about the new accountant role instead of admin, as we have one challenge about that already:

```yaml
-
  name: 'Ephemeral Accountant'
  category: 'Injection'
  description: 'Log in with the (non-existing) accountant <i>acc0unt4nt@juice-sh.op</i> without ever registering that user.'
  difficulty: 4
  hint: 'Try to create the needed user "out of thin air".'
  hintUrl: 'https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/v/develop/part2/injection.html#log-in-with-the-non-existing-accountant-without-ever-registerin-that-user'
  key: ephemeralAccountantChallenge
```

**Comment by ShepardToTheStars** [comment]
👍 Happy to help! Let me know if you want me to do any of the grunt work. Looks pretty straight-forward after the conversation above.

**Comment by bkimminich** [comment]
Ah sorry, I already implemented it while we were discussing it... 😁

If you shoot me an email with your post address I'm more than happy to send you some stickers and other swag for this nice new challenge idea! 📮
