### ISSUE TITLE
 [🐛] Payment process not completable when adding funds to wallet

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1197]
* [ ] When you fill money into your Wallet during checkout, it does not allow you to finish checkout
* [ ] Complete/fix redirect dependencies between wallet and payment component
* [ ] Unused properties (`allowContinue` and `redirectToBasket`) in payment component

**Comment by alejandrosaenz117** [comment]
>     * [ ]  Unused properties (`allowContinue` and `redirectToBasket`) in payment component

Could you elaborate on this point?  Should these properties be removed or should it be referenced?

**Comment by bkimminich** [comment]
That's a question @agrawalarpit14 should best answer, as he built that feature. In the end the functionality should be fixed, and by doing so those properties will either become used or simply vanish if not needed for the solution.

**Comment by alejandrosaenz117** [comment]
I can take a look.  Could you assign it to me, please?

**Comment by bkimminich** [comment]
Sure, take a shot at it! Assigning doesn't work on GitHub issues, though.

**Comment by J12934** [comment]
> 
> 
> Sure, take a shot at it! Assigning doesn't work on GitHub issues, though.

It does ;)

**Comment by bkimminich** [comment]
Ooh, back in my days (👴) it only worked for issue opener and project collaborators...

**Comment by bkimminich** [comment]
Just tested the checkout - now you can basically fill your wallet "for free" during the checkout... 🤑 ... also, on the regular http://localhost:3000/#/wallet screen you can just add funds, which will be added immediately w/o sending you through payment while then redirecting you into the middle of the checkout - even if your basket is currently empty.

**Comment by alejandrosaenz117** [comment]
Ah yeah, that was my concern when I opened the PR.  I guess I made it _more_ intentionally vulnerable.  Looks like it is already merged, did you want to revert that PR?

**Comment by bkimminich** [comment]
I already made a reverse commit, so it's back to square zero.
