### ISSUE TITLE
 [🐛] Issues with "Confidential Document" challenge

### ISSUE THREAD

**Issue by tinyweasel** [juice-shop/juice-shop#1202]
# :bug: Bug report

## Description

Firefox can't seem to natively open md files on Ubuntu, it asks to download the file. I enabled an addon to open the acquisitions.md file, but this does not get detected as a solution, nor does downloading the file, so I can't solve the 'Access a confidential document' challenge, even though I can read it.

### Is this a regression?

This is not a version issue, this is an OS/browser issue.

## :microscope: Minimal Reproduction

Using Firefox 68.0.2, on Ubuntu 18.04, visit localhost:3000/ftp/acquisitions.md

## :fire: Exception or Error

<pre><code>

</code></pre>

![image](https://user-images.githubusercontent.com/9930651/69156583-8e50d880-0adb-11ea-9d18-75ccab30db68.png)

## :deciduous_tree: Your Environment

<pre><code>

</code></pre>

### Additional Information

Using Firefox 68.0.2, on Ubuntu 18.04. Works on Firefox on Windows.

**Comment by J12934** [comment]
Hi 👋

Visiting `/ftp/legal.md` isn't actually supposed to solve the "Read our privacy policy" challenge.

**Comment by bkimminich** [comment]
You basically answered it yourself in https://github.com/bkimminich/pwning-juice-shop/issues/43 ... ;-)

**Comment by tinyweasel** [comment]
I'm an idiot today. :smile:

**Comment by tinyweasel** [comment]
This is happening me again even with clicking acquisitions.md, it's trying to download the file and not detecting it as a solution.

**Comment by tinyweasel** [comment]
Edited to reflect correct doc.

**Comment by bkimminich** [comment]
The Juice Shop doesn't care what your browser or OS is doing,as long as it receives a request for that file's URI, the challenge will trigger. You checked the Score Board, I assume? As it's not in the Angular UI sometimes the instant notification bubble is swallowed.

**Comment by tinyweasel** [comment]
Thanks, yeah that's what happened. I'll stop getting confused by this easy challenge at some point, hopefully. :)
