### ISSUE TITLE
Deploy to heroku doesnt work [🐛]

### ISSUE THREAD

**Issue by pendragonn** [juice-shop/juice-shop#1212]
When clicking on deploy heroku button i get a screen saying:

A valid GitHub directory could not be found.

The given URL (https://heroku.com/) is not a valid GitHub repository.

**Comment by bkimminich** [comment]
You are on https://github.com/bkimminich/juice-shop and when you click the Deploy to Heroku button you get that error? I'm just redirected to Heroku login/sign-up.

**Comment by pendragonn** [comment]
Yep, if i am not logged in then i would be redirected to login/sign-up

This is the url that i have:
https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fheroku.com%2F&template=https%3A%2F%2Fheroku.com%2F

**Comment by bkimminich** [comment]
I get https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fbkimminich%2Fjuice-shop%2Fblob%2Fmaster%2FREADME.md&template=https%3A%2F%2Fgithub.com%2Fbkimminich%2Fjuice-shop%2Fblob%2Fmaster%2FREADME.md as would be expected. Must be some issue on your end. Maybe try different Browser?

**Comment by pendragonn** [comment]
Im using Brave, i tried deactivating the "shields" but it didnt work. in fact it works with chromium. Thanks

**Comment by Techbrunch** [comment]
Same as #1193
