### ISSUE TITLE
Install problem [❓]

### ISSUE THREAD

**Issue by olJosiahlo** [juice-shop/juice-shop#1219]
Hello, 

I'm having an issue running the npm start command.  After an install i get this when i try to start

![Capture](https://user-images.githubusercontent.com/19878543/65089004-777df080-d989-11e9-9a08-961c2e565db8.JPG)

I am running the latest version of kali linux and version 10 of node js Thank you!!!

**Comment by bkimminich** [comment]
If you cloned the repo and ran `npm install` please check the log, as there must have been an error during the frontend part.

On Linux it's probably a file/folder permission problem or the Node installation itself causing trouble.

Please try using a pre-packaged archive from the GitHub release page or the Docker image as an alternative.
