### ISSUE TITLE
Issue installing Juice Shop from sources on fresh Debian 10 install [🐛]

### ISSUE THREAD

**Issue by NinjaJc01** [juice-shop/juice-shop#1238]
# :bug: Bug report

## Description

Having tried to install the project from sources, running `npm start` gives me an uncaught promise stating a missing file. The source file is there, but the destination filepath is not.
![juiceshop issue](https://user-images.githubusercontent.com/20073818/66874438-00954100-efa3-11e9-9dd7-6549b4b14a69.PNG)

### Is this a regression?

Presumably, this worked in an older version.

## :fire: Exception or Error

<pre><code>

</code></pre>

## :deciduous_tree: Your Environment

<pre><code>

Node v12.11.1, NPM 6.11.3
</code></pre>

### Additional Information
N/A

**Comment by bkimminich** [comment]
You obviously didn't run `npm install` or it failed for some reason. Also you might miss some files as the one reported as missing exists on GitHub, so maybe not even your `git clone` passed. Please recheck your setup and if problems persist please ask for help on http://gitter.im/bkimminich/juice-shop.

**Comment by KamilWowra** [comment]
try this

> yarn add electron-rebuild --dev
> yarn add sharp
