### ISSUE TITLE
File access challenge solvable using path traversal

### ISSUE THREAD

**Issue by manuteleco** [juice-shop/juice-shop#124]
Hi,

I've just noticed that getting `eastere.gg`, `package.json.bak` or `coupons_2013.md.back` using path traversal works (example: `http://localhost:3000/public/images/%2e%2e%2fftp/eastere.gg`) but doesn't qualify towards solving the challenge. Is this intentional (I couldn't find any mention to this in the docs/issues)? Otherwise I see 3 options:
- Make it count towards solving the challenge.
- Make it count, but as a different new challenge.
- Fix it so that path traversal isn't successful any more.

Regards,
Manu.

**Comment by bkimminich** [comment]
Thanks for sharing your find! Path traversal was unintentional. I'll probably add it as a separate challenge instead of preventing it. The more the merrier... :-)

**Comment by bkimminich** [comment]
Decided to prevent directory traversal by moving the `ftp` folder out of `app/public` to prevent `express.static` from handling it. I still consider adding another _explicit_ file retrieval challenge as described in #120.
