### ISSUE TITLE
 [🐛]Keyfile for the 'Login Support Team' was changed without updating the keepass database

### ISSUE THREAD

**Issue by jamiemcgregor** [juice-shop/juice-shop#1241]
# :bug: Bug report

## Description
The JPEG key file used for the 'Login Support Team' challenge was changed during the perf(elements): Optimizing the images* Pull Request (https://github.com/bkimminich/juice-shop/commit/caa3413c9319126257f9005c7e5b5cfe2ce82a3e#diff-72860628be745e6e35f66b3468f16c1c)

##Key-File
https://github.com/bkimminich/juice-shop/commits/master/frontend/src/assets/public/images/carousel/6.jpg

The keePass database file should be updated to use the optimised JPEG or the 6.jpg file reverted.

![image](https://user-images.githubusercontent.com/9799377/67401717-73a44600-f5a7-11e9-97be-058a95028a41.png)

### Is this a regression?
it would have worked in versions previous to Jun 12, 2019

## :microscope: Minimal Reproduction
Attempt to unlock the keePass database file using the current version of the 6.jpg carousel image

## :deciduous_tree: Your Environment
Docker

**Comment by bkimminich** [comment]
Oh wow, that's a great find, thank you! I doubt I would ever have noticed it myself, and probably not made that connection to the image optimization! 👍

**Comment by jamiemcgregor** [comment]
I've updated the KeePass database and can open a pull request if would like me to?

**Comment by bkimminich** [comment]
Yeah, please do! And send me your post address so I can send some stickers & swag your way! :100:
