### ISSUE TITLE
Enhancements Hacking Instructor [🚀]

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1247]
## Possible enhancements for the [Hacking Instructor](#440)

1. [x] **Are the tutorial scripts part of the `main.js`?** This would allow e.g. CTF-participants to very easily cheat even when the tutorial mode is turned off via configuration. Could scripts be lazily loaded from server be an option?
2. [x] ~~**Translatable tutorial texts!** Texts would have to be loaded from e.g. CrowdIn (which would make them less easy to write and deploy due to that additional dependency) but this might increase the beginner friendliness even more. There should be one folder per tutorial in `i18n` so the JSON files do not get mixed up too easily.~~ _Dropped until more scripts are available and stable enough._
3. [x] **Configurable helper avatar!** Custom themes could use the angry wasp, original Clippy or any other image.
4. [x] ~~**Apply theme color scheme** to the text bubble.~~
5. [x] ~~**Click-to-fill** convenience feature! Click on e.g. the payload to automatically put that value into the expected input field. Avoids accidentally skipping a step when trying to copy&paste a payload from the speech bubble.~~

(Initial collection extracted from https://github.com/bkimminich/juice-shop/issues/440#issuecomment-499364688)

**Comment by bkimminich** [comment]
Made text bubbles 10% transparent so the blue color should work on all themes somewhat...

**Comment by bkimminich** [comment]
Set all steps where user input is expected to `unskippable: true` so that selecting & copying from the text bubble should be possible now.

**Comment by bkimminich** [comment]
Idea: Wrapping all its functionality into a `HackingInstructorModule` should allow to externalize it into its own `.js` file during `ng build`, and then subsequently setting it up for lazy loading - or not loading at all if the feature is turned off... ... As I never wrote my own module for Angulat, this might require some investigation or help... 😁

**Comment by J12934** [comment]
I can look into making it load lazily.
Also not quite sure how to best do it in Angular, but might just work with the default webpack lazy loading mechanisms (Using `import('...')` instead of the `import` keyword) as the Hacking Instructor is mostly angular independent.

**Comment by bkimminich** [comment]
https://webpack.js.org/guides/lazy-loading/
https://angular.io/guide/router#milestone-6-asynchronous-routing
