### ISSUE TITLE
 [⭐] Add basic RSA challenge

### ISSUE THREAD

**Issue by jainendra** [juice-shop/juice-shop#1256]
# :star: Challenge idea
Brute force attack on plain RSA

### Description
TLDR; Decrypt the RSA encrypted document using brute force attack.

**What** - In this challenge we want to show that plain RSA (no padding) encryption is easily breakable similar to other techniques using brute force. 

**Why** - All cryptographic challenges in juice shop are based of some x vulnerability in libraries or the implementation. This is to cover the basics of RSA and will help all who are starting with data encryption.

**How** - An encrypted document file in the ftp location along with the program that encrypted the file. The program contains the public keys i.e N and e. The attacker need to get access to the program and encrypted document using null byte injection and then apply brute force to decrypt. 

Consider a scenario where a developer wrote a python script `encrypt.py` to encrypt document/s stored on the server. The developer ran the script and encrypted the document and deleted the script. However the compiled version of the script `encrypt.pyc` remained on the server.
The attacker finds out encrypted document in the ftp location and looks further finds the compiled script that was used to encrypt. The attacker decompiles it and gets the public params, `N` and `e`. The attacker finally uses brute force and decrypts the document.
```
# Public Parameters
N = <some_N>
e = <some_e>

for letter in document_text:
    print(pow(ord(letter), e, N))
``` 

### Underlying vulnerability/ies

Plain RSA(no padding) is vulnerable to brute force

### Expected difficulty

- [ ] :star:
- [ ] :star::star:
- [ ] :star::star::star:
- [x] :star::star::star::star:
- [ ] :star::star::star::star::star:
- [ ] :star::star::star::star::star::star:

### Possible attack flow
The attacker finds an encrypted file in the ftp location along  need to get access to the program and encrypted document using null byte injection and then apply brute force to decrypt.
The attacker decompiles it and gets the public params, `N` and `e`. The attacker finally uses brute force and decrypts the document to get the flag submits it to us in the feedback form and finishes the challenge

**Comment by bkimminich** [comment]
I like it! 👍 We'd just have to find something to hide in the document that then triggers the challenge, as it's an offline task. Maybe we just put the Tokensale-page URL in there, so it can be found either using that way or the existing one with de-obfuscating the Angular route...

**Comment by jainendra** [comment]
@bkimminich awesome. I'll raise a PR and we can discuss it further there

**Comment by jainendra** [comment]
@bkimminich Raised a PR - https://github.com/bkimminich/juice-shop/pull/1274. Please review and let me know your thoughts on this.

**Comment by jainendra** [comment]
Closing since PR is merged
