### ISSUE TITLE
Installation fails due to Node v4 and sqlite dependency ~3.0 on Mac OSX

### ISSUE THREAD

**Issue by timbru31** [juice-shop/juice-shop#126]
Hi,

on Mac OS X 10.11.1 with Node v4.1.1 the `npm i` command fails due the the `sqlite3` dependency.
Support for Node v4 was added in release 3.1.
(https://github.com/mapbox/node-sqlite3/issues/517)

Would be awesome if the project could be updated :smile:

**Comment by bkimminich** [comment]
I would love to get the app to Node 4.x, Jasmine 2.x etc. but unfortunately that would likely end as a rewrite of all my tests and most of the production code as well. So basically this issue depends on me or some node-wizard-volunteer finding the time to do #115 ... :-)

**Comment by bkimminich** [comment]
Closing this issue. Temporary fix: Use Docker container to run the app. Future fix: Migration to latest Node.js (#115)
