### ISSUE TITLE
Add negative ammount of items to basket [⭐]

### ISSUE THREAD

**Issue by pprchal** [juice-shop/juice-shop#1262]
# :star: Challenge idea

### Description
I' able to add negative ammount of items to basket. (-100)

### Expected difficulty
Very easy, just call api with negative ammount.

- [ x] :star:
- [ ] :star::star:
- [ ] :star::star::star:
- [ ] :star::star::star::star:
- [ ] :star::star::star::star::star:
- [ ] :star::star::star::star::star::star:

### Possible attack flow
This should be trouble in some billing-refunds or cashback systems.
I.E. shop is refunding back to your account rest of money. If you have -$100 , then please send me back.

**Comment by bkimminich** [comment]
A challenge for this API issue already exists: https://pwning.owasp-juice.shop/part2/improper-input-validation.html#place-an-order-that-makes-you-rich
