### ISSUE TITLE
Web Authentication [🚀]

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1267]
# :rocket: Feature request

### Description

Add Web Authentication as options for user registration and login. An unfinished or broken library should be picked or the manual implementation should be somehow flawed to allow a realistic hacking challenge around WebAuthn.

### Solution ideas

https://webauthn.guide/

**Comment by J12934** [comment]
I really like the idea👍

It would be cool if we could find a report on what sort of things which can be done wrong when adopting WebAuthn and basing the challenge(s) around real problems

**Comment by Nekomyst** [comment]
Hi @bkimminich , I would like to work on this issue. Let me know if you have any suggestions. :)

**Comment by bkimminich** [comment]
Hi @CaptainNick! Best first read is always https://pwning.owasp-juice.shop/part3/contribution.html, and about this idea, it's very much open for suggestions as it's just something I learned about at a conference and found interesting... 😅

**Comment by Nekomyst** [comment]
Yes @bkimminich , I've already gone through the contribution guide. I'm reading more about WebAuthn and its implementation. BTW which conference was it?

**Comment by bkimminich** [comment]
It was at German OWASP Day, https://youtu.be/XQn-OOVv6zc

**Comment by Nekomyst** [comment]
What authenticator type you want to be implemented? @bkimminich

**Comment by bkimminich** [comment]
Would be great if it worked with any (cheap) FIDO U2F key, because then its affordable for more people to experiment with.

**Comment by bkimminich** [comment]
@CaptainNick, are you working on this feature? If not I'd put it back into our backlog for the OWASP Projects Summit in Mexico next week.

**Comment by Nekomyst** [comment]
Had exams and so the work on this feature is not completed yet. You can go ahead and put it in backlog. I'll take up and work on other issues. :)

**Comment by rini-19** [comment]
hey @bkimminich, I've been investing some time on this issue lately and I would like to know if using FIDO U2F is an only considerable option or platform authenticators can also be used (like fingerprint sensor)...

**Comment by bkimminich** [comment]
Yeah sure, fingerprint sensor is also fine! 👍

**Comment by bkimminich** [comment]
Best case we get both ways implemented at some point, but it doesn't need to be done all at the same time and also not by the same person obviously.

**Comment by J12934** [comment]
I've made a bit of progress during the summit but wasn't able to complete it.
If somebody else want to continue on the progress feel free.
My work can be found in the [webauthn branch](https://github.com/bkimminich/juice-shop/tree/webauthn). Currently containing mostly changes to the 2fa pages to allow to configure another 2fa method.

**Comment by Scar26** [comment]
@J12934 Can I take this up in a couple of days?

**Comment by J12934** [comment]
> @J12934 Can I take this up in a couple of days?

I think so.
Thought I’m not sure if @rini-19 or @CaptainNick would like to continue their progress.

**Comment by bkimminich** [comment]
The `webauthn` branch has been rebased with `develop`, but build errors out during Angular compile with

```
ERROR in src/app/two-factor-auth/two-factor-auth.component.html:25:13 - error NG8001: 'mat-chip' is not a known element:
1. If 'mat-chip' is an Angular component, then verify that it is part of this module.
2. If 'mat-chip' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
25             <mat-chip color="accent" selected>Active</mat-chip>
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  src/app/two-factor-auth/two-factor-auth.component.ts:25:16
    25   templateUrl: './two-factor-auth.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component TwoFactorAuthComponent.
src/app/two-factor-auth/two-factor-auth.component.html:103:13 - error NG8001: 'mat-chip' is not a known element:
1. If 'mat-chip' is an Angular component, then verify that it is part of this module.
2. If 'mat-chip' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
103             <mat-chip>Inactive</mat-chip>
                ~~~~~~~~~~
  src/app/two-factor-auth/two-factor-auth.component.ts:25:16
    25   templateUrl: './two-factor-auth.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component TwoFactorAuthComponent.
```
