### ISSUE TITLE
 [🐛]wrong xmljs.node binary in 9.3.0 for Darwin

### ISSUE THREAD

**Issue by jfbouzereau** [juice-shop/juice-shop#1271]
xmljs.node included in the 9.3.0 release for Darwin is ELF binary

**Comment by bkimminich** [comment]
libxmljs2 is deciding what it installs on each system we package archives for. If there's anything not matching please raise an issue for that library with a bit more context and details about the actual problem this causes. Otherwise they won't be able to help either.

**Comment by jfbouzereau** [comment]
I reloaded the file and it is ok. May be I clicked the wrong link the first time (a linux version)
Sorry for the disturbance.

**Comment by bkimminich** [comment]
No problem, glad it works for you now and the "fix" was that easy... :-)
