### ISSUE TITLE
[🎭] UI harmonization towards facelifted design

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1276]
Some old screens as well as all screens newly added during GSoC 2019 might currently not be in visual harmony with the facelifted/UX-improved designs by @MarcRler. Their components should be checked for compliance and if needed be reworked towards the same Material design and usability goals.

- [x] `accounting`
- [x] `address`
- [x] `address-create`
- [x] `address-select`
- [x] `administration`
- [x] `basket`
- [x] `challenge-solved-notification`
- [ ] `challenge-status-badge`
- [x] `delivery-method`
- [x] `deluxe-user`
- [x] `error-page`
- [x] `forgot-password`
- [x] `oauth`
- [x] `order-completion`
- [x] `order-history`
- [x] `order-summary`
- [x] `payment`
- [x] `payment-method`
- [x] `photo-wall`
- [x] `product-details`
- [x] `product-review-edit`
- [x] `purchase-basket`
- [x] `recycle`
- [x] `saved-address`
- [x] `saved-payment-methods`
- [ ] `score-board`
- [x] `server-started-notification`
- [x] `token-sale`
- [x] `track-result`
- [x] `user-details`
- [x] `wallet`

**Comment by ridhishjain-zepto** [comment]
@bkimminich I'd like to work on this issue. Just wanted to know if I am guessing it right?

- all the components u have mentioned are to be refactored (in terms of UI)

-  the improved designs should be similar to or in concordance with "facelifted/UX-improved designs by @MarcRler"

Where can I get the idea about "facelifted/UX-improved designs" And once I get this, all I have to do is improve each component's UI, right?

**Comment by bkimminich** [comment]
All components _not listed_ above are considered "facelifted" and can serve as examples.

**Comment by bkimminich** [comment]
In general the goal is a consistent look and feel that is in accordance with https://material.io/design/ guidelines.

**Comment by ridhishjain-zepto** [comment]
Thanks for the help!
I'll split the work  into a number of PRs, one for each component, so that it'll be in segments and easy to cope.

**Comment by bkimminich** [comment]
This is part of the upcoming OWASP Projects Summit work items.

**Comment by bkimminich** [comment]
@MarcRler, I just noticed that the screen flow when doing a deluxe-upgrade is a bit weird: It's logging you out, throwing you back to the login screen and not showing any confirmation message that you successfully upgraded. I won't open a separate ticket for it, as the `deluxe-user` screen is not yet done, but please take a look at this when you get to it. Thanks!

**Comment by bkimminich** [comment]
@MarcRler I'll not merge the current `facelift` for the upcoming `v10.1.0` which will hopefully be released tomorrow, we'll save it for one of the next releases, ok?

**Comment by bkimminich** [comment]
Let's try the _motivational tweet_ approach to get this one eventually resolved for good... https://twitter.com/owasp_juiceshop/status/1283530731097030658 👼

**Comment by rhinojosadev** [comment]
@bkimminich could I take the accounting component?
Thanks!

**Comment by bkimminich** [comment]
Sure, @rene-ph! 👍

**Comment by MarcRler** [comment]
I would like to take care of the deluxe user page

**Comment by MarcRler** [comment]
Whereby the page looks good so far. I just see that the payment options need some rework (at least in Safari).

**Comment by bkimminich** [comment]
Just merged the divider fixes on _My Payment Options_ into `develop`. Thanks, @MarcRler!

**Comment by bkimminich** [comment]
The following are the only remaining screens which have not yet been tackled in the facelifting initiative:

### Token Sale
![image](https://user-images.githubusercontent.com/3531020/103447817-7eb93280-4c90-11eb-82e2-01d47161ef2c.png)

### Score Board _and_ Challenge-Status-Badge
_(the toughest nut to crack design and usability wise, as performance cannot degrade any further)_
![image](https://user-images.githubusercontent.com/3531020/103447866-4e25c880-4c91-11eb-8d85-4f61775b3e0a.png)

### Order History
✅ **Done!**

### Server-Started _and_ Challenge-Solved Notifications
✅ **Done!**

### Accounting
✅ **Done!**

### Deluxe User
✅ **Looks good as is**

**Comment by bkimminich** [comment]
Happy new year, @MarcRler! Would you by any chance be up to review and update the _Token Sale_ and/or _Order History_ screens? I think for the _Score Board_ we need to plan a bit more time, maybe even make that a GSoC project for 2021. So I'd probably open a separate ticket for that and close this once the last two other screens are done.

**Comment by cigar-galaxy82** [comment]
hey @bkimminich I would like to work order-history component

**Comment by cigar-galaxy82** [comment]
hey @bkimminich I would like to work on token sale component

**Comment by bkimminich** [comment]
> hey @bkimminich I would like to work on token sale component 

Awesome, feel free to! Please try to keep not just the visual end result but the HTML and SCSS structure too, as similar to other screens as possible.

**Comment by bkimminich** [comment]
Completed except for _Score Board_, which will be promoted as a GSoC 2021 project instead.
