### ISSUE TITLE
Promotion video : guitar tab

### ISSUE THREAD

**Issue by ghost** [juice-shop/juice-shop#1286]
Hello,

I love this project, in contrary of my friends. To encourage us, I want to play the music of the [(Juice Shop Jingle)](https://github.com/bkimminich/juice-shop/blob/master/frontend/src/assets/public/videos/JuiceShopJingle.mp4) with my guitar. It's only for a personal use, not for commercial uses.
What about rights on that music ? Can I have the guitar tab of this music ?

Thank you for your answer,
[Brynanum](https://gitlab.com/Brynanum).

**Comment by bkimminich** [comment]
That's probably hands down *the best* GitHub issue we've ever had... 🎸

I'll ask @braimee about that, he made the jingle... 👍

**Comment by 7MinSec** [comment]
I was 100% certain this was a joke issue submission when I saw the email, but after intensely interrogating @bkimminich I've confirmed that neither he nor my mom submitted this request, so I'm thinking it's legit!  :-)

@Brynanum you're welcome to play the music, but if you do so in any public forum I just ask you share with me so I can enjoy as well :-).  I don't currently own a guitar (long story) but next time I'm at one I will double check the tab.  I can't remember if I threw a capo on or not, but I think this is pretty close:

````
When you [D] want to shop online then you had [G] better be [D] sure
The [D] experience is safe, and [A] also secure
Don't wanna [D] let no SQLi or cross-site [G] scripting ruin your [D] day
No you [D] wanna break into a joyous [G] song [A] and [D] say

[G] Juice [D] Shop, [G walk-up to A] Juice [Bm] Shop
You can [D] order tasty beverages in [A] any quantity
[G] Juice [D] Shop, [G walk-up to A] Juice [Bm] Shop
Just don't [D] test the site with Burp Suite or you [G] won't like [A] what you [D] see
````

**Comment by bkimminich** [comment]
"I only understand railway station" as we say in Germany. Guitar tabs look like ALiBI (Arbitrary Letters in Brackets Injection) to me... Anyway, **thanks a lot, Brian!** 🍹

**Comment by 7MinSec** [comment]
Hey @Brynanum please go chuck out the FULL Juice Shop Jingle here: https://github.com/braimee/bpatty/issues/13.  Please let us know when you perform this so we can see you in person (or at least take video!) :-)

**Comment by ghost** [comment]
Hey :)
I answer you in the reopened issue, at [braimee/bpatty#13](https://github.com/braimee/bpatty/issues/13). I put again my message :
Hello again ! :)
I'm the person who ask you the chords on the jingle. I saw that you have developed it... :D
**Can we have the arpeggios version** of this music, or you didn't realize it with the expansion ?
By the way (and to answer to a private message) : yes, I will take a video of myself playing guitar and singing. Even if I'm French and I'm not a monster in guitar. ;)
[Brynanum](https://gitlab.com/Brynanum)

**Comment by ghost** [comment]
Hello again,
This is a small video on the jingle (in Tux kigurumi, because I love Linux and I want it this day) : [https://youtu.be/tx6tou8wMMQ](https://youtu.be/tx6tou8wMMQ).

**Comment by 7MinSec** [comment]
@Brynanum this made me smile and made my day.  GREAT job and my wife absolutely loves your outfit :-)

**Comment by bkimminich** [comment]
Aaaand, you're on the official Juice Shop YouTube playlist now, @Brynanum! 🥳

**Comment by 7MinSec** [comment]
Also @Brynanum do you have a Twitter handle I can tag?  I'd love to retweet this.

**Comment by ghost** [comment]
Thank you for your return ! :)
Sorry, but I don't have Twitter... ^^'
But you can tweet it with your own account if you want. ;)
