### ISSUE TITLE
Filter and info box or unavailable challenges [🚀] 

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1288]
# :rocket: Feature request

### Description

When challenges are not available (on Heroku or Docker) there should be
* [ ] a filter option to hide these challenges on the Score Board (hidden by default)
* [ ] an info box on the Score Board that states that challenges are missing for security reasons with a link to https://pwning.owasp-juice.shop/part1/challenges.html#potentially-dangerous-challenges for more information

**Comment by Scar26** [comment]
Does juice-box have inbuilt functionality to check challenge availability or should the option be kept manual?

**Comment by Scar26** [comment]
I would like to work on this.

Made an initial design for the infobox, wanted to confirm if this is what you had in mind

![infoboxfinal](https://user-images.githubusercontent.com/41830515/73744322-9503f900-4776-11ea-97b4-f62bec538dc3.jpg)

**Comment by bkimminich** [comment]
I'd probably prefer it either in the empty space near the "Show solved" button or at the very bottom between those other two info boxes. Maybe the top location is better...? Especially when we add a "Show disabled" button as well there it makes more sense to have the text next to it.
