### ISSUE TITLE
Direct login link in signup form[🚀] 

### ISSUE THREAD

**Issue by ridhishjain-zepto** [juice-shop/juice-shop#1290]
# :rocket: Feature request

### Description

 The current login form has the option of directing new users to signup or create a new account:
![Screenshot (97)](https://user-images.githubusercontent.com/45514905/73738238-202ac200-476a-11ea-99b6-f2865ffdfb70.png)

A similar thing should also be present in signup-form from where the user can directly move back to login form: `Already a customer? Log in to continue.`
![Screenshot (95)](https://user-images.githubusercontent.com/45514905/73738349-58320500-476a-11ea-8506-531c2d774cc6.png)

### Solution ideas

 The simple solution is to implement a link to login form in signup container

### Possible alternatives

 One good alternative can be to make double slider login-signup form!. It will improve UI and reduce routes.

**Comment by bkimminich** [comment]
The link idea sounds good to me! 👍

**Comment by ridhishjain-zepto** [comment]
resolved in PR #1297
