### ISSUE TITLE
Flaky API tests due to SequelizeTimeoutError [🐛] 

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1309]
# :bug: Bug report

## Description

`SequelizeTimeoutError: SQLITE_BUSY: database is locked` is occasionally thrown during API test exection locally and on Travis-CI resulting in `500` server errors and subsequently failing test expectations.

### Is this a regression?

This occured for quite some time in irregular intensity and frequency.

## :microscope: Minimal Reproduction

Execute `npm run frisby` several times and this problem is likely to occur at some point.

## :fire: Exception or Error
`SequelizeTimeoutError: SQLITE_BUSY: database is locked` resulting in:

<pre><code>
    assert.strictEqual(received, expected)

    Expected value to strictly be equal to:
      200
    Received:
      500

    Message:
      HTTP status 200 !== 500

      at FrisbySpec.status (node_modules/frisby/src/frisby/expects.js:25:12)
      at node_modules/frisby/src/frisby/spec.js:418:23
      at node_modules/frisby/src/frisby/spec.js:247:34
      at node_modules/frisby/src/frisby/spec.js:254:28
</code></pre>

**Comment by bkimminich** [comment]
Still occurs occasionally, reopening and reverting pool size reduction.

**Comment by bkimminich** [comment]
Just made a test run with in-`:memory:`  SQLite, and it didn't turn out too well during the e2e test suite:

```
Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such table: PRODUCTS
Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such table: Users
Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such table: Products
```

**Comment by bkimminich** [comment]
Unfortunately occasional 500-errors are still happening for me locally after #1341. I'm going to revert that one for now.

**Comment by Scar26** [comment]
https://activesphere.com/blog/2018/12/24/understanding-sqlite-busy

Might be helpful
