### ISSUE TITLE
Crashes if invalid json is posted

### ISSUE THREAD

**Issue by mschwartau** [juice-shop/juice-shop#131]
The following post of invalid json data
`curl -X POST --data '{password: "test123", passwordRepeat: "test123", email: "' http://localhost:3000/api/Users/`

crashes the app (the server has to be restarted after the post):
.../juice-shop/node_modules/sequelize/lib/utils/parameter-validator.js:76
    var _value       = (value === null) ? 'null' : value.toString()
                                                                                ^
TypeError: undefined is not a function

Feature or bug? 
##

**Comment by bkimminich** [comment]
All server crashes are bugs, unfortunately... :bug:  ... Will look into this, thanks for noticing!

**Comment by bkimminich** [comment]
Fixed in upcoming v6.0.0 release through #167.
