### ISSUE TITLE
SQRL [🚀] 

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1311]
# :rocket: Feature request

### Description

Allow user registration/authentication via [SQRL](https://www.grc.com/sqrl/sqrl.htm).

**Comment by bkimminich** [comment]
See https://sqrl.grc.com/threads/websites-that-could-use-help-adopting-sqrl.1093/#post-9108

**Comment by Scar26** [comment]
I would like to take this up

**Comment by bkimminich** [comment]
Might not be possible to implement SQRL after all, because I was told that it only works with HTTPS. Maybe there's a way to cheat that, but if the SQRL clients don't accept the server-side unencrypted, it's game over for this authentication option.

**Comment by bkimminich** [comment]
Feel free to do some research on if it might still be possible, though. The Node.js implementations are pretty scarce so far, though. I wouldn't put my hopes up too much.

**Comment by Scar26** [comment]
What about self signed certificates?

https://github.com/erikma/passport-sqrl/
