### ISSUE TITLE
[🤖] LMLFTFY Bot (Let me lint:fix that for you)

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1316]
# :rocket: Feature request

### Description

1. Bot that runs `npm run lint:fix` after every commit on the (configured) branches
2. Creates and pushes a Git commit to the branch when changes came out of the Linter calls
3. Has a friendly commit message like `Auto-fix linting issues of commit _____`

### Solution ideas

GitHub Action

### Possible alternatives

Heavy Travis-CI scripting 

 Have you considered any alternative solutions or workarounds?

**Comment by J12934** [comment]
Done 🎉
