### ISSUE TITLE
[⭐] Free deluxe membership (already existing vulnerability in juice-shop)

### ISSUE THREAD

**Issue by Scar26** [juice-shop/juice-shop#1325]
# :star: Challenge idea

### Description

The `rest/deluxe-membership` route is vulnerable. Users can upgrade themselves to deluxe members by simply making a POST request to this path with the following parameters

- `UserId`: your uid(which you can get by decoding your jwt)
- `payUsingWallet`: false

Though this can be easily fixed with minor refactoring, I propose that we make this into a challenge instead

### Underlying vulnerability/ies

I guess this would fall under `Security Misconfiguration` or `Miscellaneous`

### Expected difficulty

| :heavy_check_mark: / :x: | Difficulty                           |
|:------------------------:|:-------------------------------------|
|     :heavy_check_mark:       | :star::star:                         |

### Possible attack flow

You can replicate the attack right now by making a POST request to `localhost:3000/rest/deluxe-membership` with the following params
- `UserId`: your uid(which you can get by decoding your jwt)
- `payUsingWallet`: false
-  After that, logout and login again to refresh your JWT. You are now a deluxe-member and no amount has been deducted from your wallet

This vulnerability can be discovered by examining the requests made when one tries to pay for deluxe membership and then fu

**Comment by bkimminich** [comment]
That's a good idea for a new challenge but another (very easy) way to achieve this would currently probably be to set the `role` property to `deluxe` upon registration. Doing that would make the challenge almost identical to the _Admin Registration_ challenge.

I was thinking of making the deluxe upgrade a bit harder to get, e.g. by storing some kind of hash from the `UserId` plus `email` plus `createdAt` date during deluxe upgrade and make that part of the checks for deluxe actions (i.e. getting the delivery costs or quantity limits). This would block the registration attack path pretty much, but the attacker can calculate that hash and set it in his own user record to make his deluxe upgrade legit.

What do you think?

**Comment by Scar26** [comment]
Sounds great

This would work perfectly with the challenge since the attack flow I described above makes for a completely valid upgradation process, just without the payment step.

But if we're at it, why not just make the token a secure one? Since it already seems like a far stretch for an attacker to "guess" what parameters went into the hash and in what order

**Comment by bkimminich** [comment]
So the only way to bypass it, is to mess with the `/rest/deluxe-membership` route? Yep, sounds cool!

**Comment by bkimminich** [comment]
Yeah well, it unfortunately doesn't work as simple as currently implemented. Just try this:

1. Log in with credentials `demo` / `demo`
2. Go to _Deluxe Membership_ page and click the button to become a member
3. Choose the pre-existing **credit card** for payment and click _Continue_
4. The challenge is triggered as solved. Although you "paid" for it.

Simple "fix" would be giving the `payUsingWallet=true|false` needs an "upgrade" into something like `payment=wallet|card` and when that **parameter is empty** you'd still get your membership. Then it'd be believable business logic flaw and sufficiently different from the password change challenge where the old-password parameter is supposed to be **missing entirely** to change anyones password.
