### ISSUE TITLE
Update the OpenAPI Specification[🚀] 

### ISSUE THREAD

**Issue by ailton07** [juice-shop/juice-shop#1328]
# :rocket: Feature request

### Description

Once the OWASP API Security Top 10 2019 items were added to OWASP Juice Shop challenge categories (https://github.com/bkimminich/pwning-juice-shop/commit/7abe69df30eca385bcb8fd3953cbab640f733245), I think would be great if the [Juice Shop OAS](https://github.com/bkimminich/juice-shop/blob/master/swagger.yml) were updated.

### Solution ideas

Currently, the main tool to create and update OASs is [Swagger Editor ](https://swagger.io/tools/swagger-editor/), despite there extensions to several code editors (ie. [Eclipse](https://github.com/RepreZen/KaiZen-OpenAPI-Editor), [VS Code](https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi), and [Atom](https://atom.io/packages/linter-swagger)).

**Comment by ailton07** [comment]
I verified just now that [Juice Shop OAS](https://github.com/bkimminich/juice-shop/blob/master/swagger.yml) describe only 'API for our enterprise customers'. So, I suggest the creation of a new OAS to describe the 'private' APIs.

**Comment by bkimminich** [comment]
The existing B2B API is housing two hacking challenges. There is no functional need to add any other similar API descriptions from my point of view. What kind of _update_ are you suggesting exactly? The `swagger.yml` is already using `openapi 3.0.0` format.

**Comment by ailton07** [comment]
Using an API contract, like OAS, allows you to use newer solutions for API protection (thus new vulnerabilities), and with that, new challenges. For example, when we know what kind of query parameter is expected, it is easier to mitigate injection attacks and detect parameter tampering.
Create and maintain documentation of private APIs is becoming a standard due to security questions, and I think it would be interesting JS replicate this pattern. Therefore, I'm suggesting the creation of an OAS that describes all Rest APIs in Juice Shop.
However, right now, I agree that there is no functional need to the current Juice Shop case of use. But developing an API specification allows the creation of newer challenges in the future.

**Comment by bkimminich** [comment]
Okay, but having this for the generated `/api` and hand-crafted `/rest` APIs would make current challenges a lot easier, e.g. as it would spoiler that some allow `POST`/`PUT`/`DELETE` where they clearly shouldn't or are missing access control alltogether etc.

The "storyline" behind not having this, is kind of "the developers were too lazy to document the API or create a contract in front of it. Nobody will ever use that API directly anyway, it's only there for our own frontend."

**Comment by ailton07** [comment]
Indeed, having an Open API specification would make current challenges a lot easier. Actually, I hadn't thought about that.
Considering all these factors, I get it the absence of 'complete' API documentation. However, if you consider that it is interesting to add that doc in the further, I would be happy to contribute.
