### ISSUE TITLE
[⚙️] Copy challenges.yml over to www-project-juice-shop after a release

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1337]
# :⚙️: Automation request

### Description

The project website now uses a (manually committed) [copy of the `challenges.yml`](https://github.com/OWASP/www-project-juice-shop/blob/master/_data/challenges.yml) to render a table with all challenges grouped by their category:

![image](https://user-images.githubusercontent.com/3531020/76418264-9c827780-639e-11ea-93eb-7ff6af4e15b4.png)

(Source: <https://owasp.org/www-project-juice-shop/#div-challenges>)

It would be great to automate this copy+paste process whenever a new version is released.

### Solution ideas

Implement as an `after_deploy` step for tag (or `master` branch?) builds in the `travis.yml`.

### Possible alternatives

Implement as a GitHub action triggered by changes of `challenges.yml` on `master` branch or upon tag push.

**Comment by bkimminich** [comment]
This table is now also generated from the `challenges.yml` instead of a separate (and somewhat redundant) data file listing the tutorialized challenges:

![image](https://user-images.githubusercontent.com/3531020/77405285-3a207280-6db3-11ea-863c-158a8e92c8d7.png)

**Comment by Scar26** [comment]
Would it perhaps be better if instead of opening a pull request when a commit is pushed with the release tag, we get the metrics endpoint to also expose the list of all challenges and then the website could fetch it from one of the permanent instances like https://demo.owasp-juice.shop/#/ or https://juice-shop.herokuapp.com/#/ ?

**Comment by bkimminich** [comment]
I really don't want to dynamically load any data from the inherently insecure Juice Shop into the official website... 😅 _(Edit: Also, I'm not even sure Jekyll would allow that. It can't even load files from external locations, afaik.)_

But opening a PR instead of just pushing a commit would be an option, but it's not really needed as a manual intervention step. The Juicy Bot user (which is also doing the linting) should probably do just a commit.

**Comment by bkimminich** [comment]
If there's a way to load the `challenges.yml` from the Juice Shop repo as a data source in the website repo, then no commits etc. would be needed. But that's still kind of a "remote file inclusion" and afaik it is not supported by Jekyll.

**Comment by Scar26** [comment]
Oh ok, I'll go ahead with the workflow then
