### ISSUE TITLE
[⭐] OSINT Challenge

### ISSUE THREAD

**Issue by Scar26** [juice-shop/juice-shop#1358]
# :star: Challenge idea

### Description

The challenge description would read something like : 
"login as X by changing his password through the forgot password screen. Apparently, he goes by sc4p3run3 online" (suggestions for X and his alias highly appreciated)
The security question would be "What is your favorite movie"
A quick search by [sherlock](https://github.com/sherlock-project/sherlock) reveals a twitter account under the alias and using [wayback](https://archive.org/web/) to access deleted tweets, there's a tweet where he proclaims how he just watched a specific movie for the 25th  time and just can't get enough of it. This would be the answer to the security question allowing you to reset the password and login

### Underlying vulnerability/ies

I guess this could fall under sensitive data exposure but OSINT could very well be a category of its own. It could also accommodate the second challenge from #1347 

### Expected difficulty

| :heavy_check_mark: / :x: | Difficulty                           |
|:------------------------:|:-------------------------------------|
|    :heavy_check_mark:       | :star::star::star:                   |

### Possible attack flow

A quick search by [sherlock](https://github.com/sherlock-project/sherlock) reveals a twitter account under the alias and using [wayback](https://archive.org/web/) to access deleted tweets, there's a tweet where he proclaims how he just watched a specific movie for the 25th  time and just can't get enough of it. This would be the answer to the security question allowing you to reset the password and login

**Comment by bkimminich** [comment]
Love the idea with using archive.org for this! As for the category, let's keep it in "Sensitive Data Exposure" but maybe refer to OSINT in the challenge name (too on the nose maybe?) or at least in the pop-up hint text?

As for the account name, it'd be fine to create one refering to yourself, if you want to. Like I did with my cat's name and my ZIP code from childhood. But you can also "stage" it, although I guess this will be harder to actually OSINT realistically, right?

**Comment by Scar26** [comment]
Yes, the issue with using my alias is that although I don't really tweet stuff as of now, if I start tweeting at some point, the target tweet might get buried beneath real ones, making it harder to find. Though I guess that would make it more realistic.

So should I go with it or use a different name?

**Comment by bkimminich** [comment]
I like the idea of having it buried among real tweets a lot more... We can just crank up the difficulty a bit.

If you're uncomfortable using your own Twitter handle, it's of course also fine to use a generic account.

**Comment by Scar26** [comment]
No, I would love to use my own handle. That would make me a part of juice-shop literally :p
I'll go ahead with this then. Thanks!

**Comment by bkimminich** [comment]
Yep, you'd be setting yourself a little Juice Shop monument there... which is totally fine for me (and my cat)! 🗽
