### ISSUE TITLE
[🐛] Deluxe Fraud Challenge does not finish

### ISSUE THREAD

**Issue by FranzForstmayr** [juice-shop/juice-shop#1373]
# :bug: Bug report

## Description

When applying for a deluxe membership you can either choose to pay by card or wallet.
When your wallet is empty, the button for paying by wallet is disabled. When modifying the HTML entry and delete the `disabled` property, you can click "Pay", after that the submit button becomes enabled. After Submitting and login in again, you are a deluxe member.

### Is this a regression?

Don't know

## :microscope: Minimal Reproduction

Follow description above.

## :fire: Exception or Error
<pre><code>

</code></pre>

## :deciduous_tree: Your Environment

<pre><code>

Using Heroku, so node v12.x
</code></pre>

**Comment by bkimminich** [comment]
Cool, another unanticipated attack path for that challenge! 😁 ... @Scar26, can you have a look into this please? I suppose it shouldn't be as easy as this, so we probably have to close this simple solution? Or we reduce the difficulty of the challenge?

**Comment by Scar26** [comment]
Nice :laughing: !
I'll look into this in a minute. I guess we should probably block this path otherwise, it would just become another inspect-element challenge and we already have a bunch of those
