### ISSUE TITLE
Quarantine subfolder not accessible [🐛]

### ISSUE THREAD

**Issue by jamesdjuhartono** [juice-shop/juice-shop#1385]
# :bug: Bug report

## Description

Juicy malware files in /ftp/quarantine/ directory is not accessible through Poison Null Byte injection.

### Is this a regression?

Did not test this on previous version.

## :microscope: Minimal Reproduction

Perform Poison Null Byte injection to any file in /ftp/quarantine/ directory, and observe that the server will return a 403.

![image](https://user-images.githubusercontent.com/2942323/82007702-77abc880-969d-11ea-9fd6-0c5bbb3590a4.png)

## :fire: Exception or Error

<pre><code>OWASP Juice Shop (Express ^4.17.1)
403
Error: Only .md and .pdf files are allowed!
        &nbsp; &nbsp;at verify (/app/routes/fileServer.js:30:12)
        &nbsp; &nbsp;at /app/routes/fileServer.js:16:7
        &nbsp; &nbsp;at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
        &nbsp; &nbsp;at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
        &nbsp; &nbsp;at /app/node_modules/express/lib/router/index.js:284:7
        &nbsp; &nbsp;at param (/app/node_modules/express/lib/router/index.js:354:14)
        &nbsp; &nbsp;at param (/app/node_modules/express/lib/router/index.js:365:14)
        &nbsp; &nbsp;at Function.process_params (/app/node_modules/express/lib/router/index.js:410:3)
        &nbsp; &nbsp;at next (/app/node_modules/express/lib/router/index.js:275:10)
        &nbsp; &nbsp;at /app/node_modules/serve-index/index.js:135:16
        &nbsp; &nbsp;at FSReqCallback.oncomplete (fs.js:171:21)
</code></pre>

## :deciduous_tree: Your Environment
<pre><code>Tested on https://demo.owasp-juice.shop/
</code></pre>

**Comment by bkimminich** [comment]
I can confirm that behavior. Definitely not intended, and it seems there's never been an automated test for that either. Thanks for reporting!

**Comment by jamesdjuhartono** [comment]
No problem! It seems that this happen to all files in subfolder of /ftp/. I'm not familiar with node.js routing, but it seems that the file parameter passed to fileServer.js doesn't include the parent path, otherwise it should fail the <code>!file.includes('/')</code> check.

**Comment by bkimminich** [comment]
Yep, the routing was broken so that the subfolder was mistaken for the filename. I've fixed that (not elegant but simple) and it'll be part of v11.0.0 release. The files are not really important, just mildly helpful to find the malware for the _SSTi_ challenge.
