### ISSUE TITLE
[🚀] Disable the dismiss button on the welcome banner when "restrictToTutorialsFirst" is enabled

### ISSUE THREAD

**Issue by rotemreiss** [juice-shop/juice-shop#1389]
# :rocket: Feature request

### Description

When the Juice Shop is used for training sessions, I don’t see any reason to allow the trainees to dismiss the hacking instructor on the welcome banner.

### Solution ideas

IMO, when the “restrictToTutorialsFirst” and the "hackingInstructor" flags are enabled, then there shouldn't be a way to dismiss the welcome banner without starting the tutorial.

**Required changes:**
- Remove the dismiss button
- Don't close the dialog on click outside the modal / keyboard ESC button

Note that when the "hackingInstructor" flag is disabled, the functionality should remain the same as now (only a button to dismiss the dialog), although we should consider alerting on such configuration since it is odd to do so.

I will create a PR with the required changes in a few minutes. Please review and merge if accepted.

The issue has been discussed with @bkimminich via Slack.

**Comment by bkimminich** [comment]
https://github.com/bkimminich/juice-shop/pull/1390#issuecomment-629794236:
> We could instead add a "Do not show this again"-checkbox to the banner and only set the cookie when it is checked. Then at least accidental permanent closes are less likely. Then we could have a "Help getting started"-button in the navbar/sidebar to launch the tutorial directly, so the banner doesn't really matter any more and could always remain dismissable.

**Comment by bkimminich** [comment]
The "Help getting started"-button would obviously only be shown while the _Score Board_ hasn't been found.

**Comment by bkimminich** [comment]
@rotemreiss You are eligible for a pack of stickers & postcards if you email (or Slack-DM) me your address. I currently have a little Corona-related backlog of contributor package mailings, just so you know it might take a bit longer... 😷
