### ISSUE TITLE
[🐛] Challenge Blockchain Hype - Wrong RSA-Module in pyc

### ISSUE THREAD

**Issue by timmar2000** [juice-shop/juice-shop#1392]
# :bug: Bug report

## Description

The file announcement_encrypted.md, which is part of the challenge  "Blockchain Hype" is not decryptable as the file /ftp/encrypt.pyc contains the wrong value for N. This is likely due to a mismatch between the sourcefile test/files/encrypt.py and the compiled file ftp/encrypt.pyc

### Is this a regression?

No, the file hasn't been modified since being added as part of bffa158b5c961d6e19b127150e91ec64924db73c

## :microscope: Minimal Reproduction

Download the file encrypt.pyc using null-byte-injection. Run it through a python decompiler. Uncompyle6 returned:
```python
# uncompyle6 version 3.7.0
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.17 (default, Apr 15 2020, 17:20:14) 
# [GCC 7.5.0]
# Embedded file name: encrypt.py
# Compiled at: 2020-05-20 18:58:36
confidential_document = open('announcement.md', 'r')
N = 36239973541558932215768154398027510542999295460598793991863043974317503405132258743580804101986195705838099875086956063357178601077684772324064096356684008573295186622116931603804539480260180369510754948354952843990891989516977978839158915835381010468654190434058825525303974958222956513586121683284362090515808508044283236502801777575604829177236616682941566165356433922623572630453807517714014758581695760621278985339321003215237271785789328502527807304614754314937458797885837846005142762002103727753034387997014140695908371141458803486809615038309524628617159265412467046813293232560959236865127539835290549091L
e = 65537
encrypted_document = open('announcement_encrypted.md', 'w')
for char in confidential_document.read():
    encrypted_document.write(str(pow(ord(char), e, N)) + '\n')

encrypted_document.close()
# okay decompiling encrypt.py
```
It is not possible to decrypt the content of announcement_encrypted.md using this value N. Encryption works fine using the value for N from test/files/encrypt.py. The decrypt.py and decrypt._bruteforce.py contain the correct N as well. If I compile encrypt.py diff shows that the newly generated encrypt.pyc differs from ftp/encrypted.pyc. If I decompile the newly compiled encrypt.pyc again using uncompyle6 I get the correct value for N.
```python
```
## :fire: Exception or Error
<pre><code>

</code></pre>
N/A

## :deciduous_tree: Your Environment
<pre><code>

Docker Image: bkimminich/juice-shop:latest
</code></pre>

**Comment by bkimminich** [comment]
@jainendra, could you please take a look at this and verify the issue? Thanks!

**Comment by bkimminich** [comment]
@timmar2000 Did you verify that the `announcement_encrypted.md` was indeed encrypted with the `N` from the test files and not with the one from the decompiled `ftp/encrypt.pyc`? It might well be that @jainendra used a different `N` on purpose in the test files, so that it doesn't immediately spoiler the `N` needed for the challenge.

**Comment by timmar2000** [comment]
@bkimminich I've encrypted the announcement.md using test/files/encrypt.py
``` 
cd test/files
python encrypt.py 
diff -s announcement_encrypted.md ../../ftp/announcement_encrypted.md 
```
This shows me that the files are identical. So the original annoncement_encrypted.md must have been encrypted using N from the test-file.

If I try to encrypt the file using encrypt.pyc diff shows that the files are different.
 ``` 
cd ftp
mv announcement_encrypted.md announcement_encrypted.md.bak
cp ../test/files/announcement.md .
python encrypt.pyc
diff -q announcement_encrypted.md announcement_encrypted.md.bak
```

**Comment by bkimminich** [comment]
The files in `/test` are for testing, and the Python decryption is not tested automatically anyway, those files were just for manual testing afaik. The only way to verify if the used `N` is wrong in the file in `/ftp` is to try and brute force it with either `N`, I guess.

**Comment by bkimminich** [comment]
Ah, okay! Could you maybe send a PR with just the corrected `.pyc` file? That should fix the whole issue, as it seems.

**Comment by jainendra** [comment]
@bkimminich Yes, this is indeed the wrong encrypted file, not sure how this went through. Thanks @timmar2000 for pointing out and fixing it. 👍
