### ISSUE TITLE
Wrong name used

### ISSUE THREAD

**Issue by pascalschulz** [juice-shop/juice-shop#1399]
Hi Björn, 

starting with this line, you suddenly speak about Jim instead of Bender. 

https://github.com/bkimminich/juice-shop/blob/ef00293b3800037127f5eb84355713ebcc0979fa/frontend/src/hacking-instructor/challenges/loginBender.ts#L63

A little below that line again. 

Best, 
Pascal

**Comment by bkimminich** [comment]
Ah, classic copy&paste error... Thank you for noticing! 👍

**Comment by bkimminich** [comment]
And it's not only the texts, also the expected input is still Jim's email address, so this script wouldn't even be working as expected... 🤦
