### ISSUE TITLE
[🐛] Heroku deploy button broken

### ISSUE THREAD

**Issue by dare2netsec** [juice-shop/juice-shop#1406]
# :bug: Bug report

## Description

A clear and concise description of the problem...

The deploy Heroku button at https://github.com/bkimminich/juice-shop#deploy-on-heroku-free-0month-dyno is passing the incorrect link and results in an error.

It currently links to https://heroku.com/deploy

It should redirect to https://heroku.com/deploy?template=https://github.com/bkimminich/juice-shop

**Comment by bkimminich** [comment]
The button works as is, at least in my regular Chrome installation. Heroku recommends to use it this way, because that allows you to click the button on any _fork_ of the repo, and you'll get _that fork_ deployed. If I hardcoded the repo name, you'd always get my version.

**Comment by bkimminich** [comment]
See discussion in #1212.
