### ISSUE TITLE
[🐛] Error when using Username update feature

### ISSUE THREAD

**Issue by jimay422** [juice-shop/juice-shop#1407]
# :bug: Bug report

## Description

The user is authenticated and opens the "user profile" page, the update of the username is not possible. An error is visible in the server logs.

### Is this a regression?

The version used is `11.0.1`, according to the commits on this file, the problem is present since  707495a4b18a93763287770615c8a30f285a0ef1

## :microscope: Minimal Reproduction

- Authenticate with a valid user/password
- Open the "User profile" page
- Type a username and click on "Set username"
- No error is displayed, but the username is not set

## :fire: Exception or Error
<pre><code>
TypeError: Cannot read property 'includes' of undefined
    at /juice-shop/routes/updateUserProfile.js:18:83
    at Object.exports.solveIf (/juice-shop/lib/utils.js:103:36)
    at /juice-shop/routes/updateUserProfile.js:18:15
    at tryCatcher (/juice-shop/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/juice-shop/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/juice-shop/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/juice-shop/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/juice-shop/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/juice-shop/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/juice-shop/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/juice-shop/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/juice-shop/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
</code></pre>

## :deciduous_tree: Your Environment
<pre><code>
sudo docker run --rm -p 3000:3000 bkimminich/juice-shop
</code></pre>

### Additional Information

Found using Firefox 68.9.0esr 64bits
```
POST /profile HTTP/1.1
Host: localhost:3000
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost:3000/profile
Content-Type: application/x-www-form-urlencoded
Content-Length: 13
Connection: close
Cookie: language=en; welcomebanner_status=dismiss; cookieconsent_status=dismiss; continueCode=DYh2tzIEsQUrHMuzhYTyFzfBSatOi8f6SKXuqqhPjfjySwMU9puNvhLRIk3sNzUyqCeBsK5f7bUX3teLcZPTW2saL; io=caCjgpNxceE9JBDFAAAC; token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdGF0dXMiOiJzdWNjZXNzIiwiZGF0YSI6eyJpZCI6MTgsInVzZXJuYW1lIjoiIiwiZW1haWwiOiJ0ZXN0QHRlc3QuZnIiLCJwYXNzd29yZCI6ImNjMDNlNzQ3YTZhZmJiY2JmOGJlNzY2OGFjZmViZWU1Iiwicm9sZSI6ImN1c3RvbWVyIiwiZGVsdXhlVG9rZW4iOiIiLCJsYXN0TG9naW5JcCI6IjAuMC4wLjAiLCJwcm9maWxlSW1hZ2UiOiIvYXNzZXRzL3B1YmxpYy9pbWFnZXMvdXBsb2Fkcy9kZWZhdWx0LnN2ZyIsInRvdHBTZWNyZXQiOiIiLCJpc0FjdGl2ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMC0wNi0xMSAyMTowOToxMy43OTIgKzAwOjAwIiwidXBkYXRlZEF0IjoiMjAyMC0wNi0xMSAyMTowOToxMy43OTIgKzAwOjAwIiwiZGVsZXRlZEF0IjpudWxsfSwiaWF0IjoxNTkxOTA5NzU4LCJleHAiOjE1OTE5Mjc3NTh9.n6elmp2VRBg9ZJTFiJ8YrS0Iy05xeh9BwIpt5vQ6AtiukASznzKU778jWvdba0hzAVvoeoywyfeCDPABAVPz0jP7_hUgs0WK6EdF5e3av1Y-aEvQG2k_43JoDO6sgG-Bd6dx9vmcgORduc0Ptxz8Rnbv0gt2TA28EmAMotpfqoA
Upgrade-Insecure-Requests: 1

username=test
```

**Comment by jimay422** [comment]
Forget it, after restarting the server all is fine ... probably broke something ^^

**Comment by conmurray** [comment]
I'd like to reopen this. I'm experiencing this on the docker image. 

It works on 10.0.0 and fails to work on 10.1.0.
I've restarted the docker image numerous times and retested to see if it was something on my end.

I've even run two simultaneously as a side by side comparison. 
10.1.0 fails.
10.0.0 works.

Docker command:
Terminal 1:
docker run --rm -e "NODE_ENV=unsafe" -p 4000:3000 bkimminich/juice-shop:v10.1.0

Terminal 2:
docker run --rm -e "NODE_ENV=unsafe" -p 3000:3000 bkimminich/juice-shop:v10.0.0
