### ISSUE TITLE
Error on serving js files for the real easter egg[🐛] 

### ISSUE THREAD

**Issue by kwittkowsky** [juice-shop/juice-shop#1408]
# :bug: Bug report

## Description

On solving the "Nested Easter Egg" challenge browser only shows blank page.
Juice Shop not loading the real easter egg js files and I get two errors:

1. `Refused to execute script from '<URL>' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.` 

2. `Uncaught ReferenceError: THREE is not defined.`

**Comment by bkimminich** [comment]
The Three.js demo is part of the frontend code bundle and in past Angular versions it worked fine that way. Now it seems, that the Angular CLI is breaking it during final assembly. Requesting any of the JS files imported by the demo directly, gives you instead the content of the index.html - but broken. You can notice the cookie banner popping up then.

A possible solution would be to move this entire demo into a server-side rendered Pug template or even just serve the files directly from the server.

**Comment by bkimminich** [comment]
Prefixing all asset paths with `/` solves this issue. Will be released with `v11.2.0`.
