### ISSUE TITLE
Cron job for Git pull and Docker build

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1411]
I'm a dummy when it comes to Linux, so I'd really appreciate competent advice on how to set up the following in the most efficient way possible (`cron` job?) on my RasPi 4B with Raspian installed:

1. In user `pi`'s home folder `/GitHub/juice-shop` check-out master dropping any local changes and then pull from remote
2. If one or more commits _without_ `ci skip` in the commit message were pulled
3. Run shell script X (which I'll build the Docker image and push from then)

**Comment by J12934** [comment]
Maybe we could “just” migrate from the docker build to use GitHub actions. 
You could then use your raspi as a self hosted runner 😉

**Comment by bkimminich** [comment]
But then my RasPi would need to be callable from the evil Internet, and that's not going to happen... 😉

**Comment by J12934** [comment]
> But then my RasPi would need to be callable from the evil Internet, and that's not going to happen... 😉

I think its using a Pull Model not a Push, so you would not need to expose it to the internet.

**Comment by bkimminich** [comment]
> > But then my RasPi would need to be callable from the evil Internet, and that's not going to happen... 😉
> 
> I think its using a Pull Model not a Push, so you would not need to expose it to the internet.

You're right, it doesn't need to be callable, but https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories still says "_We recommend that you do not use self-hosted runners with public repositories._" - more due to risks of malicious forks, but the "Threat Model" here is just too unforeseeable to me. With a simple script that only pulls from the master branch of my own checked out repo, things should be safe pretty much all the time for my poor little RasPi.
