### ISSUE TITLE
[🐛] Error when using Username update feature

### ISSUE THREAD

**Issue by conmurray** [juice-shop/juice-shop#1418]
# :bug: Bug report

## Description

Issue was already reported and closed by the reporter in https://github.com/bkimminich/juice-shop/issues/1407
However I can consistently reproduce this

### Is this a regression?

Yes, the previous version in which this bug was not present was: `10.0.0`
It works on `10.0.0` and fails to work on `10.1.0` and upwards from what I can see.
I've restarted the docker image numerous times and retested to see if it was something on my end.

I've even run two simultaneously as a side by side comparison.
10.1.0 fails.
10.0.0 works.

Docker command:
Terminal 1:
docker run --rm -e "NODE_ENV=unsafe" -p 4000:3000 bkimminich/juice-shop:v10.1.0

Terminal 2:
docker run --rm -e "NODE_ENV=unsafe" -p 3000:3000 bkimminich/juice-shop:v10.0.0

`TypeError: Cannot read property 'includes' of undefined`
`    at /juice-shop/routes/updateUserProfile.js:18:83`
`    at Object.exports.solveIf (/juice-shop/lib/utils.js:102:36)`
`    at /juice-shop/routes/updateUserProfile.js:18:15`
`    at tryCatcher (/juice-shop/node_modules/bluebird/js/release/util.js:16:23)`
`    at Promise._settlePromiseFromHandler (/juice-shop/node_modules/bluebird/js/release/promise.js:547:31)`
`    at Promise._settlePromise (/juice-shop/node_modules/bluebird/js/release/promise.js:604:18)`
`    at Promise._settlePromise0 (/juice-shop/node_modules/bluebird/js/release/promise.js:649:10)`
`    at Promise._settlePromises (/juice-shop/node_modules/bluebird/js/release/promise.js:729:18)`
`    at _drainQueueStep (/juice-shop/node_modules/bluebird/js/release/async.js:93:12)`
`    at _drainQueue (/juice-shop/node_modules/bluebird/js/release/async.js:86:9)`
`    at Async._drainQueues (/juice-shop/node_modules/bluebird/js/release/async.js:102:5)`
`    at Immediate.Async.drainQueues [as _onImmediate] (/juice-shop/node_modules/bluebird/js/release/async.js:15:14)`
`    at processImmediate (internal/timers.js:456:21)`

## :microscope: Minimal Reproduction

- Authenticate with a valid user/password
- Open the "User profile" page
- Type a username and click on "Set username"
- No error is displayed, but the username is not set

## :fire: Exception or Error

<pre><code>

TypeError: Cannot read property 'includes' of undefined
    at /juice-shop/routes/updateUserProfile.js:18:83
    at Object.exports.solveIf (/juice-shop/lib/utils.js:102:36)
    at /juice-shop/routes/updateUserProfile.js:18:15
    at tryCatcher (/juice-shop/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/juice-shop/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/juice-shop/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/juice-shop/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/juice-shop/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/juice-shop/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/juice-shop/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/juice-shop/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/juice-shop/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

</code></pre>

## :deciduous_tree: Your Environment
Docker

<pre><code>

</code></pre>

**Comment by bkimminich** [comment]
On http://demo.owasp-juice.shop/profile (v11.1.1) it works fine to save a username.

**Comment by bkimminich** [comment]
The error can only come from this check `req.headers.origin.includes('://htmledit.squarefree.com')`, and it means that in your case there is no `origin` header in the request. As this might happen during request tampering or from unknown other reasons, I'll add a null check in front of that.
