### ISSUE TITLE
[⭐]Bellingen, stay away for me. 

### ISSUE THREAD

**Issue by GraoMelo** [juice-shop/juice-shop#1432]
# :star: Challenge idea, https/2.0

### Description

the user without being authenticated, makes a request to use the REST API.
requests will use http 2.0, instead of 1.1 or 1.0
as the application is not prepared, an error will error. This error will be the conclusion of the challenge.

### Underlying vulnerability/ies
**A6:2017-Security Misconfiguration**
Security misconfiguration is the most commonly seen issue. This is commonly a result of insecure default configurations, incomplete or ad hoc configurations, open cloud storage, misconfigured HTTP headers, and verbose error messages containing sensitive information. 

### Expected difficulty

| :heavy_check_mark: / :x: | Difficulty                           |
|:------------------------:|:-------------------------------------|
|     :heavy_check_mark:      | :star:                               |
|     :heavy_check_mark:      | :star::star:                         |
|     :grey_question:      | :star::star::star:                   |
|     :grey_question:      | :star::star::star::star:             |
|     :grey_question:      | :star::star::star::star::star:       |
|     :grey_question:      | :star::star::star::star::star::star: |

### Possible attack flow

1 - send request, 
GET/POST http://localhost:3000/rest/qwertz 2.0 

2 - returno code 500 or similar with error title: Bellingen, stay away for me. 

### The name of Challenge
Bellingen, stay away for me. refers to an event that happened in australia on 02 may 2015
reference [link](https://www.weatherzone.com.au/news/fifteen-people-rescued-from-floodwaters-in-northern-nsw-bellingen-soon-to-be-cut-off-as-heavy-rain-moves-down-the-coast/286524)

the event date is a reference to when the HTTP2.0 RFC was completed.
or Hypertext Transfer Protocol Version 2 (HTTP/2) [link](https://tools.ietf.org/html/rfc7540)
in another words http 2.0 / 02 of May and conclusion 2015.

**Comment by bkimminich** [comment]
✅ https://tools.keycdn.com/http2-test
✅ https://gf.dev/http2-test
✅ https://http2.pro/check
(on http://demo.owasp-juice.shop)

Maybe I'm missing your point, but I don't see how such a challenge would sense or be explainable as a realistic scenario.

**Comment by J12934** [comment]
Http2 Support is probably handled by Heroku.
Juice Shop itself doesn't seem to support http2.

This would probably also be a problem as any sort of loadbalancer doing http2 termination (most seem to do that) would interfere with the challenge.

```bash
curl --http2 localhost:3000
curl: (52) Empty reply from server
```

But I'm also not quite sure on what the challenge would be about.
A hidden easter egg? As this doesn't really seem to be security relevant.

**Comment by bkimminich** [comment]
I'm closing this one b/c I see no way to implement this properly. On to of the reasons @J12934 gave with potential proxy/LB issues here's another issue: As long as Juice Shop itself doesn't support HTTP/2 yet, any such requests wouldn't even get anywhere, meaning there's also no way to realize that a request came in and trigger a challenge. All in all, way too brittle circumstances.

I'll gladly reopen this if there's some stable approach to get this done along with some realistic narrative.
