### ISSUE TITLE
[🐛] SPOILER. Broken tutorial: "Log in with the administrator's user credentials without previously changing them or applying SQL Injection."

### ISSUE THREAD

**Issue by wadim-al** [juice-shop/juice-shop#1436]
# :bug: Bug report

## Description

The "Log in with the administrator's user credentials without previously changing them or applying SQL Injection." tutorial is broken at the moment where user pastes the "admin@juice-sh.op" into the login form. The blue balloon says: "Nah, that was wrong! Keep trying! I'll tell you when you're one the right track." But it should succeed, because the correct admin email was found and pasted.
![firefox-2020-08-04-15-58-02](https://user-images.githubusercontent.com/29713984/89296710-630f1900-d66b-11ea-8b98-42c6c9237be4.png)

### Is this a regression?

Have no idea

## :microscope: Minimal Reproduction

1. Install 11.1.2 from the juice-shop-11.1.2_node14_win32_x64.zip archive on Windows 10 x64 2004 with latest npm
2. Run using 'npm start' in unpacked folder
3. Navigate to http://localhost:3000/#/score-board
4. Click the 2-star tutorial for "Log in with the administrator's user credentials without previously changing them or applying SQL Injection."
5. Copy the admin@juice-sh.op value discovered in one of the comments to the clipboard
6. Open Account-Login
7. Past the admin@juice-sh.op value to the Email field

## :deciduous_tree: Your Environment

</code>
v14.7.0
6.14.7
</pre>

### Additional Information

Used juice-shop-11.1.2_node14_win32_x64.zip archive on Windows 10 x64 2004 with latest npm

**Comment by bkimminich** [comment]
Once I paste in the email as described, I get the expected hint, whereas you get the one for the password not being correct yet... Strange. Somehow your browser triggered the password field in a way mine doesn't.
![](https://i.imgur.com/vlM0iMC.png)

**Comment by wadim-al** [comment]
I think it is related to Chrome's Save Credentials feature. The browser automatically pastes in the password for the previously logged in user. Am I right? Can something be done in the tutorial to make it more compatible?

**Comment by bkimminich** [comment]
That is totally possible. I'm not using that in Chrome, though.

**Comment by bkimminich** [comment]
I don't see how we could prevent Chrome from virtually pushing submit in the form with its auto-fill feature.

**Comment by wadim-al** [comment]
But why the tutorial doesn't check the contents correctly? I'm pasting the value, so why doesn't it validate it on paste or by timer? Why does it check the password field if it is the step for filling the email correctly? If submit is pushed virtually, can the tutorial step be reworked to back-check the email and advance the state of the tutorial?

**Comment by bkimminich** [comment]
Here what the tutorial does: It checks the email field until it contains the expected admin email. Then it shows the password hint from my screenshot until you start typing in the field. When you do type, it shows the "Nah..." message you are seeing. Until your password matches "admin", then it tells you that you are close but not there yet.  Etc.

In your case the hint on the empty field seems to be skipped because your browser "types" into the field or at least a similar key event is triggered.

So there's nothing the tutorial can do about this.
