### ISSUE TITLE
[⚙️] Incompatible/Breaking dependency updates

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1440]
## `package.json`
* [x] `sequelize` 6.x not compatible with currently used 5.x
* [x] `file-types` 14.x not compatible with currently used 12.x
* [x] `socket.io` 3.x not compatible with currently used 2.x
* [x] `socket.io` and `socket.io-client` 3.x not compatible with currently used 2.x

## `frontend/package.json`
* [x] `socket.io-client` 3.x not compatible with currently used 2.x

**Comment by cigar-galaxy82** [comment]
Hey @bkimminich in this we have to update the codebase with the latest version of the mentioned package?

**Comment by bkimminich** [comment]
Hi @cigar-galaxy82! Yeah, this is basically a reminder issue, and working on it means picking one of the mentioned libs and migrating the codebase to work with the latest version w/o breaking or failing any tests.

**Comment by cigar-galaxy82** [comment]
@bkimminich  can I start working on this issue?

**Comment by bkimminich** [comment]
Sure thing, that'd be great! Just please make sure that you send one PR per migrated dependency, not all in one. Thanks!

**Comment by cigar-galaxy82** [comment]
ok thanks @bkimminich  just one more thing I want to confirm the mentioned lib file-types is a typo I think there is package file-type with version 12.x

**Comment by bkimminich** [comment]
Currently we're usign `"file-type": "^12.4.2"` but there is already `16.1.0` of that module available. When I opened the issue `14.x` was the latest. We should try to get to the latest, so `16.x`.

**Comment by cigar-galaxy82** [comment]
oh thanks
