### ISSUE TITLE
Cannot install Juice Bar 11.1.3 via packaged distributions and sources.

### ISSUE THREAD

**Issue by walldoggydogg911** [juice-shop/juice-shop#1454]
I cannot install Juice Bar from packaged distributions or  from sources. I can only install via docker.  I get an error msg.  I am running node js 14.9.  

![owasp_juice_bar_packaged_install_error](https://user-images.githubusercontent.com/54041238/91648606-711c4380-ea37-11ea-9d85-82ef1b706e30.png)

**Comment by bkimminich** [comment]
Looks like the `libxmljs2` binaries do not work on your OS. If you're sure to have used the right packaged distribution for your OS, then there's nothing we can fix here unfortunately.

**Comment by bkimminich** [comment]
Please note Juice Shop only supports 64bit OS and re-check which ZIP/TGZ archive you tried to use. The `ELF` error could occur if you're trying the Windows version on Linux or a 64bit program on 32bit OS.

https://github.com/bkimminich/juice-shop#nodejs-version-compatibility

**Comment by J12934** [comment]
Hi 👋 
Can you check if you have downloaded the correct zip for your operating system?
Wrong ELF header is likely do to the downloaded files being for the wrong OS.

Edit: Whoops the GitHub app didn't show Björn's previous comment 😅

**Comment by bkimminich** [comment]
At least we're consistent with our advice... 🤣

**Comment by walldoggydogg911** [comment]
That worked!  Thanks guys!
