### ISSUE TITLE
[🐛] Checkout without having enough money :)

### ISSUE THREAD

**Issue by PHPCore1** [juice-shop/juice-shop#1471]
# :bug: Bug report

## Description

You can use UI-Bypass on checkout to get a negative wallet (To pay without having enough money)
(It could also get a nice Challange :)

## :microscope: Minimal Reproduction

1. Add products to your basket
2. Make all steps up to the Payment-Method option
3. Select "Pay using wallet"
4. Remove class and disabled attribute from the "Pay x" button
5. Press the button
6. Checkout with "Place your order and pay"

## :deciduous_tree: Your Environment
<pre><code>
v12.18.3
6.14.8
</code></pre>

**Comment by bkimminich** [comment]
Thanks for this nice find! As we already have so many payment related challenges and also at least two where DOM-manipulation is a possible path, we might just want to fix this instead.

**Comment by RijulGulati** [comment]
I'd like to work on this one.
