### ISSUE TITLE
Photo captions not readable in light themes [🐛] 

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1474]
# :bug: Bug report

## Description

![image](https://user-images.githubusercontent.com/3531020/94294078-92515080-ff5f-11ea-92cd-102ea8f9945b.png)

## :microscope: Minimal Reproduction

1. `NODE_ENV=7ms npm start`
2. Go to http://localhost:3000/#/photo-wall
3. Hover over any photo to (not) see the caption in black text on gray-transparent background

**Comment by bkimminich** [comment]
In dark themes it's all fine, because the text is actually dependent on the theme. The transparent box isn't though, it's always dark-gray, which works with white but fails with black text color.

![image](https://user-images.githubusercontent.com/3531020/94294444-24f1ef80-ff60-11ea-9658-9161c1b711a9.png)

**Comment by surajat17** [comment]
i am new to open source commnity... can i work on it?

**Comment by bkimminich** [comment]
Of course, give it a shot! 👍

**Comment by rohan2734** [comment]
@bkimminich   Hey i would like to work on this issue can you assign me this issue

**Comment by bkimminich** [comment]
Not sure if @surajat17 started working on this yet, but give it a shot too, if you like. First (good) PR, first merge... 😁

**Comment by surajat17** [comment]
@rohan2734 go for it.

**Comment by rohan2734** [comment]
ok @surajat17 
- Hover over any photo to (not) see the caption in black text on gray-transparent background

is this saying, we need to see the caption, when we hover on the background? or is the opposite? 
pleaes be clear.

**Comment by bkimminich** [comment]
On light background you see it (good ✔️) but on dark background you don't (bad ❌). It should be readable on both color schemes.

**Comment by rohan2734** [comment]
@bkimminich okay.

**Comment by rohan2734** [comment]
@bkimminich  can you share the file names, on which it is there?
file searching is vert time taking process.

**Comment by Scar26** [comment]
@rohan2734  If you mean the photowall page, the component is defined in https://github.com/bkimminich/juice-shop/tree/master/frontend/src/app/photo-wall

**Comment by bkimminich** [comment]
The problematic part is actually this statically defined overlay color: https://github.com/bkimminich/juice-shop/blob/master/frontend/src/app/photo-wall/photo-wall.component.scss#L69

50% transparent black works nicely if you put white letters on it but totally fails if you put black letters on it. The color needs to be different depending on having a light or dark color theme. There should be an Angular-way to do this, but you'd need to investigate that as part of the issue solution.
