### ISSUE TITLE
[🤔] Proposal: Download Compiled Assets on Local Install instead of Compiling them Locally

### ISSUE THREAD

**Issue by J12934** [juice-shop/juice-shop#1477]
I'm marking this as a proposal as I'd be very interested in what you all think about this and to see if there are other downsides to this then the ones listed below.

### Description

The local Juice Shop install currently takes a long amount of time. This time is basically spent on two tasks:

1. Downloading Dependencies via npm (for both backend & frontend)
2. Compiling the Angular frontend

### Solution ideas

Instead of compiling assets locally, Juice Shop could download the compiled frontend assets, as these are identical for every install of a specific Juice Shop version, even when  a customized config.

To download the assets every (future) JuiceShop release could have these assets attached as a Zip on the GitHub Release.

The download could happen at two possible steps:

1. `postInstall`. Basically where the compilation is happening now, using a postInstall npm hook to download the Zip and unzipping it to the `frontend/dist/` folder.
2. On startup, similar to other steps, e.g. `lib/customizeApplication.js`

This download should only happen if the `frontend/dist/` folder doesn't already contain the compiled assets for the current juice-shop version. If it contains the assets for a different version, `frontend/dist/` should be deleted and replaced with the assets matching the released version.

#### 🐳 How about Docker?

The docker image build should be updated to still compile the assets locally, so that the container don't need to download the assets on startup.

#### 🔙 Backwards Compatibility

This should not interfere with older versions as these would still compile their assets locally. 

### 👍 Benefits

- Allows to completely skip the frontend npm install for most users (Saves a ~500MB download of npm dependencies, compared to the ~30MB of compiled assets)
- Allows to skip resource intensive frontend compilation
- Would enable to also improve the npm install for the server dependencies as they could more easily download **only** the production dependencies
- All in all this should improve the "git clone to running Juice Shop time dramatically by skipping / optimizing the most time consuming parts.

### 👎 Downsides

- Local install isn't "ready" to start developing, as they are missing development dependencies
- Requires additional CI config to compile and publish assets to GitHub Releases
- What to do when asset download is failing?

**Comment by bkimminich** [comment]
I like the idea and would see it more as a `postinstall` step, similar to when our XML parser or SQLite download their binaries. If the download doesn't work,then just the normal Angular compilation could happen as it does today, no? The "not ready to dev" could be solved by a separate `npm install:dev` script that does exactly what happens today on regular installation. CI config shouldn't be a big issue imho either. So, other than the effort to implement it, I don't really see any downsides.

**Comment by J12934** [comment]
Okay nice 👍 
I'll try to prototype this in my personal Juice Shop fork.

**Comment by vibhuti019** [comment]
What changes are required in this issue? I would like to contribute to this

**Comment by J12934** [comment]
A lot:

- [x] Compile frontend resources on release and attach as zip on release. (Mostly done, see: https://github.com/J12934/juice-shop/blob/101316c88fb7c1fdf5ad6b1aee632bf7447fdb8c/.github/workflows/publish-frontend-assets.yaml)
- [x] Download compiled frontend assets in a post-install step of the backend npm install (Also mostly done: https://github.com/J12934/juice-shop/commit/101316c88fb7c1fdf5ad6b1aee632bf7447fdb8c#diff-0bbf98d9ceee9217de689ef6cff76e69dfeb23720bf7e71cefcab7c5335f4946)

What was left before I ran out of time was all the hard stuff:

- [ ] Provide a good way for users to turn the "bare bones" installation into a ready development environment where people can still test changes locally
- [ ] Ensure docker build still works correctly
- [ ] Ensure packaged archives still work correctly
- [ ] Ensure sourceforge release still works correctly
- [ ] Ensure that any step in the CI which build or requires the build fronted assets still compiles the assets locally

Thats just of the top of my head, I think there are likely still things I'm forgetting about, as the build process is very interconnected with a lot of things in the Juice Shop test & release pipelines.
