### ISSUE TITLE
"Login CISO" challenge fails when using Google login button [🐛] 

### ISSUE THREAD

**Issue by teodor440** [juice-shop/juice-shop#1491]
# :bug: Bug report

## Description

Logging in as CISO bypassing oauth user doesn't seem to work anymore. There is a short succesful notice when attempting to login, but afterwards I get redirected to login page and no token is issued.

## :microscope: Minimal Reproduction
As in the solution: make a failed login attempt as ciso@juice-sh.op with remember me box checked, refresh and login with oauth

## :deciduous_tree: Your Environment
Locally and heroku

### Additional Information

**Comment by bkimminich** [comment]
The workaround that was in place originally for domains not recognized by the Google App also works here, so the challenge is still solvable. Just not in the way it was originally intended to be solved with.

A more detailed analysis needs to be done to verify if/where the necessary HTTP header with the old email got lost or broken or why Google rejects the login attempts.

**Comment by bkimminich** [comment]
- In a normal OAuth login w/o any `X-User-Email` header: ✔️ 200 from <https://www.googleapis.com/oauth2/v1/userinfo>
- With same email of Google account email in `X-User-Email` header: :x: 403 from <https://www.googleapis.com/oauth2/v1/userinfo>
- With different email address than the one of Google account email in `X-User-Email` header: :x: 403 from <https://www.googleapis.com/oauth2/v1/userinfo>

**Comment by Rishabh-Kumar-07** [comment]
Hi! I would like to work on this. Will follow up soon with PR.

**Comment by bkimminich** [comment]
Hi @Rishabh-Kumar-07, did you make any progress on this or should we consider it "up for grabs" again?

**Comment by Rishabh-Kumar-07** [comment]
Hey. I am engaged otherwise. You can mark it "up for grabs". Apology for the trouble.

**Comment by prince-7** [comment]
I would like to work on this. Please Assign.

**Comment by prince-7** [comment]
I have found some instances where ```x-user-email``` is used instead of ```X-User-Email```, Is that on purpose?

**Comment by bkimminich** [comment]
I don't know, but does it even make a difference for the Browser?

**Comment by prince-7** [comment]
Maybe. Because as I looked into the issue I found that on clicking OAuth button the success message comes up shortly before redirecting back to the login page, and the request which causes this problem seems to be this one.
![owasperror](https://user-images.githubusercontent.com/53997924/105402756-d58da880-5c4d-11eb-8200-ef4dfbb2d118.PNG)

**Comment by adityaofficial10** [comment]
Hey @prince-7 @bkimminich !
If this has stalled, can i work on this?

**Comment by bkimminich** [comment]
Totally, yes! 👍

**Comment by bkimminich** [comment]
After almost 1 month of inactivity, this issue is now back in "who want's to give it a shot?" status! 😁

**Comment by cigar-galaxy82** [comment]
Hi @bkimminich I am almost finished with the other issues I would love to give this a shot

**Comment by Krshivam25** [comment]
Hi @bkimminich this issue is related to Account linking with OAuth. Which supports two industry-standard implicit and authorization code flows.

**Comment by vibhuti019** [comment]
Hi @bkimminich, I would love to give this a shot.

**Comment by mihai02t** [comment]
Hi @bkimminich. If this is stalled and nobody picked it up yet, can I work on it?

**Comment by bkimminich** [comment]
I think I might have to add a new label for this issue... 😬

![image](https://user-images.githubusercontent.com/3531020/115440497-13c84300-a210-11eb-8145-18bfccaa0282.png)

**Comment by bkimminich** [comment]
"Fixed".
