### ISSUE TITLE
[🐛] Logging in with the administrators credentials solves Login Admin Injection challenge

### ISSUE THREAD

**Issue by yaro24** [juice-shop/juice-shop#1492]
# :bug: Bug report

## Description

When using the administrators email and password to login, both the "Password Strength" and "Login Admin" challenges are solved. Since the Login Admin challenge is categorized as Injection I was not expecting this to happen. If the challenge intention is to only "Log in with the administrator's user account.", the category injection is not very fitting.

### Is this a regression?

tested docker containers back to v8.0.0. The behaviour has been this way all along

## :microscope: Minimal Reproduction

login with the administrators correct credentials

## :deciduous_tree: Your Environment

standard docker containers with NODE_ENV=ctf

**Comment by bkimminich** [comment]
This is common in Juice Shop that you can solve some challenges in different ways. The category represents the "usual" way, but others might exist. Also double-solves are expected in some cases. So it's not exactly a bug.

**Comment by yaro24** [comment]
ahh okay. Thanks for the clarification👍🏼
