### ISSUE TITLE
[🐛] Mitigation advice button not fully visible under some browser widths

### ISSUE THREAD

**Issue by ghost** [juice-shop/juice-shop#1496]
# :bug: Bug report

## Description

Under some browser widths the `vulnerability-mitigation-button` on the score board is not fully visible:

![image](https://user-images.githubusercontent.com/65019367/96989978-c3a14a00-1526-11eb-927c-4e320ff4e8d0.png)

### Is this a regression?

Not that I'm aware of (first time user).

## :microscope: Minimal Reproduction

1. Go to the score board
1. Make sure the challenge with description "Provoke an error that is neither very gracefully nor consistently handled." is visible
1. Adjust the browser window width until the mitigation advice is only partly visible

## :deciduous_tree: Your Environment

```
                "NODE_VERSION=12.18.4",
                "YARN_VERSION=1.22.4"
```
```
            "Labels": {
                "maintainer": "Bjoern Kimminich <bjoern.kimminich@owasp.org>",
                "org.opencontainers.image.authors": "Bjoern Kimminich <bjoern.kimminich@owasp.org>",
                "org.opencontainers.image.created": "2020-10-03T14:21:06Z",
                "org.opencontainers.image.description": "Probably the most modern and sophisticated insecure web application",
                "org.opencontainers.image.documentation": "https://help.owasp-juice.shop",
                "org.opencontainers.image.licenses": "MIT",
                "org.opencontainers.image.revision": "09a72b9",
                "org.opencontainers.image.source": "https://github.com/bkimminich/juice-shop",
                "org.opencontainers.image.title": "OWASP Juice Shop",
                "org.opencontainers.image.url": "https://owasp-juice.shop",
                "org.opencontainers.image.vendor": "Open Web Application Security Project",
                "org.opencontainers.image.version": "12.1.0"
            }
```

Firefox 82.0 (64-bit) on Windows 10.

Same behavior seen with Chromium 85.0.4183.121 (Official Build) (64-bit).

**Comment by bkimminich** [comment]
Hi! Thanks for reporting this. We use a responsive UI but it seems for the width of your window it's somewhat "between states". Can you tell me the window width you experienced this in? Thanks!

**Comment by ghost** [comment]
Sure. The window is 1304 pixels wide and so is the attached PNG image.

**Comment by bkimminich** [comment]
The buttons for tutorials might still be half-hidden on some very specific screen widths, but for 1300px it's a bit better now and in general some elements hide later b/c I reduced the description column from 50% to 38% of the width.
![image](https://user-images.githubusercontent.com/3531020/97033922-5dd3b300-1564-11eb-9781-a2bf6811c2ba.png)
