### ISSUE TITLE
[🐛] Missing challenge solve notification on profile page

### ISSUE THREAD

**Issue by cnotin** [juice-shop/juice-shop#1523]
# :bug: Bug report

## Description

The green bar which notifies when a challenge is solved (through the websocket channel) is missing from the profile page. This is missing for some challenges (e.g. the SSRF challenge in the profile picture)

### Is this a regression?
No

## :microscope: Minimal Reproduction

1. Login as any user
2. Go to profile page
3. Change profile picture to solve the SSRF challenge
4. The green notification bar does not appear on the profile page (but appears in another tab on a "normal" page)

## :fire: Exception or Error

None

## :deciduous_tree: Your Environment
Running Docker image (latest, from now)
<pre><code>
/juice-shop $ node -v
v12.19.0
/juice-shop $ npm -v
6.14.8
</code></pre>

### Additional Information
It is not surprising given that the profile page does not use Angular, otherwise it would have been an easy fix :)

**Comment by bkimminich** [comment]
That is actually expected and won't be fixed due to the fact how the whole socket.io notifications are handled. Assuming you work in one tab when you solve a challenge outside Angular (profile page, FTP folder, B2B API etc.) you'll go back to it eventually and there the notification is displayed.

**Comment by cnotin** [comment]
I can understand the limitation but it is unexpected :)

**Comment by bkimminich** [comment]
From a user perspective this would be unexpected, you're right. But we do have the same issue with many other challenges which happen "off screen" from the Angular client: Everything in the `/ftp` directory, everything where direct API interaction is happening etc. The difference of the legacy profile page is, that it looks quite similar to the "normal" UI, so you might not realize first that you are in a different place. Still, I wouldn't invest time and introduce potential side effects with the web sockets to fix it just on the profile page.

**Comment by cnotin** [comment]
Sure I understand! You have the big picture and it makes sense if there are other cases :) 
Thanks for answering
