### ISSUE TITLE
[🐛] Wallet payment for checkout times out

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1527]
# :bug: Bug report

## Description

When using the digital wallet (with sufficient funds) to pay for an order during checkout, the corresponding request in the background will hang and eventually run into a `503 - Service Unavailable` while the frontend just shows no progress.

### Is this a regression?

Yes, but the previous version in which this bug was not present is unknown.

## :microscope: Minimal Reproduction

1. Log in with demo/demo
2. But stuff in basket
3. Proceed through checkout
4. Choose Digital Wallet as payment option
5. Watch Network tab of DevTools before clicking Checkout-button in final order step

**Comment by bkimminich** [comment]
PS: Paying for Deluxe Membership from wallet works fine.

**Comment by cigar-galaxy82** [comment]
Hey @bkimminich I would like to work on this issue

**Comment by bkimminich** [comment]
Much appreciated, @cigar-galaxy82! 👍
