### ISSUE TITLE
docker container built on OS X is broken

### ISSUE THREAD

**Issue by ingben** [juice-shop/juice-shop#153]
Tried to build the Docker container on OS X. The build runs without errors. However, when trying to start the container, I get the following error:

```
module.js:339
    throw err;
    ^

Error: Cannot find module '/juice-shop/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/juice-shop/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

npm info juice-shop@1.23.2 Failed to exec start script
npm ERR! Linux 4.1.13-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! juice-shop@1.23.2 start: `node app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the juice-shop@1.23.2 start script 'node app'.
npm ERR! This is most likely a problem with the juice-shop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app
npm ERR! You can get their info via:
npm ERR!     npm owner ls juice-shop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /juice-shop/npm-debug.log
```

This is caused by the fact that the sqlite module is referenced by `'/juice-shop/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node'`, whereas it is actually located at `/juice-shop/node_modules/sqlite3/lib/binding/node-v47-darwin-x64/node_sqlite3.node`.

Fix (works for me, no testing across other platforms): change the RUN command in the dockerfile to
`RUN /bin/bash -c 'cd /juice-shop; npm install; node bower_install.js; node grunt_minify.js'`

specs

```
docker -v
Docker version 1.9.1, build a34a1d5

OS X 10.11.2
```

**Comment by ingben** [comment]
Oh well. I guess it is actually caused by sqlite3.

Changing the package.json to

```
"sqlite3": "3.1.0",
```

does the trick as well. The change of the dockerfile seems to be obsolete.

Semver ftw? :)

**Comment by bkimminich** [comment]
@ingben: I added that change, although I have no idea why this happened... Could you give it a try please and let me know if it works w/o further alteration on your side?

https://hub.docker.com/r/bkimminich/juice-shop/builds/b6f73xwpecye56gjktqcwjc/

(Just use `snapshot` instead of the default `latest`)

**Comment by ingben** [comment]
@bkimminich The snapshot image is working fine. Using a locally build image based on the develop branch works as well.

I was not able to look into the root cause, though. I.e. why the path used to look up the lib changes from sqlite 3.1.0 to 3.1.1.
