### ISSUE TITLE
[🐳] Add Docker test step to CI job

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1546]
When Docker images were built automatically on DockerHub they were automatically tested via `docker-compose.test.yml`. A similar step would be good to have in the GitHub Action based CI.

**Comment by bkimminich** [comment]
~~Might not be possible due to https://github.com/actions/virtual-environments/issues/183~~

👇👇👇

**Comment by J12934** [comment]
Docker containers run fine on GitHub actions. This should only block the vagrant issue
