### ISSUE TITLE
Docker installation fails

### ISSUE THREAD

**Issue by kairosart** [juice-shop/juice-shop#1581]
After installing juice-shop according to the guide in Docker i got the following error:

`Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR`

I've read the troubleshooting section:

_If all startup checks show (OK) but you see SequelizeDatabaseError: SQLITE_ERROR: no such table: <some table name> errors right afterwards, please check if the file data/juiceshop.sqlite exists. If so just stop and restart your server and this suspected race condition issue shouid go away._

I'm not used to Docker so, can you help me to check it out?

BTW: The project is really interesting but I'm wasting a lot of time to make it work.

**Comment by bkimminich** [comment]
Please post installation issues not as GitHub issues but on Gitter where there's community members who might be able to help and also we can easily chat you through some fix options.

Anyway: In Docker you shouldn't miss any files, they're packaged in the image. The error message you posted doesn't allow any assistance with troubleshooting. I assume restarting the container didn't work?

And to be on the safe side: You're running the official Docker image following the instructions from our own README and not some 3rd party image or docs or even a self-built image?

**Comment by kairosart** [comment]
I've followed this instructions:

1. Install Docker
2. Run docker pull bkimminich/juice-shop
3. Run docker run --rm -p 3000:3000 bkimminich/juice-shop
4. Browse to http://localhost:3000 (on macOS and Windows browse to http://192.168.99.100:3000 if you are using docker-machine instead of the native docker installation)

is it right?

**Comment by bkimminich** [comment]
Yes, that's right! 👍 ... What is the exact log when you start the container?
