### ISSUE TITLE
[🐛] GoodReads link go to "Gideon Defoe, The Pirates! In an Adventure with Scientists"

### ISSUE THREAD

**Issue by AndrzejRPiotrowski** [juice-shop/juice-shop#1583]
# :bug: Bug report

## Description

A clear and concise description of the problem...

### Is this a regression?

Yes, check online - https://www.goodreads.com/review/edit/47129532 

## :microscope: Minimal Reproduction

1. Go to  https://github.com/bkimminich/juice-shop
2. Click on  in section "official companion guide"
3. You need to log into service.
4. https://www.goodreads.com/review/edit/47129532 

## :fire: Exception or Error

![11](https://user-images.githubusercontent.com/1153056/107625068-129cf780-6c5c-11eb-8fde-a9f625674296.png)

## :deciduous_tree: Your Environment

Windows - Chrome

**Comment by bkimminich** [comment]
Thanks for noticing! Link should be

https://www.goodreads.com/review/edit/49557240
