### ISSUE TITLE
Race condition between file reset and i18n initialization [🐛] 

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1585]
# :bug: Bug report

## Description

The function `lib/startup/restoreOverwrittenFilesWithOriginals` (called in `server.js` early on) copies the i18n locale files into the folder `/i18n` where they are expected to exist by the `i18n.configure` call (later in `server.js`) or later, particularly when it tries to do auto-reloading whenever a locale file changes, which might be triggered by the still ongoing copy job.

Smells like a race condition. Affects test runs frequently but also regular server starts sometimes.

### Is this a regression?

Present since i18n with auto-reloading was introduced, but it seems to occur more often recently.

**Comment by adityaofficial10** [comment]
Hey @bkimminich !
Can I work on this issue?

**Comment by bkimminich** [comment]
Totally *yes*, you can! 👍

**Comment by adityaofficial10** [comment]
@bkimminich 
Can you tell me an instance where the copying process takes place so that I can actually reproduce the error locally?

**Comment by bkimminich** [comment]
This copying always takes place on server start. The error doesn't always occur, though.

**Comment by adityaofficial10** [comment]
@bkimminich 
So we can just do one thing here and that is to make sure that the copying process finishes before the files are accessed anywhere.
Will that suffice?

**Comment by bkimminich** [comment]
Yeah, I think that's the only sure way to get rid of this issue.

**Comment by adityaofficial10** [comment]
@bkimminich 
I've added two async functions to take care of the order of the operations.
Will this suffice?
<img width="881" alt="Screenshot 2021-02-21 at 10 29 55 PM" src="https://user-images.githubusercontent.com/65034276/108632405-c2603980-7494-11eb-95e5-15bf9725ad9d.png">
The functions are as follows:
<img width="555" alt="Screenshot 2021-02-21 at 10 33 30 PM" src="https://user-images.githubusercontent.com/65034276/108632511-5f22d700-7495-11eb-8bc5-0409d1a511e0.png">
<img width="434" alt="Screenshot 2021-02-21 at 10 36 53 PM" src="https://user-images.githubusercontent.com/65034276/108632514-62b65e00-7495-11eb-847d-1da22218c850.png">

**Comment by bkimminich** [comment]
Looks good to me, gotta test it next week. 

Maybe @J12934 can also take a look b/c he's our official async-await-expert... 😁 Btw, does this change affect server start-up time calculation? 🧮

**Comment by bkimminich** [comment]
Might be worth its own stsrtup time task tracking, maybe? Now that it's async code that should be possible, similar to how data creator is measured.

**Comment by adityaofficial10** [comment]
@bkimminich 
Yeah sure..
I was thinking on the same lines.
Should I go ahead with the PR?
