### ISSUE TITLE
[🐛] Typo in Pwning OWASP Juice Shop？

### ISSUE THREAD

**Issue by TracingDrone** [juice-shop/juice-shop#1594]
# :bug: Typo in Pwning OWASP Juice Shop

## Description

I found a typo in the hints of Admin Registration. I`m not a native English speaker, but I think the word "then" should be repalced by "the".

## :microscope: Minimal Reproduction

At "https://pwning.owasp-juice.shop/part2/improper-input-validation.html#register-as-a-user-with-administrator-privileges"

![图片](https://user-images.githubusercontent.com/31869612/109772937-9170c900-7c39-11eb-89eb-1711cb3aa541.png)

![图片](https://user-images.githubusercontent.com/31869612/109772897-861d9d80-7c39-11eb-8a2e-f518a74a300a.png)

**Comment by chinggg** [comment]
I agree with you! That could be modified easily.
