### ISSUE TITLE
Missing EXIF data

### ISSUE THREAD

**Issue by dt4nn3r** [juice-shop/juice-shop#1597]
It appears according to online walkthroughs that the file 3d_keychain.jpg is supposed to have EXIF data containing a bread crumb to solving a challenge. The EXIF data was removed in June 2019. I am running the latest version, 12.6.1. Additionally, the score-board hint points to the permafrost product instead of the keychain. No images in the products contain exif data that would be beneficial to this challenge.

**Comment by bkimminich** [comment]
![image](https://user-images.githubusercontent.com/3531020/110175372-ec551c80-7e01-11eb-9741-ca77702b0253.png)

This is from the staging environment, where the hint points to the right product. But you are right about the missing EXIF data. I'll revert that change from 2019 where the image sizes were optimized and the meta data got lost unintentionally.
