### ISSUE TITLE
Empty block is used as the true branch of 'if' statement.

### ISSUE THREAD

**Issue by Krshivam25** [juice-shop/juice-shop#1606]
There is an Empty block used as the true branch of 'if' statement.
file location : 
frontend/src/app/welcome/welcome.component.ts 
 line no. 25 of code

**Comment by J12934** [comment]
https://github.com/bkimminich/juice-shop/blob/a5be4a42afdea27ca3eccc9e1c7aa4c6859345e0/frontend/src/app/welcome-banner/welcome-banner.component.ts#L22-L28

🤔 Mhh that does not appear to be true?

This is a typescript constructor with parameter properties: https://www.typescriptlang.org/docs/handbook/2/classes.html#parameter-properties. These arguments get automatically assigned as class properties.

**Comment by bkimminich** [comment]
No, its about this: https://github.com/bkimminich/juice-shop/blob/aa4bfe15c55a01008e033ddab4d2532b3e2c9760/frontend/src/app/welcome/welcome.component.ts#L25

**Comment by Krshivam25** [comment]
Hi, @bkimminich I would like to resolve this please assign it.

**Comment by J12934** [comment]
Whoops, got the wrong welcome ts file, sorry 🤦😄

**Comment by bkimminich** [comment]
> Hi, @bkimminich I would like to resolve this please assign it.

Well, then you should have just sent a PR in the first place... by the time I was done reading your issue, I was already done fixing it, too... 😉
