### ISSUE TITLE
Mime error when installing Juice from source on linux machine

### ISSUE THREAD

**Issue by demathieu** [juice-shop/juice-shop#161]
Hi,

It seems I can not install Juice from source on a nodejs server running on linux.
The installing goes smoothly but when I access the server through my browser (both chrome and firefox) I get those errors: 

Refused to execute script from 'http://localhost:3000/bower_components/underscore/underscore.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:3000/bower_components/string/dist/string.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:3000/bower_components/moment/min/moment.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:3000/bower_components/jquery/dist/jquery.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 'http://localhost:3000/bower_components/bootstrap/dist/js/bootstrap.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
localhost/:1 Refused to execute script from 

When I run Juice on an osx server and use my linux machine as a client to see the pages everything works is fine. Also using docker works but I need to be able to modify the source files. 

Same issue for node version: 6.1, 6.3, 0.12, 4.x
npm version: 3.8.6
linux version: Linux version 3.19.0-32-generic (buildd@lgw01-43) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015

**Comment by bkimminich** [comment]
Can you please verify if Bower was able to install the declared dependencies? Should put them into `app/bower_components`. If not, could this be a proxy issue?

**Comment by bkimminich** [comment]
@demathieu Could you please try a pre-packaged distribution for your node.js version? https://github.com/bkimminich/juice-shop/releases

If this works then there is probably something going wrong during your `npm install` execution.

**Comment by demathieu** [comment]
I tried it again using those packages, looks like everything is working now. 
Thank you

**Comment by scull06** [comment]
I found a solution to this problem when you clone from github. After clone you may to do

**bower install**

cause bower components are not installed.

**Comment by bkimminich** [comment]
When you do `npm install` it triggers a script that also installs bower components. So, separate `bower install` shouldn't be necessary.

If the problem persists, please attach a log.

Am 1. August 2016 11:47:23 MESZ, schrieb scull06 notifications@github.com:
