### ISSUE TITLE
Heroku error when opening website.

### ISSUE THREAD

**Issue by ghost** [juice-shop/juice-shop#1611]
After you use the Heroku launch button after the juice shop is deployed on Heroku when going to the site you get, "An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail"

**Comment by bkimminich** [comment]
Can you provide that mentioned Heroku logfile, otherwise there's no way we could help you.

**Comment by ghost** [comment]
> Can you provide that mentioned Heroku logfile, otherwise there's no way we could help you.

The log from heroku:



-----> Building on the Heroku-20 stack

-----> Determining which buildpack to use for this app

-----> Node.js app detected

       

-----> Creating runtime environment

       

       NPM_CONFIG_LOGLEVEL=error

       NODE_VERBOSE=false

       NODE_ENV=production

       NODE_MODULES_CACHE=true

       

-----> Installing binaries

       engines.node (package.json):  10 - 14

       engines.npm (package.json):   unspecified (use default)

       

       Resolving node version 10 - 14...

       Downloading and installing node 14.16.0...

       Using default npm version: 6.14.11

       

-----> Installing dependencies

       Installing node modules (package.json)

       

       > sqlite3@5.0.2 install /tmp/build_ac2d316d/node_modules/sqlite3

       > node-pre-gyp install --fallback-to-build

       

       [sqlite3] Success: "/tmp/build_ac2d316d/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" is installed via remote

       

       > iltorb@2.4.5 install /tmp/build_ac2d316d/node_modules/iltorb

       > node ./scripts/install.js || node-gyp rebuild

       

       info looking for cached prebuild @ /tmp/npmcache.mmOCv/_prebuilds/c57c4d-iltorb-v2.4.5-node-v83-linux-x64.tar.gz

       http request GET https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v83-linux-x64.tar.gz

       http 404 https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v83-linux-x64.tar.gz

       WARN install No prebuilt binaries found (target=14.16.0 runtime=node arch=x64 libc= platform=linux)

       make: Entering directory '/tmp/build_ac2d316d/node_modules/iltorb/build'

         CC(target) Release/obj.target/iltorb/brotli/c/common/dictionary.o

         CC(target) Release/obj.target/iltorb/brotli/c/common/transform.o

         CC(target) Release/obj.target/iltorb/brotli/c/dec/bit_reader.o

         CC(target) Release/obj.target/iltorb/brotli/c/dec/decode.o

         CC(target) Release/obj.target/iltorb/brotli/c/dec/huffman.o

         CC(target) Release/obj.target/iltorb/brotli/c/dec/state.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/backward_references.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/backward_references_hq.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/bit_cost.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/block_splitter.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/brotli_bit_stream.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/cluster.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/compress_fragment.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/compress_fragment_two_pass.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/dictionary_hash.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/encode.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/encoder_dict.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/entropy_encode.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/histogram.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/literal_cost.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/memory.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/metablock.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/static_dict.o

         CC(target) Release/obj.target/iltorb/brotli/c/enc/utf8_util.o

         CXX(target) Release/obj.target/iltorb/src/common/allocator.o

         CXX(target) Release/obj.target/iltorb/src/common/stream_coder.o

         CXX(target) Release/obj.target/iltorb/src/dec/stream_decode.o

         CXX(target) Release/obj.target/iltorb/src/dec/stream_decode_worker.o

         CXX(target) Release/obj.target/iltorb/src/enc/stream_encode.o

         CXX(target) Release/obj.target/iltorb/src/enc/stream_encode_worker.o

         CXX(target) Release/obj.target/iltorb/src/iltorb.o

       In file included from ../../nan/nan.h:56,

                        from ../src/iltorb.cc:1:

       /app/.cache/node-gyp/14.16.0/include/node/node.h:778:51: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>)’ to ‘node::addon_context_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>, void*)’} [-Wcast-function-type]

         778 |       (node::addon_context_register_func) (regfunc),                  \

             |                                                   ^

       /app/.cache/node-gyp/14.16.0/include/node/node.h:796:3: note: in expansion of macro ‘NODE_MODULE_CONTEXT_AWARE_X’

         796 |   NODE_MODULE_CONTEXT_AWARE_X(modname, regfunc, NULL, 0)

             |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~

       /app/.cache/node-gyp/14.16.0/include/node/node.h:827:3: note: in expansion of macro ‘NODE_MODULE_CONTEXT_AWARE’

         827 |   NODE_MODULE_CONTEXT_AWARE(NODE_GYP_MODULE_NAME,                     \

             |   ^~~~~~~~~~~~~~~~~~~~~~~~~

       ../src/iltorb.cc:8:1: note: in expansion of macro ‘NODE_MODULE_INIT’

           8 | NODE_MODULE_INIT() {

             | ^~~~~~~~~~~~~~~~

         SOLINK_MODULE(target) Release/obj.target/iltorb.node

         COPY Release/iltorb.node

         COPY ../build/bindings/iltorb.node

         TOUCH Release/obj.target/action_after_build.stamp

       make: Leaving directory '/tmp/build_ac2d316d/node_modules/iltorb/build'

       

       > libxmljs2@0.26.7 install /tmp/build_ac2d316d/node_modules/libxmljs2

       > node-pre-gyp install --fallback-to-build --loglevel http

       

       node-pre-gyp http GET https://github.com/marudor/libxmljs2/releases/download/v0.26.7/node-v83-linux-x64-glibc.tar.gz

       [libxmljs2] Success: "/tmp/build_ac2d316d/node_modules/libxmljs2/build/Release/xmljs.node" is installed via remote

       

       > core-js@2.6.12 postinstall /tmp/build_ac2d316d/node_modules/core-js

       > node -e "try{require('./postinstall')}catch(e){}"

       

       

       > juice-shop@12.6.1 postinstall /tmp/build_ac2d316d

       > cd frontend && npm install && cd .. && npm run build

       

       

       > core-js@3.6.5 postinstall /tmp/build_ac2d316d/frontend/node_modules/@angular-devkit/build-angular/node_modules/core-js

       > node -e "try{require('./postinstall')}catch(e){}"

       

       

       > @fortawesome/fontawesome-common-types@0.2.35 postinstall /tmp/build_ac2d316d/frontend/node_modules/@fortawesome/fontawesome-common-types

       > node attribution.js

       

       Font Awesome Free 0.2.35 by @fontawesome - https://fontawesome.com

       License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

       

       

       > @angular/cli@11.2.6 postinstall /tmp/build_ac2d316d/frontend/node_modules/@angular/cli

       > node ./bin/postinstall/script.js

       

       

       > @fortawesome/fontawesome-svg-core@1.2.35 postinstall /tmp/build_ac2d316d/frontend/node_modules/@fortawesome/fontawesome-svg-core

       > node attribution.js

       

       Font Awesome Free 1.2.35 by @fontawesome - https://fontawesome.com

       License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

       

       

       > @fortawesome/free-brands-svg-icons@5.15.3 postinstall /tmp/build_ac2d316d/frontend/node_modules/@fortawesome/free-brands-svg-icons

       > node attribution.js

       

       Font Awesome Free 5.15.3 by @fontawesome - https://fontawesome.com

       License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

       

       

       > @fortawesome/free-regular-svg-icons@5.15.3 postinstall /tmp/build_ac2d316d/frontend/node_modules/@fortawesome/free-regular-svg-icons

       > node attribution.js

       

       Font Awesome Free 5.15.3 by @fontawesome - https://fontawesome.com

       License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

       

       

       > @fortawesome/free-solid-svg-icons@5.15.3 postinstall /tmp/build_ac2d316d/frontend/node_modules/@fortawesome/free-solid-svg-icons

       > node attribution.js

       

       Font Awesome Free 5.15.3 by @fontawesome - https://fontawesome.com

       License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

       

       

       > core-js@3.9.1 postinstall /tmp/build_ac2d316d/frontend/node_modules/core-js

       > node -e "try{require('./postinstall')}catch(e){}"

       

       

       > frontend@12.6.1 postinstall /tmp/build_ac2d316d/frontend

       > ngcc --tsconfig "./src/tsconfig.app.json"

       

       Compiling @angular/animations : fesm2015 as esm2015

       Compiling @angular/animations : esm2015 as esm2015

       Compiling @angular/animations : main as umd

       Compiling @angular/core : fesm2015 as esm2015

       Compiling @angular/core : esm2015 as esm2015

       Compiling @angular/core : main as umd

       Compiling @angular/animations/browser : fesm2015 as esm2015

       Compiling @angular/animations/browser : esm2015 as esm2015

       Compiling @angular/animations/browser : main as umd

       Compiling @angular/animations/browser/testing : fesm2015 as esm2015

       Compiling @angular/animations/browser/testing : esm2015 as esm2015

       Compiling @angular/animations/browser/testing : main as umd

       Compiling @angular/common : fesm2015 as esm2015

       Compiling @angular/common : esm2015 as esm2015

       Compiling @angular/common : main as umd

       Compiling @angular/cdk/clipboard : fesm2015 as esm2015

       Compiling @angular/cdk/clipboard : esm2015 as esm2015

       Compiling @angular/cdk/clipboard : main as umd

       Compiling @angular/cdk/platform : fesm2015 as esm2015

       Compiling @angular/cdk/platform : esm2015 as esm2015

       Compiling @angular/cdk/platform : main as umd

       Compiling @angular/cdk/bidi : fesm2015 as esm2015

       Compiling @angular/cdk/bidi : esm2015 as esm2015

       Compiling @angular/cdk/bidi : main as umd

       Compiling @angular/cdk/collections : fesm2015 as esm2015

       Compiling @angular/cdk/collections : esm2015 as esm2015

       Compiling @angular/cdk/collections : main as umd

       Compiling @angular/cdk/scrolling : fesm2015 as esm2015

       Compiling @angular/cdk/scrolling : esm2015 as esm2015

       Compiling @angular/cdk/scrolling : main as umd

       Compiling @angular/cdk/drag-drop : fesm2015 as esm2015

       Compiling @angular/cdk/drag-drop : esm2015 as esm2015

       Compiling @angular/cdk/drag-drop : main as umd

       Compiling @angular/common/http : fesm2015 as esm2015

       Compiling @angular/common/http : esm2015 as esm2015

       Compiling @angular/common/http : main as umd

       Compiling @angular/common/http/testing : fesm2015 as esm2015

       Compiling @angular/common/http/testing : esm2015 as esm2015

       Compiling @angular/common/http/testing : main as umd

       Compiling @angular/flex-layout/core : es2015 as esm2015

       Compiling @angular/flex-layout/core : main as umd

       Compiling @angular/flex-layout/core : module as esm5

       Compiling @angular/platform-browser : fesm2015 as esm2015

       Compiling @angular/platform-browser : esm2015 as esm2015

       Compiling @angular/platform-browser : main as umd

       Compiling @angular/flex-layout/extended : es2015 as esm2015

       Compiling @angular/flex-layout/extended : main as umd

       Compiling @angular/flex-layout/extended : module as esm5

       Compiling @angular/flex-layout/flex : es2015 as esm2015

       Compiling @angular/flex-layout/flex : main as umd

       Compiling @angular/flex-layout/flex : module as esm5

       Compiling @angular/flex-layout/grid : es2015 as esm2015

       Compiling @angular/flex-layout/grid : main as umd

       Compiling @angular/flex-layout/grid : module as esm5

       Compiling @angular/flex-layout : es2015 as esm2015

       Compiling @angular/flex-layout : main as umd

       Compiling @angular/flex-layout : module as esm5

       Compiling @angular/http : fesm2015 as esm2015

       Compiling @angular/http : fesm5 as esm5

       Compiling @angular/http : esm2015 as esm2015

       Compiling @angular/http : esm5 as esm5

       Compiling @angular/http : main as umd

       Compiling @angular/http/testing : fesm2015 as esm2015

       Compiling @angular/http/testing : fesm5 as esm5

       Compiling @angular/http/testing : esm2015 as esm2015

       Compiling @angular/http/testing : esm5 as esm5

       Compiling @angular/http/testing : main as umd

       Compiling @angular/cdk/keycodes : fesm2015 as esm2015

       Compiling @angular/cdk/keycodes : esm2015 as esm2015

       Compiling @angular/cdk/keycodes : main as umd

       Compiling @angular/cdk/observers : fesm2015 as esm2015

       Compiling @angular/cdk/observers : esm2015 as esm2015

       Compiling @angular/cdk/observers : main as umd

       Compiling @angular/cdk/a11y : fesm2015 as esm2015

       Compiling @angular/cdk/a11y : esm2015 as esm2015

       Compiling @angular/cdk/a11y : main as umd

       Compiling @angular/platform-browser/animations : fesm2015 as esm2015

       Compiling @angular/platform-browser/animations : esm2015 as esm2015

       Compiling @angular/platform-browser/animations : main as umd

       Compiling @angular/forms : fesm2015 as esm2015

       Compiling @angular/forms : esm2015 as esm2015

       Compiling @angular/forms : main as umd

       Compiling @angular/material/core : fesm2015 as esm2015

       Compiling @angular/material/core : esm2015 as esm2015

       Compiling @angular/material/core : main as umd

       Compiling @angular/material/badge : fesm2015 as esm2015

       Compiling @angular/material/badge : esm2015 as esm2015

       Compiling @angular/material/badge : main as umd

       Compiling @angular/cdk/portal : fesm2015 as esm2015

       Compiling @angular/cdk/portal : esm2015 as esm2015

       Compiling @angular/cdk/portal : main as umd

       Compiling @angular/cdk/overlay : fesm2015 as esm2015

       Compiling @angular/cdk/overlay : esm2015 as esm2015

       Compiling @angular/cdk/overlay : main as umd

       Compiling @angular/cdk/layout : fesm2015 as esm2015

       Compiling @angular/cdk/layout : esm2015 as esm2015

       Compiling @angular/cdk/layout : main as umd

       Compiling @angular/material/bottom-sheet : fesm2015 as esm2015

       Compiling @angular/material/bottom-sheet : esm2015 as esm2015

       Compiling @angular/material/bottom-sheet : main as umd

       Compiling @angular/material/button-toggle : fesm2015 as esm2015

       Compiling @angular/material/button-toggle : esm2015 as esm2015

       Compiling @angular/material/button-toggle : main as umd

       Compiling @angular/material/checkbox : fesm2015 as esm2015

       Compiling @angular/material/checkbox : esm2015 as esm2015

       Compiling @angular/material/checkbox : main as umd

       Compiling @angular/material/form-field : fesm2015 as esm2015

       Compiling @angular/material/form-field : esm2015 as esm2015

       Compiling @angular/material/form-field : main as umd

       Compiling @angular/material/chips : fesm2015 as esm2015

       Compiling @angular/material/chips : esm2015 as esm2015

       Compiling @angular/material/chips : main as umd

       Compiling @angular/material/button : fesm2015 as esm2015

       Compiling @angular/material/button : esm2015 as esm2015

       Compiling @angular/material/button : main as umd

       Compiling @angular/material/dialog : fesm2015 as esm2015

       Compiling @angular/material/dialog : esm2015 as esm2015

       Compiling @angular/material/dialog : main as umd

       Compiling @angular/cdk/text-field : fesm2015 as esm2015

       Compiling @angular/cdk/text-field : esm2015 as esm2015

       Compiling @angular/cdk/text-field : main as umd

       Compiling @angular/material/input : fesm2015 as esm2015

       Compiling @angular/material/input : esm2015 as esm2015

       Compiling @angular/material/input : main as umd

       Compiling @angular/material/datepicker : fesm2015 as esm2015

       Compiling @angular/material/datepicker : esm2015 as esm2015

       Compiling @angular/material/datepicker : main as umd

       Compiling @angular/cdk/accordion : fesm2015 as esm2015

       Compiling @angular/cdk/accordion : esm2015 as esm2015

       Compiling @angular/cdk/accordion : main as umd

       Compiling @angular/material/expansion : fesm2015 as esm2015

       Compiling @angular/material/expansion : esm2015 as esm2015

       Compiling @angular/material/expansion : main as umd

       Compiling @angular/material/grid-list : fesm2015 as esm2015

       Compiling @angular/material/grid-list : esm2015 as esm2015

       Compiling @angular/material/grid-list : main as umd

       Compiling @angular/material/icon : fesm2015 as esm2015

       Compiling @angular/material/icon : esm2015 as esm2015

       Compiling @angular/material/icon : main as umd

       Compiling @angular/material/icon/testing : fesm2015 as esm2015

       Compiling @angular/material/icon/testing : esm2015 as esm2015

       Compiling @angular/material/icon/testing : main as umd

       Compiling @angular/material/divider : fesm2015 as esm2015

       Compiling @angular/material/divider : esm2015 as esm2015

       Compiling @angular/material/divider : main as umd

       Compiling @angular/material/list : fesm2015 as esm2015

       Compiling @angular/material/list : esm2015 as esm2015

       Compiling @angular/material/list : main as umd

       Compiling @angular/material/menu : fesm2015 as esm2015

       Compiling @angular/material/menu : esm2015 as esm2015

       Compiling @angular/material/menu : main as umd

       Compiling @angular/material/progress-spinner : fesm2015 as esm2015

       Compiling @angular/material/progress-spinner : esm2015 as esm2015

       Compiling @angular/material/progress-spinner : main as umd

       Compiling @angular/material/radio : fesm2015 as esm2015

       Compiling @angular/material/radio : esm2015 as esm2015

       Compiling @angular/material/radio : main as umd

       Compiling @angular/material/sidenav : fesm2015 as esm2015

       Compiling @angular/material/sidenav : esm2015 as esm2015

       Compiling @angular/material/sidenav : main as umd

       Compiling @angular/material/slide-toggle : fesm2015 as esm2015

       Compiling @angular/material/slide-toggle : esm2015 as esm2015

       Compiling @angular/material/slide-toggle : main as umd

       Compiling @angular/material/slider : fesm2015 as esm2015

       Compiling @angular/material/slider : esm2015 as esm2015

       Compiling @angular/material/slider : main as umd

       Compiling @angular/material/snack-bar : fesm2015 as esm2015

       Compiling @angular/material/snack-bar : esm2015 as esm2015

       Compiling @angular/material/snack-bar : main as umd

       Compiling @angular/cdk/stepper : fesm2015 as esm2015

       Compiling @angular/cdk/stepper : esm2015 as esm2015

       Compiling @angular/cdk/stepper : main as umd

       Compiling @angular/material/stepper : fesm2015 as esm2015

       Compiling @angular/material/stepper : esm2015 as esm2015

       Compiling @angular/material/stepper : main as umd

       Compiling @angular/cdk/table : fesm2015 as esm2015

       Compiling @angular/cdk/table : esm2015 as esm2015

       Compiling @angular/cdk/table : main as umd

       Compiling @angular/material/select : fesm2015 as esm2015

       Compiling @angular/material/select : esm2015 as esm2015

       Compiling @angular/material/select : main as umd

       Compiling @angular/material/tooltip : fesm2015 as esm2015

       Compiling @angular/material/tooltip : esm2015 as esm2015

       Compiling @angular/material/tooltip : main as umd

       Compiling @angular/material/paginator : fesm2015 as esm2015

       Compiling @angular/material/paginator : esm2015 as esm2015

       Compiling @angular/material/paginator : main as umd

       Compiling @angular/material/sort : fesm2015 as esm2015

       Compiling @angular/material/sort : esm2015 as esm2015

       Compiling @angular/material/sort : main as umd

       Compiling @angular/material/table : fesm2015 as esm2015

       Compiling @angular/material/table : esm2015 as esm2015

       Compiling @angular/material/table : main as umd

       Compiling @angular/material/tabs : fesm2015 as esm2015

       Compiling @angular/material/tabs : esm2015 as esm2015

       Compiling @angular/material/tabs : main as umd

       Compiling @angular/material/toolbar : fesm2015 as esm2015

       Compiling @angular/material/toolbar : esm2015 as esm2015

       Compiling @angular/material/toolbar : main as umd

       Compiling @angular/cdk/tree : fesm2015 as esm2015

       Compiling @angular/cdk/tree : esm2015 as esm2015

       Compiling @angular/cdk/tree : main as umd

       Compiling @angular/material/tree : fesm2015 as esm2015

       Compiling @angular/material/tree : esm2015 as esm2015

       Compiling @angular/material/tree : main as umd

       Compiling @angular/core/testing : fesm2015 as esm2015

       Compiling @angular/core/testing : esm2015 as esm2015

       Compiling @angular/core/testing : main as umd

       Compiling @angular/platform-browser-dynamic : fesm2015 as esm2015

       Compiling @angular/platform-browser-dynamic : esm2015 as esm2015

       Compiling @angular/platform-browser-dynamic : main as umd

       Compiling @angular/platform-browser/testing : fesm2015 as esm2015

       Compiling @angular/platform-browser/testing : esm2015 as esm2015

       Compiling @angular/platform-browser/testing : main as umd

       Compiling @angular/compiler/testing : fesm2015 as esm2015

       Compiling @angular/compiler/testing : esm2015 as esm2015

       Compiling @angular/compiler/testing : main as umd

       Compiling @angular/platform-browser-dynamic/testing : fesm2015 as esm2015

       Compiling @angular/platform-browser-dynamic/testing : esm2015 as esm2015

       Compiling @angular/platform-browser-dynamic/testing : main as umd

       Compiling @angular/common/testing : fesm2015 as esm2015

       Compiling @angular/common/testing : esm2015 as esm2015

       Compiling @angular/common/testing : main as umd

       Compiling @angular/router : fesm2015 as esm2015

       Compiling @angular/router : esm2015 as esm2015

       Compiling @angular/router : main as umd

       Compiling @angular/router/testing : fesm2015 as esm2015

       Compiling @angular/router/testing : esm2015 as esm2015

       Compiling @angular/router/testing : main as umd

       Compiling @angular/material/progress-bar : fesm2015 as esm2015

       Compiling @angular/material/progress-bar : esm2015 as esm2015

       Compiling @angular/material/progress-bar : main as umd

       Compiling @angular/material/card : fesm2015 as esm2015

       Compiling @angular/material/card : esm2015 as esm2015

       Compiling @angular/material/card : main as umd

       Compiling @angular-material-extensions/password-strength : fesm2015 as esm2015

       Compiling @angular-material-extensions/password-strength : fesm5 as esm5

       Compiling @angular-material-extensions/password-strength : esm2015 as esm2015

       Compiling @angular-material-extensions/password-strength : esm5 as esm5

       Compiling @angular-material-extensions/password-strength : main as umd

       Compiling @nguniversal/common : fesm2015 as esm2015

       Compiling @nguniversal/common : esm2015 as esm2015

       Compiling @nguniversal/common : main as umd

       Compiling @nguniversal/common/tokens : fesm2015 as esm2015

       Compiling @nguniversal/common/tokens : esm2015 as esm2015

       Compiling @nguniversal/common/tokens : main as umd

       Compiling @nguniversal/express-engine/tokens : fesm2015 as esm2015

       Compiling @nguniversal/express-engine/tokens : esm2015 as esm2015

       Compiling @nguniversal/express-engine/tokens : main as umd

       Compiling @ngx-translate/core : fesm2015 as esm2015

       Compiling @ngx-translate/core : esm2015 as esm2015

       Compiling @ngx-translate/core : main as umd

       Compiling @ngx-translate/http-loader : fesm2015 as esm2015

       Compiling @ngx-translate/http-loader : esm2015 as esm2015

       Compiling @ngx-translate/http-loader : main as umd

       Compiling anuglar2-qrcode : main as umd

       Compiling anuglar2-qrcode : module as esm5

       Compiling @angular/material/autocomplete : fesm2015 as esm2015

       Compiling @angular/material/autocomplete : esm2015 as esm2015

       Compiling @angular/material/autocomplete : main as umd

       Compiling ng-mat-search-bar : fesm2015 as esm2015

       Compiling ng-mat-search-bar : esm2015 as esm2015

       Compiling ng-mat-search-bar : main as umd

       Compiling ng-simple-slideshow : es2015 as esm2015

       Compiling ng-simple-slideshow : main as umd

       Compiling ng-simple-slideshow : module as esm5

       Compiling ng2-file-upload : fesm2015 as esm2015

       Compiling ng2-file-upload : fesm5 as esm5

       Compiling ng2-file-upload : esm2015 as esm2015

       Compiling ng2-file-upload : esm5 as esm5

       Compiling ng2-file-upload : main as umd

       Compiling ngx-window-token : fesm2015 as esm2015

       Compiling ngx-window-token : esm2015 as esm2015

       Compiling ngx-window-token : main as umd

       Compiling ngx-clipboard : fesm2015 as esm2015

       Compiling ngx-clipboard : esm2015 as esm2015

       Compiling ngx-clipboard : main as umd

       Compiling ngx-cookie-service : fesm2015 as esm2015

       Compiling ngx-cookie-service : esm2015 as esm2015

       Compiling ngx-cookie-service : main as umd

       Compiling ngx-spinner : fesm2015 as esm2015

       Compiling ngx-spinner : esm2015 as esm2015

       Compiling ngx-spinner : main as umd

       added 1372 packages from 600 contributors and audited 1718 packages in 176.987s

       

       94 packages are looking for funding

         run `npm fund` for details

       

       found 0 vulnerabilities

       

       

       > juice-shop@12.6.1 build /tmp/build_ac2d316d

       > cd frontend && node ./node_modules/@angular/cli/bin/ng build --aot --prod --output-hashing=none --vendor-chunk=true --source-map=false

       

       Warning: Using differential loading with targets ES5 and ES2016 or higher may

       cause problems. Browsers with support for ES2015 will load the ES2016+ scripts

       referenced with script[type="module"] but they may not support ES2016+ syntax.

       - Generating browser application bundles...

       ✔ Browser application bundle generation complete.

       - Generating ES5 bundles for differential loading...

       ✔ ES5 bundle generation complete.

       - Copying assets...

       ✔ Copying assets complete.

       - Generating index html...

       ✔ Index html generation complete.

       

       Initial Chunk Files | Names                |      Size

       vendor-es5.js       | vendor               |   1.49 MB

       vendor-es2018.js    | vendor               |   1.35 MB

       styles.css          | styles               | 578.83 kB

       main-es5.js         | main                 | 388.01 kB

       main-es2018.js      | main                 | 366.46 kB

       polyfills-es5.js    | polyfills-es5        | 149.41 kB

       polyfills-es2018.js | polyfills            |  56.83 kB

       runtime-es2018.js   | runtime              |   2.21 kB

       runtime-es5.js      | runtime              |   2.21 kB

       

       | Initial ES5 Total    |   2.59 MB

       | Initial ES2018 Total |   2.33 MB

       

       Lazy Chunk Files    | Names                |      Size

       tutorial-es5.js     | tutorial             |  29.39 kB

       tutorial-es2018.js  | tutorial             |  24.17 kB

       

       Build at: 2021-03-27T18:28:41.727Z - Hash: c478cc159ff39e3188a1 - Time: 217054ms

       

       Warning: Zone.js does not support native async/await in ES2017+.

       These blocks are not intercepted by zone.js and will not triggering change detection.

       See: https://github.com/angular/zone.js/pull/1140 for more information.

       

       

       added 1816 packages from 1337 contributors and audited 1825 packages in 499.441s

       

       92 packages are looking for funding

         run `npm fund` for details

       

       found 17 vulnerabilities (3 low, 7 moderate, 4 high, 3 critical)

         run `npm audit fix` to fix them, or `npm audit` for details

       

-----> Build

       Running build

       

       > juice-shop@12.6.1 build /tmp/build_ac2d316d

       > cd frontend && node ./node_modules/@angular/cli/bin/ng build --aot --prod --output-hashing=none --vendor-chunk=true --source-map=false

       

Warning: Using differential loading with targets ES5 and ES2016 or higher may

cause problems. Browsers with support for ES2015 will load the ES2016+ scripts

referenced with script[type="module"] but they may not support ES2016+ syntax.

- Generating browser application bundles...

✔ Browser application bundle generation complete.

- Generating ES5 bundles for differential loading...

✔ ES5 bundle generation complete.

- Copying assets...

✔ Copying assets complete.

- Generating index html...

✔ Index html generation complete.

       

       Initial Chunk Files | Names                |      Size

       vendor-es5.js       | vendor               |   1.49 MB

       vendor-es2018.js    | vendor               |   1.35 MB

       styles.css          | styles               | 578.83 kB

       main-es5.js         | main                 | 388.01 kB

       main-es2018.js      | main                 | 366.46 kB

       polyfills-es5.js    | polyfills-es5        | 149.41 kB

Warning: Zone.js does not support native async/await in ES2017+.

These blocks are not intercepted by zone.js and will not triggering change detection.

See: https://github.com/angular/zone.js/pull/1140 for more information.

       polyfills-es2018.js | polyfills            |  56.83 kB

       runtime-es2018.js   | runtime              |   2.21 kB

       runtime-es5.js      | runtime              |   2.21 kB

       

       | Initial ES5 Total    |   2.59 MB

       | Initial ES2018 Total |   2.33 MB

       

       Lazy Chunk Files    | Names                |      Size

       tutorial-es5.js     | tutorial             |  29.39 kB

       tutorial-es2018.js  | tutorial             |  24.17 kB

       

       Build at: 2021-03-27T18:30:25.049Z - Hash: c478cc159ff39e3188a1 - Time: 91284ms

       

-----> Caching build

       - node_modules

       

-----> Pruning devDependencies

       removed 845 packages and audited 977 packages in 15.346s

       

       33 packages are looking for funding

         run `npm fund` for details

       

       found 17 vulnerabilities (3 low, 7 moderate, 4 high, 3 critical)

         run `npm audit fix` to fix them, or `npm audit` for details

       

-----> Build succeeded!

-----> Discovering process types

       Procfile declares types     -> (none)

       Default types for buildpack -> web

-----> Compressing...

       Done: 258.8M

-----> Launching...

       Released v3

       https://***************.herokuapp.com/ deployed to Heroku

**Comment by bkimminich** [comment]
Looks entirely fine and it confirms successful deployment at the end, so I doubt any downtime of that instance has something to do with Juice Shop itself. Maybe you just had bad luck on Heroku side.

Both our own demo and staging instances work fine, so master and develop branch deployments should be all good.

**Comment by ghost** [comment]
Is there a .html file or something I can try this on instead of hosting it?
Or should I just try docker?

**Comment by bkimminich** [comment]
You can use any deployment option described in our README, from local Node.js to Docker everything's documented. Docker is probably easiest if you ask me.

**Comment by ghost** [comment]
The main reason that made me try deploy it on heroku is because it got
errors when I installed it on the latest kali Linux version.

**Comment by ghost** [comment]
I git cloned, npm install then I ran npm start and this is what I got.

**Comment by bkimminich** [comment]
I don't see what you got, but "Kali" was a trigger word that I saw before in support requests... 😉

Kali is known to have issues that you typically don't have in "regular" Linux distros. If you want to stick with Kali, Docker is probably your best option.
