### ISSUE TITLE
[📊] Collecting statistics for Juice Shop

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1624]
OWASP ZAP published https://www.zaproxy.org/blog/2021-04-19-collecting-statistics-for-open-source-projects explaining their way to collect some stats about usage and downloads of the project. It would be nice to have something similar (or near-identical, even) for Juice Shop.

Download stats interesting for Juice Shop would definitely include:

* Docker image pulls (main app and CTF extension)
* GitHub downloads (main app only)
* NPM downloads (CTF extension only)
* SoureForge downloads (main app only)

Additional stats will be added to this issue description over time based on proposals in the issue comments.

**Comment by the-pro** [comment]
Could we rewrite a similar thing using nodeJs and may be use it to create a user interface using the google charts. We would only need to store the github downloads and docker pulls as the rest are available to filter for time intervals.

**Comment by bkimminich** [comment]
With "rewrite" you mean the Python scripts? That would be as good approach as it's closer to our developer community... 👍 

The storage and everything would make sense on the OWASP AWS or I could create a private GH repo and we dump the data there. Should also be fine.

**Comment by the-pro** [comment]
Yeah I mean rewrite the python scripts. But is it going to be a part of this repository or a standalone one

**Comment by bkimminich** [comment]
I'd make a separate repo for this, but ideation of what stats to collect and how implemention might look like should happen here first.

**Comment by the-pro** [comment]
I think exposing out some APIs from the server and displaying the data on an html page or a server side rendered page would be a nice way to implement it. Also we cannot show the data for github downloads and docker pulls immediately as it was not recorded previously. It would require the app to store the data for some days to be able to display it in a weekly or monthly fashion

**Comment by chinggg** [comment]
I think Juice Shop may differ from ZAP in that Juice Shop is more like a website than a tool. So I guess many people will just visit http://demo.owasp-juice.shop in browser to use it without bothering downloading source code, pulling docker image or registering extra accounts. How can we collect PV statistics of our demo website? It seems our demo is also deployed in Heroku.

**Comment by the-pro** [comment]
I would say juice shop is meant to use locally where people can change its configuration according to their needs instead of like a website

**Comment by J12934** [comment]
The public heroku instance can already be monitored pretty nicely by pointing a prometheus against it to regularly collect metrics 🙃

As seen on twitter 😄 https://twitter.com/owasp_juiceshop/status/1306504380817051649

**Comment by the-pro** [comment]
I created a small rough version of the app. This is what it looks like currently: https://ancient-springs-56508.herokuapp.com/

I havent added the github and docker stats as they arent recorded yet. I am also confused a bit about how to show stats for different releases

**Comment by bkimminich** [comment]
> The public heroku instance can already be monitored pretty nicely by pointing a prometheus against it to regularly collect metrics 🙃
> 
> As seen on twitter 😄 https://twitter.com/owasp_juiceshop/status/1306504380817051649

I actually have a RasPi 3 running non-stop pulling Prometheus metrics from the demo instance, but I don't really monitor anything there. Usage of that instance is not really saying much about anything, because it's not _supposed_ to be used for hacking but it's the default data source for the CTF tool ... so it's seeing some traffic, but it's not really telling us how well the project is doing.

**Comment by bkimminich** [comment]
> I created a small rough version of the app. This is what it looks like currently: https://ancient-springs-56508.herokuapp.com/
> 
> I havent added the github and docker stats as they arent recorded yet. I am also confused a bit about how to show stats for different releases

So the source forge and npm stats you pulled live out of their APIs, not from some data store, right?

I can create a repo for Juice Shop stats collection/monitoring already, if that helps already in the "playing around"-phase of this idea... 😁

**Comment by bkimminich** [comment]
Also, this stats-collector repo is a good test balloon for https://github.com/juice-shop ... This might become the entire ecosystem's new home, if I get everything transfered from my account without breaking stuff or sending people into 404's ...

**Comment by bkimminich** [comment]
https://github.com/juice-shop/juicy-statistics 👈

**Comment by the-pro** [comment]
> > I created a small rough version of the app. This is what it looks like currently: https://ancient-springs-56508.herokuapp.com/
> > I havent added the github and docker stats as they arent recorded yet. I am also confused a bit about how to show stats for different releases
> 
> So the source forge and npm stats you pulled live out of their APIs, not from some data store, right?
> 
> I can create a repo for Juice Shop stats collection/monitoring already, if that helps already in the "playing around"-phase of this idea... grin

Yes sir they are live from the API. I only added the data for the past month.

**Comment by bkimminich** [comment]
I reserved https://juicy-statistics.herokuapp.com, so we could add auto deployment there via GH action.

Also we could keep the data in the repo for now and let @JuiceShopBot commit it automatically, similar to the lint fixing. No need for separate data repo or S3 bucket at the beginning, or is there?

**Comment by bkimminich** [comment]
Above URL is now available and development is in progress, so I'm closing this ticket here. Dedicated requirements for stats to collect and show can be put into issues on the https://github.com/juice-shop/juicy-statistics repo.
