### ISSUE TITLE
[🐛] deploy with heroku button stuck loading in heroku webapp

### ISSUE THREAD

**Issue by secureighty** [juice-shop/juice-shop#1629]
![image](https://user-images.githubusercontent.com/45250825/119213446-1925e100-ba8d-11eb-85ac-9c9d8052f50b.png)
with a brand new account, the deploy to heroku button in the readme is not functioning on heroku's end.

**Comment by bkimminich** [comment]
I tried with my existing account and everything works. I can't really imagine that this has anything to do with how new/old your account is. Did you try with another browser or without any plugins enabled?

If you keep having problems please use another run option or contact Heroku support. Thanks.
