### ISSUE TITLE
[⭐] Reset password for a user missing security question answer

### ISSUE THREAD

**Issue by snowbear** [juice-shop/juice-shop#1634]
# :star: Challenge idea

### Description

Several users originally missing security question answers - most notably bjoern.kimminich@gmail.com and two support users. For such users it is possible to set arbitrary security question/answer combination.

### Underlying vulnerability/ies

POST https://demo.owasp-juice.shop/api/SecurityAnswers/ is exposed for non-authorized access

### Expected difficulty

| :heavy_check_mark: / :x: | Difficulty                           |
|:------------------------:|:-------------------------------------|
|     :grey_question:      | :star:                               |
|     :heavy_check_mark:      | :star::star:                         |
|     :grey_question:      | :star::star::star:                   |
|     :grey_question:      | :star::star::star::star:             |
|     :grey_question:      | :star::star::star::star::star:       |
|     :grey_question:      | :star::star::star::star::star::star: |

### Possible attack flow

Find user who doesn't have a security question, for example through SQL injection. Using https://demo.owasp-juice.shop/api/SecurityAnswers/ API set an arbitrary question/answer combination.

**Comment by chinggg** [comment]
I have managed to set SecurityQuestion for bkimminich then reset his password. The solution which can be added to the companion book is as follows:
1. Log in as anyone
2. Submit a `GET` request to `api/Users` with `Authorization Bearer` to see the `UserId` of bkimminich, which is `4` in my environment.
3. Submit a `GET` request to `api/SecurityQuestions` to see the `SecurityQuestionId`, eg `10`, which refers to `the first company` question.
4. Submit a `POST` request to `api/SecurityAnswers` with body of `UserId`, `SecurityQuestionId` and `answer`
5. Now the security question/answer should have been set for bkimminich, you can go to the login page and click on Forgot your password then simply login with the password you set.

**Comment by chinggg** [comment]
@bkimminich Now I only find user `bkimminich` missing security question. So there are two options. 
One is `resetPasswordBkimminichChallenge`, which is just as existing `resetPasswordXXXChallenge`. We have told players the person missing security question.
Another is `missingSecurityQuestionChallenge`. We will not reveal the exact person, players need to use SQLi to extract the one missing security question. But I haven't found the payload yet.

And what is the criterion of successful solution? After the player POST https://demo.owasp-juice.shop/api/SecurityAnswers/ or after the player reset the password?

**Comment by marat-yuldashev** [comment]
https://juice-shop.herokuapp.com/rest/products/search?q=asfasfas%27))%20UNION%20SELECT%20%27%27,UserId,answer,%27%27,%27%27,%27%27,%27%27,%27%27,%27%27%20FROM%20SecurityAnswers%20UNION%20SELECT%20*%20FROM%20Products%20WHERE%20((name%20LIKE%20%27idassadfafs

IMO this challenge will be more interesting if you ask to reset password without pointing out the missing security question, though it makes challenge a bit too wide in terms of possible solutions (maybe create new user for this specific challenge?). But current shop implementation gives you one huge hint: if you notice the setSecurityAnswer request made when you register new user and try calling same method again for the same user the shop will reply something like 'userId is not unique' which makes it quite obvious that you can try looking for a user who doesn't have one yet.

**Comment by bkimminich** [comment]
We might still just ask for "Reset user ........`s password" and give the challenge a lower difficulty. We don't need to point out to go through the SecurityAnswer, but we should predefine the user to use and also say it's about the reset and not a subsequent login after reset. Because people might try 100s of things if not given some direction. And they might end logged in w/o the challenge solved, which could cause frustration and unnecessary support tickets.

So, I'd prefer making it easier, give it less stars but at the same time making it impossible to confuse with other login/reset challenges, maybe via the hint in Score Board or eBook.
