### ISSUE TITLE
[🐛] Cross-Site Imaging not marked as solved

### ISSUE THREAD

**Issue by Dario638** [juice-shop/juice-shop#1638]
# :bug: Bug report

## Description

The Cross-Site Imaging challenge is not marked as solved even though the images are correctly replaced.

### Is this a regression?

Unknown

## :microscope: Minimal Reproduction

1. Log into any account
2. Visit http://localhost:3000/#/deluxe-membership?testDecal=..%2F..%2F..%2Fredirect%3Fto%3Dhttps:%2F%2Fplacekitten.com%2F200%2F300%3Fq%3Dhttp:%2F%2Fleanpub.com%2Fjuice-shop

## :deciduous_tree: Your Environment

<pre><code>v14.17.0
7.10.0
</code></pre>

### Additional Information

Adding an additional `..%2F` is required for the challenge to be marked as solved.

**Comment by bkimminich** [comment]
Good catch! I removed one `../` from the solution check and corresponding test case. As the RegEx starts with `.*` it will still match for any extra `../` in the path but now no longer require the unnecessary extra one.
