### ISSUE TITLE
[🐛] Missing files in release archives

### ISSUE THREAD

**Issue by matt-moses** [juice-shop/juice-shop#1667]
There are missing files in release archives. This is causing weird installation issues but the root cause is missing files.

Download this: https://github.com/bkimminich/juice-shop/releases/download/v12.8.1/juice-shop-12.8.1_node12_linux_x64.tgz

Extract and compare with repo:

For instance the `frontend/` directory is missing `package.json` etc. in the `tgz`.

**Comment by bkimminich** [comment]
The packaged archives only contain what is needed to start to application with `npm start`. The frontend is already precompiled in there under `/frontend/dist`. You cannot develop based on the archived packages or run test suites or similar. For that you need the "full version" from GitHub source.

**Comment by matt-moses** [comment]
Thank you for that clarification! JuiceShop is awesome. Thank you so much. I'm helping to host a CTF again for high school students. JuiceShop has been a key piece these last couple of years for the CTF. Thank you!
