### ISSUE TITLE
[🚀] Backlog Post GSoC Features

### ISSUE THREAD

**Issue by the-pro** [juice-shop/juice-shop#1674]
## Extending Coding Challenges

The following changes need to be done to further extend the features that were introduced in the GSoC period:

- [ ] Create an automated system to warn about the changes done in the Vulnerable snippets during making some changes to the codebase. (Possibly in a CI/CD step)
    - (If it works)Maybe also create a command to automatically merge the changes into the fixes if the changes are not done into the vulnerable lines. (See [diff](https://www.npmjs.com/package/diff))
- [x] Introduce a cheat detection mechanism for the coding challenges that can give a cheat score or a warning if the solution of a coding challenge was submitted through cheating
  - e.g. based on submission speed of different challenges (similar to hacking challenges
  - or when loading continue codes where "Fix It" parts are completed but not the "Find It" parts of a coding challenge
- [x] Introduce a metric for coding challenge "precision" or "accuracy" based on the number of attempts to find a vulnerable line or select the correct fix
  - This should not be considered cheating and is its own metric
  - This metric would not be displayed on the Score Board as it should be considered volatile, similar to the cheat score which does not survive server starts.
- [x] Introduce a scoring system for the coding challenges similar to the hacking challenges
- [ ] A tutorial to show the users how to solve a coding challenge
- [x] Hints for "Find It" and explanations for "Fix It" choices. See #1679 for details.

**Comment by bkimminich** [comment]
Cheat detection is WIP ... (58a2b449c1dae5efb99d3d84bfccb46e3afeac76)

**Comment by bkimminich** [comment]
![image](https://user-images.githubusercontent.com/3531020/135727852-ba0ad303-78f9-4b3b-a498-3b5ca322c997.png)

**Comment by bkimminich** [comment]
Accuracy is currently only logged on server side. Calculation of "Total Accuracy" and metric for Prometheus is not yet available.

**Comment by bkimminich** [comment]
Similar to the cheat score, accuracy calculation is not triggered when challenge progress is restored. This means a freshly started server always starts clean:
![image](https://user-images.githubusercontent.com/3531020/135728034-c4759efb-701e-40ec-a79b-15bb16cf0022.png)

**Comment by bkimminich** [comment]
![image](https://user-images.githubusercontent.com/3531020/135748510-fa991527-1ff3-4dce-a522-23b388c8e5ca.png)

**Comment by bkimminich** [comment]
Only the Grafana dashboard template still needs to be updated with these new metrics. For the accuracy metrics two regular percentage bars should be fine. For the progress maybe we use a pie chart with color scheme of red = unsolved, yellow = find it and green = fix it?

On the Score Board the progress could be visualized similarly with a three-colored pie chart or progress bar, but there's seemingly no Angular Material component available for that out of the box.

**Comment by bkimminich** [comment]
All previously mentioned improvements including a new Grafana Dashboard template (for Grafana 8) have been released via `v12.10.0`.

![image](https://user-images.githubusercontent.com/3531020/135766297-6161c6ce-6800-4da3-bce0-db78e186d312.png)

**Comment by bkimminich** [comment]
Coding challenges now have their own %-progress bar. Future improvement could be a pie/donut chart like in the Grafana dashboard, as the progress bar does not distinguish between "Find It" and "Fix It" progress.

![image](https://user-images.githubusercontent.com/3531020/138035828-f55c60e7-b860-49a3-ae4e-c312a9d220f5.png)
