### ISSUE TITLE
Angular html templates are being briefly displayed on page load

### ISSUE THREAD

**Issue by DinisCruz** [juice-shop/juice-shop#169]
for example the {{version}} tag in the home page

![image](https://cloud.githubusercontent.com/assets/656739/17277055/bc3b1cbc-5731-11e6-99c2-3175faa8255b.png)

The solution is to use ng-cloak https://docs.angularjs.org/api/ng/directive/ngCloak

**Comment by bkimminich** [comment]
I'm not sure if I really want to cloak this. It's basically a nice "information leakage". I just got no idea how to make a challenge out of this... 🤔

**Comment by DinisCruz** [comment]
well, one can just look at the source and see if that same code and all the js will point to angular, so not sure we can make this one into an security issue :)

**Comment by bkimminich** [comment]
Good point, more like a cosmetic thing. So, cloaking mode it'll be!

Am 1. August 2016 22:52:06 MESZ, schrieb Dinis Cruz notifications@github.com:

**Comment by bkimminich** [comment]
Template still shows in v2.2.1, at least in Chrome on Android.

![](https://www.dropbox.com/s/3ngw0f18hsuhqnc/Screenshot_20160804-042046.png)
