### ISSUE TITLE
[🐛]  Tutorial SQL query not visible in js console in "Log in with the administrator's user account."

### ISSUE THREAD

**Issue by haster** [juice-shop/juice-shop#1696]
# :bug: Bug report

## Description

The failing SQL query is not visible in the console (despite the tutorial saying so) during the "Log in with the administrator's user account." challenge. It is visible in the response body on the networks tab (on FF at least).

This is more of a "hey, the tutorial might not be working properly for everybody" as opposed to "hey it's broken" bug report :-) 

### Is this a regression?

I assume yes, but I have not checked it.

## :microscope: Minimal Reproduction

(- Run a fresh juice shop as docker container with the "tutorial.yml" config.
- Complete all level 1 tutorials by following the tutorial.)
- Follow the steps of the "Log in with the administrator's user account." tutorial until it says "look at the console for the failing sql query" after typing " ' " in the email field.
- Note that in Chrome, the console only show stacktraces for a 500 error on the login. In Firefox, the console briefly shows what looks like a 500 error stacktrace, but it disappear (even with "persist logs" activated!) and a message appears: 
<pre><code> Console was cleared.                                       tutorial-es2018.js:1:3567</code></pre>

- In FF, if you look at the actual response from the post on /login, you can find the SQL query that errored, but it is not in the console. (In Chrome I can't find any requests in the networks tab but that might be due to a plugin or configuration on my side).

## :fire: Exception or Error

<pre><code>

</code></pre>

## :deciduous_tree: Your Environment

<pre><code>

docker image ls | grep juice-shop
bkimminich/juice-shop                                           latest          455e654df2a2   2 days ago      494MB

docker run -d -e "NODE_ENV=tutorial" -p 3000:3000 bkimminich/juice-shop
</code></pre>

### Additional Information

FF: 93.0
Chrome: Version 94.0.4606.71 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/1228217/136343895-0892e6d9-2697-427d-aca5-b2df9edbbdda.png)
![image](https://user-images.githubusercontent.com/1228217/136345710-bdf0ee9a-5431-4972-a8e1-375f50346602.png)
![image](https://user-images.githubusercontent.com/1228217/136344511-aef0378b-5b52-4947-9644-feebd896a8ff.png)
![image](https://user-images.githubusercontent.com/1228217/136345354-2d141f66-5a31-4c6c-9d2e-60870aeaf98b.png)

**Comment by bkimminich** [comment]
Thanks for noticing this discrepancy in the tutorial steps. While the https://github.com/juice-shop/juice-shop/blob/master/frontend/src/hacking-instructor/challenges/loginAdmin.ts#L67 hint points to check console and network tab it only points to the console later where it actually should point to the network tab. I think at some point the errors were in the console with the SQL query but this is no longer the case. Good catch!
