### ISSUE TITLE
Move repo to OWASP organization

### ISSUE THREAD

**Issue by DinisCruz** [juice-shop/juice-shop#170]
let me know if you need help doing that (I've done that move many times before)

**Comment by bkimminich** [comment]
I think I need to be in the OWASP org to initiate this, right? 

Do you know if webhooks and the like "survive" this move, e.g. Travis-CI, Codeclimate, Gitter.im etc.? Any experience with this? How about GitHub pages?

**Comment by bkimminich** [comment]
## Mandatory Activities

### Pre-Move
- [ ] Receive admin permission within OWASP org on GitHub (https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization)

### Move
- [ ] Move repository (https://help.github.com/articles/about-repository-transfers/)

### Post Move (High Priority / Essential Services)
- [ ] Adopt Travis-CI build
- [ ] Adopt AppVeyor build
- [ ] Adopt Codeclimate settings
- [ ] Adopt Saucelabs settings

### Post Move (Low Priority / Uncritical Side Services)
- [ ] Change references in code (e.g. package.json, redirect URL whitelist, )
- [ ] Change references in docs (e.g. Readme, GitHub-page, OWASP Wiki etc.)
- [ ] Adopt Sourceforge settings
- [ ] Move Gitter.im chatroom
- [ ] Move Huboard kanban board
- [ ] Adopt Gemnasium settings 
- [ ] Adopt Versioneye settings 
- [ ] Adopt David-DM settings 

## Optional Activities
- [ ] Move Docker image (https://success.docker.com/Cloud/Solve/How_do_I_move_repositories_among_organization_in_Docker_Hub%3F)
- [ ] Have OWASP claim juice-shop on Bountysource

**Comment by DinisCruz** [comment]
I can do that transfer if you want. I've done that recently for a couple repos that were on my personal github account

I know that Issues and Travis-CI work transparently

for example https://github.com/DinisCruz/BSIMM-Graphs is now at https://github.com/OWASP/Maturity-Models (if you try the first you will be redirected to the 2nd)

**Comment by bkimminich** [comment]
If it forwards everything, that'd be great because then I can do all URL changes afterwards without anything breaking. But this is still not a change for vacation time with lousy Internet access... 😂

I'll let you know when it can happen, if that's ok for you! Still need to be an org member before, I guess... 😉

**Comment by DinisCruz** [comment]
ok, I just invited you to join the org

let me know when you want to make the move

in fact I think that you should be able to do it your self

**Comment by bkimminich** [comment]
Prepared change to all (?) relevant URLs on https://github.com/bkimminich/juice-shop/tree/repo-move

**Comment by bkimminich** [comment]
As documented by GitHub: When trying to migrate I get **You don’t have admin rights to OWASP**.

@DinisCruz, can you please promote me to admin in OWASP org? I will then test migration with a lightly integrated dummy project, https://github.com/bkimminich/repo-move-test which has integrations configured to
- Docker
- Travis-CI
- Gemnasium
- CodeClimate
- HuBoard

If that works out, I'll prep and move iuice-shop soon after. Thanks!

**Comment by DinisCruz** [comment]
what is the name of the owasp repo(s) that you want? (I can make you admin of those)

(sorry for the late reply I was away on holidays for the past 10 days)

**Comment by bkimminich** [comment]
None, tbh. Owner status on org level is simply required to move a private repository into an organization.

**Comment by DinisCruz** [comment]
which private repo?

all owasp repos have to be pubic by design (since all code at owasp is shared)

**Comment by bkimminich** [comment]
It's not about a private repository, just the one to be moved from my personal account to the OWASP org account. Wrong terminology on my end.

The only way to do a move like that is when the original owner has "Owner" access in the target org.

If that is a problem I'd have to close this issue and just keep the repo under my account. I just expect higher levels of collaboration if it becomes part of the OWASP org, that's all.

**Comment by DinisCruz** [comment]
ok, sorry the move shouldn't be an issue, my only worry was giving you admin access to ALL Owasp repos

of course you will have admin over yours.

I can create the repo, I just need the name

**Comment by bkimminich** [comment]
GitHub documentation says it is not possible to move a repository into an account that already has a repo with the same name (see https://help.github.com/articles/about-repository-transfers/).

@DinisCruz: We can try though, if you like. Please create a repo named `OWASP/repo-move-test` and I will try to move the test repo https://github.com/bkimminich/repo-move-test I created over to OWASP. I wanted to do this one first anyway, to test how many integrations/webhook survive the move.

If this doesn't work out and Owner permissions are no-go on your end, the move can't happen. The only alternative I see - creating a new empty org-repo named OWASP/juice-shop and migrating the _content_ of bkimminich/juice-shop instead of the _repo itself_ - isn't an option because
- all existing weblinks break
- all existing integrations break
- all forks break (would affect 50 people right now)
- all favstars are gone (169 stars would be gone)
- all issues are gone or need to be recreated

**Comment by DinisCruz** [comment]
Another option is to create a temp user that we can use to make the move (one that both of us know the pwd)

**Comment by bkimminich** [comment]
For cases without/with less integrations it might also be fine to just move the repo to one of the org owners and have him then move it on to the org. Still creates an unnecessary forwarding step (original owner :arrow_right: dummy user :arrow_right: org). No idea how many GitHub actually supports.

In a cases like `juice-shop` with tons of external dependencies and integrations, I would want to pull this stunt... :smiley:

**Comment by bkimminich** [comment]
Will remain `on hold` until
- either receiving feedback from @mtesauro on how to handle repo moves into @owasp in general
- or permission for _Owner_ access to @owasp is granted

**Comment by bkimminich** [comment]
Closed for being too risky. Would require an in-depth analysis of each 3rd party service integration using some dummy test repository with similar setup. Effort for that outweighs benefit for now.

If someone feel like doing such a test with their own fork of the project, I'll happily re-open this issue...

**Comment by bkimminich** [comment]
#204 acts as pick-up issues for this task! Please do not add any more comments here but use #204 instead!

💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀
