### ISSUE TITLE
[🐛]  Container is restarting every 5-10 minutes without any reason

### ISSUE THREAD

**Issue by a10sbraun** [juice-shop/juice-shop#1703]
# :bug: Bug report

## Description

I am using juice-shop as a container but it does not keep stable up :'(
As I have a SystemD service it will automatically restart

### Is this a regression?

No, same issue also with the oldest which I tested was 11.1.3 

## :microscope: Minimal Reproduction

Start normal as a container :-)
podman create --name juice -it -p 3000:3000 --restart=always docker.io/bkimminich/juice-shop:$ver

## :deciduous_tree: Your Environment

RHEL 8.4
FW disabled
SELinux permissive

### Additional Information

podman logs juice

> juice-shop@11.1.3 start /juice-shop
> node app

info: All dependencies in ./package.json are satisfied (OK)
info: Detected Node.js version v12.18.3 (OK)
info: Detected OS linux (OK)
info: Detected CPU x64 (OK)
info: Required file index.html is present (OK)
info: Required file styles.css is present (OK)
info: Required file main-es2015.js is present (OK)
info: Required file tutorial-es2015.js is present (OK)
info: Required file polyfills-es2015.js is present (OK)
info: Required file runtime-es2015.js is present (OK)
info: Required file vendor-es2015.js is present (OK)
info: Required file main-es5.js is present (OK)
info: Required file tutorial-es5.js is present (OK)
info: Required file polyfills-es5.js is present (OK)
info: Required file runtime-es5.js is present (OK)
info: Required file vendor-es5.js is present (OK)
info: Configuration default validated (OK)
helmet deprecated helmet.featurePolicy is deprecated (along with the HTTP header) and will be removed in helmet@4. You can use the `feature-policy` module instead. server.js:151:16
info: Port 3000 is available (OK)
info: Server listening on port 3000
info: Solved challenge Exposed Metrics (Find the endpoint that serves usage data to be scraped by a popular monitoring system.)

> juice-shop@11.1.3 start /juice-shop
> node app

info: All dependencies in ./package.json are satisfied (OK)
info: Detected Node.js version v12.18.3 (OK)
info: Detected OS linux (OK)
info: Detected CPU x64 (OK)
info: Required file index.html is present (OK)
info: Required file styles.css is present (OK)
info: Required file main-es2015.js is present (OK)
info: Required file tutorial-es2015.js is present (OK)
info: Required file polyfills-es2015.js is present (OK)
info: Required file runtime-es2015.js is present (OK)
info: Required file vendor-es2015.js is present (OK)
info: Required file main-es5.js is present (OK)
info: Required file tutorial-es5.js is present (OK)
info: Required file polyfills-es5.js is present (OK)
info: Required file runtime-es5.js is present (OK)
info: Required file vendor-es5.js is present (OK)
info: Configuration default validated (OK)
helmet deprecated helmet.featurePolicy is deprecated (along with the HTTP header) and will be removed in helmet@4. You can use the `feature-policy` module instead. server.js:151:16
info: Port 3000 is available (OK)
info: Server listening on port 3000
info: Solved challenge Exposed Metrics (Find the endpoint that serves usage data to be scraped by a popular monitoring system.)

> juice-shop@11.1.3 start /juice-shop
> node app

info: All dependencies in ./package.json are satisfied (OK)
info: Detected Node.js version v12.18.3 (OK)
info: Detected OS linux (OK)
info: Detected CPU x64 (OK)
info: Required file index.html is present (OK)
info: Required file styles.css is present (OK)
info: Required file main-es2015.js is present (OK)
info: Required file tutorial-es2015.js is present (OK)
info: Required file polyfills-es2015.js is present (OK)
info: Required file runtime-es2015.js is present (OK)
info: Required file vendor-es2015.js is present (OK)
info: Required file main-es5.js is present (OK)
info: Required file tutorial-es5.js is present (OK)
info: Required file polyfills-es5.js is present (OK)
info: Required file runtime-es5.js is present (OK)
info: Required file vendor-es5.js is present (OK)
info: Configuration default validated (OK)
helmet deprecated helmet.featurePolicy is deprecated (along with the HTTP header) and will be removed in helmet@4. You can use the `feature-policy` module instead. server.js:151:16
info: Port 3000 is available (OK)
info: Server listening on port 3000
info: Solved challenge Exposed Metrics (Find the endpoint that serves usage data to be scraped by a popular monitoring system.)
info: Solved challenge Exposed Metrics (Find the endpoint that serves usage data to be scraped by a popular monitoring system.)

> juice-shop@11.1.3 start /juice-shop
> node app

info: All dependencies in ./package.json are satisfied (OK)
info: Detected Node.js version v12.18.3 (OK)
info: Detected OS linux (OK)
info: Detected CPU x64 (OK)
info: Required file index.html is present (OK)
info: Required file styles.css is present (OK)
info: Required file main-es2015.js is present (OK)
info: Required file tutorial-es2015.js is present (OK)
info: Required file polyfills-es2015.js is present (OK)
info: Required file runtime-es2015.js is present (OK)
info: Required file vendor-es2015.js is present (OK)
info: Required file main-es5.js is present (OK)
info: Required file tutorial-es5.js is present (OK)
info: Required file polyfills-es5.js is present (OK)
info: Required file runtime-es5.js is present (OK)
info: Required file vendor-es5.js is present (OK)
info: Configuration default validated (OK)
helmet deprecated helmet.featurePolicy is deprecated (along with the HTTP header) and will be removed in helmet@4. You can use the `feature-policy` module instead. server.js:151:16
info: Port 3000 is available (OK)
info: Server listening on port 3000
info: Solved challenge Exposed Metrics (Find the endpoint that serves usage data to be scraped by a popular monitoring system.)

> juice-shop@11.1.3 start /juice-shop
> node app

info: All dependencies in ./package.json are satisfied (OK)
info: Detected Node.js version v12.18.3 (OK)
info: Detected OS linux (OK)
info: Detected CPU x64 (OK)
info: Required file index.html is present (OK)
info: Required file styles.css is present (OK)
info: Required file main-es2015.js is present (OK)
info: Required file tutorial-es2015.js is present (OK)
info: Required file polyfills-es2015.js is present (OK)
info: Required file runtime-es2015.js is present (OK)
info: Required file vendor-es2015.js is present (OK)
info: Required file main-es5.js is present (OK)
info: Required file tutorial-es5.js is present (OK)
info: Required file polyfills-es5.js is present (OK)
info: Required file runtime-es5.js is present (OK)
info: Required file vendor-es5.js is present (OK)
info: Configuration default validated (OK)
helmet deprecated helmet.featurePolicy is deprecated (along with the HTTP header) and will be removed in helmet@4. You can use the `feature-policy` module instead. server.js:151:16
info: Port 3000 is available (OK)
info: Server listening on port 3000
info: Solved challenge Exposed Metrics (Find the endpoint that serves usage data to be scraped by a popular monitoring system.)

**Comment by bkimminich** [comment]
There's no messages in your logs that suggest the server crashed. I doubt the restarts have anything to do with the application, because if that'd be an issue since version 11.x in Docker in general, I am 100% sure we would have heard about it earlier.

Please check your resources consumption and try to assign a bit more. If that doesn't help, please see if you can come up with more detailed logs. I'm happy to add something to our troubleshooting docs depending on what you find out. See https://pwning.owasp-juice.shop/appendix/troubleshooting.html

**Comment by bkimminich** [comment]
You can find the recommended system specs here: https://pwning.owasp-juice.shop/part1/running.html

**Comment by a10sbraun** [comment]
closed it... way to stupid... it restarts every time when I login and dies by logout...

I again fall in this stupid trap of missing loginctl enamle-linger
