### ISSUE TITLE
[🐛] Challenge progress restore triggers XSS on Score Board

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1707]
# :bug: Bug report

## Description

1. Start local instance and go to `/#/score-board`
2. Notice that the copy-pastable XSS payloads (e.g. in _DOM XSS_ or _Bonus Payload_ challenge) are properly encoded
3. Confirm via `/api/Challenges` that those payloads are wrapped into `<code>`...`</code>` properly
4. Restore challenge progress from a local backup (works best with a continue code w/ lot of challenges solved)
5. Visit `/#/score-board` to notice that one or more XSS payloads now trigger
6. Check via `/api/Challenges` that the `<code>`...`</code>` enclosure is **now missing** in the API response

### Additional Information

Could also be reproduced on https://preview.owasp-juice.shop/#/score-board and https://preview.owasp-juice.shop/api/Challenges

**Comment by bkimminich** [comment]
It is also notable that in steps 2+3 the backend-side translation works, e.g.
![image](https://user-images.githubusercontent.com/3531020/137096603-164282a2-2776-4e75-93b6-2f34619d5d17.png)
but at 4+5 it will return the requested English string directly (as there is no translation for the string with the missing `<code>` tag)
![image](https://user-images.githubusercontent.com/3531020/137096742-9ff1a4d1-1139-4c02-a0c7-ea67e0899c54.png)

In fact, **all HTML** except for the inner `<iframe>` is removed after step 4+5 for **all** challenge descriptions, e.g.
![image](https://user-images.githubusercontent.com/3531020/137097692-40cd3ad1-4f3f-4b3b-ba51-a0d38eb2dd3b.png)
becomes
![image](https://user-images.githubusercontent.com/3531020/137097800-d58b0d34-520f-47f7-9f12-3b26b92209e9.png)

This already took place in the API response to `/api/Challenges`, so it cannot be a client-side issue.

**Comment by bkimminich** [comment]
Further inspection confirms that after the backup restore the `Challenges` table in the database already contains the altered descriptions w/o any HTML except for the tags which were embedded into `<code>`.

**Comment by bkimminich** [comment]
**Before**
![image](https://user-images.githubusercontent.com/3531020/137100601-e71473f1-e600-4c70-b5a2-91534b75c964.png)

**After**
![image](https://user-images.githubusercontent.com/3531020/137100499-f522fb70-e28d-4802-a280-1760d67025cc.png)

**Comment by bkimminich** [comment]
![image](https://user-images.githubusercontent.com/3531020/137101446-569437e9-0e43-492f-820f-e87aec3f7cd5.png)

Line 119 is the problem ... 🤦‍♂️

**Comment by J12934** [comment]
> ![image](https://user-images.githubusercontent.com/3531020/137101446-569437e9-0e43-492f-820f-e87aec3f7cd5.png)
> 
> Line 119 is the problem ... 🤦‍♂️

Not sure if I totally get it, this works just for the restore as the restore has the text encoded so that the iframe tag isn't removed by the sanitizeHtml? Or am I understanding it wrong?

**Comment by bkimminich** [comment]
![image](https://user-images.githubusercontent.com/3531020/137102505-dff2e7d1-d3f8-45ca-9afd-5966d21e9107.png)
The commit message from 2016 explains it ... this is _supposed_ to alter the description _after_ saving the Challenge to DB so that the HTML does not appear in the green notification boxes.

**Comment by bkimminich** [comment]
I'll move that code into `sendNotification()` instead...

**Comment by bkimminich** [comment]
I guess the issue was reference semantics which saved the sanitized challenge description back into the cache upon the first notification and then finding it there for any subsequent notification (i.e. local restore) and then putting it into the DB.

Pretty wild that this was not noticed for 5 years... 😬
