### ISSUE TITLE
[🐛] Hacking Instructor doesn't take into account a custom domain

### ISSUE THREAD

**Issue by eyalch** [juice-shop/juice-shop#1715]
# :bug: Bug report

## Description

Hacking Instructor doesn't take into account a custom domain.

Here's a part of my custom config:

```yml
application:
  domain: "example.com"
```

Take the "Login Jim" challenge instructor script. At the stage of inputting Jim's email, the instructor script expects "jim@juice-sh.op" and not "jim@example.com".

Looking at the source code, looks like there's already a TODO: https://github.com/juice-shop/juice-shop/blob/57b5d56da23104a7040371eb919147f917386950/frontend/src/hacking-instructor/challenges/loginJim.ts#L67

I'm planning to use Juice Shop as a fun learning CTF for the developers in my company, and, since they're not very experienced with hacking and security, the Hacking Instructor scripts are a really good feature, as it could give a nice boost to start solving challenges.

**Comment by bkimminich** [comment]
It's a known issue that the Hacking Instructor cannot access the config at the moment, so it doesn't know the custom domain. Would be a great addition to the store to have that finally. Volunteers welcome!

**Comment by bkimminich** [comment]
With `v13.0.0` this is now supported via an extra option to `waitForInputToHaveValue`:

```
resolved: waitForInputToHaveValue('#email', 'jim@juice-sh.op', { replacement: ['juice-sh.op', 'application.domain'] })
```

**Comment by eyalch** [comment]
@bkimminich Thank you very much!
