### ISSUE TITLE
[🚀] Coding Challenge RSN (Refactoring Safety Net)

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1720]
1. Create an automated system to detect changes done inside `vuln-snippet` blocks that lead to inconsistency with associated fix option files, e.g. via [diff](https://www.npmjs.com/package/diff).
2. Introduce an npm script and CI/CD step that perform this check and report/fail on findings
3. An advanced option could be to automatically carry over code snippet changes (unless done in the actually vulnerable or ignored lines) into the fix files

**Comment by the-pro** [comment]
Can i work on this?

**Comment by bkimminich** [comment]
Absolutely!!! 😁👍

**Comment by bkimminich** [comment]
The "Login Admin" code fix files are currently a good example for a slight deviation from the actual code:

![image](https://user-images.githubusercontent.com/3531020/149616342-8040eb6b-d002-41f1-bc8c-0b0e07771d46.png)
(Function parameters are now typed in the actual code snippet but not in the code-fix files)

![image](https://user-images.githubusercontent.com/3531020/149616369-794587c6-be49-465f-9c91-9f2be51ca33d.png)
(Some indentation changes occured)

**Comment by bkimminich** [comment]
I was recently thinking about a "simplified" approach on how to handle this, that might allow us to avoid some complex diff logic:

1. We add a utility that can be called with e.g. `npm run lock-codefixes` which will calculate the actual diff (or even just a hash or % value of the difference) per challenge and all its fix-files and saves this information in an e.g. `codefixes.lock.json`
2. We have a test in `test/server` that calculates the current diffs/%s/hashes with the same function and then compares them to the locked one per challenge+fix-file, failing the test whenever a difference is found

When would this trigger? Whenever we make a change to _either_ the snippet _or_ the fix-file. Then we **want** the test to fail. But it would also trigger when we changed _both_ the snippet and fix-file at the same time, as the actual diff would definitely change. A hash of the diff as well, and a % of the diff in many cases as well. Here we **wouldn't want** the test to fail. It would, unless we remember to call `npm run lock-codefixes` after such changes. So, not a big deal to "fix" this problem afterwards.

**Comment by the-pro** [comment]
Yeah I was also thinking something like that, like saving the diffs %. I have created a test which can give some additions(+) and deletions(-) on the original code relative to the fixes. It has a decent accuracy. I am trying to reduce the false positives for now and testing it. Will put a PR soon so you can check yourself. I can add the diff percentage calculator after that. Currently it detects the changes line wise.

**Comment by the-pro** [comment]
Also I think a lot of files have diffs. Around 48 files have diffs.
![Screenshot (50)](https://user-images.githubusercontent.com/42973786/149617926-1592ec78-0e9f-4e0b-9ccf-0d281dd869b5.png)

**Comment by bkimminich** [comment]
> Yeah I was also thinking something like that, like saving the diffs %. I have created a test which can give some additions(+) and deletions(-) on the original code relative to the fixes. It has a decent accuracy. I am trying to reduce the false positives for now and testing it. Will put a PR soon so you can check yourself. I can add the diff percentage calculator after that. Currently it detects the changes line wise.

If we can achieve the goal of detecting deviations without a %-based approach, that's totally sufficient. Please keep your solution as simple as you can, I was just dumping some loose ideas above... 😁

**Comment by bkimminich** [comment]
Nice work on the check tool! I've merged it into a separate branch `rsn` and did some small adjustments already (like removing the custom colorization and using `colors` module instead.

There are some false positives we need to deal with. Let's pick "Reset Morty's Password" as an example. This is what the RSN currently reports:

## RSN Report
![image](https://user-images.githubusercontent.com/3531020/149746426-fc5000a0-99f8-4204-a190-852438e63be5.png)

Here are the corresponding diffs as shown in the coding challenge dialog:

## resetPasswordMortyChallenge_1.ts
![image](https://user-images.githubusercontent.com/3531020/149746793-5285b49f-fe93-426e-b812-477b32d8010b.png)

* RSN: ❌ (the wrong fix suggestion is happening in a line that is not a `vuln-line` so the tool thinks it is an accidental diff)
* Actual: ✅ 

## resetPasswordMortyChallenge_2.ts
![image](https://user-images.githubusercontent.com/3531020/149746959-10494a4a-43bd-449f-9c32-31f5a2de28ed.png)

* RSN: ✅ (the wrong fix suggestion happens in the `vuln-line` so the tool is fine with it)
* Actual: ✅ 

## resetPasswordMortyChallenge_3.ts
![image](https://user-images.githubusercontent.com/3531020/149747038-0b88d4fd-1a7e-4e53-b0ba-7b2b443a637c.png)

* RSN: ❌ (the wrong fix suggestion is happening in a line that is not a `vuln-line` so the tool thinks it is an accidental diff)
* Actual: ✅ 

⚠️ _The tool also reports the lines 4 and 5 as both different and same simultaneously, see screenshot having 4 5 4 5 in red and green._

## resetPasswordMortyChallenge_4_correct.ts
![image](https://user-images.githubusercontent.com/3531020/149747099-81459d4d-b1bb-4765-ae57-630d885a7948.png)

* RSN: ✅ (the correct fix suggestion happens in the `vuln-line` so the tool is fine with it)
* Actual: ✅

**Comment by bkimminich** [comment]
I'm not sure this can be fixed with the "per line" approach completely, unless we somehow "lock in" the accepted changed lines per file in the cache. Actually the `vuln-line` and `neutral-line` have nothing to do with where changes can occur in a code-fix file, especially for the intentionally wrong suggestions, as seen in the Morty example.

**Comment by the-pro** [comment]
> I'm not sure this can be fixed with the "per line" approach completely, unless we somehow "lock in" the accepted changed lines per file in the cache

You lock in the accepted lines in the cache when you run `npm run rsn:update` and it will give you error only when the diffs do not match with the cached diffs.

> The tool also reports the lines 4 and 5 as both different and same simultaneously, see screenshot having 4 5 4 5 in red and green.

Green lines are not same actually, it says that it has been removed and a new line is added there.

**Comment by bkimminich** [comment]
Ok, so the four files for the "Reset Morty's Password" challenge are all exactly as they should be right now. The tool reports

![image](https://user-images.githubusercontent.com/3531020/149763714-1d1a3995-fa4c-4be5-9f21-5cfbf1cd452b.png)
and the cache contains

```
"resetPasswordMortyChallenge_1.ts":[2],"resetPasswordMortyChallenge_2.ts":[],"resetPasswordMortyChallenge_3.ts":[4,5,4,5],"resetPasswordMortyChallenge_4_correct.ts":[]
```

When I run `rsn:update` nothing changes as I've not changed any file. I manually changed the cache to

```
"resetPasswordMortyChallenge_1.ts":[],"resetPasswordMortyChallenge_2.ts":[],"resetPasswordMortyChallenge_3.ts":[],"resetPasswordMortyChallenge_4_correct.ts":[]
```

and then I get this when running `rsn`

![image](https://user-images.githubusercontent.com/3531020/149764223-999373b4-ed4f-4da9-91b6-839b61a69b61.png)

Now running `rsn:update` changes the cache back into 

```
"resetPasswordMortyChallenge_1.ts":[2],"resetPasswordMortyChallenge_2.ts":[],"resetPasswordMortyChallenge_3.ts":[4,5,4,5],"resetPasswordMortyChallenge_4_correct.ts":[]
```

The result of `rsn` considers file 1 and 3 as failed and keeps doing so, although these files are actually exactly like I want them to be. But there seems to be no way to lock in the fact that these exact file versions are fine.

**Comment by the-pro** [comment]
Yeah i wrote it like the diffs will show up anyway for reference. Although if the diffs are cached it will show `All files have the same diffs` and not give any error. Otherwise it will give the names of the files whose diffs are not cached.

I have changed the cached structure now has an interface like:

```Typescript
interface CacheData {
  [key: string]: {
    added: number[]
    removed: number[]
  }
}
```
Do you suggest i shouldnt show the diff if the lines are cached?

**Comment by bkimminich** [comment]
I suppose the "OK" (or "PASSED" as it was before) just implied that the others somehow not okay... 🤣

... that and the green/red for added/removed lines also makes it look a bit more good vs. bad than we'd want it to.

I'll see if I can make this more clear with different wording and coloring later today or tomorrow.

**Comment by the-pro** [comment]
There is also a function seePatch() which when called will let you see the diffs in the teminal itself. You have to pass the filename in the arguments
![Screenshot (52)](https://user-images.githubusercontent.com/42973786/149787084-c1f12162-5522-4f7d-be57-8eac7fdbcc1b.png)

**Comment by bkimminich** [comment]
Can we maybe get rid of the _ok / not ok_ idea, because currently "ok" means that there are absolutely no differences except in the vuln or neutral lines and "not ok" means anything else. I played with visualizing a bit, and maybe we just show the vuln/neutral lines as well, e.g. like

![image](https://user-images.githubusercontent.com/3531020/149813414-5e7bd4a6-5023-4f41-b071-cc8772b96ceb.png)

and the only feedback at the end is  then the list of files where something changed compared to the cache. So, we'd remove the "Total files passed" and "Total files failed" messages altogether, because they don't really mean pass/fail - see above.

Does that make sense? It'd still give us any unexpected changes with a certain accuracy and list the affected files. We'd not catch formatting changes in the original code when occuring in the vuln/neutral lines, but that might be fine for now.

**Comment by bkimminich** [comment]
Then of course, next level would be listing changed lines as modified (e.g. yellow) instead of removed-added pairs. That way we'd also get rid of the duplicate vuln/neutral line listings in output log.

**Comment by the-pro** [comment]
ok so I will remove the log of the added/removed lines. Will there be a separate script to see the log of modified lines?

**Comment by bkimminich** [comment]
No, the line change logs per file are actually nice, we just should also show changes in vuln/neutral lines. The "passed/failed" message should be removed, though.

**Comment by bkimminich** [comment]
![image](https://user-images.githubusercontent.com/3531020/149898514-c12be768-3112-47ea-b978-22940f795006.png)

* Red/Green background: Regular lines removed/added
* Red/Green text: Neutral lines removed/added
* Red/Green bold+bright: Vuln line removed/added

The ones _most likely_ to be an accident are the ones with colored background now, but neutral lines could also be accidental. And if _no_ vuln line change shows up for at least a `_correct`-file, that is also dubious.

**Comment by bkimminich** [comment]
But with this the passed/failed log is now obsolete.

**Comment by bkimminich** [comment]
I've tried to clarify the different possible outcomes of the tool:

![image](https://user-images.githubusercontent.com/3531020/149942313-df5b8974-2ad5-4486-897b-375c75bf2d43.png)

vs.

![image](https://user-images.githubusercontent.com/3531020/149942354-8cae40e3-a0c2-45ca-8b57-5fe61baa8897.png)

and when updating:

![image](https://user-images.githubusercontent.com/3531020/149942403-06af255c-3206-464f-9817-9d6d10d8ec8c.png)

**Comment by bkimminich** [comment]
I turned ths RSN on as a CI/CD step, and it seems there's different behavior on Windows vs. Linux:

## GitHub Action on Ubuntu
![image](https://user-images.githubusercontent.com/3531020/150109862-2b20351e-2498-4b77-a828-5307c009f671.png)
![image](https://user-images.githubusercontent.com/3531020/150109964-d6c5e57e-64c8-4d6c-b859-58a2a5b2bfde.png)

## Local on Windows
![image](https://user-images.githubusercontent.com/3531020/150110085-52e89e86-641f-4c10-810a-b4f7c47ccb8d.png)
![image](https://user-images.githubusercontent.com/3531020/150110121-d4f2f46e-7205-442c-90d3-4e1cf7cd5cf2.png)

**Comment by bkimminich** [comment]
Line 9 in the original snippet is one with a `hide-line` marker, and it seems Windows doesn't bother with this (as intended) while Linux is seeing some added line. Also theres a change tagged on line 33 on Linux while it's line 34 on Windows.

I've been fixing all unwanted code differences on my Windows machine and all code-fixes now look exactly as they should in the _Coding Challenge_ screen. I'll compare to the Heroku instance later to see if they look the same over there.

For now I'll switch the CI/CD job to a Windows runner, which will hopefully make it consistent with my machine. But we might want to properly address this issue so that Linux and Windows users don't mess with the cache file all the time.
