### ISSUE TITLE
[🚀] Customization: Add option to define custom currency symbol

### ISSUE THREAD

**Issue by nakami** [juice-shop/juice-shop#1725]
# :rocket: Feature request

### Description

For the sake of customization, it would be great to be able to easily define a custom currency symbol. In some places (e.g. translation strings) there is "`¤`" used. In some template files there is "`&curren;`" resulting in the mentioned character, too.

### Solution ideas

I would like to be able to define a currency symbol in a custom configuration (`config/<CONFIGNAME>.yml`).

### Possible alternatives

Maybe it is possible to source the currency symbol to the translation files, but that would be less convenient as the configuration files are a central piece when it comes to customization and the translation files are not intended to be touched.

**Comment by bkimminich** [comment]
Variables can be injected into i18n files, but this would change a few strings for a relatively rarely used feature, I'd guess.

The currency symbol also became kind of a running gag, so I grew fond of it and wouldn't put effort into making it configurable.

But: If you or someone else want to build this feature, I'm happy to review and merge that. It needs to cover all places to get merged, no exceptions.

**Comment by nakami** [comment]
Alright, thank you for the clarification.

Since I didn't find any issue mentioning this and it might help someone save some time, I'll put my procedure down here if anybody stumbles across this. AFAIK it doesn't break any challenge. Correct me if I'm wrong.

## Replacing the currency symbol

These steps replace the occurences of "`¤`" (unicode representation) and "`&curren;`" (HTML encoding) in the relevant files. The text-file `files_for_currency_symbol_replacement.txt` contains a list of files where both strings are replaced. Please keep in mind that these commands work on linux-based shells only.

Put this file list in the directory of your local instance of the repository:
[files_for_currency_symbol_replacement.txt](https://github.com/juice-shop/juice-shop/files/7530444/files_for_currency_symbol_replacement.txt)

Then run these commands to replace the default currency symbol with "`€`" or one of your choice (replace "`€`" before running):

```shell
# Replace currency symbol (unicode representation)
while read i; do printf "Current file: %s\n" "$i"; sed -i -- 's/¤/€/g' "$i"; done < files_for_currency_symbol_replacement.txt
```

```shell
# Replace currency symbol (HTML encoding)
while read i; do printf "Current file: %s\n" "$i"; sed -i -- 's/&curren;/€/g' "$i"; done < files_for_currency_symbol_replacement.txt
```

Afterwards, you'll have to run `npm install` again.

**Comment by bkimminich** [comment]
If you replace every occurence via `sed`, even translations which contain the currency symbol will still work. Challenges should also not be impacted. I'll leave this issue open anyway if someone likes to pick it up.
