### ISSUE TITLE
Heroku and Local deployment not working [🐛] 

### ISSUE THREAD

**Issue by Abhisaran** [juice-shop/juice-shop#1732]
# :bug: Bug report

## Description

Sorry if this is not a real issue, I tried for about a week asking around before I wanted to raise this here. I tried to deploy juice shop on Heroku and locally, but it threw an error during installation both times (Import error i assume). I could not find a way to make it work. I would really appreciate any help I get.

### Is this a regression?

I do think as the docs suggest, one-click on heroku or just "npm install" should do the trick to deploy the app but it doesn't

## :microscope: Minimal Reproduction

Just try deploying, I'll also attach the error here. I have tried in a browser without any extensions, my main browser for heroku and my local environment for deploying using npm.

## :fire: Exception or Error

<pre><code>

Error: ./node_modules/ngx-window-token/fesm2015/ngx-window-token.mjs 3:19-33
Can't import the named export 'InjectionToken' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (\juice-shop\frontend\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:88:6)
    at HarmonyImportSpecifierDependency.getErrors (\juice-shop\frontend\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (\juice-shop\frontend\node_modules\webpack\lib\Compilation.js:1463:22)
    at \juice-shop\frontend\node_modules\webpack\lib\Compilation.js:1258:10
    at _next0 (eval at create (\juice-shop\frontend\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:43:1)
    at eval (eval at create (\juice-shop\frontend\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:57:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
 @ ./node_modules/ngx-clipboard/fesm2015/ngx-clipboard.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

</code></pre>

## :deciduous_tree: Your Environment

<pre><code>
node - v14.17.4
npm - 8.1.3
</code></pre>

### Additional Information

Heroku, Chrome, firefox, Windows 10 local

**Comment by bkimminich** [comment]
Can you try deleting your `node_modules` folders and run `npm install` again? 4 days ago I cherry-picked a fix for a upstream dependency that became incompatible.

That fix worked on CI/CD (see https://github.com/juice-shop/juice-shop/actions/runs/1464427677) so it should also work locally

**Comment by Abhisaran** [comment]
I did that, I deleted node modules like three times, refreshed cache but still did not deploy. Even if my system environment was buggy, heroku should have worked right?

**Comment by Abhisaran** [comment]
Sorry I skimmed through your comment. You said you fixed it 4 days ago, I will try the steps again. I apologize for it!

**Comment by bkimminich** [comment]
You also deleted the `frontend/node_modules`? Because when I run `rm -rf node_modules/ frontend/node_modules/ && npm install` on `master` locally, it works.

**Comment by Abhisaran** [comment]
Thank you so much, it worked now! Sorry for the extra work!
