### ISSUE TITLE
[🐛] Errors not rendered on "Change Password" form

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1733]
The only working feedback when submitting the _Change Password_ form is the success notification in `this.confirmation`. No error message is ever displayed on screen. The corresponding code blocks are reached for the expected error conditions, but the `this.error` field is never shown on screen.

**Comment by SakshiUppoor** [comment]
Hi @bkimminich 
I would like to work on this issue
Will make a PR soon

**Comment by bkimminich** [comment]
Hi! That’s great & highly appreciated! Once your PR is merged please mail me your post address so I can send you our famous „first time contributor sticker pack“! 😊 Cheers, Björn

 

Von: Sakshi Uppoor ***@***.***> 
Gesendet: Sonntag, 2. Januar 2022 16:52
An: juice-shop/juice-shop ***@***.***>
Cc: Björn Kimminich ***@***.***>; Mention ***@***.***>
Betreff: Re: [juice-shop/juice-shop] [🐛] Errors not rendered on "Change Password" form (Issue #1733)

 

Hi @bkimminich <https://github.com/bkimminich> 
I would like to work on this issue
Will make a PR soon

**Comment by SakshiUppoor** [comment]
Thanks for the speedy response, Björn! :D

Sorry, I deleted my previous comment. Thought it would be better to explain my approach too but then decided to mention it in the PR itself

**Comment by bkimminich** [comment]
Thanks @SakshiUppoor for this fix! If you email or Slack-DM me your address, I'll send you [those promised stickers](http://juice-shop.github.io/juice-shop/#/11/10) asap!
