### ISSUE TITLE
[🐛] npm erro while installing from source

### ISSUE THREAD

**Issue by spacemanssd** [juice-shop/juice-shop#1745]
when i run: npm install i get the follow error
``
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nlpjs/language@^4.22.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
``

EDIT: It seems  it's a problem related to npm:  https://github.com/axa-group/nlp.js/issues/1031 , there is nothing you can do.

**Comment by bkimminich** [comment]
If @axa-group doesn't fix this in a timely manner I'll try to trace the dependency paths and declare all manually within `juicy-chat-bot` until they do.
