### ISSUE TITLE
Add Server-side JS Injection flaw

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#175]
see http://nodegoat.herokuapp.com/tutorial/a1

:skull: Danger: Adding something like unsafe `eval()` would make Juice Shop easily DoS'able without any chance of self-recovery other than restart! Challenge must ask for a non-dangerous script injection! 
##

**Comment by jonasvanalderweireldt** [comment]
Whitelist a set of usable commands that can be send to the server. Keep in control of what commands you can expect.

**Comment by bkimminich** [comment]
Obsolete through #269.
