### ISSUE TITLE
[🧹] Migrate insecurity.js lib to TypeScript

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1758]
During the migration of the server-side codebase to TypeScript the `/lib/insecurity.js` was not migrated as this caused errors in automated tests and at runtime which could not be solved back then.

## Recommended steps 

1. Renaming the file into `insecurity.ts`
2. Running all test suites (particularly `npm run frisby`)
3. Gradually correcting the runtime issues
4. Fix all errors from `npm run build:server` on `insecurity.ts`

**Comment by njmulsqb** [comment]
Please assign this to me!

**Comment by bkimminich** [comment]
Happy to do so!

**Comment by njmulsqb** [comment]
I have forked and cloned the repo, and ran `npm run frisby` and technically it should pass as I have not made any changes in the  code but still one of out of 47 test suites is failing.
Failed test suite:  
![image](https://user-images.githubusercontent.com/47940898/161033134-bfdf9b37-a123-4a13-aa70-33aabda1fc6a.png)
What could be the reason? Stackoverflow.com is working fine in browser then why is it receiving timeout?

**Comment by ShubhamPalriwala** [comment]
Try running it again! Probably a timeout issue of your CLI.

**Comment by bkimminich** [comment]
Yeah, that test is glitchy sometimes... 😐

**Comment by bkimminich** [comment]
Hi @njmulsqb! Any progress on this issue or should I unassign it so someone else might work on it?

**Comment by njmulsqb** [comment]
> Hi @njmulsqb! Any progress on this issue or should I unassign it so someone else might work on it?

Actually these days I am working on a ZAP issue and would come back to this later, but if its urgent you can assign it to someone else, no problem

**Comment by ShubhamPalriwala** [comment]
@njmulsqb @bkimminich Let me know if you want me to take this up? Should not ideally take much time as it should be pretty direct after the migration of the models in my opinion!

**Comment by njmulsqb** [comment]
> @njmulsqb @bkimminich Let me know if you want me to take this up? Should not ideally take much time as it should be pretty direct after the migration of the models in my opinion!

Sure

**Comment by ShubhamPalriwala** [comment]
Can we close this now? @bkimminich? I doubt that the PR got linked hence auto-closing failed
