### ISSUE TITLE
Error while running npm start in the juice-shop directory

### ISSUE THREAD

**Issue by Somdutta** [juice-shop/juice-shop#1762]
Hi,

I have installed nodejs and npm whose versions are v8.10.0 and v3.5.2. I am using Ubuntu18.04. I followed the installation steps of installing juice-shop from "sources". When I run npm start in the juice-shop directory I get an error. Attached is the log file showing the error. I have also tried the same using the archive, https://github.com/bkimminich/juice-shop/releases/download/v8.4.0/juice-shop-8.4.0_node11_linux_x64.tgz.
[npm-debug.log](https://github.com/juice-shop/juice-shop/files/8037976/npm-debug.log)

Thanks,
Somdutta.

**Comment by bkimminich** [comment]
The version of Juice Shop you are trying to install is long out of any support as is the NodeJS version you have. The archive you tried is for NodeJS 11 and also won't work with your installed NodeJS 8.

If you really want to use such an old Juice Shop version, I recommend you try a Docker image, but it's a better idea to just install latest NodeJS 14 or 16 and use the latest Juice Shop release. Make sure to download the correct archive for the version you plan to use.

**Comment by Somdutta** [comment]
Hi,

I have updated versions of juice shop and nodejs. I am using Juice shop version 13.2.2, npm version 8.3.1 and 16.14.0.  I am getting the following error:
Error: The module '/home/cc/Downloads/juice-shop_13.2.2/node_modules/libxmljs2/build/Release/xmljs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

Any suggestions on how to resolve this?

Thanks.

**Comment by bkimminich** [comment]
You downloaded an archive for a different NodeJS version. The version is in the archive filename, if you use a matching one, it should work. If it still doesn't, I recommend using Docker instead.

**Comment by Somdutta** [comment]
Thanks. I was able to start juice shop.
