### ISSUE TITLE
Security question's field which is the drop down menu is not working.

### ISSUE THREAD

**Issue by Somdutta** [juice-shop/juice-shop#1763]
Hi,

I have installed juice shop and it is running. I am trying to register, but the security question's field which is the drop down is not working.  I have tried with Chrome version 98.0.4758.80 and Firefox version 96.0 - both 64 bit version.

Has anyone else faced this issue?

Thanks.

**Comment by bkimminich** [comment]
I cannot reproduce this problem. Works on https://demo.owasp-juice.shop (`master`) and https://staging.owasp-juice.shop (`develop`) just fine. If those work for you too, then something unrelated to Juice Shop is broken in your setup, I assume.

**Comment by Somdutta** [comment]
Could it be because I get the following error when I do a npm start?


Error: algorithms should be set
    at module.exports (/home/cc/Downloads/juice-shop_13.2.2/node_modules/express-jwt/lib/index.js:22:34)
    at Object.exports.isAuthorized (/home/cc/Downloads/juice-shop_13.2.2/build/lib/insecurity.js:28:30)
    at /home/cc/Downloads/juice-shop_13.2.2/build/server.js:266:38

After this error it shows that Server is listening on 3000.

**Comment by bkimminich** [comment]
If you get errors during installation, all bets are off for what happens when you start the application. If you run into installation issues you cannot trace, best try a packaged archive (version must match your NodeJS and OS) or - even safer - Docker image.

For additional help with your install issues I'd need to see the full logs.

**Comment by Somdutta** [comment]
When I ran "sudo npm install" in the juice shop directory I get the following:

npm WARN lifecycle juice-shop@13.2.2~postinstall: cannot run in wd juice-shop@13.2.2 cd frontend && npm install --legacy-peer-deps && cd .. && npm run build:frontend && (npm run --silent build:server || cd .) (wd=/home/cc/Downloads/juice-shop_13.2.2)
audited 2091 packages in 6.776s

139 packages are looking for funding
  run `npm fund` for details

found 11 vulnerabilities (10 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for detailsjuice-shop@13.2.2

After this I ran "sudo npm start" and it says "Server is listening on 3000".

The juice-shop version is juice-shop@13.2.2.

The log for the command "sudo npm start" is given below:

> juice-shop@13.2.2 start /home/cc/Downloads/juice-shop_13.2.2
> node build/app

info: All dependencies in ./package.json are satisfied (OK)
info: Chatbot training data botDefaultTrainingData.json validated (OK)
info: Detected Node.js version v12.22.10 (OK)
info: Detected OS linux (OK)
info: Detected CPU x64 (OK)
info: Configuration default validated (OK)
info: Required file server.js is present (OK)
info: Required file styles.css is present (OK)
info: Required file main.js is present (OK)
info: Required file tutorial.js is present (OK)
info: Required file polyfills.js is present (OK)
info: Required file index.html is present (OK)
info: Required file runtime.js is present (OK)
info: Required file vendor.js is present (OK)
info: Port 3000 is available (OK)
Error: algorithms should be set
    at module.exports (/home/cc/Downloads/juice-shop_13.2.2/node_modules/express-jwt/lib/index.js:22:34)
    at Object.exports.isAuthorized (/home/cc/Downloads/juice-shop_13.2.2/build/lib/insecurity.js:28:30)
    at /home/cc/Downloads/juice-shop_13.2.2/build/server.js:266:38

**Comment by bkimminich** [comment]
https://pwning.owasp-juice.shop/appendix/troubleshooting.html recommends something for this issue, can you try that please?

```
If npm install on Linux runs into WARN cannot run in wd problems (e.g. during the frontend installation step) try running npm install --unsafe-perm instead.
```

If that doesn't help, it is some issue on OS/permission/system level that is not fixable for Juice Shop. I can only advise you again to switch to Docker in that case.
