### ISSUE TITLE
[🐛] Submitting deluxe-membership payment form without selecting payment method crashes app

### ISSUE THREAD

**Issue by CrazyKidJack** [juice-shop/juice-shop#1786]
[juice-shop_dockerHubLog.txt](https://github.com/juice-shop/juice-shop/files/8430114/juice-shop_dockerHubLog.txt)

# :bug: Bug report

## Description

This is probably a low priority bug.

When on the deluxe-membership payment form, I removed the "disable" attribute from the submit button and clicked the button. That cased the whole app to crash.

### Is this a regression?

Unknown

## :microscope: Minimal Reproduction

Note: I'm doing this on the docker version of the app... i don't know if that makes a different or not

1. login with your own account
2. navigate to http://localhost:3000/#/deluxe-membership
3. click "Become a member"
4. "inspect" continue button
5. manually remove `disabled="true"` attribute
6. Click continue button
7. See application crash

## :fire: Exception or Error
See attached file for the full run log copied from Docker Desktop. The _most_ relevant error is at the very bottom.
<pre><code>

</code></pre>

## :deciduous_tree: Your Environment
I'm just using the provided docker container as is. What follows are the values shown in the "inspect" tab of Docker Hub for this container
<pre><code>

Environment
PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

NODE_VERSION
16.13.2

YARN_VERSION
1.22.15

Port
3000/tcp
0.0.0.0:3000
</code></pre>

**Comment by bkimminich** [comment]
Good catch! I'll leave this one open (e.g. as a low-entry-barrier task for future GSoC students) as it has probably a straightforward root cause and should be fixable without disturbing any actual hacking challenges. If it doesn't get picked up before going stale, I'll fix it myself.

**Comment by bkimminich** [comment]
Just tested with Node.js 14.x and there it only throws an error but doesn't crash, but since Node.js 16 promise error are known to be less forgiving. Will make sure this one is caugth and sent to the error handler instead.

**Comment by CrazyKidJack** [comment]
Our of curiosity, what is a “GSoC” student?

Thanks,
Jackson Pfeffer
White Box Pen Testing – Citi Global InfoSec
BS in Computer Science at UNT, UT Austin, and CCCC
BA in Music Performance (partial) at UNT and UT Austin
Eagle Scout

**Comment by bkimminich** [comment]
GSoC = Google Summer of Code
