### ISSUE TITLE
Missing challenges

### ISSUE THREAD

**Issue by cybertuxh4xor** [juice-shop/juice-shop#1790]
I am running version 13.3.0 on Kali Linux using docker. I am going through a course from TCMSecurity that walk though different types of XSS challenges. It appears that my version is missing all XSS challenges expect, 
![image](https://user-images.githubusercontent.com/88122300/162586397-ed6b76db-8782-442a-8929-d18139d9b16f.png)
as compared to what i am seeing the in the course material,which has: API-only XSS,Classic Stored XSS, Client-side XSS Protection, HTTP-Header XSS, Reflected XSS, Server-side XSS Protection, Video XSS.
I have selected show all and it still only shows the 2x in the screenshot. All help is appreciated.

**Comment by bkimminich** [comment]
> using docker

This solves the issue... 😁 See https://pwning.owasp-juice.shop/part1/challenges.html#potentially-dangerous-challenges. If you click the _Show unavailable_ button on the Score Board (which wouldn't be there if all challenges were enabled) you'll see the missing ones.
