### ISSUE TITLE
"Deploy to Heroku" button in github doesn't seem to work.

### ISSUE THREAD

**Issue by connorcarr** [juice-shop/juice-shop#1795]
I tried across two browsers to deploy to heroku on a newly-created account via clicking the button at https://github.com/juice-shop/juice-shop#deploy-on-heroku-free-0month-dyno and this seemed to load indefinitely.

Visiting https://elements.heroku.com/buttons/bkimminich/juice-shop and clicking the "Deploy to Heroku" button works.

**Comment by bkimminich** [comment]
Please try with a different browser and make sure that there is no interference from plugins etc. with the referer header that the button is relying on. So far all Heroku button issues we ever encountered were solvable by using a "vanilla" browser instance. Just tested on Chrome and it works just fine for me.

**Comment by connorcarr** [comment]
Thanks for the quick response. My initial attempt was with Firefox that contained several addons, it worked without the addons. My second attempt was with Safari, which still doesn't seem to work, but I can live without Safari support! That would likely be a Heroku issue regardless. I'll close my issue, thanks again.
