### ISSUE TITLE
[🐛] Liking a review with empty ID crashes the app

### ISSUE THREAD

**Issue by Geetub** [juice-shop/juice-shop#1797]
# :bug: Bug report

## Description
Sending a POST message to /rest/products/reviews with empty ("") ID causes the app to crash.
Easily reproduce with FireFox "edit and resend" after doing a legit "like".

### Is this a regression?
Unknown

## :microscope: Minimal Reproduction
1. Login to the Juice Shop
2. Pick a product with some review that wasn't yet liked by the current user.
3. Press the like button for the review.
4. Resend the last post message to /rest/products/reviews with ID set to "".
5. See application crash

## :fire: Exception or Error
<pre><code>
D:\juice-shop_13.3.0\build\routes\likeProductReviews.js:16
            const likedBy = review.likedBy;
                                   ^
TypeError: Cannot read properties of undefined (reading 'likedBy')
    at D:\juice-shop_13.3.0\build\routes\likeProductReviews.js:16:36
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.9.0
</code></pre>

## :deciduous_tree: Your Environment

<pre><code>
Windows 10 Home

Node:
v17.9.0

npm:
8.5.5

</code></pre>

**Comment by Geetub** [comment]
Hi,
Thanks for handling this.
I re-tested the server with this fix but it still crashes few lines later when accessing the non-existent review.
(Please see my comment on the commit)

**Comment by bkimminich** [comment]
You're right, it wasn't fully fixed. It now immediately throws a `404` when no review is found in the outmost code block, so crashes should no longer occur.
