### ISSUE TITLE
Bypass built-in WAF [⭐] 

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1804]
# :star: Challenge idea

### Description

Juice Shop could add a JavaScript WAF module (e.g. https://github.com/undertuga/WAF-JS or https://github.com/MurylloEx/Mini-WAF) and configure it so that it either offers some (bypassable) protection in front of an existing or a newly created challenge.

### Underlying vulnerability/ies

Security Misconfiguration of WAF module, e.g. https://github.com/undertuga/WAF-JS or https://github.com/MurylloEx/Mini-WAF

### Expected difficulty

Could become actually two challenges, one easy rule bypass, one hard.

**Comment by the-pro** [comment]
I was looking into this and found a way we can include this in juice shop. In https://github.com/undertuga/WAF-JS, the isBotCheck method just checks the user-agent of a request and rejects it if it matches one of the preloaded signatures. We can include signatures of some well known automation frameworks like selenium, puppeteer, cypress etc. so the user cannot solve the challenge without overriding the default user-agent of the script. It can be included in the challenge captcha bypass where you have to write a script to solve the challenge.

**Comment by bkimminich** [comment]
Ah, so it wouldn't become a new challenge but just make the Captcha Bypass and other scriptable challenges maybe +1⭐ more difficult. That also works for me!

**Comment by the-pro** [comment]
Also, should we write our own similar method of bot-check or use the wafjs library as it is not maintained.

**Comment by bkimminich** [comment]
Using an unmaintained lib is kind of the point, because we want our users to be able to find out which one we use, so they can check how it works. In this case it's easy to bypass anyway, but still makes it a bit more realistic for Juice Shop to just use some "legacy module" without even checking what it can and cannot do.

**Comment by bkimminich** [comment]
We need to add wafjs then also to the `ftp/package.json.bak` or spoiler some place else, that we use it.

**Comment by the-pro** [comment]
> more realistic for Juice Shop to just use some "legacy module" without even checking what it can and cannot do.

😅 
Got it.

**Comment by the-pro** [comment]
Seems like the user-agent only has some detectable string only when it runs in headless mode. Otherwise the checker cannot detect the bot
