### ISSUE TITLE
SQL Error from fresh install [🐛] 

### ISSUE THREAD

**Issue by RobertEnderBabaev** [juice-shop/juice-shop#1805]
# :bug: Bug report

## Description

When starting an instance of the Node server, a few seconds after the app says it's listening on port 3000, the app then crashes with an SQLITE error stating that a table is missing. This occurs despite verifying that the table does exist in the Sqlite database.

### Is this a regression?

Unknown.

## :microscope: Minimal Reproduction

1. Get a fresh install of Juice Shop from the main branch
2. `npm install`
3. `npm start`
4. Wait for the error to pop up. If it doesn't within a few seconds, try accessing the app like normal.

## :fire: Exception or Error

<pre><code>

> juice-shop@13.3.0 start
> node build/app

info: All dependencies in ./package.json are satisfied (OK)
Model
info: Chatbot training data botDefaultTrainingData.json validated (OK)
info: Detected Node.js version v16.13.0 (OK)
info: Detected OS linux (OK)
info: Detected CPU x64 (OK)
info: Configuration default validated (OK)
info: Required file server.js is present (OK)
info: Required file index.html is present (OK)
info: Required file styles.css is present (OK)
info: Required file main.js is present (OK)
info: Required file tutorial.js is present (OK)
info: Required file polyfills.js is present (OK)
info: Required file runtime.js is present (OK)
info: Required file vendor.js is present (OK)
(node:84251) [DEP0152] DeprecationWarning: Custom PerformanceEntry accessors are deprecated. Please use the detail property.
(Use `node --trace-deprecation ...` to show where the warning was created)
info: Port 3000 is available (OK)
/home/robert/Experimental/juice-shop/node_modules/sequelize/lib/dialects/sqlite/query.js:403
        return new sequelizeErrors.DatabaseError(err);
               ^

DatabaseError [SequelizeDatabaseError]: SQLITE_ERROR: no such table: Wallets
    at Query.formatError (/home/robert/Experimental/juice-shop/node_modules/sequelize/lib/dialects/sqlite/query.js:403:16)
    at Query._handleQueryResponse (/home/robert/Experimental/juice-shop/node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
    at afterExecute (/home/robert/Experimental/juice-shop/node_modules/sequelize/lib/dialects/sqlite/query.js:238:27)
    at Statement.errBack (/home/robert/Experimental/juice-shop/node_modules/sqlite3/lib/sqlite3.js:14:21) {
  parent: [Error: SQLITE_ERROR: no such table: Wallets] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'SELECT sum(`balance`) AS `sum` FROM `Wallets` AS `Wallet`;'
  },
  original: [Error: SQLITE_ERROR: no such table: Wallets] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'SELECT sum(`balance`) AS `sum` FROM `Wallets` AS `Wallet`;'
  },
  sql: 'SELECT sum(`balance`) AS `sum` FROM `Wallets` AS `Wallet`;',
  parameters: undefined
}
</code></pre>

## :deciduous_tree: Your Environment

<pre><code>

v16.13.0
8.1.0
</code></pre>

**Comment by bkimminich** [comment]
Please see https://github.com/juice-shop/juice-shop/issues/1380 or https://pwning.owasp-juice.shop/appendix/troubleshooting.html#sqlite
