### ISSUE TITLE
[🐛] unclear score: bug or feature?

### ISSUE THREAD

**Issue by ghost** [juice-shop/juice-shop#1818]
# :bug: Bug report

## Description

I read things like "solved in 69min (expected ~8min) " in the terminal. It seems there are extra points for the fastest hackers, which sounds fair for a CTF, but how can you solve 6-stars challenges in 8min?

Sometimes, you have to code custom scripts, and these challenges (even some with 4-5 stars) are not trivial.

Is it the expected speed?

**Comment by J12934** [comment]
Hi 👋

these aren't meant to be be extra points, they are intended to catch obvious cheating in competitions, that's why it's called "cheat score" :)

See more on https://pwning.owasp-juice.shop/appendix/cheat-detection.html

**Comment by ghost** [comment]
@J12934 ouch! I did not read the fabulous manual carefully 😕.
