### ISSUE TITLE
[🐛] Alternative solution to challenge "Kill Chatbot"

### ISSUE THREAD

**Issue by jiachen247** [juice-shop/juice-shop#1819]
# :bug: Bug report

## Description
The challenge states: **Permanently disable the support chatbot so that it can no longer answer customer queries.**
When queried with the following string, the chatbot VM enters into an inf loop and fails to respond further request. This should be a valid solution as well however, challenge was not solved and points were not issued.

Method 1: `hello", ""); users = {}//`
Method 2: `'hello", ""); while(true){};//'`

![image](https://user-images.githubusercontent.com/17170991/169955649-53c1fa19-02b4-4677-9155-470f8a934db3.png)

Not too sure what's the success condition / metric for this challenge but it seems to be tied to a specific way of solving the challenge, Im wondering if there is a more general way to check that the bot is dead.

### Is this a regression?

Nope

## :microscope: Minimal Reproduction

- Login and go to support chat
- Enter `hello", ""); users = {}//`
- Notice no further respond from the bot upon more queries

## :deciduous_tree: Your Environment
- Running locally on M1 MBP
- Node 14
- Firefox

**Comment by bkimminich** [comment]
It is indeed tied to shutting down the process the bot runs in completely. We'll have to check if this could be expanded w/o making the challenge too easy, as we do have another challenge solvable by infinite loops already. Other options: Adding a second challenge with -1 difficulty that allows more solutions _or_ expanding the description to clarify infinite loops do not count.
