### ISSUE TITLE
Installation problem: Can't fin module error

### ISSUE THREAD

**Issue by KingTomasi** [juice-shop/juice-shop#1848]
Hello everyone, I try to start juiceshop, after going through the installation process and I keep getting this error:
![Screenshot_2022-07-23_08_30_43](https://user-images.githubusercontent.com/55114030/180605109-5d5248fc-db3d-4e4f-98e4-48f986add660.png)

Please is there a fix?

**Comment by bkimminich** [comment]
So, you install without error from source? And then it doesn't start? I saw you use Kali, which is almost always problematic with Node.js. So your easiest way to get going is to use Docker or another OS.

**Comment by KingTomasi** [comment]
Yes I install without error from the start only for it not to run when I try to use
I will try docker, thanks!

**Comment by bkimminich** [comment]
https://pwning.owasp-juice.shop/appendix/troubleshooting.html#linux
