### ISSUE TITLE
[🐛] CSRF challenge not possible anymore?

### ISSUE THREAD

**Issue by DarkR0ast** [juice-shop/juice-shop#1868]
# :bug: Bug report

## Description

While trying to complete the CSRF challange using Firefox 140.0, I was not able to complete the challenge because the token cookie (or any other) is not beeing send during the post request, using the required HTML website and suggested HTML form code. Based on the current Juiceshop documentation it should be possible to solve the challange with Firefox as long as the default behaviour for not specifying the SameSite cookie attribute in Firefox and the default behaviour for the used cookie library (ngx-cookie) does not change.  (See Issue #1592 ) As far as I can tell the library didn't mention any changes in their recent commits and by checking https://samesite-sandbox.glitch.me/ I can see that the browser also behaves as expected and I see the "set x" in the "Cross-site?" column. So I don't think that the used cookie library or the browser default behavior for not setting the SameSite flag on a cookie are the problem. Also, when I inspect my cookies locally they are set correctly: Secure: false and SameSite: None.

Based on this I assume that the Browser should send the corresponding cookies which it doesn't. Am I missing something?

Update: After searching for a bit on the Mozilla developers page (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) it mentions that standards related to the Cookie SameSite attribute recently changed as expected, e.g.: "Cookies with SameSite=None must now also specify the Secure attribute (they require a secure context/HTTPS)." I guess this is the problem? However then there is the question why does it work on the https://samesite-sandbox.glitch.me/ website? 

### Is this a regression?

Based on previous issues I assume that the challenge worked without needing an outdated browser version after issue #1592 was merged (on 28 Mar 2021)

## :microscope: Minimal Reproduction

Follow the CSRF challange's description on how to solve it, using an up to date Firefoy browser.

## :fire: Exception or Error
The following error is displayed because no authentication token is included inside the request:

<pre><code>

Error: Blocked illegal activity by ::ffff:172.24.96.1
    at /home/stephan/juicy/juice-shop/build/routes/updateUserProfile.js:38:18
    at Layer.handle [as handle_request] (/home/stephan/juicy/juice-shop/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/stephan/juicy/juice-shop/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/stephan/juicy/juice-shop/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/stephan/juicy/juice-shop/node_modules/express/lib/router/layer.js:95:5)
    at /home/stephan/juicy/juice-shop/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/stephan/juicy/juice-shop/node_modules/express/lib/router/index.js:346:12)
    at next (/home/stephan/juicy/juice-shop/node_modules/express/lib/router/index.js:280:10)
    at /home/stephan/juicy/juice-shop/build/routes/verify.js:135:5
    at Layer.handle [as handle_request] (/home/stephan/juicy/juice-shop/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/stephan/juicy/juice-shop/node_modules/express/lib/router/index.js:328:13)
    at /home/stephan/juicy/juice-shop/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/stephan/juicy/juice-shop/node_modules/express/lib/router/index.js:346:12)
    at next (/home/stephan/juicy/juice-shop/node_modules/express/lib/router/index.js:280:10)
    at /home/stephan/juicy/juice-shop/build/routes/verify.js:71:5
    at Layer.handle [as handle_request] (/home/stephan/juicy/juice-shop/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/stephan/juicy/juice-shop/node_modules/express/lib/router/index.js:328:13)
    at /home/stephan/juicy/juice-shop/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/stephan/juicy/juice-shop/node_modules/express/lib/router/index.js:346:12)
    at next (/home/stephan/juicy/juice-shop/node_modules/express/lib/router/index.js:280:10)
    at logger (/home/stephan/juicy/juice-shop/node_modules/morgan/index.js:144:5)
    at Layer.handle [as handle_request] (/home/stephan/juicy/juice-shop/node_modules/express/lib/router/layer.js:95:5)

</code></pre>

## :deciduous_tree: Your Environment

<pre><code>
node: v16.17.0
npm: 8.15.0

</code></pre>

### Additional Information

Tried it with Firefox 104.0.

Also, I am running the JuiceShop application from source and start it normally using npm start. The app runs inside WSL2 and therfore I don't access it via localhost but a different ip.

(This is my first bug report ever, please excuse any mistakes or forgotten info. Ty!)

**Comment by bkimminich** [comment]
I can confirm that it does not work for me in Firefox 104 and also not in Chrome 104 launched with `--disable-features=SameSiteByDefaultCookies`.

**Comment by bkimminich** [comment]
If someone can test with an older FF version or some other less prominent browser and get it to work, please comment here so I can update the challenge hints and step-by-step solution.

We can also test with older library versions for the cookies, but I also doubt this is the reason for CSRF not working. Maybe it's really dying out finally... 🤞 ... 😁

**Comment by DarkR0ast** [comment]
Yes, it seems to be dying ou thank god. 😄  

Also, a possible reason why the cookies are being sent at https://samesite-sandbox.glitch.me/ and not at http://htmledit.squarefree.com/ seems to be that https://samesite-sandbox.glitch.me/ uses another website embedded as an iFrame to evaluate if cookies would be included in a request from a different origin. And apparently websites embedded as an iFrame seem to be a special case for Firefox where the SameSite=None flag is still treated the old way (meaning cookies will be included in the resquest), even when the Secure flag is not set (only reference I could find:  https://makandracards.com/makandra/71018-samesite-cookies).

**Comment by DarkR0ast** [comment]
After testing a couple of versions the attack seems to work all the way up to version 100 of Firefox, even though it shouldn't be possible since version 96 (https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/96). Based on some bug reports it looks like they did some rollbacks in between Version 96 and 100.

So recommending any version below (including) version 100 of Firefox should work based on my testing, and any version below version 96 will work 100%. The highest version I could get the attack to work is Firefox 100. So recommending FF 100 is an option.

**Comment by bkimminich** [comment]
Brilliant, I'll add this to the ebook hints and the the hint-text that is shown when hovering over the "Unsolved"-badge on the Score Board. Thanks!

**Comment by jub0bs** [comment]
> Maybe it's really dying out finally...

Not quite: https://jub0bs.com/posts/2021-01-29-great-samesite-confusion/

Eventually, all major browsers are likely to default to `SameSite=Lax`, which will make the _CSRF_ challenge unviable, short of a same-site Web origin from which to launch the attack. I see two ways of extending the life of this challenge:

- Set the `token` cookie with `SameSite=None` and `Secure`. Downside: Juice Shop would need to be set up with HTTPS or things would simply not work.
- Hint that the attack is only possible from a same-site Web origin. That's comparatively easier to set up, because `http://localhost:3000` (Juice Shop) and, say, `http://localhost:3001` (the attacking origin) are considered same-site.
