### ISSUE TITLE
[🐛] Reflected XSS Attack not working

### ISSUE THREAD

**Issue by astra1dev** [juice-shop/juice-shop#1876]
# :bug: Bug report

## Description

I´m trying to solve the "Reflected XSS" Challenge in the Juice Shop. 
But when I paste the Code in the URL and reload the page, then it only shows this:
![image](https://user-images.githubusercontent.com/90265231/188433745-6a1299d3-86d8-4733-888f-4f6a1bbc7333.png)
and no popup...

## :microscope: Minimal Reproduction
just click this link: http://127.0.0.1:3000/#/track-result?id=%3Ciframe%20src%3D%22javascript:alert(%60xss%60)%22%3E

## :deciduous_tree: Your Environment

I´m hosting the Juice Shop locally on my computer using npm
In my browser I allowed the usage of javascript 

### Additional Information

I´m using Windows 11 and Brave as browser

**Comment by bkimminich** [comment]
I can reproduce this issue with `v14.2.0` in latest Chrome and Firefox on Windows 10.

**Comment by bkimminich** [comment]
This challenge is disabled by default when a Docker or Heroku environment is detected, and the string returned as tracking ID looks exactly sanitized like that. This sanitization should not trigger in general, though. Will have to check what happened there and when.

**Comment by bkimminich** [comment]
Root cause: https://github.com/juice-shop/juice-shop/blob/master/lib/utils.ts#L155 fires `true` in the `isGitpod()` check on Windows. This is not visible on the Score Board as Windows is checked before Gitpod when determining the environment, so Juice Shop considers running on Windows when preparing the disabled challenges on the Score Board. But then during challenge checks, it triggers the Gitpod check as `true`. This should affect all challenges which are disabled on Gitpod, i.e. all stored XSS, the XXE and some more as well. This doesn't occur during CI/CD as there the e2e suite runs on Linux and not Windows.

CC: @knut-erik

**Comment by knu73r1k** [comment]
Thanks for notifying @bkimminich - I'll try to have a look into this later.

**Comment by astra1dev** [comment]
ive tried running the juice shop in my kali VM, and it says this:
"16 challenges are unavailable on Gitpod due to security concerns or technical incompatibility"
so i guess its the same error on kali aswell

**Comment by bkimminich** [comment]
I opened a ticket with the `isGitpod` module already, it seems their check is just checking for a message that now looks different, therefore all think they're on Gitpod.

**Comment by bkimminich** [comment]
@kkb3st, this issue should be solved via workaround now. I will enable the `isGitpod()` check once the issue on their end is fixed. For now it is overwritten with `const isGitpod = () => { return false }`.

**Comment by yuvadm** [comment]
This issue still persists in `latest` docker image on `arm64`:

```bash
$ docker images --digests
REPOSITORY              TAG       DIGEST                                                                    IMAGE ID       CREATED      SIZE
bkimminich/juice-shop   latest    sha256:6102f82c1b3ee80aa29dafa2d8d4029312662dce1f4cd8411c2fac274cd5b523   c7b660b49703   3 days ago   522MB
```

**Comment by bkimminich** [comment]
On Docker this challenge is in fact disabled by default. Please check your Score Board if the challenge is there, and if not enable the "Show unavailable" filter. It should then state that it is unavailable.

You can run Juice Shop with `NODE_ENV=unsafe` environment variable to turn all dangerous challenges back on.
