### ISSUE TITLE
[🚀] Cypress Improvements

### ISSUE THREAD

**Issue by ShubhamPalriwala** [juice-shop/juice-shop#1878]
# :rocket: Cypress Test Suite enhancements

A Tracker issue to keep a log of all the improvements and enhancements to be made:
- [x] Reduce test time for the bullyChatbot spec:
    check for the coupon to be out and then break when the source has the text: "Oooookay, if you promise to stop nagging me here's a 10% coupon code for you"

- [ ] Remove cy.wait() in the login command:
    check for products to be loaded rather than 500 ms wait time

- [x] Skip the delay due to the "translation info" modal:
    try to set the language via cookie storage not to show the modal by setting the following cookie before the tests:
    ````
	"language : en"
    ````

- [x] Add Linting
    Add the directory to our listing rules and lint the entire directory (make manual changes if any errors are received when automated)
- [x] Move cypress directory
   Move the current cypress directory from root to under `test/`
- [x] Remove the old e2e CI/CD pipelining
    Remove the old tests running in the CI via GitHub actions and only run Cypress e2e tests and not the old e2e ones
- [x] Add documentation for running Cypress tests 
- [x] Remove upload artifacts for Cypress in GitHub Actions since we can now use the Cypress dashboard for the same [Added on 2nd October]

Feel free to add any more enhancements/bugs regarding our Cypress testing!

**Comment by ShubhamPalriwala** [comment]
Damn, this is my first issue, WOAHHH! Thanks for the heads-up lmao

**Comment by bkimminich** [comment]
> Damn, this is my first issue, WOAHHH! Thanks for the heads-up lmao

Luckily it wasn't a support request... 😇

**Comment by bkimminich** [comment]
Languages cookie is already set: https://github.com/juice-shop/juice-shop/blob/develop/cypress/support/setup.ts#L4

**Comment by bkimminich** [comment]
I've added a first part of the documentation via https://github.com/juice-shop/pwning-juice-shop/commit/1d2d1f864ad441a115e5af0a5177daa37960421d but I don't think this is necessarily the smartest way to locally start those tests. Also the docs need to be updated again once the tests have been moved to their final location.
