### ISSUE TITLE
Juice-Shop crashes when solving challenge "Database Schema"

### ISSUE THREAD

**Issue by hcoggins** [juice-shop/juice-shop#1885]
# :bug:  Bug report
## Description

The Juice-Shop crashes when attempting to solve the challenge "Database Schema" when calling the following url for a locally running instance:

 `localhost:3000/rest/products/search?q=a'))+union+select+sql,2,3,4,5,6,7,8,9+from+sqlite_master+where+type='table'--`

The Juice-Shop responds with the information about the database schema, but then immediately crashes.

### Is this a regression?
I could not find an earlier version where the Juice-Shop did not crash

## :microscope:  Minimal Reproduction
1. Start the Juice-Shop with `npm run start` from the project directory
2. Paste the following url into the address bar of your browser:  
`localhost:3000/rest/products/search?q=a'))+union+select+sql,2,3,4,5,6,7,8,9+from+sqlite_master+where+type='table'--`

## :fire: Exception or Error

```
juice-shop/build/lib/utils.js:72
    return (0, exports.contains)(str, element.replace(/"/g, '\\"'));
                                              ^

TypeError: Cannot read properties of null (reading 'replace')
    at containsEscaped (/juice-shop/build/lib/utils.js:72:47)
    at Object.containsOrEscaped (/juice-shop/build/lib/utils.js:76:79)
    at /juice-shop/build/routes/search.js:50:54
```

## :deciduous_tree: Your Environment

The bug was observed on the following environment:

node: v16.17.0
npm: 8.15.0

but could not be reproduced with:

node: v14.20.0
npm: 6.14.17

### Additional Information
System Information:
* OS: Arch Linux 
* Kernel: 5.19.7-arch1-1

Also, I encountered this bug when using the [heroku app](https://juice-shop.herokuapp.com/#/), which may have caused it to crash. If that is the case, I am very sorry.

**Comment by bkimminich** [comment]
Will be fixed with 14.3.0 release. Thanks for reporting this! ❤️
