### ISSUE TITLE
Juiceshop crashes in chatbot

### ISSUE THREAD

**Issue by CyberStefNef** [juice-shop/juice-shop#1909]
# :bug: Bug report

## Description

If the user sets a username in their account settings with malicious code, the Juice Shop server crashes.

## :microscope: Minimal Reproduction

1. Log in as a User
2. Go to your account page and set the username to, for example: "
3. Try to go to the Chatbot

## :fire: Exception or Error
<pre><code>
users.addUser("2", """)
                   ^^
SyntaxError: missing ) after argument list
    at new Script (node:vm:100:7)
    at VM.run (C:\Users\...\Downloads\juice-shop-14.3.0_node16_win32_x64\juice-shop_14.3.0\node_modules\vm2\lib\main.js:878:13)
    at Bot.addUser (C:\Users\...\Downloads\juice-shop-14.3.0_node16_win32_x64\juice-shop_14.3.0\node_modules\juicy-chat-bot\index.js:36:18)
    at C:\Users\...\Downloads\juice-shop-14.3.0_node16_win32_x64\juice-shop_14.3.0\build\routes\chatbot.js:155:17
</code></pre>

## :deciduous_tree: Your Environment
<pre><code>
node: v16.17.0
npm: 8.15.0
</code></pre>

**Comment by bkimminich** [comment]
Confirmed crash when setting the username in the user profile first and then going to the chatbot page. Crash does _not_ occur when going to the chatbot directly without username set and then answering the question for my name with `"`. It then just logs `error: Could not set username: missing ) after argument list`. Tested with `juicy-chat-bot` version 0.6.6.

Anwering the chatbot question for your name as `"` and then going to the profile gives the following username field:
```
<input class="form-control mdl-textfield__input" id="username" type="text" name="username" value="&quot;" style="color: #FFFFFF;" placeholder="e.g. SuperUser" aria-label="Text field for the username">
```
In the `Users` table the username is stored as `"` for the user. Setting the username via the profile page instead will lead to the exact same HTML on the profile and also the exact same DB property.

The difference is when going back to the chatbot:
- If the name was stored as `"` via the chatbot, it will ask again for the name as if it didn't recognize the stored one
- If the `"` was stored via the profile page, the crash will occur as described above
