### ISSUE TITLE
Heroku Public Instance Down[🐛] 

### ISSUE THREAD

**Issue by HeIp** [juice-shop/juice-shop#1916]
# :bug: Bug report

## Description

https://juice-shop.herokuapp.com seems to have crashed.
Any way you guys can restart the instance ?

### Is this a regression?

No

### Additional Information

![image](https://user-images.githubusercontent.com/31706214/199049073-20efb0d3-0c2d-4bdb-b28e-449cf35f24b2.png)

**Comment by HeIp** [comment]
Marked it would die in November

**Comment by bkimminich** [comment]
No, it won't die in November. It just gets killed by funny hackers once in a while but then automatically restarts soon after.
