### ISSUE TITLE
[🏗️] Migration to Angular 15

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1925]
<https://update.angular.io/?l=3&v=14.0-15.0>

**Comment by Freedisch** [comment]
Hi, @bkimminich I wanted to know which version of the project should I use to migrate to Angular 15, The develop branch or the master branch? Sorry if the question sounds silly 🤧😁

**Comment by bkimminich** [comment]
All development please on `develop` branch only. Thanks!
