### ISSUE TITLE
[🐛] Error 500

### ISSUE THREAD

**Issue by douglasrosa0110** [juice-shop/juice-shop#1932]
# :bug: Bug report

## Description
We get an error with status 500 when we remove the cookie "token" when the user is logged.

### Is this a regression?
No

## :microscope: Minimal Reproduction
1. User logged
2. Open Browser Console (F12)
3. Click over Storage > Cookies > URL
4. Remove the cookie "token"
5. Refresh the page
6. Click over Account icon (Header) > Email (which is blank)

## :fire: Exception or Error
<pre><code>
Error: Blocked illegal activity by ::ffff:127.0.0.1
    at /home/aluno/development/juice-shop/build/routes/userProfile.js:69:22
    at /home/aluno/development/juice-shop/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:71:3)
</code></pre>

## :deciduous_tree: Your Environment
<pre><code>
v14.21.1

</code></pre>

### Additional Information
I think that this error needs be fixed or should be a challenge.

**Comment by bkimminich** [comment]
This is not a bug. `Blocked illegal activity` errors are deliberately thrown security errors.
