### ISSUE TITLE
[🏗️] Remove support for Node.js 14 (until end of April 2023)

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1941]
As Node.js 14 goes end-of-life on April 30th 2023 Juice Shop should remove support for it by then. Unless the legacy `linux/arm/v7` Docker images can be built on Node.js 16+ by then, these need to be removed as well.

![image](https://user-images.githubusercontent.com/3531020/208513333-5d5d15ed-040d-43ea-9d6a-0def448e8608.png)

**Comment by Subhajit009iitr** [comment]
Hey, I am a beginner in the world of Open Source Contribution and I was looking for Good First issues. This one seemed to me a pretty interesting one. I would love to contribute to solving this issue if you would allow me to do so.

**Comment by bkimminich** [comment]
Node 14 support should not be removed before April, but if you want to take a look into ARMv7 support with a Node 16 or higher Docker base image, that'd be highly appreciated.

**Comment by Subhajit009iitr** [comment]
Ya I would love to.

**Comment by Freedisch** [comment]
Hi @bkimminich, I wonder if this issue should not be closed since you already updated the node version for the docker image and removed the ARMv docker image.

**Comment by bkimminich** [comment]
Not yet, as you can still launch JS locally with Node 14 and 15. The next major release will prevent that behavior, and then the full scope of this issue is solved.

**Comment by Aarav238** [comment]
I want to work on it as I am looking for good first issues , I have knowledge of containerization as well . Please assign this issue to me. @bkimminich

**Comment by bkimminich** [comment]
> I want to work on it as I am looking for good first issues , I have knowledge of containerization as well . Please assign this issue to me. @bkimminich 

Happy to! But please keep in mind that the only thing to work on here is finding out about a possible `arm/v7` image with Node.js 16 or even better 18 as runtime.

If it's working with the new distroless base image we moved to, that'd be amazing, but I think there were some issues building on 32bit. Feel free to play with it and see how far you get.

**Comment by Aarav238** [comment]
we have to make changes in  DockerFile right ?

**Comment by bkimminich** [comment]
You could try using the existing Dockerfile on a 32bit ARM system and if it doesn't work (which is highly likely) you could try to create a separate one which does work.

Up to https://github.com/juice-shop/juice-shop/tree/v14.4.0 we had a Dockerfile.arm for that which was based on Node 14. If you can come up with an image based on Node 18 instead that actually builds and works under 32bit ARM, its a huge success.
