### ISSUE TITLE
[🐛] Checkboxes not aligned with code lines in "Find It" screen

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1948]
The line-selection checkboxes in the "Find It" screen of any Coding Challenge are slightly shifted from the actual line of code which makes it harder to select the correct one:
![image](https://user-images.githubusercontent.com/3531020/210316217-102da905-6911-434b-b5a1-4aafbab5d6cd.png)

Zoomed in this issue is a lot more obvious:
![image](https://user-images.githubusercontent.com/3531020/210316360-c30f8ce0-44f6-4799-a44d-c40a445fecc6.png)

## How to reproduce
1. Go to Score Board
2. Launch Coding Challenge of _Score Board_ challenge (or for any other solved hacking challenge which has a Coding Challenge)
3. Go to "Find It" tab if not already on it

**Comment by MostlyGenius** [comment]
I'd like to solve the issue, please assign it to me.

**Comment by bogminic** [comment]
@MostlyGenius after some digging I think the fix should be changing the padding by adding `padding-top: 14px;` or maybe `padding: 14px 0.5em;` to `#emphasize`. https://github.com/juice-shop/juice-shop/blob/6faf960c1019686c8f05abe1a497fa01a99e082c/frontend/src/app/code-area/code-area.component.scss#L3-L6

**Comment by MostlyGenius** [comment]
Pushed fix can you verify and close please. @bkimminich

**Comment by bkimminich** [comment]
PR is still at one commit. Push didn't go through or maybe went to a wrong branch on your side?

**Comment by bkimminich** [comment]
Fixed by using `padding: 1em 0.5em;` which gives a cleaner alignment than `padding: 14px 0.5em;` did.
