### ISSUE TITLE
[🐛] Code diff component on "Fix It" screen forgets settings

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#1949]
The code diff component on the "Fix It" screen forgets its settings when selecting a different fix option. The component should remember its settings while switching. Even better: It should persist its settings in a cookie that is even included in the local backup, similar to the _Score Board_ filter settings or language selection etc.

# How to reproduce

## 1. Default settings
![image](https://user-images.githubusercontent.com/3531020/210316942-6eae3c9b-352b-4645-852f-ceee17046e0c.png)

## 2. Change settings to personal preference
![image](https://user-images.githubusercontent.com/3531020/210317002-8f0a3990-5248-4490-a2cb-6364c2e61546.png)

## 3. Select different fix option (❌)
![image](https://user-images.githubusercontent.com/3531020/210317042-08222498-b1b9-49b3-9050-99fbd76528d2.png)

## How it should behave (✅)
![image](https://user-images.githubusercontent.com/3531020/210317111-25e5a45f-1468-4d09-bef2-3ea3f61e9dc0.png)

ℹ️ Switching between "Fix It" and "Find It" tab does not make the component forget its settings, as it doesn't reload when doing so.

**Comment by Coder-Manan** [comment]
I would like to work on this issue.
I would be highly obliged if you could provide a specific piece of code / file from where you think this issue arises.
Thanks!

**Comment by Coder-Manan** [comment]
No worries, got it. Also, please assign the issue to me

**Comment by AhmedEHaddad** [comment]
is this like react component ?

**Comment by bogminic** [comment]
I did some digging and the component responsible for the `Fix it` section is CodeFixesComponent.
As we see below, we need to save the `Correct Fix` selection, the `Coding Challenge`, and also information about random fixes into the Cookie.
Maybe something like this:
`{"codingChallenge": "Score Board", "selectedFix: 2, "randomness": [1,2,0]}`
https://github.com/juice-shop/juice-shop/blob/5773e02ba27695790c531bd5e33a8bbe693158e9/frontend/src/app/code-fixes/code-fixes.component.ts#L25-L48

@bkimminich What do you think?

@Coder-Manan Did you managed to find a solution or shall I give it a try?

**Comment by Coder-Manan** [comment]
@bogminic yeah, I also thought on same lines. the angular component has a `Format` attribute which decides between `Side By Side` and `Line By Line`. I have thought of storing the format attribute as string on the local computer and add a listener to the component which changes the value stored in the local computer whenever the user toggles between the two modes.
There were some issues related to logging which was fixed recently hence I will start working now.

**Comment by bkimminich** [comment]
We should not store any information about the randomization order on the client. I don't think this is needed anyway, because only the settings for

1. line-by-line vs. side-by-side
2. show-only-lines-with-differences

are is really needed to get the expected behavior. It is not needed or even desirable to save the selected dropdown.

**Comment by Coder-Manan** [comment]
I have made the code-changes regarding point 1, will do for point 2 also soon (I thought that only point 1 had to be done)

**Comment by Coder-Manan** [comment]
I am setting the `hideMatchingLines` attribute of the code fix component but due to some reason that is not working.
The attribute value is getting set correctly and even the checkbox adjacent to `Only Show Line With Differences` is getting selected/unselected correctly, but the code within the component isn't getting displayed correctly.
There seems to be an issue with the Angular component itself.

**Comment by bkimminich** [comment]
Hm, okay. Maybe it needs some kind of trigger to render after setting this property...

**Comment by Coder-Manan** [comment]
Yeah, but I am unable to find it. The [official documentation](https://www.npmjs.com/package/ngx-text-diff) doesn't specify anything of this sort.

**Comment by Coder-Manan** [comment]
Yeah, I am looking for it... Looks like it will require a bit more work
