### ISSUE TITLE
npm start in localhost or 127.0.0.1 only

### ISSUE THREAD

**Issue by w0lfcat** [juice-shop/juice-shop#1950]
When I run Juice Shop with npm start, I noticed that it's listening on port 3000 and binds to my ip address and anyone within the same network can access this.

Is it possible to change this behavior to localhost or 127.0.0.1?

https://github.com/juice-shop/juice-shop/blob/master/README.md#from-sources

**Comment by bkimminich** [comment]
I'm no network expert, but how is this supposed to work? Your machine is hosting the server on that port, you can access it via localhost or 127.0.0.1 of course, but how should the application server prevent your network IP to also expose port 3000?

**Comment by w0lfcat** [comment]
Thanks for your prompt response, really appreciate it. I'm not sure how to do this with npm, but here is how to do it via docker.

This docker command will open connection to all:
`docker run --rm -p 3000:3000 bkimminich/juice-shop`

Verify it with ss -ant, it's listening on "0.0.0.0:3000"
```
$ ss -ant
State     Recv-Q    Send-Q    Local Address:Port    Peer Address:Port
LISTEN    0         5             0.0.0.0:3000          0.0.0.0:*
```

To limit it to only localhost or 127.0.0.1, use this command:
`docker run --rm -p 127.0.0.1:3000:3000 bkimminich/juice-shop`

Verify it with ss -ant, it's listening on "127.0.0.1:3000" now instead of "0.0.0.0:3000"
```
$ ss -ant
State     Recv-Q    Send-Q    Local Address:Port    Peer Address:Port
LISTEN    0         5             127.0.0.1:3000          0.0.0.0:*
```

Now, no one can access vulnerable juice-shop app except for myself via localhost. 

p/s: I use npm instead of docker image as I wanted to learn about it as well.

**Comment by J12934** [comment]
I don't think it currently possible without code changes.
You specify where to listen on in then server.listen call. See: https://stackoverflow.com/questions/33953447/express-app-server-listen-all-interfaces-instead-of-localhost-only

For JuiceShop that is in https://github.com/juice-shop/juice-shop/blob/6c26fe960826c3fcc27a3c944aa1fb17a7c8af12/server.ts#L665

If you change that line to `server.listen(port, '127.0.0.1', () => {` you can restrict it to only listen to your local interface. (By default it listens on all)

**Comment by bkimminich** [comment]
Technically we could make this configurable via the `server` section of our config, where you can also set the port. But I'm not sure this isn't just a real edge case or something more users would actually like to have.

**Comment by w0lfcat** [comment]
> I don't think it currently possible without code changes. You specify where to listen on in then server.listen call. See: https://stackoverflow.com/questions/33953447/express-app-server-listen-all-interfaces-instead-of-localhost-only
> 
> For JuiceShop that is in
> 
> https://github.com/juice-shop/juice-shop/blob/6c26fe960826c3fcc27a3c944aa1fb17a7c8af12/server.ts#L665
> 
> If you change that line to `server.listen(port, '127.0.0.1', () => {` you can restrict it to only listen to your local interface. (By default it listens on all)

Thanks, I did change it as follows, and `npm start` again. however it is still listening to all. Did I miss anything like restart certain services?

```
$ grep -n server.listen server.ts
665:  server.listen(port, '127.0.0.1', () => {

$ ss -antp
State       Recv-Q  Send-Q   Local Address:Port   Peer Address:Port  Process
LISTEN         0      511                *:3000               *:*    users:(("node",pid=28789,fd=24))
```

**Comment by J12934** [comment]
@w0lfcat ah sorry. You'll need to compile the typescript again before restarting.
`npm run build:server` should compile it

**Comment by w0lfcat** [comment]
@J12934 perfect. You guys are awesome. Finally it's listening only on my localhost.

@bkimminich thanks for the very cool project. Not sure which one is the best, but having more option is good. Localhost is good for security, but in some cases like a school with limited hardware, maybe this is the best solution as a teacher can configure it on a PC and students can access from the same LAN.

**Comment by bkimminich** [comment]
If we make this configurable I'd leave the "all interfaces"-behavior we currenly have as default. It'd be possible to limit to localhost or specific address via configuration then.
