### ISSUE TITLE
[🎯] Challenge to register an entirely blank user account

### ISSUE THREAD

**Issue by lionheartdevs** [juice-shop/juice-shop#1958]
# :bug: Bug report

## Description
I was able to register for a blank account by capturing the POST request and resending the JSON body and modifying it to {"email":"","password":"",passwordRepeat:""} and deleted the rest of the JSON for the POST request for registration.

This was successfully added to the database. 

I then used Burp Suite to sign in with fake credentials and intercept the POST request. I changed the JSON body to {"email":"","password":""}

 And I successfully logged in with a blank account.

I thought this I figured something out at first...but it was not a challenge. Perhaps it could be?

Please provide any feedback on how I can improve my report writing in the future. Kinda new to this =). Thanks. 

### Is this a regression?
Not sure, this is the first version I ever tried, and I could not find this in any old issues.

## :microscope: Minimal Reproduction

I was able to register for a blank account by capturing the POST request and resending the JSON body and modifying it to {"email":"","password":"",passwordRepeat:""} and deleted the rest of the JSON for the POST request for registration.

This was successfully added to the database. 

I then used Burp Suite to sign in with fake credentials and intercept the POST request. I changed the JSON body to {"email":"","password":""}

 And I successfully logged in with a blank account.

## :deciduous_tree: Your Environment

Node: v16.18.1
NMP: 8.19.2

Please let me know if I should submit pictures. Thank you.

**Comment by bkimminich** [comment]
Hi! Thank for submitting this bug/idea! We already have a challenge that is based on the fact that you can just submit anything - including an XSS payload - as `email` to the `POST` endpoint of the `Users` API. Could we spice this up a bit maybe, so it feels less similar as a dedicated challenge?

For example, we could actually check in the API that username and password are not empty, but then trim leading/trailing spaces before creating the actual DB entry. Doing that would allow you to create an empty username/password with a request payload like `{"email":" ","password":" ",passwordRepeat:" "}`. The success condition could then be for a user to appear in the DB that really has empty username _and_ password.

**Comment by lionheartdevs** [comment]
Gotcha, yeah, that would be cool. Thanks a lot for your feedback. This whole journey is super exciting, and I appreciate the hard work you guys do in making JuiceShop. It's such a great learning tool. Keep up the good work! =)

**Comment by aayushhyadav** [comment]
Hi, I would like to work on this issue. Just to reiterate, we need to implement a functionality which allows to create a blank user account right? @bkimminich you have mentioned that there is an existing challenge that allows any payload for credentials. So do we need to make changes for that particular challenge? Any suggestions from where to begin?

**Comment by tausiq2003** [comment]
hey! I want to work on this issue @bkimminich @lionheartdevs

**Comment by bkimminich** [comment]
> hey! I want to work on this issue @bkimminich @lionheartdevs 

😀👍 Great! Go for it! 🏁
