### ISSUE TITLE
[🐛] Product ID as text causes JuiceShop to crash

### ISSUE THREAD

**Issue by vbakke** [juice-shop/juice-shop#1960]
# :bug: Bug report

## Description
A rest call where the numeric product ID is replaced with a text string, causes the app to crash.
Changing the URL http://127.0.0.1:3000/rest/products/6/reviews  --> http://127.0.0.1:3000/rest/products/text/reviews

This also causes the Heroku app to crash on https://juice-shop.herokuapp.com/.
(I only tried it once. Please try on your own app, and not the public Heroku app.)

### Is this a regression?
Sorry. New to Juice Shop, so I don't know.

## :microscope: Minimal Reproduction
Open http://127.0.0.1:3000/rest/products/6/reviews 
Change the ID 6 to a text string, e.g. http://127.0.0.1:3000/rest/products/text/reviews 
Press ENTER. 
Watch the stack trace fill your screen

## :fire: Exception or Error

<pre><code>undefined:3
return this.product == text

ReferenceError: text is not defined
at Object.eval (eval at $where (C:\\juice-shop\node_modules\marsdb\dist\DocumentMatcher.js:419:23), <anonymous>:3:24)    
at DocumentMatcher._docMatcher (C:\juice-shop\node_modules\marsdb\dist\DocumentMatcher.js:424:38)          
at DocumentMatcher.documentMatches (C:\juice-shop\node_modules\marsdb\dist\DocumentMatcher.js:112:19)      
at queryFilter (C:\juice-shop\node_modules\marsdb\dist\Cursor.js:243:39)                                  
at EventEmitter.<anonymous> (C:\juice-shop\node_modules\marsdb\dist\DocumentRetriver.js:114:42)           
at EventEmitter.emit (C:\juice-shop\node_modules\marsdb\node_modules\eventemitter3\index.js:89:35)       
at C:\juice-shop\node_modules\marsdb\dist\StorageManager.js:122:19)
</code></pre>

## :deciduous_tree: Your Environment

<pre><code>v16.13.1
8.1.2</code></pre>

**Comment by parthn2** [comment]
Hi, can i work on this?

**Comment by bkimminich** [comment]
Of course! 😀👍

**Comment by bkimminich** [comment]
This fix would break one of the NoSQLi challenges. You can verify this by running the tests locally, see https://pwning.owasp-juice.shop/part3/contribution.html#testing.

**Comment by bkimminich** [comment]
Now that I looked at the code again, I would have expected https://github.com/juice-shop/juice-shop/blob/master/routes/showProductReviews.ts#L45 to catch any exceptions occuring during the `find()`-call on MarsDB - but it seems it crashes in there already and the error doesn't even reach the calling function?

Even worse: On Heroku, `id` is supposed to be assigned to `Number(req.params.id)` - so this shouldn't even happen at all...

**Comment by parthn2** [comment]
> Now that I looked at the code again, I would have expected https://github.com/juice-shop/juice-shop/blob/master/routes/showProductReviews.ts#L45 to catch any exceptions occuring during the `find()`-call on MarsDB - but it seems it crashes in there already and the error doesn't even reach the calling function?

Yes that's where the problem is!
`$where: 'this.product == ' + id `
This code leads application to failure I believe. So, I thought of making a check for id before but it leads to failure of a challenge as you told in this [`comment`](https://github.com/juice-shop/juice-shop/pull/1966#issuecomment-1419650442).
I am not getting any idea how should I approach the problem then. Can you help me out as I am not aware of the challenges  yet?

What best solution to be then seems is to use Number(id) rather than id and it works as I have tested. About Heroku, I am not so sure why is it happening then as hardcoding to number doesn't lead to any problem!

**Comment by vbakke** [comment]
Sorry, I don't know what the fix is. But I tried http://127 . 0 . 0 . 1:3000/rest/products/this.product/reviews, and got all the reviews returned. I didn't get a new flag in the score board, so I guess this is not intential.  (?)

(If this is one of the challenges, delete this post, or let me know.)

**Comment by bkimminich** [comment]
The challenge is injecting a sleep command. Check the failing Cypress test, it'll show the actual attack.

In Heroku and Docker this should be impossible by default as a numeric ID is supposedly enforced. You could reproduce the difference by running the app in Docker and locally. Then you have one vulnerable and one supposedly protected one to test your approach with.

**Comment by parthn2** [comment]
> The challenge is injecting a sleep command. Check the failing Cypress test, it'll show the actual attack.
> 
> In Heroku and Docker this should be impossible by default as a numeric ID is supposedly enforced. You could reproduce the difference by running the app in Docker and locally. Then you have one vulnerable and one supposedly protected one to test your approach with.

It is working as expected using docker and even with Heroku app and is not failing at all, so I believe making the ID to be number is the best approach. I am not so sure why it failed in case of @vbakke. https://juice-shop.herokuapp.com/rest/products/text/reviews doesn't lead to a crash.

**Comment by vbakke** [comment]
That's good. I only tried the Heroku app URL once. I got an error, and the site was unresponsive for a few minutes. So I assumed that a fail over guard kickstarted the process again. I did not want to explore the live site too much. 

I see that https://juice-shop.herokuapp.com/rest/products/this.product/reviews does not return all rows, as the https://localhost:3000/rest/products/this.product/reviews does.

**Comment by bkimminich** [comment]
Okay, that restores my confidence in the `Number()` constructor... 😆👍

**Comment by parthn2** [comment]
> Okay, that restores my confidence in the `Number()` constructor... 😆👍
https://github.com/juice-shop/juice-shop/blob/c7e1ade8c593875d5fdb6b3b51cef306adf53de9/routes/showProductReviews.ts#L30
Its not clear to me why this if-else was created, why numeric id was not used for local host. So, should I create a PR changing this line?

**Comment by bkimminich** [comment]
This injection vulnerability is needed for hacking challenge. If it's not possible to prevent a server crash, then so be it. In "safe mode" (on Heroku, Docker, GitPod) there's no crash, so essentially this bug was a false positive and the Heroku instance was just down by coincidence when the reporter opened it.

So, unless someone has any idea how to prevent a server crash in "unsafe" mode, but without breaking the NoSQL challenge, this issue has to be closed.

**Comment by parthn2** [comment]
> This injection vulnerability is needed for hacking challenge. If it's not possible to prevent a server crash, then so be it. In "safe mode" (on Heroku, Docker, GitPod) there's no crash, so essentially this bug was a false positive and the Heroku instance was just down by coincidence when the reporter opened it.
> 
> So, unless someone has any idea how to prevent a server crash in "unsafe" mode, but without breaking the NoSQL challenge, this issue has to be closed.

Oh, okay! Got it now. I will try to understand the challenge and find some solution. Though will take a little more time as having exams from next week.
