### ISSUE TITLE
Add SSL/TLS [🚀] 

### ISSUE THREAD

**Issue by vishrantkhanna** [juice-shop/juice-shop#1962]
# :rocket: Feature request

### Description

 A lot of testing scenarios might involve having the web application using SSL/TLS.

### Solution ideas

 Add an option to run web application on both http and https simultaneously. 

### Possible alternatives

 Have you considered any alternative solutions or workarounds? N/A

**Comment by bkimminich** [comment]
When I tried something in this direction in the past, it completely messed up the test automation. For that reason I didn't pursue it and left it to whoever hosts the application to sprinkle SSL/TLS on the environment, e.g. like http://demo.owasp-juice.shop/ and https://demo.owasp-juice.shop/ both work fine on Heroku.
