### ISSUE TITLE
[🐛] Mass Dispel `#closeButton`

### ISSUE THREAD

**Issue by sfuerte** [juice-shop/juice-shop#1974]
# :bug: Bug report

## Description

> Mass Dispel: Close multiple "Challenge solved"-notifications in one go.

not sure what other option is expected but http://localhost:3000/#/score-board#closeButton worked just fine for me. Though the task is still shown as "unsolved".

## :microscope: Minimal Reproduction

Have at least 2 solved tasks, add `#closeButton` to the URL and refresh the page.

## :deciduous_tree: Your Environment

<pre><code>
> docker images | grep juice-shop
bkimminich/juice-shop    latest       976b14cf12e9   8 days ago     576MB

> docker run --rm -p 3000:3000 bkimminich/juice-shop
info: All dependencies in ./package.json are satisfied (OK)
info: Chatbot training data botDefaultTrainingData.json validated (OK)
info: Detected Node.js version v18.14.0 (OK)
info: Detected OS linux (OK)
info: Detected CPU arm64 (OK)
</code></pre>

as per Web App:
> OWASP Juice Shop v14.5.1

**Comment by bkimminich** [comment]
> refresh the page

_That_ is what actually makes the notifications go away in your scenario. The challenge is about using Shift-"X" on one notification, and its only purpose is to teach users about this handy feature.
