### ISSUE TITLE
Fresh juice-shop install from Docker shows no graphics, broken text

### ISSUE THREAD

**Issue by 7MinSec** [juice-shop/juice-shop#199]
Hi,

I just tweeted with you about this issue (https://twitter.com/braimee/status/778628073725964288) but essentially I've got a fresh 64-bit Ubuntu VM that I wanted to setup to host the Juice Shop app, and I'm having an issue where the app appears kinda broken.

All I did "out of the box" was the ol' `apt-get update` and `apt-get upgrade` followed by `apt-get install docker.io` and `docker pull bkimminich/juice-shop` followed by `docker run -d -p 3000:3000 bkimminich/juice-shop` and this is what I'm seeing:

<img width="391" alt="screen shot 2016-09-21 at 11 10 02 am" src="https://cloud.githubusercontent.com/assets/17596787/18720447/7b084dda-7ff1-11e6-8463-dafa1122bfdd.png">

I tried it on multiple browsers and flushed cache on all of them to make sure.  

You'd asked me to check the console for errors but there weren't any - just confirmation that the container started.

Thanks,
Brian

**Comment by bkimminich** [comment]
I guess I found it meanwhile. The UI dependencies which are supposed to be installed via bower are **not installed** at all:

```
[0m[91mnpm [0m[91mWARN [0m[91mcannot run in wd juice-shop@2.9.1 bower install && grunt minify (wd=/juice-shop)
```

Seems that since I removed the helper scripts and replaced them with global bower/grunt-cli installations this never worked.

@braimee Thanks for noticing and reporting this!

**Comment by bkimminich** [comment]
Well, that only made things worse... 😞 

```
> juice-shop@2.9.2 postinstall /juice-shop
> bower install && grunt minify

[91minfo postinstall juice-shop@2.9.2
[0m[91mbower ESUDO         Cannot be run with sudo
[0m[91m
Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option
[0m[91m
[0m[91mnpm [0m[91minfo [0m[91mjuice-shop@2.9.2 Failed to exec postinstall script
[0m[91mnpm [0m[91mERR! Linux 4.4.0-34-generic
[0m[91mnpm [0m[91mERR! [0m[91margv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm"
[0m[91mnpm [0m[91mERR! [0m[91mnode v4.5.0
[0m[91mnpm [0m[91mERR! [0m[91mnpm  v2.15.9
[0m[91mnpm [0m[91mERR! [0m[91mcode ELIFECYCLE
[0m[91mnpm [0m[91mERR! juice-shop@2.9.2 postinstall: `bower install && grunt minify`
[0m[91mnpm [0m[91mERR! Exit status 1
[0m[91mnpm [0m[91mERR! 
[0m[91mnpm [0m[91mERR! Failed at the juice-shop@2.9.2 postinstall script 'bower install && grunt minify'.
[0m[91mnpm [0m[91mERR! This is most likely a problem with the juice-shop package,
[0m[91mnpm [0m[91mERR! not with npm itself.
[0m[91mnpm [0m[91mERR! Tell the author that this fails on your system:
[0m[91mnpm [0m[91mERR!     bower install && grunt minify
[0m[91mnpm [0m[91mERR! You can get information on how to open an issue for this project with:
[0m[91mnpm [0m[91mERR!     npm bugs juice-shop
[0m[91mnpm [0m[91mERR! Or if that isn't available, you can get their info via:
[0m[91mnpm [0m[91mERR! 
[0m[91mnpm [0m[91mERR!     npm owner ls juice-shop
[0m[91mnpm [0m[91mERR! There is likely additional logging output above.
[0m[91m
npm[0m[91m ERR![0m[91m Please include the following file with any support request:
npm[0m[91m ERR![0m[91m     /juice-shop/npm-debug.log
[0mRemoving intermediate container e08f913fc2dd
The command '/bin/sh -c cd /juice-shop; npm install bower -g; npm install grunt-cli -g; npm install --unsafe-perm' returned a non-zero code: 1
```

**Comment by 7MinSec** [comment]
Hey sorry for the trouble but thanks for looking into this so quickly!  I should've mentioned that I did this on another test VM _last_ week and it worked like a champ, which made me go "Uhh...what did I do wrong this time??? There's not that many commands for me to mess up!"  :-)

**Comment by bkimminich** [comment]
Yeah, I just removed those scripts yesterday with 9d4d459e868f16f5ee3c85eb76b0706eb3db28aa because they _seemed_ obsolete now that locally and on Travis-CI/AppVeyor everything worked fine. Unfortunately the Docker build didn't crash from these unexecutable commands.

Meanwhile you should be able to work around the issue with an image that is later, e.g. https://hub.docker.com/r/bkimminich/juice-shop/builds/bg9xmbfuftqqcuszaewoss5/

**Comment by 7MinSec** [comment]
Forgive the newbness, but what is the syntax for pulling that specific build?  I can't seem to make it work.

**Comment by bkimminich** [comment]
🎆 It's fixed in `latest` 🎆 ! 😄

**Comment by 7MinSec** [comment]
Awesome...testing shortly!

**Comment by 7MinSec** [comment]
Thanks - will you let me know if I did something wrong here?  I tried to grab the latest and it appears to launch fine, but port 3000 isn't listening:

> root@juice:~# docker pull bkimminich/juice-shop
> Using default tag: latest
> latest: Pulling from bkimminich/juice-shop
> 2f5fbf611374: Already exists 
> 9338b080890f: Already exists 
> 27e9f9640562: Already exists 
> 5dff8d6297fa: Already exists 
> 7126816c0725: Already exists 
> 154a36c4c98b: Already exists 
> 5d2c72d21bad: Already exists 
> a12885d224a7: Pull complete 
> e620ba76af61: Pull complete 
> ab2121fb10c4: Pull complete 
> a0820d39e63c: Pull complete 
> 70329b03b5ce: Pull complete 
> Digest: sha256:c631ca8e4ffd0c41eec39e73dd1cd9881664e4488e0c1bac55fbf88e945994fd
> Status: Downloaded newer image for bkimminich/juice-shop:latest
> root@juice:~# docker run -d -p 3000:3000 bkimminich/juice-shop
> 981a2ead575225668dd2de4140eaab2ee923a6256fe55301715d7cbac50bd910
> root@juice:~# netstat -tulnp
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
> tcp        0      0 0.0.0.0:22              0.0.0.0:\*               LISTEN      1307/sshd  
> tcp6       0      0 :::22                   :::\*                    LISTEN      1307/sshd  
> udp        0      0 0.0.0.0:68              0.0.0.0:\*                           999/dhclient  
> root@juice:~# 
> root@juice:~#

**Comment by 7MinSec** [comment]
If it helps, here's what my syslog says right as I start to fire the container up.
[docker-log.txt](https://github.com/bkimminich/juice-shop/files/486476/docker-log.txt)

**Comment by bkimminich** [comment]
This seems more like a host problem. I found this ticket where someone had a similar issue: https://github.com/docker/docker/issues/21390

Anyway, I'll set up an EC2 instance with the latest image and see if that works out of the box.

**Comment by 7MinSec** [comment]
Hey I just pulled latest and it's working again - thanks much!

**Comment by bkimminich** [comment]
Happy hacking! And if you email/DM me your address I make sure some stickers come your way!

**Comment by 7MinSec** [comment]
I will absolutely take you up on your generous offer shortly, thanks!
