### ISSUE TITLE
[🐛] Alternative solution to NoSQL DoS

### ISSUE THREAD

**Issue by theemathas** [juice-shop/juice-shop#2000]
# :bug: Bug report

## Description

The challenge "NoSQL DoS" has the description "Let the server sleep for some time. (It has done more than enough hard work for you)". As per [the guide](https://pwning.owasp-juice.shop/appendix/solutions.html), the intended solution is to visit the URL `http://localhost:3000/rest/products/sleep(2000)/reviews`.

I found an alternative solution to cause a DoS using a NoSQL injection, by visiting `http://localhost:3000/rest/track-order/',sleep(10000),'`. This causes the server to be unresponsive to all requests for about 5 seconds (so it is an effective DoS), but does not count as solving the challenge according to the scoreboard.

This injection is caused by [this code](https://github.com/juice-shop/juice-shop/blob/9a0789b5ecb4ee76fe528b1860095e945f6302ac/routes/trackOrder.ts#L18). The URL `http://localhost:3000/rest/track-order/',sleep(10000),'` seems to cause the code to run the following, which causes the server to sleep:
```
db.orders.find({ $where: "this.orderId === '',sleep(10000),''" })
```

(I spent quite some time confused by this, oops lol)

## :microscope: Minimal Reproduction

Run the Juice Shop, and navigate to `http://localhost:3000/rest/track-order/',sleep(10000),'` in a browser. The server takes about 5 seconds to send back a JSON response. During this ~5 second period, the server is unresponsive to other requests (if I navigate to `http://localhost:3000/` in another browser tab, the page won't load until this ~5 second period ends.)

After doing this, the scoreboard for the "NoSQL DoS" challenge is still displayed as unsolved.

Note that navigating to `http://localhost:3000/rest/track-order/',sleep(1),'` instead (i.e., using a 1 millisecond sleep time instead) causes the server to respond instantly, so it does seem like the server is actually running the sleep command.

## :deciduous_tree: Your Environment

I ran Juice Shop using the command: `docker run -p 3000:3000 --env NODE_ENV=unsafe bkimminich/juice-shop`

Running `docker images | grep juice-shop` gives:
```
bkimminich/juice-shop   latest    976b14cf12e9   2 months ago    576MB
```

The webapp sidebar says that the version is v14.5.1

**Comment by J12934** [comment]
Ahh cool yes I guess that should also solve the challenge 👍 Thank you for the report 👍

(Also congrats on opening issue #2000 😅)

**Comment by bkimminich** [comment]
The order tracking is not supposed to have this vulnerability actually, so there is no code checking for your payload. We'll probably just fix it there, because the same challenge firing from different places would get confusing really easily.
