### ISSUE TITLE
[🚀]  Upgrade Cypress to 11.x

### ISSUE THREAD

**Issue by ShubhamPalriwala** [juice-shop/juice-shop#2014]
# :rocket: Feature request

### Description
Upgrade Cypress testing suite as per the latest v12.x documentation

### Link
https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-120

### Possible alternatives
None

**Comment by ShubhamPalriwala** [comment]
thanks ❤️ @J12934 
I'll make sure you dont have to do this again 🤞🏼

**Comment by Freedisch** [comment]
@ShubhamPalriwala , I can work on it if u don't mind

**Comment by ShubhamPalriwala** [comment]
Thanks a lot! Definitely, do ping me either here or on Slack if you have any queries!

**Comment by bkimminich** [comment]
Migration from 9.x to 10.x is work in progress at https://github.com/juice-shop/juice-shop/tree/cypress10

(With 10.x the entire configuration structure was changed, so jumping over this release seems like trying too much at once)

**Comment by bkimminich** [comment]
ℹ️ If already stable enough, migration could be extended to 13.x instead of originally proposed 12.x
