### ISSUE TITLE
[🐛] JuiceShop ChatBot UI Bug

### ISSUE THREAD

**Issue by parthn2** [juice-shop/juice-shop#2015]
# :bug: Bug report

## Description
The chat bot response is hidden after the screen is filled up and we need to scroll down to find out the response while the ideal behaviour should be that the response could be seen directly without any scrolling.

A clear and concise description of the problem...

https://github.com/juice-shop/juice-shop/assets/74675085/226f8ae3-6edc-4d5f-9aad-d1eab2a7d0bd

## :microscope: Minimal Reproduction

Run http://127.0.0.1:3000/#/chatbot and just give input random things to chatbot and fill up the space

## :fire: Exception or Error

<pre><code>

</code></pre>

## :deciduous_tree: Your Environment

<pre><code>

</code></pre>

### Additional Information
Not a browser-specific issue. Tested on chrome and safari.

**Comment by bkimminich** [comment]
Thanks for opening this as an issue. It's a known problem which I tried to solve several times but never succeeded so far.

**Comment by parthn2** [comment]
> Thanks for opening this as an issue. It's a known problem which I tried to solve several times but never succeeded so far.

I will like to try it out then once!

**Comment by parthn2** [comment]
I guess I have found the solution. The problem with it was that the scrolling was done until the sent text and not on the response even if the response have been pushed. To solve this, I have used the timeout function and it seems it works fine now. Will create a PR soon!

**Comment by bkimminich** [comment]
Brilliant! 🎊

**Comment by bkimminich** [comment]
![image](https://github.com/juice-shop/juice-shop/assets/3531020/17e3c1e1-f22f-4fd8-87e5-64876e6f5aed)

At least on my Chrome on http://preview.owasp-juice.shop/#/chatbot the scrolling still ends up with the immediate answer being not visible. Can someone confirm this, please?

**Comment by bkimminich** [comment]
Hm, just re-tested locally and it works fine...
...but with same browser on Preview-Heroku it still doesn't scroll down. Maybe it's slower and the timeout isn't sufficient.

**Comment by bkimminich** [comment]
Increased the timeout to 1/4 sec - fingers crossed this will suffice.

**Comment by parthn2** [comment]
Oh! There would be a bit more delay for the deployed version! I put the timeout time to be the minimum before. It doesn't seem to suffice 1/4 seconds too. We need to use binary search kind of strategy for finding right time for deployed version too

**Comment by bkimminich** [comment]
It didn't deploy to Heroku yet, so we can still hope...

**Comment by bkimminich** [comment]
250ms is working for me! 🎊

**Comment by J12934** [comment]
Getting this error regularly in the frontend unit tests:

```
TypeError: Cannot read properties of null (reading 'scrollHeight')
	    at apply (src/app/chatbot/chatbot.component.ts:105:33)
	    at apply (node_modules/zone.js/fesm2015/zone.js:2405:41)
	    at _ZoneDelegate.invokeTask (node_modules/zone.js/fesm2015/zone.js:406:31)
	    at ProxyZoneSpec.onInvokeTask (node_modules/zone.js/fesm2015/zone-testing.js:318:39)
	    at _ZoneDelegate.invokeTask (node_modules/zone.js/fesm2015/zone.js:405:60)
	    at Zone.runTask (node_modules/zone.js/fesm2015/zone.js:178:47)
	    at call (node_modules/zone.js/fesm2015/zone.js:487:34)
	    at apply (node_modules/zone.js/fesm2015/zone.js:476:48)
	    at data.args.<computed> (node_modules/zone.js/fesm2015/zone.js:2385:
```

I'm guessing we need a angular lifecycle hook to remove the timeout when the component is destroyed. Otherwise it's trying to perform the scrolling after the component is already gone.

**Comment by J12934** [comment]
Added a clear timeout on destroy: https://github.com/juice-shop/juice-shop/commit/57688655d11039bc579d79d542aa82c5a9976a30
Should fix the issues in the tests
