### ISSUE TITLE
[🚀] SBOM for packaged releases

### ISSUE THREAD

**Issue by jkowalleck** [juice-shop/juice-shop#2028]
# :rocket: Feature request

### Description

As your releases are not just tags but complete assembled/bundled packages and Docker images,
it would be great to ship a software bill of materials with each individual release package and Docker image.

This application may ship outdated and vulnerable components on purpose.
Having SBOM as part of the package would allow users to identify what they are hosting/using, so that they know the risks better.

### Solution ideas

as this is already an OWASP project, I'd recommend using another OWASP project for generating the SBOM: [OWASP CycloneDX](https://owasp.org/www-project-cyclonedx/).

Alter the build-processes and the release-processes for each OS/node-version
1. generate BOMs via all of these
   - server-side(node/NPM): https://www.npmjs.com/package/@cyclonedx/cyclonedx-npm
   - frontend(Angular/webpack): https://www.npmjs.com/package/@cyclonedx/webpack-plugin
2. have the generated BOMs added to the package 

the files in the bom could be named `bom-frontend.cdx.{json,xml}` and `bom-backend.cdx.{json,xml}`
to reflect https://cyclonedx.org/specification/overview/#recognized-file-patterns 

Similar for the Docker image.

PS: bom file names in the final solution differed. see https://github.com/juice-shop/juice-shop/issues/2028#issuecomment-1711705197

### Possible alternatives

 Have you considered any alternative solutions or workarounds?

**Comment by jkowalleck** [comment]
I could pullrequest a solution, if you like.

**Comment by jkowalleck** [comment]
CC @stevespringett @msymons

**Comment by J12934** [comment]
Sounds interesting.
When you say "have the generated BOMs added to the package" how does that work / to what would they be added?

**Comment by jkowalleck** [comment]
If this was already implemented, then each of [v15](https://github.com/juice-shop/juice-shop/releases/tag/v15.0.0)'s release assets' packages would include a file `bom-backend.cdx.{json,xml}` and `bom-frontend.cdx.{json,xml}` inside each of the `juice-shop-*.{tgz,zip}` files.

The individual BOMs would be generated during build processes for frontend(during `ng build`) and serverside(after `npm install` and before `npm pack`) for each build target individually, to reflect the actually used packages and components that are in the final package for each OS/nodeVersion combination, that is part of a release. 
`npm pack` or (whatever is used) then should pick up the generated BOM files and add them to the package, which is later a release asset.

I am uncertain whether to include dev-components in the BOM. This is an arguable topic, which  mostly depends on the point of view - the audience of the BOM.
On one side they explain how the assembly was generated, on the other hand they are not part of the shipped package/application, so they might even be omitted.

**Comment by jkowalleck** [comment]
updated the feature request: added expected file names according to https://cyclonedx.org/specification/overview/#recognized-file-patterns

PS: the file names in the final solution differed. see https://github.com/juice-shop/juice-shop/issues/2028#issuecomment-1711705197

**Comment by bkimminich** [comment]
It is essentially an equivalent to a package.lock file but in a tech stack independent format, correct? I'm not sure who the target audience would be, though and what the use cases are for having these. I get it for "normal" applications, but Juice Shop simulates the worst possible security posture in a web app, so it definitely wouldn't come with a CDX manifest in that scenario. I'm concerned we'd be making it easier for security tools to analyze than it would normally be under the "we're terrible at security" premise.

**Comment by jkowalleck** [comment]
> but Juice Shop simulates the worst possible security posture in a web app

I totally understand.
If I gave people access to the in-house hosted juice-shop they would not get access to the source code; they would not have access to the content of the `node_modules` folder nor a `package.json` nor a BOM. 
If they had access to a `package.json` and a `node_modules` folder, it was easy to gather the basic information a BOM would provide. So there is no downside in providing a BOM, I assume.
 

Target audience of that BOM would be
- people who want to host a juice-shop: they need to know the risks and what they are actually  running. They need to know which attack surfaces to expect. Therefore, they need to know the components (packages/names/versions), so that these components can be aggregated and categorized by scanners like [dependency-check](https://owasp.org/www-project-dependency-check/), [dependency-track](https://owasp.org/www-project-dependency-track/) and security-related tools.
- people who want to reproduce the build or know build details: there is no lock file in the packaged releases. So it is hard to know which software was used to build/assemble the packages or which components are bundled in the packages.

> It is essentially an equivalent to a package.lock file but in a tech stack independent format, correct?

Yes, that is correct. But it can contain even more met data, like build time, assembly line descriptions, and so on.
If I wanted a `juice-shop` hosted for an in-house training or CTF, then my secOps/devOps team would ask me for a BOM of the application, to know what security impact to expect. If I told them it was a web-app that was designed to be as vulnerable as possible, then they would not let me, unless they knew the risks and which layer of protection they needed to enclose the host-environment.
Having such a BOM would make it easy for my secOps/devOps team, to gather the needed information.

**Comment by jkowalleck** [comment]
An alternative I see, if the general BOM was accepted, but it must not be in the package: have it as a separate release assets.
like the current `*.md5` files, there could be files like `juice-shop-15.0.0_node18_linux_x64-BOM_frontend.cdx.json`

**Comment by bkimminich** [comment]
> So there is no downside in providing a BOM, I assume.

Alright, let's try it out then.

**Comment by jkowalleck** [comment]
will prepare a PR so we could see how it turns out and what it might look like.

**Comment by jkowalleck** [comment]
proposed solution: #2031

**Comment by jkowalleck** [comment]
got fixed via #2031 
 
as of [release v15.1.0](https://github.com/juice-shop/juice-shop/releases/tag/v15.1.0)
the individual SBOMs for backend and frontend bundled with every artifact. and with every docker image.
for backend it is `bom.{json,xml}` in the package root dir,
for frontend it is `bom.{json,xml}` in `frontend/dist/bom/` dir.
