### ISSUE TITLE
[🐛] Stabilize Flaky Wallet Api Tests

### ISSUE THREAD

**Issue by J12934** [juice-shop/juice-shop#2030]
# :bug: Bug report

## Description

Wallet Integration Tests seem to be flaky and often fail randomly because the wallet amount are different than the expected amounts.

### Is this a regression?

Yes, the previous version in which this bug was not present was: `x.y.z`

## :microscope: Minimal Reproduction

https://github.com/juice-shop/juice-shop/actions/runs/5192325123/jobs/9363195202#step:6:1071

## :fire: Exception or Error

<pre><code>
 FAIL test/api/walletApiSpec.ts
  ● /api/Wallets › GET wallet retrieves wallet amount of requesting user

    assert(received)

    Expected value to be equal to:
      true
    Received:
      false

    Message:
      Response [ {"status":"success","data":-199} ] does not contain provided JSON [ {"data":100} ]

      at jsonContainsAssertion (node_modules/frisby/src/frisby/expects.js:91:16)
      at Object.withPath (node_modules/frisby/src/frisby/utils.js:13:12)
      at FrisbySpec.json (node_modules/frisby/src/frisby/expects.js:79:11)
      at node_modules/frisby/src/frisby/spec.js:421:23
      at node_modules/frisby/src/frisby/spec.js:250:34
          at runMicrotasks (<anonymous>)
      at node_modules/frisby/src/frisby/spec.js:257:28
          at runMicrotasks (<anonymous>)
</code></pre>

## :deciduous_tree: Your Environment

Seems to affect all supported env.
Seen this on both linux and macos, both on Node 16 & 18

**Comment by roipav** [comment]
test

**Comment by vsaur** [comment]
test

**Comment by bkimminich** [comment]
The test might still be flaky if charging the wallet happens before testing the current amount. If it happens too frequently, we should change the test to not check the amount itself but only that any number is returned. The charging test could then retrieve the current amount and then compare it to be +10 after charging.
