### ISSUE TITLE
[🐛] docker-compose.test.yml returns error: smoke tests failed

### ISSUE THREAD

**Issue by D3vil0p3r** [juice-shop/juice-shop#2040]
# :bug: Bug report

## Description

When I clone the repository and I rename `docker-compose.test.yml` to `docker-compose.yml` and I run:
```
sudo docker compose up
```
I get the following error:
```bash
[+] Building 0.0s (0/0)                                                                                               
[+] Running 2/0
 ✔ Container juice-shop-app-1  Created                                                                           0.0s 
 ✔ Container juice-shop-sut-1  Created                                                                           0.0s 
Attaching to juice-shop-app-1, juice-shop-sut-1
juice-shop-app-1  | 
juice-shop-app-1  | > juice-shop@12.1.1 start /juice-shop
juice-shop-app-1  | > node app
juice-shop-app-1  | 
juice-shop-app-1  | info: All dependencies in ./package.json are satisfied (OK)
juice-shop-app-1  | info: Chatbot training data botDefaultTrainingData.json validated (OK)
juice-shop-app-1  | { locale: 'en', useNoneFeature: undefined, trainByDomain: undefined }
juice-shop-app-1  | info: Detected Node.js version v12.19.0 (OK)
juice-shop-app-1  | info: Detected OS linux (OK)
juice-shop-app-1  | info: Detected CPU x64 (OK)
juice-shop-app-1  | info: Configuration default validated (OK)
juice-shop-app-1  | info: Required file index.html is present (OK)
juice-shop-app-1  | info: Required file polyfills-es2018.js is present (OK)
juice-shop-app-1  | info: Required file styles.css is present (OK)
juice-shop-app-1  | info: Required file tutorial-es2018.js is present (OK)
juice-shop-app-1  | info: Required file vendor-es2018.js is present (OK)
juice-shop-app-1  | info: Required file tutorial-es5.js is present (OK)
juice-shop-app-1  | info: Required file polyfills-es5.js is present (OK)
juice-shop-app-1  | info: Required file runtime-es5.js is present (OK)
juice-shop-app-1  | info: Required file vendor-es5.js is present (OK)
juice-shop-app-1  | info: Required file runtime-es2018.js is present (OK)
juice-shop-app-1  | info: Required file main-es2018.js is present (OK)
juice-shop-app-1  | info: Required file main-es5.js is present (OK)
juice-shop-app-1  | info: Port 3000 is available (OK)
juice-shop-app-1  | info: Server listening on port 3000
juice-shop-sut-1  | Waiting 20sec for http://app:3000 to launch....................
juice-shop-sut-1  | Running smoke tests...
juice-shop-sut-1  | Index smoke test passed!
juice-shop-sut-1  | API smoke test passed!
juice-shop-sut-1  | Angular smoke test failed!
juice-shop-sut-1  | Code snippet smoke test failed!
juice-shop-sut-1  | Smoke tests exiting with code 2 (FAILED)
juice-shop-sut-1 exited with code 2
```
I'm using the latest docker package on Arch Linux.

**Comment by J12934** [comment]
Hi
The docker compose is really just meant for the smoke tests.

If you want to run juiceshop using docker you can start it directly using the commands found in the readme.

**Comment by D3vil0p3r** [comment]
> Hi The docker compose is really just meant for the smoke tests.
> 
> If you want to run juiceshop using docker you can start it directly using the commands found in the readme.

Y I did it. Since I'm automating some stuff, is it possible to create a simple docker-compose.yml file directly on this repository?

**Comment by J12934** [comment]
Sure it would be possible, but I don't really see too much value in a docker-compose for it? 

It is just a single container without any dependencies. Not really much to compose. It's well documented on how to run it with docker, so anybody who really wanted to run it with compose should be able to do so but don't see how this would help us as a additional official installation method.

**Comment by D3vil0p3r** [comment]
It is right, it was not a much value, but it could be useful to have a basic one just for "formality", since there is one for testing purpose. In my case I would like to have because I'm writing a script that clone the repo and should run the docker compose after that instead of using docker run.

**Comment by bkimminich** [comment]
Closing this issue as we won't go for `docker-compose` unless it'd be _needed_ in a future version. As long as Juice Shop remains a single-container application, we'll stick to the simpler setup without it.

**Comment by D3vil0p3r** [comment]
Ok Thanks
