### ISSUE TITLE
[🐛] Broken completion detection for challenge "Gain read access to an arbitrary local file on the web server"

### ISSUE THREAD

**Issue by gyetblokrd** [juice-shop/juice-shop#2060]
# :bug: Bug report

## Description

OWASP Juice Shop v15.0.0

When sending POST request to /dataerasure, any request with a 'layout' body parameter completes the challenge, even when the file hasn't been accessed

Additionally, even after the challenge is marked completed on the Score Board, the POST request can be spammed for infinite banners and confetti 

### Is this a regression?

Have not tested other versions

## :microscope: Minimal Reproduction

Send a POST request more than once to /dataerasure with body parameter layout=anything.

My exact request when I found the bug (sent with Burp Suite community):
<pre><code>POST /dataerasure HTTP/1.1
Host: localhost:3000
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 7
Origin: http://localhost:3000
DNT: 1
Connection: close
Referer: http://localhost:3000/dataerasure
Cookie: language=en; continueCode=n2HouohDtbIyTnCBsKFVi1fKSYUoH2u2h2tzcNIDTrCMFQioSlUeuxhet8c1I1TzsQFYikfMSPUBH6vubbh3DcR2I2yCJMs83i7Jf4VSLNUwKubKh2YtzNcEXI6eTY3sp2UMQHLguoLhMxCgxs8qFO2fxZSYaUPeHQ8uXgtJxcYYIeKTpPCVmF5yiK5frXSWMUjpH7guxl; cookieconsent_status=dismiss; welcomebanner_status=dismiss; continueCodeFindIt=JXhBczt3udIDTEUWhDczU2fWUQwcq9i6YfRJS1nujKTexs3MU29FywhBmtzpFby; continueCodeFixIt=RLUqIEh8uninTnHPUwIeHjcmHkyIB2tWbc4VFmKu3PTQdfZkHDgSbjURlT5PugP; code-fixes-component-format=LineByLine; token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdGF0dXMiOiJzdWNjZXNzIiwiZGF0YSI6eyJpZCI6OSwidXNlcm5hbWUiOiIiLCJlbWFpbCI6IkoxMjkzNEBqdWljZS1zaC5vcCIsInBhc3N3b3JkIjoiM2MyYWJjMDRlNGE2ZWE4ZjEzMjdkMGFhZTM3MTRiN2QiLCJyb2xlIjoiYWRtaW4iLCJkZWx1eGVUb2tlbiI6IiIsImxhc3RMb2dpbklwIjoiIiwicHJvZmlsZUltYWdlIjoiYXNzZXRzL3B1YmxpYy9pbWFnZXMvdXBsb2Fkcy9kZWZhdWx0QWRtaW4ucG5nIiwidG90cFNlY3JldCI6IiIsImlzQWN0aXZlIjp0cnVlLCJjcmVhdGVkQXQiOiIyMDIzLTA4LTEwIDIwOjIyOjE0Ljg4NiArMDA6MDAiLCJ1cGRhdGVkQXQiOiIyMDIzLTA4LTEwIDIwOjIyOjE0Ljg4NiArMDA6MDAiLCJkZWxldGVkQXQiOm51bGx9LCJpYXQiOjE2OTE3MTk4NDZ9.wADhYnVbsjeEAHOs01t9DJ7OL1XbB5fL4FYscOuu7QFOr5VZkIlqji9OKtk2oB-ZEafZB4F_lclYXwtO8MGtkIYWLNsPXYHqgcI-LoBxlHB0KTjc761E5KyCSutM2GJ0CmveWpOlklDlpa43U_nMT-jqZFW4-T7qVH59NzluVUs
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1

layout=
</code></pre>

## :deciduous_tree: Your Environment

<pre><code>v18.13.0
9.2.0
</code></pre>

### Additional Information
VirtualBox, Linux 6.3.0-kali1-amd64

**Comment by bkimminich** [comment]
Hi! Thanks for reporting this one. The spamming part is easy*, the verification that an actual LFR happened is something I have to look into and write some test cases for.

*we normally use solveIf() instead of solve() function to solve challenges, seems to have been just forgotten or was overlooked here.

**Comment by bkimminich** [comment]
@gyetblokrd, please check if the challenge behavior is now fine and no longer spammable on our `develop` branch or (in a couple hours) with the `snapshot` Docker image. I also added some tests and to me the behavior now looks good.
