### ISSUE TITLE
[🐛] Failing API / Frisby Tests on Node.js 20

### ISSUE THREAD

**Issue by J12934** [juice-shop/juice-shop#2068]
# :bug: Bug report

## Description

Our API / Frisby Tests have been failing regularly on Node.js 20.
Reproducible both locally and in CI environments on all operating systems.

### Is this a regression?

Yes, before ~21.8.23 they have been working API / Frisby, e.g. for this commit 68ef6d3229c45e4d73b88cd9833d8e5a60e14a19

First commit on develop where it stopped working:
1fb0f12e512e9cbe4d000c99fea788f21ecf2bb1

(Also broke around the same time on other unrelated branches, so might rather be a change in a dependency than a code change on JuiceShop side)

Currently unclear what has changed at this point

## :microscope: Minimal Reproduction

```bash
nvm use 20
rm -rf node_modules/
npm install
npm run frisby
```

## :fire: Exception or Error

```
FAIL test/api/feedbackApiSpec.ts
  ● /api/Feedbacks › POST feedback is associated with current user

    FetchError: request to http://localhost:3000/rest/user/login failed, reason: socket hang up

      at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1501:11)
```

The `POST feedback is associated with current user` always appears to be failing.
Unfortunately other tests are sometimes failing as well.

## :deciduous_tree: Your Environment

```
$ node -v && npm -v
v20.5.1
9.8.0
```

### Additional Information

Related slack discussion: https://owasp.slack.com/archives/C255XSY04/p1692548270574669

Potentially related to:
- https://github.com/node-fetch/node-fetch/issues/1735
- https://github.com/nodejs/node/issues/47130

**Comment by bkimminich** [comment]
Just tested that the issue is entirely generic and not related to any particular test. `xit`ing failing test cases will then make a different test case in the spec file fail. Removing the entire spec file will then make another spec file fail. Tested this for three iterations before giving up.

**Comment by bkimminich** [comment]
Tried these, also with no success: https://connectreport.com/blog/tuning-http-keep-alive-in-node-js/

**Comment by bkimminich** [comment]
I ran the test suite with network debugging enabled (`NODE_DEBUG=net npm run frisby`) but I can't spot any difference between the log output right before a test case fails from `ECONNRESET` vs. where test cases just pass without issue.

**Comment by bkimminich** [comment]
I tried to narrow things down a bit more by removing the server-launch via the test script, i.e. removing
```
    "globalSetup": "./test/apiTestsSetup.ts",
    "globalTeardown": "./test/apiTestsTeardown.ts",
```
and instead starting the server manually a minute before launching the test suite. The error behavior remains the same, so I am quite confident that the problem has nothing to do with the server "not being ready" in any way.
