### ISSUE TITLE
[🐛]  Remove shipping addresses for other users

### ISSUE THREAD

**Issue by makarov05bm** [juice-shop/juice-shop#2082]
# :bug: Bug report

## Description
There is a bug in the API that isn't in the list of challenges on the score-board, which can let you remove shipping addresses of other users.

## :microscope: Minimal Reproduction
For any order when you add a new address, intercept the request and change the ID to an ID used for address by another user (the IDs are incremented so it's easy). You will notice that the address will be added to your list of addresses but removed for the victim user.

**Comment by bkimminich** [comment]
Nice find! We'll probably close that gap rather than make another challenge from it, as we have so many API related challenges already.

**Comment by makarov05bm** [comment]
I think this one IDOR is quite interesting, because usually deleting entities owned by another user would mean using a verb like DELETE, PUT or PATCH, but POST is usually for creating non-existent entities, but here it's overriding the already existing one rather than deleting it (that's how I imagine it, I hope you explain the real behaviour if it's possible)

**Comment by r0ckYr** [comment]
I would like to fix this, can you assign this issue to me.
