### ISSUE TITLE
[🐛] pwning.owasp-juice.shop - not found

### ISSUE THREAD

**Issue by eric-nieuwland** [juice-shop/juice-shop#2098]
# :bug: Bug report

## Description

References to pwning.owasp-juice.shop result in a 404.

### Is this a regression?

I think it worked before, but I'm not sure.

## :microscope: Minimal Reproduction

Click on https://pwning.owasp-juice.shop/part1/challenges.html#hacking-instructor (a link on https://owasp.org/www-project-juice-shop/)

**Comment by bkimminich** [comment]
Isssue on https://owasp-juice.shop website and affects multiple links. Fixed via https://github.com/OWASP/www-project-juice-shop/commit/99cec2bf50f6bb26080f88f69abb509e29d6d72e
