### ISSUE TITLE
[🐛] Juice Shop Docker image - Pod dies when unable to reach sepolia.infura.io

### ISSUE THREAD

**Issue by MitchellKelly-AlphaSights** [juice-shop/juice-shop#2100]
# :bug: Bug report

## Description

A clear and concise description of the problem...

When Running Juice Shop Docker image within Kubernetes and you block traffic to sepolia.infura.io the pod throws the error listed below and dies.

### Is this a regression?

I have not tested older versions.  The version I am running is 15.1.0

## :microscope: Minimal Reproduction

Deploy image to Kubernetes (docker might work) and block traffic to sepolia.infura.io (firewall rule, blacklist, ect)

## :fire: Exception or Error

<pre><code>

node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 3.230.137.166:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/juice-shop/node_modules/ws/lib/websocket.js:961:13)
    at ClientRequest.<anonymous> (/juice-shop/node_modules/ws/lib/websocket.js:820:5)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '3.230.137.166',
  port: 443
}
</code></pre>

## :deciduous_tree: Your Environment

<pre><code>

AWS Kubernetes 1.25 with
ELB/ALB 
and Cilium (that is what is initially blocking traffic) followed by a firewall preventing egress.
</code></pre>

### Additional Information
When I run the image locally It doesnt die but I also dont have any firewall restrictions on my computer.

**Comment by bkimminich** [comment]
v15.1.0 and later contain several Web3 related challenges which need to communicate with some Smart Contracts deployed on Ethereum testnets. Calls to infura.io come from these challenges.

At this point in time I wouldn't consider the Web3 challenges "dangerous", so it's probably something to be solved by allowlisting on your end.

That the server dies is of course a bad behavior, and I could imagine either a startup check that pings those external URLs and prevents the server start or disables the now impossible-to-solve challenges similar to the dangerous ones.

**Comment by aut0exec** [comment]
Also ran across this issue this evening while trying to update an OWASP VM that I maintain. Slightly different setup though. Not using docker but the Juice Shop instance doesn't have access to the Internet (running on a host-only adapter). If I switch the VM over to NAT/bridged adapter, Juice Shop gets out to the Internet and everything starts up just fine.

The ability to disable challenges that require Internet connectivity would be nice.

**Comment by MitchellKelly-AlphaSights** [comment]
@bkimminich Without context I just had to ask.  If they are intended behaviour I can allow it.  But I would suggest an update in the Readme at a minimum outlining external dependencies.

**Comment by bkimminich** [comment]
I think we just failed to notice that 15.1 should have been 16.0 as the external Smart Contracts dependency is actually a breaking change.

I'll update the release notes accordingly, so at least people will be aware.

**Comment by bkimminich** [comment]
I think we just failed to notice that 15.1 should have been 16.0 as the external Smart Contracts dependency is actually a breaking change.

I'll update the release notes accordingly, so at least people will be aware.

**Comment by bkimminich** [comment]
On `develop` branch / `snapshot` Docker image tag there should now be a fixed version that doesn't crash on start-up when infura.io cannot be reached. Instead the first actual attempt to connect to it will result in a non-blocking retry loop to connect every 1sec.

@MitchellKelly-AlphaSights, once the Docker image is published by the running CI/CD job, could you try the `snapshot` image and see if it starts in your locked-down environment?

**Comment by bkimminich** [comment]
I've tested locally on my Win11 with Airplane mode on/off and the server starts fine when offline. Once you open a page which triggers one of the two infura.io connections, the server will spam reconnect-attempts every 1sec and flood the console with those, but it shouldn't crash at least.

_Edit: I'll also introduce a tag "Internet Traffic" for the two affected challenges to make it clear on the Score Board that these won't be solvable if traffic (in this case to infura.io) is blocked._

**Comment by MitchellKelly-AlphaSights** [comment]
I just pulled down the snapshot and I have had it running with full restrictions for an hour (usually issues occurred within an hour) and no errors to report.  I think what you did is a reasonable fix.

However just to note, I have not tested the Web3 challenges directly.  But the pod is stable.

**Comment by bkimminich** [comment]
The two challenges that need infura.io will not work, but good to hear that it runs fine now.

**Comment by MitchellKelly-AlphaSights** [comment]
@bkimminich Thank you for your quick response and fix.  The core of my issue is resolved.  I dont know if you want to keep this ticket open to track something else but I am satisfied with the result.

**Comment by bkimminich** [comment]
Release v15.2.0 is just building, so we can close this ticket. I'll probably add some startup check to verify Internet access works and also a configuration option to let people disable all challenges depending on Internet.
