### ISSUE TITLE
📖 Dead link in README[🐛] 

### ISSUE THREAD

**Issue by manchicken** [juice-shop/juice-shop#2106]
# :bug: Bug report (I guess it's a bug? It's a documentation error)

## Description

The README contains a broken link at the top: https://github.com/juice-shop/juice-shop#setup

### Is this a regression?

I don't think so, I think the page just moved.

## :microscope: Minimal Reproduction

https://github.com/juice-shop/juice-shop#setup

**Comment by bkimminich** [comment]
That link is an anchor to the setup section in the README and works perfectly fine.

**Comment by bkimminich** [comment]
I assume you mean the link https://pwning.owasp-juice.shop/part1/running.html in that paragraph, that is indeed broken b/c the documentation base URLs changed. Is fixed now.

**Comment by manchicken** [comment]
Yeah, thanks for that. I'm sorry my post was confusing, I was trying to show you where the broken link was located, not tell you where the broken link was going. 

I probably should have mentioned both. Sorry for that, and thanks again.
