### ISSUE TITLE
[🐛] build fails with module not found when building the project

### ISSUE THREAD

**Issue by asalbers** [juice-shop/juice-shop#2108]
# :bug: Bug report

## Description

Looks like there is a react dependency on useShallow that is coming from zustand. I was getting the error below when running a npm install on nodejs version 20. It worked once I added react as a dependency in the package.json. Also looks like the folks that maintain zustand are aware. 

https://github.com/pmndrs/zustand/discussions/2095 

## :microscope: Minimal Reproduction

run npm install 

## :fire: Exception or Error

<pre><code>

./node_modules/zustand/esm/shallow.mjs:1:0-31 - Error: Module not found: Error: Can't resolve 'react' in '/home/andrew/juice-shop/frontend/node_modules/zustand/esm'

</code></pre>

## :deciduous_tree: Your Environment

<pre><code>
v20.8.0
10.1.0
</code></pre>

**Comment by bkimminich** [comment]
This is solved on `develop` branch already by adding+pinning `zustand` to the previous version. Should also be in the `snapshot` Docker image already.

**Comment by bkimminich** [comment]
Release `v15.2.1` is currently building and addresses this issue.
