### ISSUE TITLE
[🐛] Incorrect URL on the redirect allowlist

### ISSUE THREAD

**Issue by tghosth** [juice-shop/juice-shop#2120]
# :bug: Bug report

## Description

As noted in https://github.com/juice-shop/pwning-juice-shop/pull/140 the allowlist for redirects currently allows `https://github.com/bkimminich/juice-shop` whereas this should be changed to `https://github.com/juice-shop/juice-shop`.

This seems to be configured in a lot of places so I didn't want to open a PR.

Note that the automated tests will also need to be changed.

### Is this a regression?

Don't know when this was changed.

**Comment by tghosth** [comment]
I discovered this because the solutions document **had** been updated

**Comment by bkimminich** [comment]
Will be fixed with `v15.3.0`. Thanks!
