### ISSUE TITLE
a

### ISSUE THREAD

**Issue by mehmetkaramaan** [juice-shop/juice-shop#2126]

**Comment by bkimminich** [comment]
Please stop creating spam issues. The first one earned you a 7 day ban from interaction with our repositories, the immediate second extended that to 30 days. The next step is a permanent ban. Please refrain from toying with our repositories. See https://pwning.owasp-juice.shop/companion-guide/latest/part3/contribution.html#_handling_of_spam_prs for details (also applies to issues in the same fashion).
