### ISSUE TITLE
[🐛] node:internal/modules/cjs/loader:959

### ISSUE THREAD

**Issue by eliassal** [juice-shop/juice-shop#2134]
# :bug: Bug report

## Description

I cloned the repo, did npm install which went through but with a lot ot WARN. Then I issued
npm start

I right away get 

node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module 'M:\CloudGuru\Introduction to OWASP Top 10 Security Risks\JuiceShop\juice-shop\build\app'
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

### Is this a regression?

This is the 1st time I try this app

## :fire: Exception or Error

<pre><code>
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module 'M:\CloudGuru\Introduction to OWASP Top 10 Security Risks\JuiceShop\juice-shop\build\app'
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

</code></pre>

## :deciduous_tree: Your Environment

<pre><code>
Node.js v18.7.0
win 10 64 bit

</code></pre>

**Comment by bkimminich** [comment]
Hi! And that folder actually doesn't exist or is it there? Also, I would suspect that something did go wrong during `npm install` that caused an actual hickup for the installation. If you could check your log or better: post it here, that'd help troubleshooting a lot.

**Comment by eliassal** [comment]
@bkimminich thanks for your response, I saw a message indicating node version should be 18.10 or 20 so I upgraded my node to v21.1.0
After that I started getting errors mainly around npm ERR! gyp ERR. here is the log of npm install. Also, what is strange I have VS 2022 and have VC++ desktop workload installed but it is erroring on it as well

> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: 'juice-shop@15.2.1',
> npm WARN EBADENGINE   required: { node: '16 - 20' },
> npm WARN EBADENGINE   current: { node: 'v21.1.0', npm: '9.6.6' }
> npm WARN EBADENGINE }
> npm WARN deprecated @types/socket.io-parser@3.0.0: This is a stub types definition. socket.io-parser provides its own type definitions, so you do not need this installed.
> npm WARN deprecated @types/express-unless@2.0.1: This is a stub types definition. express-unless provides its own type definitions, so you do not need this installed.
> npm WARN deprecated @types/cypress@1.1.3: This is a stub types definition for cypress (https://cypress.io). cypress provides its own type definitions, so you don't need @types/cypress installed!
> npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
> npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
> npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
> npm WARN deprecated eivindfjeldstad-dot@0.0.1: Use @eivifj/dot instead
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
> npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
> npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
> npm WARN deprecated jsonwebtoken@0.1.0: Critical vulnerability fix in v5.0.0. See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
> npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
> npm WARN deprecated jws@0.2.6: Security update: Versions below 3.0.0 are deprecated.
> npm WARN deprecated samsam@1.1.2: This package has been deprecated in favour of @sinonjs/samsam
> npm WARN deprecated jsonwebtoken@0.4.0: Critical vulnerability fix in v5.0.0. See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/
> npm WARN deprecated notevil@1.3.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
> npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
> npm WARN deprecated messageformat@2.3.0: Package renamed as '@messageformat/core', see messageformat.github.io for more details. 'messageformat@4' will eventually provide a polyfill for Intl.MessageFormat, once it's been defined by Unicode & ECMA.
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated vm2@3.9.17: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
> npm WARN deprecated ecstatic@3.3.2: This package is unmaintained and deprecated. See the GH Issue 259.
> npm WARN deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
> npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
> npm WARN deprecated sinon@1.17.7: 16.1.1
> npm WARN deprecated sinon@11.1.2: 16.1.1
> npm ERR! code 1
> npm ERR! path M:\CloudGuru\Introduction to OWASP Top 10 Security Risks\juice-shop\node_modules\libxmljs2
> npm ERR! command failed
> npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build --loglevel http
> npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\salam.SALAM\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --loglevel=http --module=M:\CloudGuru\Introduction to OWASP Top 10 Security Risks\juice-shop\node_modules\libxmljs2\build\Release\xmljs.node --module_name=xmljs --module_path=M:\CloudGuru\Introduction to OWASP Top 10 Security Risks\juice-shop\node_modules\libxmljs2\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120 --python=C:\ProgramData\Anaconda3\python.exe --msvs_version=2015' (1)
> npm ERR! (node:21772) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
> npm ERR! node-pre-gyp http GET https://github.com/marudor/libxmljs2/releases/download/v0.32.0/node-v120-win32-x64-unknown.tar.gz
> npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/marudor/libxmljs2/releases/download/v0.32.0/node-v120-win32-x64-unknown.tar.gz
> npm ERR! node-pre-gyp WARN Pre-built binaries not installable for libxmljs2@0.32.0 and node@21.1.0 (node-v120 ABI, unknown) (falling back to source compile with node-gyp)
> npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/marudor/libxmljs2/releases/download/v0.32.0/node-v120-win32-x64-unknown.tar.gz
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@9.3.1
> npm ERR! gyp info using node@21.1.0 | win32 | x64
> npm ERR! gyp info ok
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! find VS msvs_version was set from command line or npm config
> npm ERR! gyp ERR! find VS - looking for Visual Studio version 2015
> npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
> npm ERR! gyp ERR! find VS checking VS2022 (17.6.33829.357) found at:
> npm ERR! gyp ERR! find VS "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
> npm ERR! gyp ERR! find VS - found "Visual Studio C++ core features"
> npm ERR! gyp ERR! find VS - found VC++ toolset: v143
> npm ERR! gyp ERR! find VS - found Windows SDK: 10.0.22000.0
> npm ERR! gyp ERR! find VS - msvs_version does not match this version
> npm ERR! gyp ERR! find VS checking VS2022 (17.5.33414.496) found at:
> npm ERR! gyp ERR! find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
> npm ERR! gyp ERR! find VS - found "Visual Studio C++ core features"
> npm ERR! gyp ERR! find VS - found VC++ toolset: v143
> npm ERR! gyp ERR! find VS - found Windows SDK: 10.0.22000.0
> npm ERR! gyp ERR! find VS - msvs_version does not match this version
> npm ERR! gyp ERR! find VS checking VS2017 (15.9.33403.129) found at:
> npm ERR! gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\TestPro"
> npm ERR! gyp ERR! find VS - "Visual Studio C++ core features" missing
> npm ERR! gyp ERR! find VS checking VS2017 (15.9.33027.88) found at:
> npm ERR! gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\SQL"
> npm ERR! gyp ERR! find VS - "Visual Studio C++ core features" missing
> npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
> npm ERR! gyp ERR! find VS not looking for VS2015 as it is only supported up to Node.js 18
> npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! find VS valid versions for msvs_version:
> npm ERR! gyp ERR! find VS - "2022"
> npm ERR! gyp ERR! find VS - "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
> npm ERR! gyp ERR! find VS - "2022"
> npm ERR! gyp ERR! find VS - "C:\Program Files\Microsoft Visual Studio\2022\Community"
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! find VS **************************************************************
> npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
> npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
> npm ERR! gyp ERR! find VS For more information consult the documentation at:
> npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
> npm ERR! gyp ERR! find VS **************************************************************
> npm ERR! gyp ERR! find VS
> npm ERR! gyp ERR! configure error
> npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
> npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\salam.SALAM\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
> npm ERR! gyp ERR! stack     at C:\Users\salam.SALAM\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
> npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\salam.SALAM\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:369:14)
> npm ERR! gyp ERR! stack     at C:\Users\salam.SALAM\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
> npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2015 (C:\Users\salam.SALAM\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:353:14)
> npm ERR! gyp ERR! stack     at C:\Users\salam.SALAM\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:67:12
> npm ERR! gyp ERR! stack     at VisualStudioFinder.parseData (C:\Users\salam.SALAM\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:237:5)
> npm ERR! gyp ERR! stack     at C:\Users\salam.SALAM\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:143:14
> npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:414:7)
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:515:28)
> npm ERR! gyp ERR! System Windows_NT 10.0.19045
> npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\salam.SALAM\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--loglevel=http" "--module=M:\\CloudGuru\\Introduction to OWASP Top 10 Security Risks\\juice-shop\\node_modules\\libxmljs2\\build\\Release\\xmljs.node" "--module_name=xmljs" "--module_path=M:\\CloudGuru\\Introduction to OWASP Top 10 Security Risks\\juice-shop\\node_modules\\libxmljs2\\build\\Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v120" "--python=C:\\ProgramData\\Anaconda3\\python.exe" "--msvs_version=2015"
> npm ERR! gyp ERR! cwd M:\CloudGuru\Introduction to OWASP Top 10 Security Risks\juice-shop\node_modules\libxmljs2
> npm ERR! gyp ERR! node -v v21.1.0
> npm ERR! gyp ERR! node-gyp -v v9.3.1
> npm ERR! gyp ERR! not ok
> npm ERR! node-pre-gyp ERR! build error
> npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\salam.SALAM\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --loglevel=http --module=M:\CloudGuru\Introduction to OWASP Top 10 Security Risks\juice-shop\node_modules\libxmljs2\build\Release\xmljs.node --module_name=xmljs --module_path=M:\CloudGuru\Introduction to OWASP Top 10 Security Risks\juice-shop\node_modules\libxmljs2\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120 --python=C:\ProgramData\Anaconda3\python.exe --msvs_version=2015' (1)
> npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (M:\CloudGuru\Introduction to OWASP Top 10 Security Risks\juice-shop\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
> npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:515:28)
> npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
> npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
> npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19045
> npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "M:\\CloudGuru\\Introduction to OWASP Top 10 Security Risks\\juice-shop\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
> npm ERR! node-pre-gyp ERR! cwd M:\CloudGuru\Introduction to OWASP Top 10 Security Risks\juice-shop\node_modules\libxmljs2
> npm ERR! node-pre-gyp ERR! node -v v21.1.0
> npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
> npm ERR! node-pre-gyp ERR! not ok
> 
> npm ERR! A complete log of this run can be found in: C:\Users\salam.SALAM\AppData\Local\npm-cache\_logs\2023-10-29T13_43_40_346Z-debug-0.log

Also attached is the full log file
[2023-10-29T13_43_40_346Z-debug-0.log](https://github.com/juice-shop/juice-shop/files/13198382/2023-10-29T13_43_40_346Z-debug-0.log)

**Comment by bkimminich** [comment]
Node 21 isn't supported yet, see https://github.com/juice-shop/juice-shop#nodejs-version-compatibility

If you use Node 18 or 20 you should be fine. If you fiddled with different versions, best delete the node_modules and frontend/node_modules folders and try installation again.

**Comment by eliassal** [comment]
Well I switched to 20.0.0 instead of 20.1.0, removed the directory node_modules (there was no frontend/node_modules directory), rerun npm install, then start and everything went through, I can now brose the app but it started on port 3001 instead of 3000.How or where the port can be configured?
Thanks for your help

**Comment by J12934** [comment]
Maybe also try to clone and install this inside a path which doesn't contain white spaces in it's folder name.

`M:\CloudGuru\Introduction to OWASP Top 10 Security Risks\JuiceShop\juice-shop\build\app`
the `"Introduction to OWASP Top 10 Security Risks"` part worries me here.

At least historically this has often been a problem with software in general, not sure how well node handles this (especially on windows)

**Comment by bkimminich** [comment]
> Well I switched to 20.0.0 instead of 20.1.0, removed the directory node_modules (there was no frontend/node_modules directory), rerun npm install, then start and everything went through, I can now brose the app but it started on port 3001 instead of 3000.How or where the port can be configured? Thanks for your help

Juice Shop always starts on port 3000 by default: https://github.com/juice-shop/juice-shop/blob/master/config/default.yml#L2. Also, it won't pick the next free port but will instead complain and exit with an error if that port is in use already:

<img width="396" alt="image" src="https://github.com/juice-shop/juice-shop/assets/3531020/2a6764a6-2aa3-474c-a9d5-7799aa29f2e6">

**Comment by eliassal** [comment]
Please look at the port
![image](https://github.com/juice-shop/juice-shop/assets/8447864/f884514c-7eeb-401f-95bf-083a161c3d6b)

**Comment by bkimminich** [comment]
I didn't say the port _cannot be_ 3001, it just is never the Juice Shop default. So _someone_ has changed the `config/default.yml` or a different port is passed into the application via environment variable `PORT`. One of these things must happen on your system, neither is under the control of the Juice Shop application.

**Comment by eliassal** [comment]
Absolutly nothing touched the code source as it is my dev box at my home office, cloned the git repo then npm install, then npm start nothing else has been done. I tested on a fedora VM, did exactly the same steps and it started on port 3000, maybe Gasper the freindley ghost :-)

**Comment by bkimminich** [comment]
Spooky... 👻

Did yoh check if that env variable PORT is set for some reason? Maybe from some different server you worked with?

**Comment by eliassal** [comment]
YEEEES you are correct, in my System variables I have PORT = 3001. I have played with several node apps in the past.
So If I understand well from your 2nd response that we can change port in config/default.yml? am I correct?

**Comment by bkimminich** [comment]
> YEEEES you are correct, in my System variables I have PORT = 3001. I have played with several node apps in the past.
> So If I understand well from your 2nd response that we can change port in config/default.yml? am I correct?

See https://pwning.owasp-juice.shop/companion-guide/latest/part4/customization.html#_server_section

TL;DR: The `PORT` env variable always wins if defined, otherwise the value from the config is used.

**Comment by eliassal** [comment]
So many thanks for the details
