### ISSUE TITLE
Migration ot PostgreSQL[🚀] 

### ISSUE THREAD

**Issue by nyck33** [juice-shop/juice-shop#2137]
Can you please do this?
SQLite is not realistic for a modern app.  
Also options to make quantities unlimited so I can load test it and create logs of what looks to be normal traffic.
As of now, quantities run out quick and then it's errors if I say have 100 users spawn at 10 then not too long before quantities urn out.  

I tried migrating to PostgreSQL but it's difficult.

https://github.com/nyck33/juice_shop_cursor_win11

**Comment by bkimminich** [comment]
Juice Shop is using sequelize as an ORM framework to access the DB anyway, so the underlying actual DB is not really relevant for the learning/hacking experience. SQLite has the unbeatable benefit of running in "file based mode", which allows Juice Shop to work as a singular Docker image. This makes it very easy to run and play with, as our 81 Million Docker image pulls indicate. I don't want to give this simplicity up for a - yes, more realistic but - more complex setup.

**Comment by bkimminich** [comment]
If it were possible - with reasonable effort - to support two different DBs to pick from, then I'd be on board with the idea, but the effort is presumably quite huge. So, there'd need to be significant benefits and sufficient demand for such a dual-DB support.

**Comment by nyck33** [comment]
What about hacking a Database directly?  Just not even bothering to attack a web app and going right at a Postgres or other SQL database?  https://cheatsheetseries.owasp.org/cheatsheets/Database_Security_Cheat_Sheet.html
I think it's worth while although my efforts are not as polished. The `nolimit` branch on the repo I posted above seems okay with Locust from which I want to create logs for normal and anomalous behavior to train autoencoders for NVIDIA Morpheus which is off-topic but maybe it can be good practice just to be able to launch DoS attacks?

![image](https://github.com/juice-shop/juice-shop/assets/25189545/94f6bc29-0636-4eb0-923f-47b933678fd1)

I believe my failure rates on Locust is tied to my code that resets the quantities available to the max integer in JS (I'm not as familiar with JS) when quantities run out but then another request asks for that product before the reset occurs so I might buffer that a bit later.

**Comment by nyck33** [comment]
Also, I"m not as familiar with Node and JS but is there mixing of ESM and CJS in this app by design?  I read that might cause problems of its own.

**Comment by nyck33** [comment]
Thanks for taking time out of your busy day @bkimminich .  That's true because of all the different ways the connection can be set up on a network and then it becomes endless for covering use cases.

**Comment by bkimminich** [comment]
> What about hacking a Database directly? Just not even bothering to attack a web app and going right at a Postgres or other SQL database?

Juice Shop is an intentionally vulnerable web app that happens to have a database. I would assume there's better ways to learn direct database hacking than to attack Juice Shop's underlying DB, no matter what kind it would be.
