### ISSUE TITLE
Keep direct links to challenges stable for OpenCRE and others

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#2149]
The new Score Board should accept `?challenge=<name>` as an alias for `?searchQuery=<name>` on the new Score Board, so that OpenCRE (and others) already using this link to jump to a dedicated challenge, do not need to change anything when the default Score Board is changed to the new one with v16.0.0.

<img width="516" alt="image" src="https://github.com/juice-shop/juice-shop/assets/3531020/dcea6667-e394-4a23-b6cc-edb2f93e2480">

**Comment by bkimminich** [comment]
## Proposed solution
1. If `?challenge=<name>` is a query parameter **and** `?searchQuery=<name>` as well, ignore `?challenge=<name>`
2. If `?challenge=<name>` is a query parameter **without** `?searchQuery=<name>` being present, rewrite `?challenge=<name>` into `?searchQuery=<name>` and trigger route locally without browser reload

**Comment by bogminic** [comment]
@bkimminich I've submitted a pull request addressing this issue. Please review it at your earliest convenience. Thank you!
