### ISSUE TITLE
Use median instead of average for total cheat score

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#2150]
The current anti cheat module stores the likelihood of individual challenges having been cheated and then calculates the average as a total cheat score. When running the automated tests (which solve almost all challenges in mere minutes) there's usually a total cheat score of 85-89% calculated at the end of the suite.

The average drops off whenever a trivial or related challenge is solved, counting as 0% cheat probability and therefore bringing the average down. If the median would be used instead, the impact of such outliers would be reduced. Similarly, an honest user who just by coincidence solved one challenge "too fast" would no longer end up with an arbitrarily high total score.

**Comment by Sanket-Arekar** [comment]
Hey @bkimminich  I would like to work on this issue. Can you Please assign me this issue?

**Comment by bkimminich** [comment]
Sure, feel free to go for it!
