### ISSUE TITLE
[🚀] Improve user experience in Coding Challenge: Bonus Payload section

### ISSUE THREAD

**Issue by bogminic** [juice-shop/juice-shop#2152]
# :rocket: Feature request

### Description

Hello Team,

I’ve been frequently using the “Coding Challenge: Bonus Payload” feature and I believe there’s room for improvement in terms of user experience. Let me elaborate.

Currently, when we want to submit the “Find it” code line/lines, if the code portion is long, we need to scroll to the footer. Similarly, in the “Fix it” section, we have to toggle between the header (where we select the solution) and the footer (where the submit button is located). You can see an example in the image attached below.

![Fix it section bad user experience](https://github.com/juice-shop/juice-shop/assets/10672395/4125b22b-254b-45c8-989f-171961668ddb)

### Solution ideas

To address this, I propose making the footer fixed and moving the “Fix it” selection used for the solution to the footer, thereby increasing the code area. This way, users won’t need to scroll to press the submit button. I've visually illustrated the suggested solution both with accompanying text and without it in the two images presented below.

![Fixed footer with no text](https://github.com/juice-shop/juice-shop/assets/10672395/a8bae94c-d222-4013-958b-ce9f23f3bca4)

![Fixed footer with text](https://github.com/juice-shop/juice-shop/assets/10672395/1e289006-b5be-4bc1-86e4-34e6838ee70e)

I’d love to hear your thoughts on this. Do you think it’s worth investing time to resolve this issue?

**Comment by bkimminich** [comment]
Love the idea, the scroll behavior of this dialog bugs me as well all the time... 😬

**Comment by bogminic** [comment]
Great! Please assign me to this item, and I will try to address it in the coming weeks.
