### ISSUE TITLE
[⭐] Steal someone address

### ISSUE THREAD

**Issue by bahylol** [juice-shop/juice-shop#2160]
# :star: Steal someone address

### Description

 The challenge involves the attacker attempting to steal the address of another user. What makes this challenge unique is that the API with the vulnerability is unexpected, and the bug is not easy to spot. The attacker needs to carefully observe the changes that occur in their account, as well as in the other account, by manipulating parameters and the request body.

### Underlying vulnerability

 Broken Access Control 

### Expected difficulty

|  heavy_check_mark    | Difficulty                           |
|:------------------------:|:-------------------------------------|
|     :grey_question:      | :star:                               |
|     ✔️   | :star::star:                         |
|    ✔️     | :star::star::star:                   |
|     ✔️     | :star::star::star::star:             |
|     :grey_question:      | :star::star::star::star::star:       |
|     :grey_question:      | :star::star::star::star::star::star: |

### Possible attack flow

  1-The attacker will observe the requests that is sent when trying to update his address .
2-The attacker will try to manipulate the id of address parameter.
3-The attacker will observe from another account that the address disappeared.
4-The attacker will try to steal the address rather than deleting it from the other account by clearing the body of the request.

**Comment by bkimminich** [comment]
While this is a case of "more of the same" when it comes to the underlying access control vulnerability, it would be a good challenge for a new contributor to implement. So, I'll leave this up for grabs if someone is interested!

**Comment by Azathoth-X** [comment]
Hi,
I usually do pentesting only but dipping my toes in dev side, I would like to take up this but have a few questions:
- Does this need to include file path traversal?
- Is there any guide for inherent insecure webdev, only things I could find were some basic exammples on owasp site

**Comment by bahylol** [comment]
Hi, No the attack does not include path traversal.
