### ISSUE TITLE
error while instaalling

### ISSUE THREAD

**Issue by Rehan919** [juice-shop/juice-shop#2171]
npm start

> juice-shop@9.3.1 start
> node app

info: All dependencies in ./package.json are satisfied (OK)
node: symbol lookup error: /home/rehan/Downloads/juice-shop_9.3.1/node_modules/libxmljs2/build/Release/xmljs.node: undefined symbol: _ZN2v87Isolate19CheckMemoryPressureEv

**Comment by bkimminich** [comment]
Juice Shop v9.3.1 is no longer supported. You can try to run its ZIP archive variant or Docker image, but local installation on a current NodeJS version is not going to work.

**Comment by bkimminich** [comment]
I would recommend to use the latest v16 version, though as it will work with current NodeJS, meaning you don't have to install an old unmaintained NodeJS version to make the old Juice Shop version run.
