### ISSUE TITLE
[🚀] Option to disable danger zone challenges manually

### ISSUE THREAD

**Issue by jvmdc** [juice-shop/juice-shop#2174]
# :rocket: Feature request

### Description
It would be nice to have the option to disable the danger zone challenges manually through the configuration just like you can explicitly allow them.

Use case is when running in a containerized environment that is not one of the ones you are automatically detecting, e.g. Podman, Containerd, Runc or any of the other alternatives to Docker that exist.

### Solution ideas
Add an additional option in the configuration similar to safetyOverride that can be set to explicitly disable the danger zone vulnerabilities

### Possible alternatives
Running it on one of the auto-detected platforms

**Comment by bkimminich** [comment]
We could even consider having an incompatible config change with v17.0.0 that uses an enumeration instead:

`safetyMode: auto # auto / on / off`

Automatic would be today's default behavior, off would be today's unsafe mode, on would be what you are looking for.

**Comment by bkimminich** [comment]
It needs to be considered that one JWT challenge is disabled on Windows using the same mechanism as for dangerous challenges today. In the `safetyMode: on` case this challenge would also be disabled on any other OS, even if the challenge could work there technically and is completely harmless. This would either have to be an accepted collateral damage, or the Windows case would have to be handled separately when this change is made.

**Comment by Pratham1812** [comment]
Hey @bkimminich , I would like to take up this issue. Also would it be a good idea to not add the challenges with "Danger Zone" tag in the datacache, after doing this we won't have to change anything else in other functions, or is there any better approach which I may have not considered.

**Comment by bkimminich** [comment]
> Hey @bkimminich , I would like to take up this issue. Also would it be a good idea to not add the challenges with "Danger Zone" tag in the datacache, after doing this we won't have to change anything else in other functions, or is there any better approach which I may have not considered.

The datacache is just a shortcut to avoid querying the DB on the serverside all the time. It doesn't enable/disable any vulnerable code sections.

**Comment by Pratham1812** [comment]
How can I go ahead with this considering I am just starting to contribute to juice shop :). One of the other approach (seems laborious) identify which vulnerable functions are associated for challenges tagged with "Dangerous Zone" and explicitly call a function similar to "disableOnContainerEnv" and disable that vulnerable function.
@bkimminich

**Comment by bkimminich** [comment]
The dangerous challenges have their vulnerable code sections already wrapped in a check if they should be disabled. But this check depends on the identified runtime environment. It today considers Docker/Heroku/GitPod "on container" but the same mechanism also is used to disable a challenge that doesn't work on Windows, although it's not really dangerous. If you'd run the Juice Shop with the `unsafe` config, the whole mechanism would be disabled.

The feature request in #2174 is to have the option for an override in the opposite direction, where dangerous challenges (and that one challenge broken Windows due to using the same mechanism) would just be hard disabled independent of any environment the server is running on.

**Comment by bkimminich** [comment]
| `safetyMode` | Behavior on Docker/Heroku/GitPod  | Behavior on Windows | Behavior anywhere else | 
|--------|--------|--------|---|
| `auto` | Dangerous challenges disabled | Dangerous enabled; [broken JWT Challenge disabled](https://github.com/juice-shop/juice-shop/issues/2174#issuecomment-1887594677) | Dangerous challenges enabled |
| `off` | Dangerous challenges enabled | Dangerous enabled; [broken JWT Challenge disabled](https://github.com/juice-shop/juice-shop/issues/2174#issuecomment-1887594677) | Dangerous challenges enabled |
| `on` | Dangerous challenges disabled | Dangerous disabled; [broken JWT Challenge disabled](https://github.com/juice-shop/juice-shop/issues/2174#issuecomment-1887594677) |  Dangerous challenges disabled|

**Comment by bkimminich** [comment]
The Windows case could also be handled similar to missing Internet connection, where just a warning during startup is shown that some challenges will not work:

<img width="597" alt="image" src="https://github.com/juice-shop/juice-shop/assets/3531020/0dde9832-b7b1-4174-bdd6-116926030d4b">

This would cleanly split "broken challenges" from "dangerous challenges". For the broken ones a warning on the Score Board would also be possible independent of the deactivation notice from the _Danger Zone_ challenges.

**Comment by Pratham1812** [comment]
@bkimminich could you please review the latest changes done in the PR :)

**Comment by jvmdc** [comment]
FYI I've worked around the issue for now by setting the env. variable HEROKU to some value - This makes Juice Shop think I am running on Heroku and disables the dangerous challenges
