### ISSUE TITLE
[⭐] Reset password with leaked token

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#2175]
# :star: Challenge idea

### Description

Inspired by @troyhunt's talk at NDC Security 2024 in Oslo the Juice Shop could get an additional password reset mechanism (so the user can choose between that and the existing one based on security question) where a link with a onetime token is sent to the user email (which won't really happen to avoid spamming). The challenge is to reset some account's password using this method.

### Underlying vulnerability/ies

Initiation of the password reset leaks the token in the response (but doesn't show it on screen). It can just be used to craft the actual reset link.

### Expected difficulty

| :heavy_check_mark: / :x: | Difficulty                           |
|:------------------------:|:-------------------------------------|
|     :grey_question:      | :star:                               |
|     :grey_question:      | :star::star:                         |
|     :heavy_check_mark:      | :star::star::star:                   |
|     :grey_question:      | :star::star::star::star:             |
|     :grey_question:      | :star::star::star::star::star:       |
|     :grey_question:      | :star::star::star::star::star::star: |

### Possible attack flow

1. Choose password reset for a dedicated account with a real email behind it (to simulate not having access to the email being sent)
2. Notice token in HTTP response
3. Find out the URL structure of the actual reset link from client side JavaScript
4. Craft magic link with the token from 2.
5. Pick new password to solve challenge

Important note: Juice Shop cannot send out reset links by mail because those could be abused for spamming. This needs to be mentioned somewhere, e.g. in the hint tooltip to not lead users on a wrong track how to solve this challenge. A fake failed XHR request which says that the email service is down, might be an option.

**Comment by rohansx** [comment]
Hi @bkimminich 

I noticed your proposal for a new password reset mechanism. The idea of introducing an additional method using a one-time token sent via a simulated email is fascinating and seems like a valuable addition to the project.

I'm interested in taking on this challenge and would like to dive deeper into the specifics. Here are a few points I'd like to clarify before getting started:

Token Mechanics: Could you shed some light on the preferred approach for generating the token and ensuring it's leaked in the HTTP response without being visible on the UI?

URL Structure: Is there a particular method or format we should adhere to when figuring out the reset link's URL from the client-side JavaScript?

Simulating Email Service Failure: For the implementation of the fake email service error, what specific details or behavior should be mimicked?

Security Aspects: Given the sensitive nature of password reset functionality, are there any special security considerations or practices I should be mindful of during development?

I'm excited about the prospect of contributing to this feature and would appreciate any guidance or additional information you could provide. If it's alright with you, I'd like to start working on this issue.

**Comment by rohansx** [comment]
@bkimminich Shall i start working on it ?
