### ISSUE TITLE
question re: Dockerfile vs. package.json

### ISSUE THREAD

**Issue by thatsjet** [juice-shop/juice-shop#225]
Sorry, probably a bit of n00b question, but I want to make the port configurable so I forked to add config and when I looked at package.json I notice there is a postinstall to run bower and grunt minify, but these are also in the Dockerfile. Anybody familiar with the project, especially the Dockerfile can tell me why both are needed?

Why do I want to do this?: -- I'm creating a containerized set of vuln webapps all to be run in their own containers as a "wapt dojo" of sorts and want the users to be able to specify the ports they run on to avoid conflicts.

**Comment by bkimminich** [comment]
For some reason the `postinstall` scripts of the `package.json` are not properly executed when `npm install` runs during Docker image creation:

```
[0m[91mnpm [0m[91minfo [0m[91mlifecycle juice-shop@2.16.1~postinstall: juice-shop@2.16.1
[0m[91mnpm [0m[91mWARN [0m[91mlifecycle juice-shop@2.16.1~postinstall: cannot run in wd %s %s (wd=%s) juice-shop@2.16.1 bower install && grunt minify /juice-shop
```

That's why the `bower install` and `grunt package` are executed manually afterwards - it's basically a workaround.

**Comment by thatsjet** [comment]
Gotcha. I'll add my dep's in both spots. Thanks.

**Comment by bkimminich** [comment]
I just read somewhere that `--unsafe-perm` might fix that... I'll try that on `develop` right away, maybe the workaround can be gotten rid of with this new workaround... 😀

**Comment by bkimminich** [comment]
Looks good, the Dockerfile `RUN` is now just `npm install --production --unsafe-perm` - no more extra `bower` or `grunt` calls needed.
