### ISSUE TITLE
[⭐] Add socket.io-based challenge

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#226]
Maybe forging an event emission for a challenge that does not really exist but make the client pick it up nonetheless?
##

**Comment by bkimminich** [comment]
- http://stackoverflow.com/questions/36080207/new-in-socket-io-how-to-prevent-socket-io-client-script-hacking
- https://www.christian-schneider.net/CrossSiteWebSocketHijacking.html

**Comment by bkimminich** [comment]
@cschneider4711 Seems you are a subject-matter expert on Websockets! 😃 I'd happily take ideas for practical bad implementation of socket.io in Juice Shop client or server, that could be turned into a hacking challenge. For example "Fake a solved-challenge notification that contains a link to http://kimminich.de (or https://www.christian-schneider.net)" 😀

**Comment by agrawalarpit14** [comment]
Hi @bkimminich @J12934, I read through the documentation of socket.io. I was thinking of an attack where a user connects to the server by writing a small script like the following in a html page.
```
<script src="socket.io.js"></script>
<script src="https://code.jquery.com/jquery-1.11.1.js"></script>
<script>
  var sock = io('http://localhost:3000');
  sock.on('server started', function(socket){
  console.log('someone connected');
  socket.on('challenge solved', function(msg){
      console.log('message: ' + msg);
    });
  });
</script> 
```
After connecting, the user will broadcast `data`  using `challenge solved` which will make the data reach on the original juice-shop client as well which will trigger a solved-challenge notification.
I am trying to achieve this scenario. Please let me know your views on it. Thank You

**Comment by agrawalarpit14** [comment]
Although such a scenario is possible only when the server emits the received file to all the clients connected, which I think is the case presently?

**Comment by supra08** [comment]
@agrawalarpit14 are you still working on this? If not, I would be glad to pick it up. @bkimminich

**Comment by agrawalarpit14** [comment]
You can go forward with the same. Thank You
