### ISSUE TITLE
Improving user experience for scrollbars on score-board page[🚀] 

### ISSUE THREAD

**Issue by ThReinecke** [juice-shop/juice-shop#2261]
# :rocket: Feature request

### Description

Hi, first of all thanks for the Juice Shop! One thing I realised from a user perspective are the scrollbars on the score-board page for the challenge card component. I think there is room for some improvement:

- The scrollbars look “bulky” and could look a bit more “modern”.
- Sometimes the scrollbar track (so the background) is not visible and the thumb is either not showing up at all or doesn’t move when using the up/down arrows.
- I personally don’t find the scrollbar corner on the bottom right looks good.

Here are 2 screenshots for reference:
![Screenshot (45)](https://github.com/juice-shop/juice-shop/assets/126483857/60d34bfc-6dae-4537-b880-f642950ddbb4)
![Screenshot (46)](https://github.com/juice-shop/juice-shop/assets/126483857/4034f4a4-c6a5-49b7-9fd0-75ce75f953ad)

### Solution ideas
I know that design can be subjective but I would propose the following changes:

- Make the scrollbars thinner, and look a bit more “modern” with slightly rounded edges.
- I propose moving from the arrow and (occasionally) fixed thumb to a design without arrows and a scrollbar track where at least a small part is always visible. That would be a better indication that one can scroll.
- A minimum contrast of 7:1 between the track and thumb.
- Remove the scrollbar corner.

I don't think there are any hard guidlines on scrollbar design but I loosely got inspiration from: https://adrianroselli.com/2019/01/baseline-rules-for-scrollbar-usability.html and https://developer.apple.com/design/human-interface-guidelines/color.

I played a bit with the design and came up with something like this:

![Screenshot (47)](https://github.com/juice-shop/juice-shop/assets/126483857/49f0bd13-9190-4f03-bb49-0b1094f44725)
![Screenshot (48)](https://github.com/juice-shop/juice-shop/assets/126483857/11225b6f-4b78-4052-8f40-fd64392ff235)

This is just a minor thing that bothered me but I thought it could be a good first contribution to familiarise myself more with the juice-shop codebase. If there is interest, I could contribute this.

Best,
Thomas

**Comment by bkimminich** [comment]
Looks *a lot* nicer than the default ones! A PR with this enhancement would be appreciated! 👍

**Comment by ThReinecke** [comment]
Great, I will finalize the work and submit the PR!
