### ISSUE TITLE
[🐛] Commit package-lock.json

### ISSUE THREAD

**Issue by relaxnow** [juice-shop/juice-shop#2268]
# :bug: Bug report

## Description

package-lock.json is not committed to the repo, this means that different installs at different times will generate different third party libraries.
It is best practice to commit package-lock.json: https://stackoverflow.com/a/44210813/4512

**Comment by ashellwig** [comment]
I think this is intentional judging by the [.npmrc](https://github.com/juice-shop/juice-shop/blob/master/.npmrc) file. Perhaps it is because people will be using different versions of Node.js/NPM and will increase compatibility for those users.

**Comment by bkimminich** [comment]
It was a conscious decision to rather always build from scratch. We have occasional issues with it when libs introduce bugs or don't follow semantic versioning, but those cases were rare. The benefit of not having one is indeed compatibility issues we had and also that it would have made the build job more complicated with two variants, i.e. full vs. locked build. We do have an SBOM in our packaged distributions and container images, though.
