### ISSUE TITLE
[🐛] Server-side exception on orders without sufficient funds

### ISSUE THREAD

**Issue by romulusFR** [juice-shop/juice-shop#2272]
# :bug: Bug report

## Description

It seems there is a double send on the server-side order route.

### Is this a regression?

I've used another version one year ago in a lab session, i don't remember that issue.

## :microscope: Minimal Reproduction

That seems to happen when putting an order without money in the wallet.

## :fire: Exception or Error

```raw
node:_http_outgoing:659
    throw new ERR_HTTP_HEADERS_SENT('set');
          ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (node:_http_outgoing:659:11)
    at ServerResponse.header (/juice-shop/node_modules/express/lib/response.js:795:10)
    at ServerResponse.send (/juice-shop/node_modules/express/lib/response.js:175:12)
    at ServerResponse.json (/juice-shop/node_modules/express/lib/response.js:279:15)
    at WriteStream.<anonymous> (/juice-shop/build/routes/order.js:64:25) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

```

## :deciduous_tree: Your Environment

I use docker lastest image `sha256:c24b8ae4373e8ac85e6ab821007c972907a98f1cfebb98957492b75056002a38` (version 17.0.0) created at 2024-05-24T20:06:16.681929814. 

### Additional Information

Looking to .js after translation from .ts, the issue may be a double sent between lines 64 and 159 as suggested by the error.
The async `finish` event tries to send on line 64 but Express has already sent through its standard error handler via `next` on line 159.

```js
  61                 fileWriter.on('finish', async () => {
  62                     void basket.update({ coupon: null });
  63                     await basketitem_1.BasketItemModel.destroy({ where: { BasketId: id } });
  64                     res.json({ orderConfirmation: orderId });
  65                 });
```

```js
if (req.body.UserId) {
 151                     if (req.body.orderDetails && req.body.orderDetails.paymentId === 'wallet') {
 152                         const wallet = await wallet_1.WalletModel.findOne({ where: { UserId: req.body.UserId } });
 153                         if ((wallet != null) && wallet.balance >= totalPrice) {
 154                             wallet_1.WalletModel.decrement({ balance: totalPrice }, { where: { UserId: req.body.UserId } }).catch((error) => {
 155                                 next(error);
 156                             });
 157                         }
 158                         else {
 159                             next(new Error('Insufficient wallet balance.'));
 160                         }
 161                     }
 162                     wallet_1.WalletModel.increment({ balance: totalPoints }, { where: { UserId: req.body.UserId } }).catch((error) => {
 163                         next(error);
 164                     });
 165                 }
```

**Comment by bkimminich** [comment]
I tested the behavior of the application by putting expensive items >1000$ into the cart of user `demo`, going through checkout, then via DevTools re-enabling the wallet payment button. Clicking on that button results in the expected error popup complaining about insufficient funds. The fact that behind the scenes a non-crashing error occurs, seems harmless to me. Do I miss something?

**Comment by romulusFR** [comment]
Several students had this issue on a lab session, crashing their servers with the same error as reported , so i had to restart the dockers. Unfortunately, they where unable to find the precise query that crashed it. They were using Burp to craft the query, not the web interface.
