### ISSUE TITLE
[🐛] Hacking instructor can't be disabled on the score board

### ISSUE THREAD

**Issue by abelLastro** [juice-shop/juice-shop#2279]
# :bug: Bug report

## Description

I'm trying to customise Juice Shop for some security training however my custom config isn't working as expected.

I'm trying to turn off the hacking instructor and I can see there's the `hackingInstructor.isEnabled` config option as described in the docs [here](https://pwning.owasp-juice.shop/companion-guide/latest/part4/customization.html#_hackinginstructor_section). However, when setting this value to false, the hacking instructor is still available on the scoreboard.

In terms of recreating this I note that Juice Shop's default CTF mode looks like it's trying to disable the hacking instructor too as seen [here](https://github.com/juice-shop/juice-shop/blob/master/config/ctf.yml#L14). However, when I start the master branch of Juice Shop up with `NODE_ENV=ctf npm start`, although CTF flags are displayed as expected, the hacking instructor is still there too.

When asking on OWASP slack it was suggested that this might be related to the new score board.

## :microscope: Minimal Reproduction

Start the master branch of Juice Shop up using the default CTF mode, e.g. start it up with `NODE_ENV=ctf npm start`. Even though the CTF config [here](https://github.com/juice-shop/juice-shop/blob/master/config/ctf.yml#L14) sets the hacking instructor to false, the hacking instructor is still present on the score board.

**Comment by abelLastro** [comment]
Seems like a similar issue with the coding challenges. I'm trying to disable these by setting `challenges.codingChallengesEnabled` to `never` but I'm still seeing them on the score board.

**Comment by bkimminich** [comment]
Should be fixed for both hacking instructor and coding challenges now on `develop` branch. If you still experience issues, just let me know.
