### ISSUE TITLE
xss defacement bug is removed can you tell me which version was it [🚀] 

### ISSUE THREAD

**Issue by MrDe6u9** [juice-shop/juice-shop#2283]
Hello team, 
I want to try the xss webpage defacement and I have installed the latest version of it. But when I try in it didn't work, the xss on the username is not working. 
can you please tell me in which version it is available on.

**Comment by bkimminich** [comment]
Username has a persisted XSS vuln, so in case you're using Docker or Heroku, the challenge might just be disabled by default. Check https://pwning.owasp-juice.shop/companion-guide/latest/part1/challenges.html#_potentially_dangerous_challenges for details.
