### ISSUE TITLE
[🚀] 

### ISSUE THREAD

**Issue by dorp007** [juice-shop/juice-shop#2284]
# :rocket: Feature request

### Description

I feel that I should speak out for all of us Shyriiwook spoken by Chewbacca and other Wookiees, droidspeak spoken by R2-D2 and BB-8, Ewokese spoken by Ewoks, and Huttese spoken by Jabba the Hutt. None of these is added to the project yet there is Klingon.

### Solution ideas

Join the rebels

### Possible alternatives

`https://funtranslations.com/`

**Comment by bkimminich** [comment]
You'd have to rather convince CrowdIn to add those languages to their portfolio, and I would _immediately_ add them in Juice Shop.
