### ISSUE TITLE
[🐛] Juice shop won’t start with a module not found error

### ISSUE THREAD

**Issue by agottschling** [juice-shop/juice-shop#2303]
# :bug: Bug report

## Description

Juice Shop will not start and fails with a “Cannot find module …\build\app” message. 
The build directory is also missing in the zip file and therefore the extracted directory.

### Is this a regression?

I tried bringing up v16.0.1, but got a different error about a different module being missing.

## :microscope: Minimal Reproduction

Download the win32 package for node 20 or 21, extract and run npm start. 
Also observe that the zip file is missing the build directory

## :fire: Exception or Error

<pre><code>

Cannot find module \build\app
</code></pre>

## :deciduous_tree: Your Environment

<pre><code>

Node -v: v20.16.0
Npm -v: 10.8.1
</code></pre>

### Additional Information

Running on W11, tested also with NodeJS 21 with the same error

**Comment by bkimminich** [comment]
I can confirm this issue:
```
Error: Cannot find module 'C:\temp\juice-shop-17.0.0_node20_win32_x64\juice-shop_17.0.0\build\app'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

It seems the entire `build/` folder is missing:
![image](https://github.com/user-attachments/assets/9f01605a-eac2-49b2-877c-170f5529fba8)

I tried `grunt package` locally on Win10 with Node20 and there the resulting ZIP contains everything as it should:
![image](https://github.com/user-attachments/assets/a74b5771-ddd2-40a6-a570-2cf754f11c85)

I would conclude that `grunt package` is fine, but the CI-command is behaving differently than before and our tests seem to miss that case:

```
npm prune --production && npm dedupe && cd frontend && npm prune --legacy-peer-deps --production && cd .. && npm run --silent sbom && grunt package
```

**Comment by bkimminich** [comment]
I locally reproduced the CI/CD steps, and `npm install --production` is not producing the `build/` folder. Only the regular `npm install` does. Tested on Windows.

I also checked some other packages from the 17.0.0 release page. It seems only for Windows and MacOS the `build/` folder is missing. For Linux it is in the archive as it should be.

Lastly, I checked all Node.js packages: For MacOS and Windows the `build/` folder is missing in all versions, i.e. from Node 18, 20 and 21.

**Comment by bkimminich** [comment]
Found the problem and fixed it by reverting a commit from May 2024: https://github.com/juice-shop/juice-shop/commit/4049d1d0511ea32828f1259e70670ccc9ca823d8. It seems that the move of `ts-node-dev` into the dev dependencies resulted in this problem.

cc @J12934

**Comment by bkimminich** [comment]
Will be fixed with `v17.1.0`.

**Comment by agottschling** [comment]
Thanks! Any idea when the new version will be out to play around with?

**Comment by bkimminich** [comment]
It's already released: https://github.com/juice-shop/juice-shop/releases/tag/v17.1.0

**Comment by J12934** [comment]
> Found the problem and fixed it by reverting a commit from May 2024: https://github.com/juice-shop/juice-shop/commit/4049d1d0511ea32828f1259e70670ccc9ca823d8. It seems that the move of `ts-node-dev` into the dev dependencies resulted in this problem.
> 
> 
> 
> cc @J12934

Mh ok weird. Will try to take another look why this might be the case. Typescript is somewhat big AFAIK. Would be nice to not have it in the container

**Comment by Onisoya** [comment]
![Screenshot 2024-12-31 144825](https://github.com/user-attachments/assets/ab8bcc13-0849-4fbf-886f-130c0c41093f)
![Screenshot 2024-12-31 144825](https://github.com/user-attachments/assets/0af50387-4550-4293-882c-3a215144db06)

**Comment by Onisoya** [comment]
![Screenshot 2024-12-31 144825](https://github.com/user-attachments/assets/bf60bae5-4d6d-43b9-ac61-003861716818)
![Uploading missing-build-subdirectory.png…]()



I think '...build/app' subdirectory is missing and this could be the error, please how can I fix this?

**Comment by Onisoya** [comment]
![Uploading missing-build-subdirectory.png…]()

**Comment by Onisoya** [comment]
![Uploading missing-build-subdirectory.png…]()

**Comment by bsplayer2020** [comment]
In my case the development tools were missing, hence after installing them on RedHat:

sudo yum groupinstall 'Development Tools'
sudo yum install libxml2-devel python3

It installed without any error and now up and running.

Hope this has been useful and informative.

Thanks.
