### ISSUE TITLE
[🐛] Product Tampering Challenge doesn't work for other languages

### ISSUE THREAD

**Issue by mum-viadee** [juice-shop/juice-shop#2341]
# :bug: Bug report

## Description
If you change the language in juice-shop, even the product description for the OWASP SSL Advanced Forensic Tool (O-Saft) is changed to that language. That's awesome, but the product tampering challenge checks for the complete anchor tag to be like  `<a href="https://owasp.slack.com" target="_blank">More...</a>`. If I just change the href part, as specified in the challenge description, the link text will stay in the language I have selected before. With german language selected, the anchor tag would be something like `<a href="https://owasp.slack.com" target="_blank">Mehr...</a>`, which does not solve the challenge because of the translated link text ("Mehr..."). 

### Is this a regression?
No, I don't think so.

## :microscope: Minimal Reproduction
- Switch to german language and reload the page
- Just change the href part for the product tampering challenge, leave link text as given. 
=> Challenge is not solved, event if the link (href) has been changed correctly

### Additional Information
No browser or deployment specific issue!

**Comment by bkimminich** [comment]
Wow, that's a really nice catch! 🎣

**Comment by mum-viadee** [comment]
I stumbled across it rather by accident.
