### ISSUE TITLE
[🐛] Error [ERR_MODULE_NOT_FOUND] after running npm istall

### ISSUE THREAD

**Issue by Vireshwar313** [juice-shop/juice-shop#2354]
# :bug: Bug report

## Description
<img width="804" alt="image" src="https://github.com/user-attachments/assets/61a1ed24-6344-428f-b4ba-d157b91d39f4">

After running npm install command i'm getting error as mentioned in the attached image

**Comment by bkimminich** [comment]
I can see your node and Juice Shop version in the log, but could you post your OS type and processor architecture as well please? I just did a from-scratch `npm install` after deleting both `node_modules` folders on my Windows 11 Intel, and it passed without any problems.

**Comment by sir-Five5** [comment]
Just so you know I'm having the same problem. My OS is Kali and processer is Intel

**Comment by bkimminich** [comment]
Are any error thrown in the preceding steps? This is the `postinstall` hook failing because it misses something, so I'd expect some of the actuall installation step going wrong beforehand?

**Comment by bkimminich** [comment]
Please check also https://pwning.owasp-juice.shop/companion-guide/latest/part4/troubleshooting.html#_linux for some previously seen issues. Particularly, Kali Linux has in the past proven to behave different than "normal" Linux distributions when it comes to running Juice Shop.

**Comment by sir-Five5** [comment]
I removed the directory and cloned it again, now it's working perfectly
