### ISSUE TITLE
[🐛] Session storage crashes docker container

### ISSUE THREAD

**Issue by mezotv** [juice-shop/juice-shop#2358]
# :bug: Bug report

## Description
When trying to generate a coupon code I modified the session storage to attempt that issue. When doing so and trying to purchase the item my docker container crashed.

### Is this a regression?
No

## :microscope: Minimal Reproduction

1. Open the dev tools and navigate to session storage
2. Put items in your basket
3. Go to checkout and add any valid coupon
4. Set the percentage of that coupon to 100
5. Try to purchase said item at 100% discount

## :fire: Exception or Error

<pre><code>
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (node:_http_outgoing:659:11)
    at ServerResponse.header (/juice-shop/node_modules/express/lib/response.js:795:10)
    at ServerResponse.send (/juice-shop/node_modules/express/lib/response.js:175:12)
    at ServerResponse.json (/juice-shop/node_modules/express/lib/response.js:279:15)
    at WriteStream.<anonymous> (/juice-shop/build/routes/order.js:64:25) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
</code></pre>

## :deciduous_tree: Your Environment

<pre><code>
Node 20.17.0
Npm 10.8.3
Docker 27.2.0

</code></pre>

**Comment by KapilSareen** [comment]
Hi @mezotv , I tried to recreate this issue but it does not seem to crash in my case. Are you certain these were the only steps you did that led to the docker container crash?

**Comment by bkimminich** [comment]
How do you perform step 4? When submitting the coupon, you will get the discount value as a response, so that the UI can show the value. At no point is the discount value is directly submitted by the client to the server. It only submits the code, which is then processed on the server.

@mezotv If you meant that you created a coupon with the equivalent of 100% discount, could you post that here please so I can try it?

**Comment by mezotv** [comment]
> How do you perform step 4? When submitting the coupon, you will get the discount value as a response, so that the UI can show the value. At no point is the discount value is directly submitted by the client to the server. It only submits the code, which is then processed on the server.
> 
> @mezotv If you meant that you created a coupon with the equivalent of 100% discount, could you post that here please so I can try it?

There was a value in the session/local storage that represented the percentage of the coupon for me changing that to 100 and trying to purchase with that coupon crashed the container.

**Comment by bkimminich** [comment]
Please send your example, otherwise I'm not even sure if you used a regular coupon or a campaign code. Thanks.

**Comment by mezotv** [comment]
> Please send your example, otherwise I'm not even sure if you used a regular coupon or a campaign code. Thanks.

Ill try to do that tlday after work!

**Comment by mezotv** [comment]
Pretty sure it was this code I applied `pEw8pg+yBo` added that then edited the local storage and pressed the purchase button. Thats when the container crashed

**Comment by bkimminich** [comment]
Would you be able to reproduce this and could post the error log from the server so I see the exception stack trace?

**Comment by mezotv** [comment]
> Would you be able to reproduce this and could post the error log from the server so I see the exception stack trace?

I probably wont have time to do that in the next few days but somewhere later next week I should be able to!

**Comment by KapilSareen** [comment]
Hi is there any update regarding this issue? @mezotv
