### ISSUE TITLE
[🐛] Missing challenge for login with user ethereum@juice-sh.op

### ISSUE THREAD

**Issue by UweKrause** [juice-shop/juice-shop#2371]
# :bug: Bug report

## Description

One of the easier credential leaks lead to the password of the user `ethereum@juice-sh.op`. Logging in with this password works, but there is no associated challenge to this.

To find the passwort, there is no SQLi or anything else involved. The `rest/memories/` endpoint leaks some user information, among other the hashed passwords. The password of the user `ethereum@juice-sh.op` is an easy find in free to use online rainbow tables.

I was a little bit disappointed to not get a "solve" :(

[Thanks for the juice shop, really an awesome project!!]

## :microscope: Minimal Reproduction

- Go to the photo wall (`/#/photo-wall`)
- view response for endpoint `/rest/memories/`
- "data" contains some photos, some memories and the User object (including hashed password)
- get the unhashed values for the passwords (for example with crackstation.net)
- see that the hash `2c17c6393771ee3048ae34d6b380c5ec` is md5 hash of `private`
- login with `ethereum@juice-sh.op` and `private`

## :fire: Expectation

Receiving a successful solve notification

**Comment by bkimminich** [comment]
We have already several "Login as..." challenges which can be solved via guessing, SQLi, rainbow tables, brute force,... I do not think we need another one of the same category really.
