### ISSUE TITLE
[🐛] Missing Translations for Challenge Descriptions in Non-English Languages

### ISSUE THREAD

**Issue by TinTinTheGuy** [juice-shop/juice-shop#2396]
# :bug: Bug report

## Description

Some challenge descriptions and hints in OWASP Juice Shop remain in English when the application is switched to a different language, such as French or Spanish. This creates an inconsistent user experience for non-English speakers and may hinder their ability to complete challenges
### Is this a regression?

No, this behavior is not a regression. It appears to be an issue with challenges in http://127.0.0.1:3000/#/score-board

## :microscope: Minimal Reproduction

Launch OWASP Juice Shop and navigate to http://127.0.0.1:3000/#/score-board
Switch the language using the dropdown menu in the top-right corner to a non-English language (e.g., French or Spanish).
Scroll through the list of challenges and observe that some challenge descriptions and hints remain in English.

## :fire: Exception or Error

<pre><code>

</code></pre>

## :deciduous_tree: Your Environment

Chrome
Docker version 26.1.1, build 4cf5afa

<pre><code>

</code></pre>

**Comment by bkimminich** [comment]
Which challenges exactly are missing? Did you check if they're not translatable (due to missing entries in `i18n.json`) or just haven't been translated yet? Because in the latter case, English is just the fallback language for everything.

**Comment by bkimminich** [comment]
Which challenges exactly are missing? Did you check if they're not translatable (due to missing entries in `i18n.json` or just haven't been translated yet? Because in the latter case, English is just the fallback language for everything.

Update: In German all challenge descriptions are translated when I scroll through the list. So, this isn't really a bug, just a lack of volunteer translators for certain languages. Unless I missed something?

**Comment by bkimminich** [comment]
If you want to help translate Juice Shop, check out https://crowdin.com/project/owasp-juice-shop

**Comment by TinTinTheGuy** [comment]
Hi, sorry for late response. all of the challenge when I change to different language, It will not translate at all. I checked for German, France and Japanese, they will not translate the challenge section but instead translate everything that is out side the challenge box.

**Comment by TinTinTheGuy** [comment]
Oh I checked again, it have to be reloaded in order to be translated. But yes, I will try to contribute to the translate. Thanks

**Comment by bkimminich** [comment]
> Oh I checked again, it have to be reloaded in order to be translated. But yes, I will try to contribute to the translate. Thanks

Yes, they're texts in the database and those need a refresh to apply translations. The texts hardcoded in the frontend reload immediately.

😄👍
