### ISSUE TITLE
[🐛] Not a bug but support needed

### ISSUE THREAD

**Issue by FarManCoder003** [juice-shop/juice-shop#2415]
Recently I've completed the juice shop with multiple sources as help. But a single help/solution was nowhere to be found. SO I started to make a solution file for the challenges. Can anyone review if possible?

This is the mentioned GitHub repo

https://github.com/FarManCoder003/Owasp-Juice-Shop

**Comment by J12934** [comment]
Hi, nice to hear that you had a good time. 

Sorry if you have a question please ask it here directly, I'm not digging through a google docs that's linked from a GitHub repo.

Please also let us know what sources you used and what's missing in your view.

**Comment by bkimminich** [comment]
There is a complete set of step by step solutions for all challenges in the official documentation, btw.

https://pwning.owasp-juice.shop/companion-guide/latest/appendix/solutions.html

**Comment by FarManCoder003** [comment]
Ok

**Comment by J12934** [comment]
Allright, feel free to reopen when you have a question
