### ISSUE TITLE
[🐛] Sessions are not isolated

### ISSUE THREAD

**Issue by vbakke** [juice-shop/juice-shop#2418]
# Disclaimer
I have not been able to figure out if this is a configuration issue with https://juice-shop.herokuapp.com/ only. If it applies to all Juice Shops, or only the ones deployed to Heroku.

# :bug: Bug report

## Steps to reproduce
* Open incognito mode and go to: https://juice-shop.herokuapp.com/#/score-board
  *  Notice that there are lots of solved challenges
* Open https://juice-shop.herokuapp.com/#/score-board on a different PC, mobile, etc, that is not connected to you other account
  * Notice that the same challenges have been solved here as well

If you leave the page open for a while, you will get fireworks and congratulations. I presume because someone else solved a challenge.

### Is this a regression?

The herokuapp has been like this for a while now. (A few months at least.) But it was not like this when I first tried https://juice-shop.herokuapp.com. 

_My apologies if this is the wrong issue tracker. I could not find out who was responsible for the https://juice-shop.herokuapp.com_

**Comment by J12934** [comment]
Hi @vbakke 👋

JuiceShop is a single user application. Challenge progress is always shared with anyone who has access to the instance.

So this is by design 😊

We have the MultiJuicer project to host isolated JuiceShop instances for multi user settings. https://github.com/juice-shop/multi-juicer

**Comment by vbakke** [comment]
Ah. I thought the official heroku app had made juice shop multiuserfriendly. Since it is public.

Sorry to raise the false alarm
