### ISSUE TITLE
Contributing to the guidebook (gitbook)?

### ISSUE THREAD

**Issue by jabbrwcky** [juice-shop/juice-shop#242]
Is it possible to contribute to the gitbook (e.g. writing down solutions for problems)?

**Comment by bkimminich** [comment]
Sure thing! The book content lives at https://github.com/bkimminich/pwning-juice-shop! Happy to take PRs! Just let me know what chapters you'd like to contribute to, so I don't work on the same ones simultaneously!

**Comment by bkimminich** [comment]
I'm closing this issue here, if you'd like to help with the book, please send me an email or contact me via [Gitter](https://gitter.im/bkimminich/juice-shop), ok? Thanks!
