### ISSUE TITLE
Order Dashboard: Tracking & rerouting

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#244]
_As an_ information-hungry customer
_I want_ a dashboard showing the status of my current orders
_so that_ I know when to expect a delivery.

**and**

_As a_ customer who is seldom at home
_I want_ to be able to reroute my upcoming deliveries
_so that_ I can send them to a neighbour, friend or post office
_and_ I do not have to stay home and wait for the postman.

This form is supposed to be the staging ground for additional (to be defined) challenges.

**Comment by bkimminich** [comment]
A good template for this feature is the "Recycle" feature which is also without built-in challenges yet.

**Comment by shoebpate1** [comment]
where should the Tracking tab be placed ? because now there is no place on navbar. Any Suggestion ?

**Comment by bkimminich** [comment]
Hm, best we add a _Track your Order_ or _Order Tracking_ menu item and then have a new screen with just a text field _Order No._ and a _Track_ button to kick off the order search?

**Comment by shoebpate1** [comment]
So, Order Tracking menu item will be besides Recycle menu item on navbar ? and is search actually needs to be implemented right now?

**Comment by bkimminich** [comment]
Besides _Recycle_ menu is perfectly fine!

**Comment by shivamluthra** [comment]
@CaptainFreak Are you working on this issue?

**Comment by shoebpate1** [comment]
Nearly completed.

**Comment by shoebpate1** [comment]
addressed in #500 .

**Comment by bkimminich** [comment]
At some point we'll probably have to persist a `orders` entities and I think these are a perfect candidate for the NoSQL MarsDB, because in the end a completed order is nothing but the data printed to the PDF the user receives. This might then be a basis for more NoSQL tiers as proposed in #465.
