### ISSUE TITLE
Christmas challenge always pops a notification, even when solved.

### ISSUE THREAD

**Issue by incognitjoe** [juice-shop/juice-shop#246]
Noticed this while scripting some challenges earlier - no matter how many times you complete "Order the Christmas special offer of 2014.", you'll receive a challenge complete notification for repeating it. 

From the logs, without restarting:
[...]
Executing (default): UPDATE `Challenges` SET `id`=29,`name`='christmasSpecial',`description`='Order the Christmas special offer of 2014.',`difficulty`=2,`solved`=1,`createdAt`='2016-12-19 09:29:47.000 +00:00',`updatedAt`='2016-12-19 09:31:06.000 +00:00' WHERE `id`=29
POST /rest/basket/1/checkout 200 119.949 ms - 47
Solved challenge christmasSpecial (Order the Christmas special offer of 2014.)
[...]
Executing (default): UPDATE `Challenges` SET `id`=29,`name`='christmasSpecial',`description`='Order the Christmas special offer of 2014.',`difficulty`=2,`solved`=1,`createdAt`='2016-12-19 09:29:47.000 +00:00',`updatedAt`='2016-12-19 09:31:25.000 +00:00' WHERE `id`=29
POST /rest/basket/1/checkout 200 117.583 ms - 47
Solved challenge christmasSpecial (Order the Christmas special offer of 2014.)
[...]
Executing (default): UPDATE `Challenges` SET `id`=29,`name`='christmasSpecial',`description`='Order the Christmas special offer of 2014.',`difficulty`=2,`solved`=1,`createdAt`='2016-12-19 09:29:47.000 +00:00',`updatedAt`='2016-12-19 09:33:01.000 +00:00' WHERE `id`=29
POST /rest/basket/1/checkout 200 95.839 ms - 47
Solved challenge christmasSpecial (Order the Christmas special offer of 2014.)

Screenshot:
![image](https://cloud.githubusercontent.com/assets/12628265/21307699/9d781b52-c5ce-11e6-8fc2-8b1c8812916a.png)

Looks like a problem with this line in routes/order.js:
`if (utils.notSolved(challenges.christmasSpecialChallenge && product.id === products.christmasSpecial.id))`

**Comment by bkimminich** [comment]
Yeah, the `)` is totally in the wrong place... :grinning: ... saw you fixed that already in https://github.com/incognitjoe/juice-shop/commit/6828c4d060ff719ff1d5d219087617e763120b75, awesome! Thanks!
