### ISSUE TITLE
 QR Challenge

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#250]
* Add a QR code, e.g. in the Payment section of `/basket`
* Let the QR target take user input
* Add challenge to create a link that has a certain QR code to another (e.g. Bitcoin) address

**Comment by bkimminich** [comment]
So far there are two separate modal dialogs (for Bitcoin and Dash). These should be merged into a generic dialog with title, label, link etc. _supplied externally_ - with the challenge built around that decision.

**Comment by bkimminich** [comment]
Latest implementation of QR codes uses a `QrCode.html` view which takes its `title`, `url`, `data` and `address` from scope variables of the `QrCodeController`. The `BasketController` has three static functions to instanciate the `QrCodeController` and display `QrCode.html` as a modal overlay.

**Comment by agrawalarpit14** [comment]
@bkimminich Can you please elaborate more on the following line: 
`Add challenge to create a link that has a certain QR code to another (e.g. Bitcoin) address`.
and by `Let the QR target take user input` do you mean let the user supply label, link?

**Comment by bkimminich** [comment]
The idea was to craft a URL to the Juice Shop which ends up on some page with a QR code modal dialog open showing an attacker-supplied code and label, yes. I didn't think about how to best check for challenge successfully solved, though.

**Comment by agrawalarpit14** [comment]
@bkimminich IMO It won't make sense to put input fields for user input directly on the payment section(maybe I am wrongly interpreting your suggestion). Can it be something like this:

We make an API which adds a QR code and returns the url(which is supposed to be an admin only API)
Juice shop by mistake forgot to put restriction on it so users are able to call the obvious path(/api/payment/qr) which is letting them to register an extra payment option.

(This is something which actually happened in a company I was interning at recently, they had admin logins leading to a admin dashboard which gave access to APIs which were supposed to be Admin Only, like checking logs, deleting users, etc. But on some of them they forgot to put decorators.)

We can check it simply by checking if the IP is rightly called.

**Comment by agrawalarpit14** [comment]
Although, this would need us to make multiple user types in the app, which presently does not exist if I am right. But, if we make multiple user types, I think it will help us to add many challenges too, revolving around privilege escalation, security through obscurity etc.😆

Please let me know your views on this. Thank You🙂🙂

**Comment by bkimminich** [comment]
QR code popups for crypto currencies will be removed from all views with 8.6.0 release making them kind of unattractive for attacks and therefore challenges.
