### ISSUE TITLE
"Get rid of all 5-star customer feedback"

### ISSUE THREAD

**Issue by Aman-1412** [juice-shop/juice-shop#255]
Really loving juice shop as a beginner!!

After i completed this challenge,
Get rid of all 5-star customer feedback

It started spamming me:
 **_You successfully solved the challenge : Get rid of all 5-star customer feedback
 You successfully solved the challenge : Get rid of all 5-star customer feedback
 You successfully solved the challenge : Get rid of all 5-star customer feedback
 You successfully solved the challenge : Get rid of all 5-star customer feedback_
..**
.
I had to refresh the page to stop it. Don't think this is intended behaviour. Please look into it. Thanks :)

**Comment by bkimminich** [comment]
Sounds familiar (see #246), will look into that! Thanks for reporting!

**Comment by bkimminich** [comment]
@Aman-1412, I tried to reproduce this on the current v2.20 (`master` branch) and on the upcoming version from `develop` - and I only get the message once. I tried deleting the Feedback via UI and also via API but both ways worked fine for me.

What version did you use? If <v2.20, please update. Else, please tell me how to reproduce this effect.

**Comment by Aman-1412** [comment]
I am using v2.20 on master branch. 
Yeah even i couldn't reproduce it.  I tried to solve the challenge again to try and reproduce it but i only got this message once. 

I think i had the ZAP's fuzzer running (dirbuster) when i first faced this. Maybe the fuzzer caused this issue. When I get back home I'll try to do it again. 

A side issue: i stopped the juice shop and ran it again to try and reproduce this issue. When i couldn't reproduce it, i wanted to restore my previous progress but i could not.. I had saved the progress in the previous session.. Please tell me where did i mess up(or should i create another issue with this? Not a big problem. I just liked  to see more green than red on my score-board)

**Comment by bkimminich** [comment]
If several requests were in progress before the application realized that the Feedback challenge was solved, each request would trigger that solution message. Basically ZAP overpowered/outran the async Javascript backend... 😀

About the session restore: Did you clear cookies in between? There is a cookie called `continueCode` for that purpose, so if it's deleted you cannot restore.

**Comment by Aman-1412** [comment]
Okay, so it was zap after all. Thanks

I did not explicitly clear cookies but i did close that tab and opened a new tab in chrome..

**Comment by bkimminich** [comment]
That should *not* make the cookie go away. It's set to 30 days expiration. If that problem persists and you are sure that cookies are not deleted (or prevented in the first place), please open a separate ticket for that one, ok?

I'm closing this one as _"impossible to fix because ZAP is just too much of a tool to handle for the poor little Juice Shop"_.
