### ISSUE TITLE
Add DockerCloud as run option

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#257]
Investigate how DefectDojo implemented their "Deploy to Docker Cloud" button to create individual instance on https://cloud.docker.com.

Note: This is not supposed to replace the existing Heroku deployment button, just add another possibility for users to run the app.

**Comment by bkimminich** [comment]
Reference: https://github.com/aaronweaver/docker-DefectDojo

**Comment by abhibundela** [comment]
Hi, bkimminich assign this issue to me.

**Comment by bkimminich** [comment]
Hi @abhishekbundela, consider yourself assigned! 👍

**Comment by bkimminich** [comment]
![image](https://cloud.githubusercontent.com/assets/3531020/23344065/258b2920-fc76-11e6-81b3-3c4ab631cb0b.png)

**Comment by bkimminich** [comment]
@abhishekbundela, would a predefined `docker-cloud.yml` make that wizard go away? I guess without that it doesn't make any sense as an option, because it's basically "Click here and you're on your own!" ... 😒

**Comment by bkimminich** [comment]
Just added a very simple `docker-cloud.yml` but it's not recognized when clicking the button. And the whole manual Stack setup process is quite horrible: I got errors and just by chance realized I would have had to create a node first... Weird UX...

@abhishekbundela If you know how to make this a more smooth experience I think I'm taking this out of the README again to not confuse people. Or: We need a good step-by-step instruction list, because the wizard on Dockercloud doesn't really help.

**Comment by abhibundela** [comment]
@bkimminich Sorry for that, i thought you will create docker-cloud.yml.

**Comment by bkimminich** [comment]
I played with Docker Cloud a bit, and decided to drop the option. It is _way more complicated_ than what Heroku is offering with no real benefit. This might become another story when deploying a prepared CTF environment with multiple team instances and a CTFd in the middle, but for now this will be dropped.
