### ISSUE TITLE
Name field of challenge

### ISSUE THREAD

**Issue by tghosth** [juice-shop/juice-shop#264]
Does this need to be camelCase? Could it be made prettier for humans? Alternatively, could a prettier version be created for use in [CTF mode](https://github.com/bkimminich/juice-shop/issues/166).

**Comment by bkimminich** [comment]
No, it doesn't need to be CamelCase. This could easily be renamed into something more pleasing to read.

**Comment by tghosth** [comment]
@bkimminich Do you want me to submit a PR with prettier names?

**Comment by bkimminich** [comment]
I already stated pulling the names apart and refactored the test cases along the way. Will commit shortly, but thanks for the offer!

**Comment by bkimminich** [comment]
@tghosth https://github.com/bkimminich/juice-shop/releases/tag/v2.21.2 will have human- and CTF-friendly `name` per challenge.
