### ISSUE TITLE
Support Login challenge (SPOILER ALERT)

### ISSUE THREAD

**Issue by tghosth** [juice-shop/juice-shop#265]
SPOILER ALERT
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
*
I cannot seem to make this work. I have KeePass 2.35 installed and I have freshly downloaded both files but I still get an error.

Opening file:
![image](https://cloud.githubusercontent.com/assets/13623828/22637783/b100ec2c-ec4c-11e6-968d-099dea6cd310.png)

Error received:
![image](https://cloud.githubusercontent.com/assets/13623828/22637957/c6197948-ec4d-11e6-8e48-60661e758bc4.png)

KeePass version:
![image](https://cloud.githubusercontent.com/assets/13623828/22637909/71b8541e-ec4d-11e6-94e4-7bf774d04bd7.png)

File hashes:
![image](https://cloud.githubusercontent.com/assets/13623828/22637934/a59abb1e-ec4d-11e6-9a15-80be798bd4f6.png)
![image](https://cloud.githubusercontent.com/assets/13623828/22637941/b2e12aa6-ec4d-11e6-9267-e2a3ea1ada42.png)

**Comment by bkimminich** [comment]
Just tried myself with KeePass 2.35 and the files from `develop` branch - it worked. 

You used the SVG, not the PNG, right?

**Comment by tghosth** [comment]
I just double checked this and it is still not working for me. Are you able to check that the screens and checksums above match what you are using? As per the above I am using the SVG.

I have tried on 2 separate Windows 8.1 machines plus a Windows 10 machine and it doesn't work on any of them.

Interestingly, when using the SVG it seems to think for a long time before deciding it doesn't work whereas with other files it says so immediately...

**Comment by bkimminich** [comment]
Okay, here are my SHA256 file hashes (identical for `master` and `develop`):

* KeePass file: `07 49 42 73 26 7e e5 fc c9 fa 63 71 c2 e0 c6 42 65 42 e7 94 87 4a bf 0b c7 93 27 86 99 f9 d7 1b`
* SVG logo: `c4 db 55 78 be 9a dd 2e 77 bc 78 04 8d 03 92 8a 8a b2 56 d5 8f fb 79 31 34 fd c3 5d 24 df b7 07`

Seems that the logo is not identical to yours... Strange... Can you please attach your logo file here so I can diff it with the one from the repo?

**Comment by tghosth** [comment]
Remove the .PDF extension (github won't accept upload of SVG files)

[JuiceShop_Logo.svg.PDF](https://github.com/bkimminich/juice-shop/files/757885/JuiceShop_Logo.svg.PDF)

See also this:
![image](https://cloud.githubusercontent.com/assets/13623828/22694667/ba2845c0-ed50-11e6-8b78-e73bd1df5d9c.png)

**Comment by bkimminich** [comment]
Your file is definitely _smaller_ than mine, so something happened to it somewhere on the way...
![image](https://cloud.githubusercontent.com/assets/3531020/22694956/5fae41f0-ed49-11e6-90e3-8add6deec6bb.png)

**Comment by bkimminich** [comment]
That's what I suspected... Okay, probably I have to change the challenge to use a binary file...

![image](https://cloud.githubusercontent.com/assets/3531020/22695103/d744421e-ed49-11e6-8334-bbea71b28394.png)
