### ISSUE TITLE
Include challenge name somewhere in the UI

### ISSUE THREAD

**Issue by tghosth** [juice-shop/juice-shop#268]
Would it be possible to include the challenge name either alongside the flag in the notification or alongside  the challenge description in the scoreboard? It would help a lot for CTF mode.

**Comment by bkimminich** [comment]
Sure. Could be added to both the score board table (new 1st column?) and the notifications (`name` as headline? Or just `name`: `description`?).

**Comment by tghosth** [comment]
Either sounds great.

**Comment by bkimminich** [comment]
![image](https://cloud.githubusercontent.com/assets/3531020/22805151/8593c50a-ef1c-11e6-8ae0-eb7a52534e2e.png)
