### ISSUE TITLE
Migrate to Angular 1.6

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#294]
## Known tasks
* `$http` will use Promise API, impacts all services
* `$http` will return `response` wrapping previous `data` object, leading to ugly `response.data.data` or need to resolve promises inside service and "re-promise" as expected by current controllers implementation

## Docs
* https://toddmotto.com/angular-1-6-is-here
* https://docs.angularjs.org/guide/migration

Note: This migration step makes only sense to implement before #165.

**Comment by shivamluthra** [comment]
@bkimminich Can you assign me to this one? Migrating to v1.6, for now, will give an idea about the app structure and will be easy to migrate it to v5.x later.

**Comment by bkimminich** [comment]
Sure thing, knock yourself out! I suggest you regularly rebase your fork against `develop`, that way no crazy merge conflicts should pile up.

**Comment by shivamluthra** [comment]
@bkimminich Yeah cool! And I see that you added some commits to this issue regarding 'preparation for migration to v1.6' and changed the promises in controllers. Would my task be to change rest of them i.e. in services only or anything else is expected too?

**Comment by bkimminich** [comment]
Well, I guess all tests need to pass and then it should be fine. I honestly don't know how much needs to be touched to migrate from 1.5 to 1.6 ... 🙈

**Comment by shivamluthra** [comment]
@bkimminich Okay, I'll take care of whatever needs to be changed and push it asap. For now, I'll be targeting controllers, services, and juice-shop.min.js file along with unit tests.

**Comment by bkimminich** [comment]
Sounds good! JFYI, `juice-shop.min.js` is generated from the controllers, services and templates.

**Comment by shivamluthra** [comment]
I suppose this issue should get closed by now so that no new contributor starts working on it just by seeing master branch docs :sweat_smile:
