### ISSUE TITLE
Feature: Add refresh button to score-board.

### ISSUE THREAD

**Issue by thefishermanhacker** [juice-shop/juice-shop#307]
It will be nice to have refresh button on the score-board.
Today, after I solve challenge I need to refresh the whole page.

**Comment by bkimminich** [comment]
Hm, can you give some examples for which challenges it does not refresh? Do you have the score board open in a separate tab? Do you see the green notification immediately when solving a challenge? 

It should not be necessary to `F5`-refresh the browser to get a score board update. The Angular databinding should do that automatically.

**Comment by thefishermanhacker** [comment]
I have separate tabs, chrome Ubuntu.
 I solved the redirects challenge and it didn't change the status from unresolve to resolved.
I see the green message for every solved challenge(s).

**Comment by bkimminich** [comment]
Ok, the sepeate tab is why you need to refresh because it doesn't recognize anything changed. Having a **refresh button on the score board** would be good for that case, agreed. Might even be possible to extend it with an **auto-refresh in case a _challenge solved_-notification arrives**.

**Comment by J12934** [comment]
I had the same issue when i first used the juice-shop. 
I accessed the scoreboard, got the notification, but the table was still suggesting that the challenge was unsolved.

I implemented the auto sync via websocket you suggested to avoid this sort of problem for future hackers 😉. 

I hope this will solve the problem.

**Comment by bkimminich** [comment]
Released with 3.1.0.
