### ISSUE TITLE
Issue achievement badges

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#308]
## Story
As a gamer
I want to receive badges for solving challenges
So that I can show off what an awesome hacker I am.

## Solutions ideas
* integrate with <http://openbadges.org>, e.g. via Badgr, Mozilla Backpack etc.
* create a GitHub org per badge and invite achievers into that org (like Coderwall did it in the past)

> Please post your thoughts and ideas in the comments below!

**Comment by bkimminich** [comment]
Some possible badges examples:
- XSS Master: Solve all cross site scripting challenges
- SQLi Ninja: Solve all SQL injection challenges
- File Sleuth: Access all forgotten content
- ...
- **Juice Shopper: Solve all challenges of the OWASP Juice Shop**

**Comment by J12934** [comment]
**I think this is a really cool idea!**

And those Mozilla Badges look really neat 😃

The Github Orgs Idea would be cool as the would be a lot more prominent. 
But the "GitHub Org Switcher" would probably get cluttered when you would have multiple of these kind of badges. Or am i overthinking this? 😅

**Comment by bkimminich** [comment]
> But the "GitHub Org Switcher" would probably get cluttered

This was exactly the main reason why I left the Coderwall orgs at some point... 😁

**Comment by bkimminich** [comment]
OWASP will move to Discourse at some point, and they offer badges. These would probably first be used for broader scoped badges such as "Project Leader", "Co-Project Leader" or "Top Contributor". Would have to be checked if they can also be used for "in-project"-achievement badges like proposed above.

(FYI/CC @mtesauro)

**Comment by bkimminich** [comment]
Juice Shop (or more broadly: OWASP) could issue badges for contributions that build on top of each other, e.g. using Bronze/Silver/Gold levels. This could be done digitally or virtually with stickers onto which smaller stickers are placed representing the corresponding level! 💡

**Comment by bkimminich** [comment]
For now dropped due to lack of relevance, resources and time.
