### ISSUE TITLE
Replace product photos

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#315]
Instead of the currently used photos all products should be depicted either by some drawing or a self-taken photo to avoid any possibility of legal issues.

## Products where *new images* are required
* [x] Apple Juice (1000ml)
* [x] Orange Juice (1000ml)
* [x] Eggfruit Juice (500ml)
* [x] Raspberry Juice (1000ml)
* [x] Lemon Juice (500ml)
* [x] Banana Juice (1000ml)
* [x] Quince Juice (1000ml)
* [x] Strawberry Juice (500ml)
* [x] Carrot Juice (1000ml)
* [x] Green Smoothie
* [x] Woodruff Syrup "Forest Master X-Treme"
* [x] Apple Pomace
* [x] Fruit Press
* [ ] Christmas Super-Surprise-Box (2014 Edition)
* [x] ~~OWASP SSL Advanced Forensic Tool (O-Saft)~~ _(will get same image as Orange Juice)_ 
* [x] Melon Bike _(Might be subtitled as "Comeback-Product" of the Year)_

## Products where images best *remain* unchanged
* OWASP Juice Shop T-Shirt
* OWASP Juice Shop CTF Girlie-Shirt
* OWASP Juice Shop Sticker (2015/2016 design)
* OWASP Juice Shop Iron-Ons (16pcs)
* OWASP Juice Shop Magnets (16pcs)
* OWASP Juice Shop Sticker Page
* OWASP Juice Shop Sticker Single
* OWASP Juice Shop Temporay Tattoos (16pcs)
* OWASP Juice Shop Mug
* OWASP Juice Shop Hoodie
* OWASP Juice Shop Logo (3D-printed)
* Juice Shop Artwork
* Global OWASP WASPY Award 2017 Nomnation
* OWASP Juice Shop Sweden Tour 2017 Sticker Sheet (Special Edition)
* Pwning OWASP Juice Shop

## Products planned *to be removed* with v7.0.0
* Enhanced White Rafford`s Decoction
* Jawa Script T-Shirt
* OWASP Node.js Goat

**Comment by bkimminich** [comment]
Might be addressed during [Google Summer of Code 2018](https://www.owasp.org/index.php/GSOC2018_Ideas#UI.2FGraphics_Design_Update).

**Comment by madhurw7** [comment]
@bkimminich How about some illustrations for the product pictures?

**Comment by bkimminich** [comment]
It totally can be illustrations, no need for photos imo. The product inventory is also not set in stone. Some products can remain as is, others must for challenge reasons. These are all the Juice Shop-related merchandise items (shirt, stickers, 3d prints, mug etc.) - The others can be different, but should a) have a juice- or fruit-related theme somehow and b) some should be not serious or outright funny.

**Comment by bkimminich** [comment]
Also, having the products "Fruit Press" and "Pomace" (=juice production leftovers) are mandatory for the _Recycle_ use case to make sense. All others can be either kept with just a new image/illustration or be replaced with something even better. Also if more products end up in the inventory than today, that'd be a cool optional goodie.

**Comment by bkimminich** [comment]
@madhurw7 is on it...
![image](https://user-images.githubusercontent.com/3531020/36636046-c6f87e14-19be-11e8-8808-4a5e30270566.png)

(To avoid duplicate work/unncessary competition corresponding aspect of https://www.owasp.org/index.php/GSOC2018_Ideas#UI.2FGraphics_Design_Update was marked as _in progress_)

**Comment by shoebpate1** [comment]
Wow. Nice picture @madhurw7 :1st_place_medal:

**Comment by madhurw7** [comment]
@CaptainFreak Thank You! 😄

**Comment by bkimminich** [comment]
@madhurw7, I updated the issue description adding the list of product photos I would like to see replaced. I also listed those products which should not get a new image, mostly the merchandise of the project or other OWASP related products. Of course the artwork of my daughter can also not be replaced. I'm totally open for new products (more juices, more fun stuff, ...) as well!

**Comment by madhurw7** [comment]
@bkimminich I was about you for something like this, which would let me know which ones I need to make. I am finished with Orange, Apple, Lemon, Banana, Green Smoothie and Melon Bike. Will be sending the pull request 😄 Sad to see the melon bike go though 😅

**Comment by bkimminich** [comment]
No way, Melon bike will come back [now](https://github.com/bkimminich/juice-shop/commit/f789d8593190f5b5954e52723925a8fc5fb94453)! :+1:

**Comment by madhurw7** [comment]
@bkimminich I am almost done with all the products that are listed here. The ones left are wood syrup and Fruit Press. I wanted to ask if we could skip the Fruit Press? The thing is it has some very small parts and I don't personally think that it would look better in the illustration form.

**Comment by bkimminich** [comment]
I don't think the fruit press really needs to be very detailed. If you google for "fruit press" you'll find also different models, some rather simple some more complex. I'm totally fine if you pick one of the "cheap" versions to illustrate. I could then adapt the virtual product price accordingly, so it makes sense.

Not having the press altogether would be a pitty, because it - together with the pomace - is one of the most iconic items and crucial for the _Recycle_ page of the application:

![image](https://user-images.githubusercontent.com/3531020/36901509-c2b37666-1e27-11e8-8352-d9fc8b3c2aa2.png)

**Comment by madhurw7** [comment]
I din't mean to ask to remove the product, I was asking about not replacing the picture 😅 But the different Fruit Press Model is a nice idea, I think I can work with that 😄
