### ISSUE TITLE
Travis-CI build stages

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#319]
## Introduce https://docs.travis-ci.com/user/build-stages

* end-to-end tests should run *only* if `npm test`  has *passed* for all supported node.js versions
* deployment should still only trigger for one chosen node.js version if unit/int tests and e2e tests have *passed*

**Comment by yindia** [comment]
@bkimminich it run for 6 & 8 . Check .travis.yml
`node_js:
- 6  # recommended version
- 8`

**Comment by bkimminich** [comment]
With the `&&`-concatenated `script` this has become kind of unnecessary.
