### ISSUE TITLE
Ubuntu Install from Source - PhantomJS issue

### ISSUE THREAD

**Issue by cynicXer** [juice-shop/juice-shop#327]
When attempting to install in Ubuntu 16.04 LTS using the instructions at https://github.com/bkimminich/juice-shop#from-sources, I get an error when running npm install.

`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm ERR! Linux 4.4.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cynicxer/juice-shop/npm-debug.log`

**Comment by bkimminich** [comment]
Is there any more being logged? The warnings (line 1+2) do not matter, this is just an optional depdency only installed on Macs and not the root of the problem you encounter. Best would be to clear `npm-debug.log`, retry and then attach the fresh logfile to this ticket. Thanks!

**Comment by bkimminich** [comment]
Ah, just saw that `phantomjs-prebuilt` seems to be the culprit...

**Comment by bkimminich** [comment]
Please check if https://www.npmjs.com/package/phantomjs-prebuilt#troubleshooting can solve your issue. It has a section on `spawn ENOENT` issues at least.

If you solved it and post the resolution here, I'll gladly add it to our `TROUBLESHOOTING.md`.

**Comment by cynicXer** [comment]
It looks like in Ubuntu 16.04 the "node" command is part of the nodejs-legacy package.  I got past the phantomJS issue by adding a symlink: /usr/bin/node -> /usr/bin/nodejs.

However, running npm start seems to bump into a similar issue.  

cynicxer@pc:~/juice-shop$ npm start

> juice-shop@3.2.0 start /home/cynicxer/juice-shop
> node app

module.js:328
    throw err;
    ^

Error: Cannot find module '/home/cynicxer/juice-shop/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/cynicxer/juice-shop/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

npm ERR! Linux 4.4.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! juice-shop@3.2.0 start: `node app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the juice-shop@3.2.0 start script 'node app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the juice-shop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs juice-shop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls juice-shop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cynicxer/juice-shop/npm-debug.log


If I run nodejs app instead of npm start, the app tries to start but still can't find the sqlite module.

**Comment by cynicXer** [comment]
Interestingly, the packaged distribution for node4 works.

**Comment by bkimminich** [comment]
Hm, I heard complaints about node from Linux users before, but I see no way to fix this in the Juice Shop itself. Maybe by adding a link to some good node-installation manual for Linux? Or a blog post about the issues with it?
