### ISSUE TITLE
Angular Template Injection

### ISSUE THREAD

**Issue by nunoloureiro** [juice-shop/juice-shop#329]
Angular specific vulnerability:
XSS without HTML: Client-Side Template Injection with AngularJS

http://blog.portswigger.net/2016/01/xss-without-html-client-side-template.html

**Comment by alejandrosaenz117** [comment]
Is this issue open for contribution?

**Comment by bkimminich** [comment]
I'm not sure if this is still an issue in Angular7. Feel free to investigate and post some idea for implementation here.

**Comment by alejandrosaenz117** [comment]
Very true, I should've checked the version to begin with.  It's the thought that counts.
