### ISSUE TITLE
3D printer model(s) of Juice Shop logo

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#331]
> Just because **why not?**!

## Ideas
* keychain of flat logo
* keychain of threedimensional juice box with leak and puddle (idea by @viktorlindstrm)
* Paperweight/statue sized version of 3d-keychain model
* Vase, e.g. with backside of the top with cap being open (idea by @TiffOWASPCM)

**Comment by ViktorLindstrm** [comment]
A first try:
http://imgur.com/a/GeHQP

**Comment by bkimminich** [comment]
Ok, so here's my idea for this becoming a new challenge actually:
* [x] @ViktorLindstrm PRs the 3D model file(s) into `app/public/images/products`
* [x] Add totally overpriced product to inventory: _Official Juice Shop Logo (3d-printed)_...
* [x] ...with the product image containing some meta information that gives away the original 3D-model filename...
* [x] ...which needs to be requested in order to trigger the challenge _**Retrieve Blueprint**: Deprive the shop of earnings by downloading the blueprint for one of its products._

To keep this challenge working in customized environments the following is needed:
* [x] The product is tagged with the new `fileForRetrieveBlueprintChallenge` in `default.yml` where a filename or URL to the "blueprint" is given. If a URL is given that file is downloaded and put into the folder `app/public/images/products`
* [x] The product image of the must somehow give away the original blueprint name. Possible ways to do this
  * use the same filename just with different type or maybe some suffix in between, e.g. `draft` or `v1`
  * adding metadata (e.g. via [piexifjs](https://github.com/hMatoba/piexifjs)) that reveals important clues

**Comment by bkimminich** [comment]
Thanks, @ViktorLindstrm! I've left a hint for the challenge by adding your name to the _authors_ meta-tag and OpenSCAD as _camera vendor_ on the product image. Nice challenge overall!

**Comment by bkimminich** [comment]
Hi @ViktorLindstrm, is the smaller thingie you made a distinct model file or just downscaled when printed?

**Comment by ViktorLindstrm** [comment]
It is just downscaled, (actually both of them are, but in different scales). But fully possible to create distinct model files instead.
