### ISSUE TITLE
Recycling invoice tracking for accounting users

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#334]
🔧 **TODO:** Add description

(Follow-up feature of #243)

**Comment by agrawalarpit14** [comment]
Hi @bkimminich Can you please elaborate on the issue. Is it that they are able to see all the invoices in the juice shop or are they allowed to do some operation on it?

**Comment by agrawalarpit14** [comment]
Hi @bkimminich 
Do you mean the following features should be present:
- People should get an invoice when they submit a recycle request.
- Accounting users of the juice shop should be able to see all such invoices(adding up the is_accounting field in the jwt token).
Please let me know. Thank You!!!

**Comment by supra08** [comment]
@bkimminich, I would like to work on the implementation of invoice and further features on this ticket. I believe, the invoice and any new feature here can help implant new challenges.

**Comment by bkimminich** [comment]
Discussion about possible feature details are welcome, but this feature might be better as part of a potential "Feature Pack" project in GSoC. I'll create a corresponding project or milestone to block issues like this for that purpose.
