### ISSUE TITLE
Introduce user roles to JWT authorization

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#336]
* Add user roles, e.g. _admin_ and _accounting_ (see #334)
* Restrict access to certain (backend) routes using these roles instead of `defaultSecret`
* Increase corresponding challenge difficulties slightly
* Add a Mass Assignment challenge using one of these roles (see #256)

**Comment by agrawalarpit14** [comment]
@bkimminich This is actually what I have been looking forward to. I never read it after seeing the ready tag. Can I take up the issue and resolve in the following manner? Users table has properties `is_admin` and `is_accounting`. When adding JWT I supply these properties and on the server I check the flags while decoding? Further, to satisfy the second point you have mentioned, can I form few APIs that are supposed to be admin only and build challenge around it?

**Comment by agrawalarpit14** [comment]
I will comment actual scenarios for challenges after little bit of research. Please let me know if you have some expectations in mind with the corresponding challenges?

**Comment by bkimminich** [comment]
`isAdmin` already exists in `Users` table, and maybe we start by just adding that to the JWT properly and enforcing it to view `/#/administration`? Then the corresponding challenge should become :star::star: instead of :star: and we'll continue from there with `isAccounting` (for which we currently do not have a dedicated screen yet - #334)?

**Comment by agrawalarpit14** [comment]
Sure, I will start with that and later we will implement `isAccounting`.😆

**Comment by zachfedor** [comment]
After this change, the solution in the [appendix](https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/appendix/solutions.html) needs updated.

**Comment by bkimminich** [comment]
You're right, I added a TODO into the solution for the _Admin Section_ challenge already.
