### ISSUE TITLE
Configure CTF key via enviroment variable

### ISSUE THREAD

**Issue by achimgrimm** [juice-shop/juice-shop#346]
Currently the CTF key will always be used from the key file `ctf.key`. 
While running the shop as a docker container, the file can not be changed. 

So there should be the option to set the key via a enviroment variable. This can be passed into the docker container on runtime.

**Comment by bkimminich** [comment]
Actually you can mount the file to a file outside the container. See https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-file-as-a-data-volume. Please try that, probably we don't need any implementation for this issue then.

**Comment by bkimminich** [comment]
If it works like that it should go into the CTF and customization documentation.

**Comment by achimgrimm** [comment]
I think this was my suggested solution before:
`docker run -d -p 3000:3000 -e "NODE_ENV=ctf" -v /tmp/mySecretKey.key:/juice-shop/ctf.key --name juice-shop bkimminich/juice-shop`

I already complted the pull request. So please feel free to merge or decline the PR.

**Comment by bkimminich** [comment]
I installed your exact node version (`4.2.6`) on my Windows 10 machine, deleted `node_modules` and `app/bower_components` and ran `npm install`.

It took a while, but ran through only with warnings, no errors. Subsequent `npm start` worked just fine.

So, I'm pretty sure it's something with your combination of Linux & Node.
