### ISSUE TITLE
Standard Issue

### ISSUE THREAD

**Issue by J12934** [juice-shop/juice-shop#349]
Hi,
i am currently having problems with running Standard on the JuiceShop Project. It is currently failing for me even on the latest commit from the master branch. I tried reinstalling it standard but i didn't  change anything.

![image](https://user-images.githubusercontent.com/13718901/27256346-f5992c92-53b1-11e7-8553-895a993f29ec.png)

Do you have an Idea why this is happening?

**Comment by bkimminich** [comment]
Juice Shop currently has a dependency on standard 8.6 and there it complies with all rules. Migration to 10.0 is slightly overdue.

To install the right version locally, you need to run `npm i - g standard@8.6`.

**Comment by J12934** [comment]
Ah ok.
Thank you!

**Comment by bkimminich** [comment]
I just updated to `standard@10` and changed the syntax in the specs it complained about.

**Comment by J12934** [comment]
Nice thank you 😉
