### ISSUE TITLE
Add Alexa Skill webservice endpoint

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#356]
1. https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/getting-started-guide
2. https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/overviews/understanding-custom-skills
3. https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/developing-an-alexa-skill-as-a-web-service

**Comment by bkimminich** [comment]
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs

**Comment by bkimminich** [comment]
### Coupon code skill

##### Trigger phrases
_"Alexa, what is the (current|latest) Juice Shop (monthly) coupon (code)?"_
_"Alexa, tell me the (current|latest) Juice Shop (monthly) coupon (code)."_
_"Alexa, give me the (current|latest) Juice Shop (monthly) coupon (code)."_
_"Alexa, give me a `[number]` percent Juice Shop coupon (code)."_ (accepts `number` from 1-20)

##### Implementation
Retrieves coupon code for `[number]%` or `10%` per default for the current month

**Comment by agrawalarpit14** [comment]
Hi @bkimminich ! I was reading through the resources you have pointed. I had this query that amazon skills kit will support web service only over HTTPS. So, are we planning to host it somewhere?(a person installing juice shop locally would not be having a SSL/TLS certificate). And have you thought of any invocation name? I guess the `trigger phases` you have suggested will change accordingly.

According to the docs:
A user would say something like:

User: Alexa, _get high tide for Seattle_ from **Tide Pooler**
(In this example, the italicized words form the sample utterance you have defined, while the invocation name is shown in bold).

Alternatively, it can be called in multiple commands:
User: Alexa, Open **Tide Pooler**
Alexa: ....
User: Alexa, _Get high tide for Seattle_

**Comment by bkimminich** [comment]
@agrawalarpit14, I started working on this one, but the Juice Shop application will not serve the endpoint for that skill. It will be a Lambda function that will eventually retrieve coupon codes from the same Lambda that I wrote for automatic monthly publishing of a coupon on Twitter and (:new:) Reddit.

**Comment by agrawalarpit14** [comment]
@bkimminich Yes, I understood the way you are implementing it. I guess I got a bit late in asking this.😅. I did little bit research on this, so ping me if you think I will be able to help.
