### ISSUE TITLE
Allow more individual theming

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#379]
At the moment only official Bootswatch themes can be configured in the customization YAML. For companies with very individual corporate colors it would be nice to have some more possibilities to customize the theme.

Supplying a URL to a custom Bootswatch CSS might be the easiest option.

**Comment by wurstbrot** [comment]
I could do this during the OWASP Summit.

**Comment by bkimminich** [comment]
Outdated by new theming mechanism of Angular frontend coming with v8.0.0
