### ISSUE TITLE
Docker ARM/RPi image

### ISSUE THREAD

**Issue by battletux** [juice-shop/juice-shop#380]
Would it be possible to provide an arm version of the docker container?

I have managed to get juice shop running on a raspberry pi 3 via source but it would be great if it could run via docker instead. I've not made a docker container before so I'm not 100% sure on how simple it is to do.

Docker would make it simpler and quicker to roll out a small scale ctf on cheap raspberry pis.

**Comment by bkimminich** [comment]
Using https://hub.docker.com/r/hypriot/rpi-node/ as a base image might result exactly in what you want. I can define such an image via a distinct dockerfile and would let you know when it's ready for testing.

**Comment by bkimminich** [comment]
Ok, doesn't work out of the box as it seems...

https://hub.docker.com/r/bkimminich/juice-shop/builds/bvemtq7hmwxbgldh8qnachg/

**Comment by bkimminich** [comment]
I cannot seriously drive this issue due to lack of RPi experience especially when it comes to Docker. If someone wants to pick this up, please let me know!

**Comment by battletux** [comment]
I've been playing around with this and managed to get it to work.

I can not say that this is going to be perfect or secure (it's my first time building a docker container from a Dockerfile).

My Dockerfile for this is as follows:
```
# OWASP Juice Shop - An intentionally insecure JavaScript Web Application
# Arm docker container 
FROM            resin/rpi-raspbian

RUN sudo apt update && sudo apt upgrade -y && cd /root/ &&\
 sudo apt install apt-utils -y && sudo apt install git python wget build-essential libfontconfig1-dev sqlite3 -y && sudo git clone https://github.com/piksel/phantomjs-raspberrypi.git && \
 ls -alh && sudo chmod +x phantomjs-raspberrypi/bin/phantomjs && sudo chmod 775 phantomjs-raspberrypi/bin/phantomjs && sudo ln -s phantomjs-raspberrypi/bin/phantomjs /usr/bin/ && \
sudo wget https://nodejs.org/dist/latest-v6.x/node-v6.11.3-linux-armv6l.tar.gz && sudo tar -xvf node-v6.11.3-linux-armv6l.tar.gz && cd ~/node-v6.11.3-linux-armv6l && sudo cp -R * /usr/local/ && cd /root \
&& git clone https://github.com/bkimminich/juice-shop.git && cd juice-shop && npm install --production --unsafe-perm

EXPOSE  3000
WORKDIR /root/juice-shop
CMD ["npm", "start"]
```


I had to build it with trial and error. Phantomjs is not available as an offical module on Raspbian so I had to use the one provided by Piksel (`https://github.com/piksel/phantomjs-raspberrypi`). I then needed to ensure the required packages were installed followed by installing nodejs and then juice-shop.

I built this on my raspberry Pi 3 and then ran it  successfully on the same pi.

If you know the commands to upload this container to my Docker hub account I can do that and provide the link to it.

**Comment by battletux** [comment]
Ah figured it out. Just pushing it to my hub account now, once complete it should be available at arclight/juice-shop_arm

Once it's uploaded I'm going to figure out how to set up a swarm and have it run on a few devices at once.

**Comment by bkimminich** [comment]
Cool! Why have phantom-js at all? It is not in the prod-dependencies, just used in test phase, which is not supposed to run in Docker container.

**Comment by bkimminich** [comment]
If you want to have it automatically update the image with every change in the application, feel free to submit your Dockerfile as a PR!

**Comment by battletux** [comment]
I couldn't get it to run without it. When trying to install on the pi 3 npm install would fail and it seemed phantomjs was the cause.

I'll clone the repo and do a pull request later this evening when I get home.

**Comment by bkimminich** [comment]
Awesome, thank you! I can look into the dependency issue with phantom-js afterwards. Might be coming from the `peerDependency` in the config.

**Comment by bkimminich** [comment]
@battletux I just removed the `peerDependency` on `phantom-js-prebuilt` from `package.json`. I don't even remember why it was there in the first place, so I'll let Travis-CI decide if it's actually required... :smirk:

https://travis-ci.org/bkimminich/juice-shop/builds/275117274

**Comment by bkimminich** [comment]
Another thought: Is it cleaner to have this alternative base image as a tag like `bkimminich/juice-shop:arm` or would a separate repository and therefore individual image like `bkimminich/arm_juice-shop` be the better design? What do the Docker experts say? (I'm looking at you, @wurstbrot :grinning:)

If the latter, then actually `arclight/juice-shop_arm` that @battletux already created could just remain as it is, it would just need to make sure its getting updated regularly.

**Comment by bkimminich** [comment]
@battletux I copied & pasted your Dockerfile into `/Dockerfile_ARM.df` but it still fails during auto-build on Dockerhub: https://hub.docker.com/r/bkimminich/juice-shop/builds/b8ieeadbjeueij2w9ym2mq9. As `phantom-js` should be out of the equasion, I also tried one build before (https://hub.docker.com/r/bkimminich/juice-shop/builds/bevudrbo5kfpwaku6bsthgg/) without all the `phantom-js` installation pieces, but that also failed:

```
Build failed: The command '/bin/sh -c sudo apt update && sudo apt upgrade -y && cd /root/ && sudo apt install apt-utils -y && sudo apt install git python wget build-essential libfontconfig1-dev sqlite3 -y && sudo wget https://nodejs.org/dist/latest-v6.x/node-v6.11.3-linux-armv6l.tar.gz && sudo tar -xvf node-v6.11.3-linux-armv6l.tar.gz && cd ~/node-v6.11.3-linux-armv6l && sudo cp -R * /usr/local/ && cd /root && git clone https://github.com/bkimminich/juice-shop.git && cd juice-shop && npm install --production --unsafe-perm' returned a non-zero code: 1
```

**Comment by bkimminich** [comment]
Ah, silly me, as the base image expects an ARM processor it will probably never successfully auto-build on DockerHub with their x86 infrastructure, right? 🥇

So, I'll happily close this as solved and refer to https://hub.docker.com/r/arclight/juice-shop_arm/ as the resolution. Will put a link to it into the README of the Docker-setup section as well.

**Comment by battletux** [comment]
I'm going to try building it with the arm32v7/node image, that should make it work on other arm platforms (I've an asus tinkerboard to test it with) also allowing the image to be smaller. I tried my build on an RPI2 and it failed to run, not sure why so I need to test some more. If you could hold off on the change to the README until I can figure this out, i''l let you know when I am happy that it is working.

**Comment by bkimminich** [comment]
The README remark is only on `develop` so far, so it's not immediately visible to visitors. Also, I think you can now remove all the `phantom-js` stuff from the image, which might make it even smaller and faster to build.

Looking forward to trying that image on one of my own RPi2's!

**Comment by battletux** [comment]
Ok so my existing docker image only seems to work on Raspberry Pi 3's. Just working on the arm32v7/node:6 based image and it is taking some time to build sqlite3 it seems. once it's up I'll test it on the RPi3's on my desk here at work and the Asus Tinkerboard. If i can get a "generic" Armv7 build then it should work on most arm platforms that support that architecture (RPI2&3 and others). I wont be able to test an RPi2 until the weekend though.

**Comment by battletux** [comment]
Ok I have rebuilt this using the arm32v7/node:6 image and it comes out as being 2mb smaller. Confirmed it working on 2 Raspberry Pi 3's. I couldn't get it to run on the Tinkerboard as Docker wont  run on it for some reason.

I have pushed this over to my hub account as arclight/juice-shop_arm:beta so feel free to test it on your RPi2, i'll give it a go on the weekend too to check it works on the RPi2 as well (which is should).

The docker file was as follows:

```
# OWASP Juice Shop - An intentionally insecure JavaScript Web Application
FROM            arm32v7/node:6
LABEL version = "5.0.0"

COPY . /juice-shop
WORKDIR /juice-shop
RUN npm install --production --unsafe-perm

EXPOSE  3000
CMD ["npm", "start"]
```

**Comment by battletux** [comment]
Once I can confirm this works on a RPi2 I'll push it out as latest to my docker hub account.

**Comment by battletux** [comment]
Ok so it all works on a Pi2 and Pi3, but I can not get it to work on the tinkerboard (as I cant get docker to run on it.).

I have updated the repo and will update the blurb to highlight this.

Going forwards I think it could be possible to look into multiarch support on docker, but it needs to be an official base image that is supported on both platforms, sadly the node-alpine image is not available for Arm, just x86. 
Unfortunately this is out of my ability with Docker at present.

**Comment by bkimminich** [comment]
@battletux I'm not sure if I already offered to send you a couple of stickers for your great work on the RPi image...? In any case, if you want some, please send me your address via email!

**Comment by battletux** [comment]
@bkimminich that would be great, thank you. Will drop you an email shortly, thanks.
