### ISSUE TITLE
Feature request: Show authenticated user in UI

### ISSUE THREAD

**Issue by roelstorms** [juice-shop/juice-shop#388]
We use this application to demonstrate some of the web application vulnerabilities. During such demo's it would be of great help to have the currently authenticated user shown on the page. This makes it easier to follow some of the authentication bypasses for our spectators.

**Comment by bkimminich** [comment]
You can see the currently logged in user on the Feedback and Complaint pages, but nowhere else. A more prominent display on the navbar would better and was originally planned (https://github.com/bkimminich/juice-shop/issues/49) but never implemented.

**Comment by roelstorms** [comment]
Alright, thanks for the info!
