### ISSUE TITLE
Migration to Bootstrap 4

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#400]
- [ ] Migrate to `bootstrap` 4.x (see http://getbootstrap.com/docs/4.0/migration)
- [ ] Migrate to `bootswatch` 4.x as an affected dependency (see https://bootswatch.com/)

**Comment by bkimminich** [comment]
Shut up, stalebot! 😀

**Comment by aaqaishtyaq** [comment]
I would love to work on techstack upgrade but can I go in order of upgrading UI first then upgrading to JavaScript ?

**Comment by bkimminich** [comment]
:warning: This issue might be obsolete if #165 is implemented with an alternative frontend framework/widget library etc.

**Comment by bkimminich** [comment]
Obsolete with switch to Material Design in 8.x
