### ISSUE TITLE
Doing the XSS Tier 2 via the API seems to invalidate the XSS Tier 3 challenge?

### ISSUE THREAD

**Issue by sondr3** [juice-shop/juice-shop#402]
Quick question, we had a hack night at school today and it was really fun. I really enjoyed it, however I did the XSS Tier 2 challenge via Postman and got that one solved, however, doing the same for the Tier 3 challenge doesn't register that I've actually done it. I successfully get two popups in the admin interface, but it doesn't show as completed. Just curious if completing the Tier 2 challenge via the API somehow overwrites the Tier 3 or if I'm just missing something.

**Comment by bkimminich** [comment]
XSS Tier 2 and Tier 3 are done in different places with their own underlying vulnerabilities. So, keep looking for other possible attack vectors for that XSS 3... :-)
