### ISSUE TITLE
Auto-submit CTF flag codes to CTFd

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#403]
- [ ] Add a config or command line parameter to pass in the URL to a CTFd instance. Must be undefined by default
- [ ] If above URL is set and CTF flags are enabled upon solving a challenge its solution flag is submitted to the CTFd API
- [ ] Should happen together with the websocket notification to benefit from existing replay feature for solution notifications (e.g. if the CTFd was not reachable at the right moment)

Alternative to config and automatic submit, a submit button could be added to the flag notification itself.

**Comment by omerlh** [comment]
Can you share how CTFd API looks like? I've look for it, but could not find any documentation...

**Comment by bkimminich** [comment]
There is a chance the CTF tool will get a second option to generate FBCTF data instead of CTFd. That would invalidate or complicate this enhancement, so I'm setting it to _blocked_ for the time being. See https://github.com/bkimminich/juice-shop/issues/403

**Comment by bkimminich** [comment]
Obsolete for reason mentioned above in https://github.com/bkimminich/juice-shop/issues/403#issuecomment-347559780.
