### ISSUE TITLE
Docker container dies on startup when passing CTF_KEY

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#407]
![image](https://user-images.githubusercontent.com/3531020/33170061-312bbae2-d047-11e7-9e84-479a78486171.png)

Launching a docker container while passing a `CTF_KEY` results in the container dying immediately. Without the `CTF_KEY` environment variable it works fine. Reproducable on `master` (5.x) and `develop` (6.x) branch, so it cannot be related to recent `Dockerfile` changes from #404.

Suspectedly problematic code is in `utils.js`:

```
let ctfKey
if (process.env.CTF_KEY !== undefined && process.env.CTF_KEY !== '') {
  ctfKey = process.env.CTF_KEY
} else {
  fs.readFile('ctf.key', 'utf8', (err, data) => {
    if (err) {
      throw err
    }
    ctfKey = data
  })
}
```

**Comment by bkimminich** [comment]
Just verified that passing in a `CTF_KEY` during local execution on node.js works as it should. So, this only happens in Docker as it seems.

**Comment by battletux** [comment]
It works, for me at least, if you pass the -e CTF_KEY option before calling the docker container and -e NODE_ENV.

Also works with the current release:

```
$ docker run -d -e "CTF_KEY=1234567" -e "NODE_ENV=ctf" -p 3000:3000 bkimminich/juice-shop
b738edfdda8c86df3d6abf8315d2608f23dbc479d4237e87ddd2a2ac6d2d3459
$ docker ps
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS              PORTS                    NAMES
b738edfdda8c        bkimminich/juice-shop   "npm start"         2 seconds ago       Up 1 second         0.0.0.0:3000->3000/tcp   jovial_haibt
$ docker ps
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS              PORTS                    NAMES
b738edfdda8c        bkimminich/juice-shop   "npm start"         6 seconds ago       Up 5 seconds        0.0.0.0:3000->3000/tcp   jovial_haibt
$
```

Snapshot fails:

```
$ docker run -d -e "CTF_KEY=1234567" -e "NODE_ENV=ctf" -p 3000:3000 bkimminich/juice-shop:snapshot
d581f21a8e416114f693c4ef3aa99abca3aac372c3d484ad202ea98846939768
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
$ docker run -e "CTF_KEY=1234567" -e "NODE_ENV=ctf" -p 3000:3000 bkimminich/juice-shop:snapshot

> juice-shop@6.0.0-SNAPSHOT start /juice-shop
> node app

/juice-shop/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:31
        throw new Error('Please install sqlite3 package manually');
        ^

Error: Please install sqlite3 package manually
    at new ConnectionManager (/juice-shop/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:31:15)
    at new SqliteDialect (/juice-shop/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
    at new Sequelize (/juice-shop/node_modules/sequelize/lib/sequelize.js:233:20)
    at Object.<anonymous> (/juice-shop/models/index.js:5:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/juice-shop/routes/authenticatedUsers.js:3:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/juice-shop/server.js:29:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

npm ERR! Linux 4.9.49-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! juice-shop@6.0.0-SNAPSHOT start: `node app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the juice-shop@6.0.0-SNAPSHOT start script 'node app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the juice-shop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs juice-shop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls juice-shop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /juice-shop/npm-debug.log
$
```

**Comment by psiinon** [comment]
With the latest repo from dockerhub (note that sometimes it works and sometimes it doesnt!)

docker run -p 3000:3000 -e "NODE_ENV=ctf" -e "CTF_KEY=123456789" bkimminich/juice-shop

> 
> > juice-shop@5.0.3 start /juice-shop
> > node app
> 
> Segmentation fault (core dumped)
> 
> npm ERR! Linux 4.4.14-200.fc22.x86_64
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
> npm ERR! node v6.12.0
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! juice-shop@5.0.3 start: `node app`
> npm ERR! Exit status 139
> npm ERR! 
> npm ERR! Failed at the juice-shop@5.0.3 start script 'node app'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the juice-shop package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node app
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs juice-shop
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls juice-shop
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /juice-shop/npm-debug.log

**Comment by bkimminich** [comment]
@battletux, that failing snapshot seems unrelated to the CTF_KEY. Occasionally the SQLite package does not properly install. Happens on all OS but luckily very rarely.

**Comment by bkimminich** [comment]
Sidenote: I just realized that @battletux's `Dockerfile` optimization was only in the (generated) file, not in the template. This has been changed.

But: Could the #405 change actually be the culprit for this undeterministic behavior of the container when passing in environment variables?

**Comment by bkimminich** [comment]
I've found the SQLite-🐛 that @battletux experienced:

```
# OWASP Juice Shop - An intentionally insecure JavaScript Web Application
FROM            node:8-alpine
MAINTAINER      Bjoern Kimminich <bjoern.kimminich@owasp.org>
LABEL version = "6.0.0-SNAPSHOT"

RUN apk update && apk add git

COPY . /juice-shop
WORKDIR /juice-shop
RUN npm install --production --unsafe-perm

FROM    node:6-alpine
WORKDIR /juice-shop
COPY --from=0 /juice-shop .
EXPOSE  3000
CMD ["npm", "start"]
```

The app ist built on a `node:8-alpine` but later run on `node:6-alpine`. SQLite's binaries do not like that.

**Comment by battletux** [comment]
D'oh! Scratch that one up to the dyslexia.

**Comment by bkimminich** [comment]
For me everything worked just fine in several tries. I'll close this issue for now.

**Comment by psiinon** [comment]
Looks good on the snapshot :)
