### ISSUE TITLE
Add timing attack challenge

### ISSUE THREAD

**Issue by omerlh** [juice-shop/juice-shop#411]
I've read this [paper](https://www.blackhat.com/docs/us-15/materials/us-15-Morgan-Web-Timing-Attacks-Made-Practical-wp.pdf) from BlackHat 2015, and thought that it could be nice to add such challenge. To make timing attack works, one way to achieve that is to have multiple queries. One place this could be done is the reset password flow. Instead of the existing code, I propose to do the following:
* Query the database to find the security question for this user.
* If the security question match to the one sent by the user, run another query to get the answer.
This will allows an attacker to use a timing attack to find out which security question the user choose.
I know this is somewhat different from the current flow - it could be implemented also in other flows, if that sound too complex.

**Comment by bkimminich** [comment]
Sounds great! I think it would need an artificial wait between queries though, as SQLite might be too fast to give a noticeable time difference. At least if it should be noticeable by a human being... 😁

**Comment by omerlh** [comment]
I know, I  played a bit with timing attack recently and it is pretty hard to detect. Wonder if we can make the sqlite slower somehow...

**Comment by bkimminich** [comment]
Probably would put it into some other use case though and not the security questions or password reset. Password reset is about CSRF and security questions about sensitive information disclosure already. Wouldn't want to overload them more.

**Comment by omerlh** [comment]
Yeah, I noticed them while reading the code. The login looks too simple to add something there - but I could change it to first check if the user exist and then check the password (2 queries).

**Comment by shoebpate1** [comment]
So I have a great proposal/idea for this challenge. 

![timing-attack](https://user-images.githubusercontent.com/20478531/41278766-4cf64522-6e48-11e8-9377-64c4ee653b49.png)

What do you think @J12934 @wurstbrot @bkimminich ?
