### ISSUE TITLE
Alternative Solution to "Zero Stars"

### ISSUE THREAD

**Issue by kjpark** [juice-shop/juice-shop#425]
The following method of leaving a zero star rating doesn't award the point.

on the `.../#/contact` page, executing the following in the console:
```
$('#submitButton').click()
```
Successfully leaves a zero star rating without awarding the achievement.

**Comment by bkimminich** [comment]
The challenge is awarded upon DB `INSERT`, so I assume your method inserts `null` rather than zero.

I guess it should either have a constraint against `null` or count it as solved then. Will look into this some time after the holidays!

**Comment by kjpark** [comment]
Thanks so much & happy holidays! :)

**Comment by plaverty9** [comment]
Thanks Bjoern, I came here with a similar issue. My solution was to remove the disabled="disabled" on the submit button, which then allows me to submit a zero star review. Maybe mine is also submitting null. Thanks!

**Comment by bkimminich** [comment]
Hm, it's already supposed to accept `null` as a zero ... 
```
    rating: {
      type: DataTypes.INTEGER,
      set (rating) {
        this.setDataValue('rating', rating)
        if (utils.notSolved(challenges.zeroStarsChallenge) && (rating === 0 || rating == null)) {
          utils.solve(challenges.zeroStarsChallenge)
        }
      }
    }
```
