### ISSUE TITLE
Remove Gratipay link from checkout

### ISSUE THREAD

**Issue by amahlaka** [juice-shop/juice-shop#427]
As Gratipay has been shut down and is no longer operational, the link to send donations via gratipay should be removed
Opening the link leads to 404 error page

**Comment by bkimminich** [comment]
Thanks for the notice! I'll remove it with the upcoming v6.2.0 release.

**Comment by bkimminich** [comment]
I actually came up with an idea to make a new easy one-star challenge out of this fact... @amahlaka, If you tell me your address via mail, I'll send you a few stickers as a thank-you!

**Comment by amahlaka** [comment]
sent email to you
