### ISSUE TITLE
Add Scoreboard to the Menu Bar after Finding the Scoreboard Page

### ISSUE THREAD

**Issue by tomjackman** [juice-shop/juice-shop#431]
It would be nice if a link to the scoredboard page could be added to the menu bar automatically after you solve the challenge (Find the carefully hidden 'Score Board' page.) so you don't need to manually type the URL each time to access the page.

**Comment by bkimminich** [comment]
Done. Thanks for this simple yet great idea for extra convenience! If you email me your address, I'll send some stickers your way!
