### ISSUE TITLE
Apache 2 error from proxypass on Vagrant 2.0.1

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#434]
Vagrant 1.9.x complained about unsupported Virtualbox 5.2.x installation, so I updated Vagrant to 2.0.1. Since then the Apache does not start any more, thus server and logger are inaccessible.

@wurstbrot Do you have any idea why this is happening?

```
default: apache2_switch_mpm Switch to prefork
    default: apache2_reload: Your configuration is broken. Not restarting Apache 2
    default: apache2_reload: AH00526: Syntax error on line 5 of /etc/apache2/sites-enabled/000-default.conf:
    default: apache2_reload: Invalid command 'proxypass', perhaps misspelled or defined by a module not included in the server configuration
    default: apache2_invoke: Enable module php7.0
    default: apache2_reload: Your configuration is broken. Not restarting Apache 2
    default: apache2_reload: AH00526: Syntax error on line 5 of /etc/apache2/sites-enabled/000-default.conf:
    default: apache2_reload: Invalid command 'proxypass', perhaps misspelled or defined by a module not included in the server configuration
    default: Setting up libapache2-mod-php (1:7.0+35ubuntu6) ...
```

**Comment by wurstbrot** [comment]
I upgraded to vagrant 2.0.1 (with virtualbox 5.1.30) and created successfully a new box.

Have you tried to remove the existing box and setup a new one?
`vagrant destroy -f && vagrant up`

However I enhanced the setup process. A PR will come after the final test.

**Comment by bkimminich** [comment]
When doing a fresh `vagrant destroy && vegrant up` on my Windows 10 machine I end up with this screen default screen when going to `192.168.33.10`:
![image](https://user-images.githubusercontent.com/3531020/36231676-397aceac-11df-11e8-8796-b30b1262de96.png)

Also I was wondering why this is done in the `bootstrap.sh` at all because I do not see any use of NodeJs other than within the Docker container where it is already included:
```
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
```

**Comment by bkimminich** [comment]
@kfl, thanks for #483! That solves the issues! 🥇
