### ISSUE TITLE
Make URL for product tampering challenge configurable

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#442]
Instead of `useForProductTamperingChallenge: true` is should  be `urlForProductTamperingChallenge: https://www.owasp.org/index.php/O-Saft` by default which can be overwritten with an arbitrary URL. The URL to change it into should still statically be `http://kimminich.de`, of course! 😁

**Comment by WVik** [comment]
Hello! I'm new here. I want to get started to contribute to juice-shop. Where exactly should I make this particular change?

**Comment by bkimminich** [comment]
Hi @WVik! Best start by checking out how the entire configuration mechanism works: https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part1/customization.html. And also how to generally contribute to the project: https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part3/contribution.html. With that and looking at how the `datacreator.js` works, you should be good to go. Please ask if you have further questions.

**Comment by WVik** [comment]
@bkimminich Thanks! I'll go through the links you suggested!

**Comment by shoebpate1** [comment]
Addresed this in #444

**Comment by WVik** [comment]
@bkimminich I went through the links. The links are very nice, got an overall understanding of the code. Thanks!
