### ISSUE TITLE
Rate Limit Circumvention Challenge

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#446]
Adding https://www.npmjs.com/package/ratelimiter to some route (e.g. _login_ or _change-password_) would make an additional challenge possible where the rate limit needs to be circumvented somehow.

For this to work, `ratelimiter` needs to be misconfigured or maybe an older version with known weaknesses can be used. Needs to be analyzed.

* Alternative 1: Write an own (broken) rate limiting feature.
* Alternative 2: Typosquat `ratelimiter` and make it broken. (Risky because it might be kicked off npmjs.org at some point?)

**Comment by shoebpate1** [comment]
I have some nice idea to implement this challenge.
Like:-

1.Rate limit Bypass on BruteForce of Forgot Password Secret Token
2.Login Form Bruteforcing 

Broken feature will be Implementation of rate limiting on the basis of Originating IP.
which then can be bypassed by Spoofing X-Forwarded-For: IP Header.

Will look into ratelimiter and will look into any cool way of misconfiguring it.

**Comment by bkimminich** [comment]
## Draft
* [x] Add a new user (e.g. [morty](http://rickandmorty.wikia.com/wiki/Morty_Smith)@juice-sh.op) whose password is super strong and the security answer is too hard to guess but brute forcible using some common word list
* [x] Implement rate limiting on _Forgot Password_ endpoint (or in general?)
* [x] Make sure rate limiting can be bypassed by spoofing `X-Forwarded-For` header
* [x] Add challenge to reset Morty's password and verify success like with the existing 3 reset challenges

**Comment by shoebpate1** [comment]
Tackled in #452

**Comment by bkimminich** [comment]
@CaptainFreak, I changed the security question and answer a bit to make this challenge all about pre-creating a list of 1337-speak-mutations of a suspected answer string. See https://github.com/bkimminich/pwning-juice-shop/blob/develop/appendix/solutions.md#reset-mortys-password-via-the-forgot-password-mechanism for the step-by-step solution.
