### ISSUE TITLE
Complaint .XML upload causes segmentation fault

### ISSUE THREAD

**Issue by corysabol** [juice-shop/juice-shop#449]
I'm running the docker image of juice-shop on windows 10 pro.

When uploading a pdf to the complaint form, the application handles it fine. However when uploading an XML file the node application crashed with a segfault, which crashes the docker container as well. This is demonstrated in the linked in this gif.

![js_complaint_xml_sefault](https://user-images.githubusercontent.com/4594324/35773335-e3ae093c-091c-11e8-8fbf-fd1ce14a1b9c.gif)

I tried to reproduce this by running the application from the source on my host machine, however I had some issues with libxmljs installing. I will look into that later, when I have more time. I will also see if there is a way that I can get to the npm logs that get generated on the crash. But that is giving me some trouble, as when I run the container, and then attach an ash instance to it, the segfault still crashes the container, which of course boots me out of my ash instance.

Let me know if anybody can reproduce this. I'm fairly certain I'm running the current version of the docker image, I just did a pull a few minutes ago.

Here is the output of the crash:
```
Segmentation fault
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! juice-shop@6.4.1 start: `node app`
npm ERR! Exit status 139
npm ERR!
npm ERR! Failed at the juice-shop@6.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-04T00_46_41_737Z-debug.log
```

**Comment by corysabol** [comment]
I managed to extract the npm log by starting the container with an ash process rather than with `npm start`, then manually ran the juice-shop app, reproduced the issue, then after the app crashed, I was able to view the log. However, the log didn't seem too helpful.

```
/juice-shop # npm --verbose start
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   '--verbose',
npm verb cli   'start' ]
npm info using npm@5.6.0
npm info using node@v8.9.4
npm verb run-script [ 'prestart', 'start', 'poststart' ]
npm info lifecycle juice-shop@6.4.1~prestart: juice-shop@6.4.1
npm info lifecycle juice-shop@6.4.1~start: juice-shop@6.4.1

> juice-shop@6.4.1 start /juice-shop
> node app

sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:237:13
Server listening on port 3000
Solved challenge Score Board (Find the carefully hidden 'Score Board' page.)
Solved challenge Error Handling (Provoke an error that is not very gracefully handled.)
Solved challenge Login Admin (Log in with the administrator's user account.)
Solved challenge Password Strength (Log in with the administrator's user credentials without previously changing them or applying SQL Injection.)
Solved challenge Five-Star Feedback (Get rid of all 5-star customer feedback.)
Solved challenge Confidential Document (Access a confidential document.)
Solved challenge Admin Section (Access the administration section of the store.)
Segmentation fault
npm verb lifecycle juice-shop@6.4.1~start: unsafe-perm in lifecycle true
npm verb lifecycle juice-shop@6.4.1~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/juice-shop/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle juice-shop@6.4.1~start: CWD: /juice-shop
npm info lifecycle juice-shop@6.4.1~start: Failed to exec start script
npm verb stack Error: juice-shop@6.4.1 start: `node app`
npm verb stack Exit status 139
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at EventEmitter.emit (events.js:214:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at ChildProcess.emit (events.js:214:7)
npm verb stack     at maybeClose (internal/child_process.js:925:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm verb pkgid juice-shop@6.4.1
npm verb cwd /juice-shop
npm verb Linux 4.9.60-linuxkit-aufs
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "--verbose" "start"
npm verb node v8.9.4
npm verb npm  v5.6.0
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! juice-shop@6.4.1 start: `node app`
npm ERR! Exit status 139
npm ERR!
npm ERR! Failed at the juice-shop@6.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 139, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-04T01_42_39_383Z-debug.log
```

**Comment by shoebpate1** [comment]
Please can you just confirm that the port on which your server is running is not in use. Maybe its a port conflict.

**Comment by shoebpate1** [comment]
Ah ! My bad. So the server is successfully running but after upload it crashes.

**Comment by corysabol** [comment]
Yeah, everything works as intended for the most part. But trying to upload
an xml file via the complaint form causes the node process to segfault.

This is takes the container down if started normally. But I was able to
start the container with a /bin/ash instance first and manually launch the
node app, then crash it. This let me grab the npm logs, which were not too
helpful.

**Comment by shoebpate1** [comment]
This is not reproducible on running it from source. *SPOILER ALERT* Actually this is one of the challenge.
Will look into docker instance in some time.

**Comment by bkimminich** [comment]
@corysabol, could you please attach the XML file that you used? Does it happen with any XML file?

Could you please try out if the same happens when using the `snapshot` Docker image?

I'll look into the autobuild logs for the `latest` image you are using in the meantime. My suspicion is, that a) the XML parser did not install properly, b) something wasn't installed into the final Alpine image that is needed by the parser lib, or c) the underlying C library of the parser can be built on `node` image but is incompatible with `node:alpine` image where it later runs on.

**Comment by bkimminich** [comment]
Ok, so `libxmljs` installed just fine in the `latest` image by downloading a pre-built `xmljs.node` file:
```
> libxmljs@0.18.7 install /juice-shop/node_modules/libxmljs

> node-pre-gyp install --fallback-to-build --loglevel http



[91mnode-pre-gyp[0m[91m http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.7/node-v57-linux-x64.tar.gz

[0m[91mnode-pre-gyp http 200 https://github.com/libxmljs/libxmljs/releases/download/v0.18.7/node-v57-linux-x64.tar.gz

[0m[libxmljs] Success: "/juice-shop/node_modules/libxmljs/build/Release/xmljs.node" is installed via remote
```
That's the same way how it works for `sqlite3`, and that works on the final image later on just fine. I'll do some reproducing...

**Comment by bkimminich** [comment]
I'm running the `latest` container and can upload a harmless XML file without any problems:
![image](https://user-images.githubusercontent.com/3531020/35774993-cc5d7d40-097f-11e8-8b79-e91fed6896f2.png)
This is the file I used: https://github.com/bkimminich/juice-shop/blob/master/test/files/deprecatedTypeForServer.xml

Will try with some malicious or simply broken XML files now...

**Comment by bkimminich** [comment]
Okay, using a "bad" file that would normally be blocked by the parser itself is doing the segfault thingie;
```
Segmentation fault
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! juice-shop@6.4.1 start: `node app`
npm ERR! Exit status 139
npm ERR! 
npm ERR! Failed at the juice-shop@6.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-04T06_50_03_553Z-debug.log
```
(File: https://github.com/bkimminich/juice-shop/blob/master/test/files/xxeBillionLaughs.xml)

The local behavior when uploading the same file on my Windows machine is as follows:
```
Server listening on port 3000
Solved challenge Score Board (Find the carefully hidden 'Score Board' page.)
Solved challenge Login Bjoern (Log in with Bjoern's user account without previously changing his password, applying SQL Injection, or hacking his Google account.)
Error: B2B customer complaints via file upload have been deprecated for security reasons: Detected an entity reference loop
 (xxeBillionLaughs.xml)
    at C:\Data\GitHub\juice-shop\routes\fileUpload.js:41:18
    at Layer.handle [as handle_request] (C:\Data\GitHub\juice-shop\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Data\GitHub\juice-shop\node_modules\express\lib\router\route.js:137:13)
    at Array.<anonymous> (C:\Data\GitHub\juice-shop\node_modules\multer\lib\make-middleware.js:53:37)
    at listener (C:\Data\GitHub\juice-shop\node_modules\on-finished\index.js:169:15)
    at onFinish (C:\Data\GitHub\juice-shop\node_modules\on-finished\index.js:100:5)
    at callback (C:\Data\GitHub\juice-shop\node_modules\ee-first\index.js:55:10)
    at IncomingMessage.onevent (C:\Data\GitHub\juice-shop\node_modules\ee-first\index.js:93:5)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Solved challenge Deprecated Interface (Use a deprecated B2B interface that was not properly shut down.)
Solved challenge Error Handling (Provoke an error that is not very gracefully handled.)
```
The server survives this just fine with the `Detected an entity reference loop` being thrown by `libxmljs` and caught/handled by the application.

**Comment by bkimminich** [comment]
Just verified that segfault also happens on `snapshot` image.

**Comment by bkimminich** [comment]
I created a branch `fix-segfault` which triggers building a new Docker image tag `debug` for experimenting with different build options.

**Comment by corysabol** [comment]
@bkimminich I'd be happy to take a look at the new branch and mess around as well, tomorrow (it's quite late where I am, now). Assuming you don't have it sorted out by then. Best of luck!

By the way @CaptainFreak here is the xml I used; https://msdn.microsoft.com/en-us/library/ms762271(v=vs.85).aspx

**Comment by bkimminich** [comment]
@corysabol I didn't sort it out, but my random first fix of using node v9 instead of v8 in the Docker image actually fixed the problem... 😀 ... I'll put this into a `6.4.2` bugfix release, so when you try `latest` image next time, all should be fine.

**Comment by bkimminich** [comment]
@corysabol If you shoot me an email with your address I'll send some Juice Shop stickers your way! An animated GIF bug report merits a reward... 🥇

**Comment by corysabol** [comment]
@bkimminich Oh, glad it got fixed though, even if it was a random first try. I love stickers! I'll shoot you an email shortly. Thanks a bunch 👍
