### ISSUE TITLE
Error in setup

### ISSUE THREAD

**Issue by kunal-mohta** [juice-shop/juice-shop#461]
![screenshot 2018-02-15 00 29 12](https://user-images.githubusercontent.com/30414954/36222499-7fed3d54-11e7-11e8-9b15-c57687ad77fe.png)

Got this error when I tried `npm start` after following the steps as mentioned in `README.md` under **From Sources** sub-heading.

**Comment by bkimminich** [comment]
Can you please provide your OS, node.js and NPM version as well as the log from `npm install`? Seems the binaries for the XML parser could neither be downloaded nor built on your system.

**Comment by kunal-mohta** [comment]
`npm install` log is what missed my eyes
I ran it again and got this..

![screenshot 2018-02-15 00 56 09](https://user-images.githubusercontent.com/30414954/36223687-3255fc3a-11eb-11e8-80bd-1280fc428e57.png)


**OS** - Ubuntu 15.10
**Node.js** - v8.9.0
**npm** - 5.6.0

**Comment by bkimminich** [comment]
This looks fine. Okay, could you please delete your `node_modules` folder and run install again? That should give some error and if it doesn't, starting the app should work. Fallback: Have you tried using Docker instead? That is the best option on Linux to be on the safe side.

**Comment by kunal-mohta** [comment]
It worked when I reinstalled `node_modules`.
Thanks for your help!
You can close this issue now.

**Comment by bkimminich** [comment]
Linux❤️Node.js... 😁
