### ISSUE TITLE
XSLT Injection Challenge

### ISSUE THREAD

**Issue by shoebpate1** [juice-shop/juice-shop#463]
Recently researched a lot about XSLT Injection Vulnerability. Its a obscure vulnerability but with great security impact which is somewhat relatable to XML Injection. This challenge if possible can be implemented around pdf creation for reports/receipts etc. Obscure vulnerabilities are more fun and will encourage users to research.

References : 
1.https://www.contextis.com/blog/xslt-server-side-injection-attacks
2. [My simple php Implementation](https://gist.github.com/CaptainFreak/bf8fb57f5029d29569f76bc7f67c5389).
3.https://cocoon.apache.org/2.1/howto/howto-html-pdf-publishing.html
4.https://www.npmjs.com/browse/keyword/xslt

**Comment by supra08** [comment]
@bkimminich @CaptainFreak I would like to take up this issue. Do have something in mind for the implementation?

**Comment by supra08** [comment]
@bkimminich, @CaptainFreak, currently `pdfkit` is being used to create the pdf files, so xslt can't be used to create this challenge. But if the library can be altered, an injection based challenge can be created. The flow could be like this:
* The order invoice is created using the order details input.
* We can make the attacker generate an invoice for products not currently in the juice shop, and he too will not be aware of the products to order. He will be instructed that there exists a misplaced xml file containing some discontinued products. He's got to order these.
* He needs to first find the file and then inject `<xsl:copy-of select=\"document('./products.xml')\"/>` to include the contents of `products.xml` in the invoice.

This marks the successful completion of the challenge. We may employ few other steps to make the challenge a bit tougher.

**Comment by bkimminich** [comment]
XSLT Injection could be done within XML data export once that is implemented. Issue needs more detailed idea how to place it there.
