### ISSUE TITLE
NoSQL injection

### ISSUE THREAD

**Issue by RonDoesit** [juice-shop/juice-shop#465]
More NoSQL injection challenges are wanted and needed :)
From my opinion juice shop is the only one that has nosql injection challenges, all other vulnerable servers dont have nosql injection at the moment.

I really like the juicyfruit on herokuapp: straight forward, fast and free setup!
But as NoSQL injection gets more and more popular and there is a increase of noqsl-ransomware. We must practice with nosql injection to make the world safer. Practise with f.e. nosqlmap and juicyfruit to train ourselves :)

More info:
https://www.trendmicro.com/vinfo/au/security/news/cybercrime-and-digital-threats/hacking-groups-attack-more-than-20-thousand-mongodb-databases
https://www.databreaches.net/mongodb-databases-held-up-for-ransom-by-mysterious-attacker/
https://krebsonsecurity.com/tag/victor-gevers/

**Comment by bkimminich** [comment]
There are now 3 different tiers of NoSQL injection challenges.
