### ISSUE TITLE
Persist language selection in cookie

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#523]
At the moment `angular-translate` uses the Browser language by default. When selecting another language, it will be reset to this default whenever the AngularJS client is reloaded, e.g. on `F5` or when a non-Angular page has been visited.

It would be nicer to store the last selection in a cookie and use it if present. Otherwise fall back to Browser default.

**Comment by bkimminich** [comment]
Woah, that #524 was fast, @Aashish683! 👍

**Comment by Aashish683** [comment]
Thanks @bkimminich , is there anything more which needs to be resolved for this issue ?

**Comment by bkimminich** [comment]
No, works like a charm! 👍
