### ISSUE TITLE
Learn about the TokenSale challenge bypassed?

### ISSUE THREAD

**Issue by corysabol** [juice-shop/juice-shop#532]
The challenge to find out about the token sale seems to be bugged. I was able to complete it in a way that may not have been intentional or even as challenging as the intended solution.
I've attached a GIF of what I did to solve the challenge. 

![This is where a gif of what I did would be.](https://a.pomf.cat/cnltfm.gif)

Basically what happened while trying to solve this challenge is that I just went to the bottom of `juice-shop.min.js` (line 3599 in the unminified file) and found the string `views/TokenSale.html`. So, I just slapped that onto the end of the url like so, `localhost:3000/views/TokenSale.html` an viola, I got the challenge complete notification.

I only bring this up because the actual solution is more challenging and forces a closer examination of what the app is doing. More suitable for a 3-start challenge, I think.

**Comment by bkimminich** [comment]
Ah, that's b/c in the end it's verified by loading a tracking image... Hm, so I'll have to "secure" the HTML template just as well as the route... Thanks for noticing!

**Comment by corysabol** [comment]
Awesome, thanks! Keep up the good work with Juice-Shop 👍

**Comment by corysabol** [comment]
Also, I just noticed that my gif seems to cut off just before it shows the challenge solved banner. That's lame.
