### ISSUE TITLE
Editing Admin's reviews is not listed as a challenge

### ISSUE THREAD

**Issue by elfakyn** [juice-shop/juice-shop#538]
SPOILERS AHEAD!

You can edit Admin's review of apple juice by:
* logging in as an arbitrary user
* using the broswer inspector on the review and changing `btn-default` from `ng-hide` to `ng-show`
* clicking on "Edit"
* editing the review and submitting

This, however, isn't tracked by the challenge scoreboard -- and it seems like something that should have a level 1 reward attached to it.

**Comment by shoebpate1** [comment]
Actually PUT request to add review was also vulnerable along with PATCH for edit review as both were relying on client side and no back-end access control was present, So added this as a challenge in #572 .

**Comment by bkimminich** [comment]
To be released with v8.0.0
