### ISSUE TITLE
Ciphertext for premium paywall challenge is corrupted

### ISSUE THREAD

**Issue by jmaxxz** [juice-shop/juice-shop#545]
Ciphertext for premium paywall challenge is corrupted 

Currently cipher text is:
`IvLuRfBJYlmStf9XfL6ckJFngyd9LfV1JaaN/KRTPQPidTuJ7FR+D/nkWJUF+0xUF07CeCeqYfxq+OJVVa0gNbqgYkUNvn//UbE7e95C+6e+7GtdpqJ8mqm4WcPvUGIUxmGLTTAC2+G9UuFCD1DUjg==`

but it should be:
`i0ycvJyZ+WoHTEIjAatNFK5A8r8GxRbwOLC2OuXHVsZcKkEc3lRgc58KjEKn2Byj8Fg3A3ai5yahQANdWL/5j5k3E3qHTjm93tuenE0YlauCdy+7tGkFvo5OltIhiXSWt1SiICecyghFZ8ca/aKtHQ==`

Bug here:
https://github.com/bkimminich/juice-shop/blame/06cfe881178144516f36fe0e4fa42d623b08e055/data/static/challenges.yml#L332

**Comment by bkimminich** [comment]
Thanks for the report! I'll have to verify that, b/c I don't have a clue why the original one might be corrupt...

**Comment by bkimminich** [comment]
I checked and the current ciphertext is correct. What is wrong is the solution in the eBook, which still uses the shorter IV. I will update the ebook section accordingly.
