### ISSUE TITLE
Packaged release unpacks in current directory

### ISSUE THREAD

**Issue by kramse** [juice-shop/juice-shop#552]
downloaded the packaged node8 tgz and used the usual, tar zxvf from my home dir.

Ended up with files and dirs from tar file messing up my home dir, because it doesnt contain a sub-directory.

Would expect tar zxvf to produce dir juice-shop with files

**Comment by bkimminich** [comment]
That is a very good idea, sir! Thanks for reporting it and sorry for messing up your `home` ... :-)
