### ISSUE TITLE
UI-Error.

### ISSUE THREAD

**Issue by Tikam02** [juice-shop/juice-shop#555]
UI is not rendering on the server. Please Provide the dependencies to install for UI.
![screenshot from 2018-05-13 23-17-54](https://user-images.githubusercontent.com/10548085/39970130-13124cda-5704-11e8-88ee-281f0ef2d215.png)

**Comment by wurstbrot** [comment]
Hi @Tikam02 , thank you for the information. For me, it is working in develop and with the current docker image.
Please provide information on how you start the juice shop, your browser-version and the console-tab from the developer tools. In case there is no error shown, in addition the network tab.

**Comment by bkimminich** [comment]
It is very likely that some component(s) is/are missing on your install. Did you run via local installation or by unzipping the latest ZIP archive?

**Comment by Tikam02** [comment]
OS: Kali Linux
Installation:  via Git-clone->npm install->npm start
 Everything is ok but the UI not the same. The CSS part is not rendered.

**Comment by bkimminich** [comment]
Okay, this is most likely an issue with your node.js installation. What version do you use? Best run `node -v` and `npm -v`. My recommendation is to install a fresh node.js on your system or use Docker instead.

**Comment by Tikam02** [comment]
![screenshot from 2018-05-14 09-40-09](https://user-images.githubusercontent.com/10548085/39977934-e7332a38-575a-11e8-9471-36c7ee0b0b96.png)

root@hal:~# node -v
v10.0.0
root@hal:~# npm -v
5.6.0

**Comment by bkimminich** [comment]
NPM 5.6 does not support Node 10.x. At least on Windows it does not. You'd need to get a newer NPM version (6.x?) or downgrade to Node 9.x or 8.x.

If this does not fix your problem, please re-open!

**Comment by Tikam02** [comment]
#### root@hal:~/juice-shop# npm -v
6.0.1
#### root@hal:~/juice-shop# npm start

> juice-shop@7.1.0 start /root/juice-shop
> node app

Updated NPM but UI didn't change it's same as previous without CSS.
Server listening on port 3000

**Comment by bkimminich** [comment]
Juice Shop 7.1.0 does not support Node 10 yet. It only officially runs on 8 or 9. With 7.2.0 which you could already get from `master` branch Node 10 will be supported as well, but with an "experimental feature"-warning.

So, if you want to be sure, please get Node 8 or 9. If you feel lucky, please update your code to 7.2.0 and try again.

**Comment by Tikam02** [comment]
👍 Yeah, sure. @bkimminich  Thanks for the information.
