### ISSUE TITLE
Update RasPi Docker image to 7.2.1

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#560]
Hi @battletux! While at the Secure360 TC conference this week, some people showed interest in the RasPi image for the OWASP Juice Shop. I just checked and https://hub.docker.com/r/arclight/juice-shop_arm/currently is at v6.0.0. Would you mind doing an updated image for current 7.2.1 version?

Also, is there a way we might get this automated similarly to my original Docker images? That way every new release would also get a new RasPi image. What do you think?

**Comment by battletux** [comment]
Hi @bkimminich Sorry, life seems to have gotten in the way. I'll try and get this done this evening after I wrap up some stuff for work, otherwise it might have to wait until the weekend.

_Definitely_ need to look into a way of automating the build process. My Docker skills are basic but I'm keen to learn that part of the process.

**Comment by simbas** [comment]
Hi @battletux and @bkimminich ,

What do you think about adding the arm dockerfile in this project and then having a new automated build in hub.docker.com pointing to the arm dockerfile?

**Comment by battletux** [comment]
Ok I have a quick and dirty image up, it is tagged as BETA7.2.1. Going to try and get a nicer one up Soon<sup>TM</sup>.

@simbas That would be great but I'm having issues building on arm32v7/node. As soo as it tries to do the npm install it spits out an error and fails to build, both in dockerhub and on my Raspberry pi.

Here is the error from Docker hub:

```
Step 4/12 : RUN npm install --production --unsafe-perm

 ---> Running in 4075ef1cf28c

[91mstandard_init_linux.go:187: exec user process caused "exec format error"

[0mThe command '/bin/sh -c npm install --production --unsafe-perm' returned a non-zero code: 1

build hook failed! (1)

```
My work around, that I hope will work, is to use resin/raspberry-pi-alpine-node as the base. And as this is not an official build it wont work with docker hubs auto build process. At least as far as I understand it.

**Comment by battletux** [comment]
Latest is being pushed now.
