### ISSUE TITLE
Let us redirect you to a donation site that went out of business Challenge - Redirect URL Do not exist anymore 

### ISSUE THREAD

**Issue by ashutosh567** [juice-shop/juice-shop#561]
While Inspecting Element for Donation page the redirect URL according to challenge solution do not exist with v 7.0.2. Please check below screen shot. According to Challenge document it should show like this while 
![screen shot 2018-05-17 at 4 36 11 pm](https://user-images.githubusercontent.com/14334424/40205106-7451dcc4-59f0-11e8-89e1-c8568d813dfa.png)

With  v7.0.2 the link Gratipay option is not available. 

![screen shot 2018-05-17 at 4 39 35 pm](https://user-images.githubusercontent.com/14334424/40205235-e8f1e9f2-59f0-11e8-8a27-b15f68dab53d.png)

**Comment by bkimminich** [comment]
Hi @ashutosh567! If you inspect any of the buttons in the _Payment_ section, you will see it is in fact still there as described in the ebook's appendix. Just checked on 7.2.1:

![image](https://user-images.githubusercontent.com/3531020/40224294-02f860a2-5a86-11e8-81f4-dd0b94a2e4ed.png)

**Comment by jeffersonbenson** [comment]
Though perhaps done in error, it would appear that the link described is no longer present (see attached screenshot). The only way I found was to visit the link listed in the gitbook and that appeared to complete the challenge. I would like to ask that the issue be reopened and checked out.

![selection_008](https://user-images.githubusercontent.com/19256220/49607080-01ad1900-f963-11e8-91d0-cd4364438e57.png)

**Comment by bkimminich** [comment]
Your assessment is correct, there is no such link any more, but the URL can be found elsewhere now, because it was not very smartly removed by the developers... Corresponding Gitbook section is not updated yet (still marked with ":warning:") but I'm sure you can find it without help...
