### ISSUE TITLE
Trainer Guide

### ISSUE THREAD

**Issue by wurstbrot** [juice-shop/juice-shop#564]
As a trainer I need a guide with a list off all features to provide awareness- and full blown app-sec trainings.
The guide should have a list of features and links to the relevant documentation.

The current documentation has the title "Pwning Juice Shop" (see https://github.com/bkimminich/pwning-juice-shop ) which doesn't match content like "Juice Shop Trainer Guide". An option is to create an extra repository for the trainer guide.

@bkimminich Which process do you suggest?

**Comment by bkimminich** [comment]
I think we should make a list of information that is missing in the eBook as it is now, specifially for trainers. Then there might just be a distinct chapter in it aimed at trainers, no? At the moment I guess most information is there, it is just scattered because the book was not written with trainers in mind.

So, it might just be a chapter reordering task or an additional chapter. Or maybe a separate "Trainer's Checklist" which just has links to all the relevant chapters of the ebook. What do you think?

**Comment by wurstbrot** [comment]
Trainer's Checklist might be good.

**Comment by bkimminich** [comment]
1. Make sure every participant has his/her own running Juice Shop instance
  * You can let them install it individually following any of the [Run options](https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part1/running.html#run-options)
  * You might instead want to host an instance for each participant and give each their own URL
2. If you want to track progress centrally during the training, you might want to host a central CTF server, following the [Hosting a CTF event](https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part1/ctf.html) guide.
3. List of challenges which are well or less suited for demos
4. Recommend https://github.com/wurstbrot/shake-logger for awareness trainings
5. Theming Juice Shop to match your client's corporate identity (with [7MS](https://github.com/bkimminich/juice-shop/blob/master/config/7ms.yml) and [Mozilla](https://github.com/bkimminich/juice-shop/blob/master/config/mozilla.yml) as most sophisticated examples)
6. ...

**Comment by bkimminich** [comment]
Some more ideas:
* List of challenges which are well or less suited for demos
* Link to shake.js demo
* ...

**Comment by bkimminich** [comment]
@wurstbrot, I created a https://github.com/bkimminich/pwning-juice-shop/blob/develop/appendix/trainers.md where I think the checklist should live. Makes links within the book much easier (especially when anchors change, my Markdown plugin for IntelliJ can refactor those properly) and then in the README we could just add a subsection beneath https://github.com/bkimminich/juice-shop#additional-documentation where the _Trainer's checklist_ is explicitly advertised. Does that make sense for you?

**Comment by wurstbrot** [comment]
yes

**Comment by bkimminich** [comment]
https://github.com/bkimminich/pwning-juice-shop/blob/develop/appendix/trainers.md
