### ISSUE TITLE
standard_init_linux.go:178: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by sugumarv** [juice-shop/juice-shop#580]
I installed docker using
  sudo apt install docker.io

and installed juice-shop

while running it showed some permission error, so I added my user to docker.

Now while running I get the following error;

standard_init_linux.go:178: exec user process caused "exec format error"

My machine is ubuntu 16

**Comment by bkimminich** [comment]
Are you on `latest` or `snapshot` image? Could you try the latest tagged image (`7.2.1`)?
