### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#581]
Add an actually decent privacy policy stating that
* the application is supposed to be fed only fake sensitive and private identifiable data
* all data is deleted upon server restart
* server logs depend on chosen deployment option
etc.

Mostly relevant for the public demo instances on Heroku, I guess. Could use review by an actual DPO or legal expert.

**Comment by J12934** [comment]
The `thank-you.jpg` file for the `Privacy Policy Tier 2` is currently missing.
Did this get lost or is it still in the works?

**Comment by bkimminich** [comment]
Hehehe, that's on purpose because we are _not really_ thankful at all... 😈

**Comment by J12934** [comment]
🤣 Haha, Shit. Thats embarrassing that I didn't get the joke
