### ISSUE TITLE
Integrate retire.js to scan for unwanted vulnerabilities

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#59]
Using Grunt task `"grunt-retire": "~0.3"`

**Comment by bkimminich** [comment]
Waiting for https://github.com/bekk/grunt-retire/issues/15

**Comment by eoftedal** [comment]
I'm on it

**Comment by eoftedal** [comment]
Updating grunt-retire to 0.3.3 should fix this issue

**Comment by bkimminich** [comment]
Works perfectly fine now, thanks!
