### ISSUE TITLE
Score Board Filter Options

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#592]
The Score Board should receive additional filters to
* [x] Hide all solved challenges to avoid scrolling and spotting leftover red "unsolved"-markers (suggestion by @braimee). Sovled challenges should be shown by default.
* [x] Show only challenges of selected categories (defined in https://github.com/bkimminich/pwning-juice-shop/blob/master/part1/categories.md). All categories should be selected by default.

**Comment by 7MinSec** [comment]
Yay!
