### ISSUE TITLE
Enhance Design/Layout of PDF-Page

### ISSUE THREAD

**Issue by wurstbrot** [juice-shop/juice-shop#595]
At the confirmation page there should be a logo, a bold font for the title.
Optionally, the bought products should be shown in a table.

Thanks to @lisa-devseccon for raising this issue.

**Comment by bkimminich** [comment]
I used the PDFs ugliness as a kind of running gag during talks or trainings, but in all honesty: I was just too lazy to ever make them pretty... :+1:
