### ISSUE TITLE
Redesign Product Overview

### ISSUE THREAD

**Issue by wurstbrot** [juice-shop/juice-shop#598]
Here is a suggestion for the product overview redesign.

Google Fonts (for the new area "Welcome to OWASP Juice Shop") can be downloaded and integrated into this repository, otherwise an other font than suggested should be used.

[juiceshop copy 2.pdf](https://github.com/bkimminich/juice-shop/files/2080970/juiceshop.copy.2.pdf)

Thanks to @lisa-devseccon.

**Comment by aaryan01** [comment]
@wurstbrot  @bkimminich  I would love to work on this.

**Comment by aaryan01** [comment]
Just a doubt regarding the design you have attached, can I improvise on it or should I attempt to make a new one? Thanks!

**Comment by bkimminich** [comment]
Hi! Thanks for the offer, but please do not work on any design tickets right now. Beginning of March a student will be doing his master thesis on UI design.

**Comment by aaryan01** [comment]
Sure. Thanks for informing!
