### ISSUE TITLE
Usage of a corporate idententy

### ISSUE THREAD

**Issue by wurstbrot** [juice-shop/juice-shop#599]
As suggested in [juiceshop copy 2.pdf](https://github.com/bkimminich/juice-shop/files/2080970/juiceshop.copy.2.pdf) page 3 we should use other colors for information like solving challenges.

Thanks to @lisa-devseccon.

**Comment by bkimminich** [comment]
You mean fixed colors for challenge notifications and solved/unsolved badged that stay static even when a different theme is used via the config mechanism?

**Comment by wurstbrot** [comment]
Yes, but the colors should be defined in the config for easy overwriting.

**Comment by bkimminich** [comment]
Different Angular Material themes will be provided for customization. Static colors (i.e. solved/unsolved markers and notifications) have been changed to the suggested colors from https://github.com/bkimminich/juice-shop/files/2080970/juiceshop.copy.2.pdf.
