### ISSUE TITLE
Redesign Navbar

### ISSUE THREAD

**Issue by J12934** [juice-shop/juice-shop#600]
The current navbar gives up a lot of space for imformation which can be represented in a much smaller form factor. E.g. the application version or the logout button.

Heres a suggestion how the items could be aligned to highlight the important elements more than the others.

![homepage](https://user-images.githubusercontent.com/13718901/41109201-4fedb874-6a6e-11e8-81be-4322e5d2bc0b.png)

There are also some parts of the navbar which could be embedded in a dropdown sort of way to save a lot of space.

![homepage hoverover](https://user-images.githubusercontent.com/13718901/41109332-afdb175e-6a6e-11e8-9f18-b0bf97193746.png)

**Comment by bkimminich** [comment]
See #583 for additional sub menu idea of "Contact us" combining feedback, complaints and (to be created) data subject contact form.

**Comment by bkimminich** [comment]
With Angular Material Design shouldn't the top navbar be replaced with a typical sidenav of Material?

https://material.angular.io/components/sidenav/overview

**Comment by bkimminich** [comment]
### Large
![image](https://user-images.githubusercontent.com/3531020/46144375-06679980-c25d-11e8-897e-c50c79664edd.png)

### Medium
![image](https://user-images.githubusercontent.com/3531020/46144424-2a2adf80-c25d-11e8-9699-ec40662d9f1a.png)

### Small
![image](https://user-images.githubusercontent.com/3531020/46144443-3d3daf80-c25d-11e8-9617-68661771900d.png)

### Extra Small
![image](https://user-images.githubusercontent.com/3531020/46144460-49c20800-c25d-11e8-9dec-d9ed4fc33470.png)
