### ISSUE TITLE
Replace bootswatch based theming

### ISSUE THREAD

**Issue by Aashish683** [juice-shop/juice-shop#628]
The themes currently provided through Bootswatch would need to be replaced with themes implemented through Angular Material.
Four themes are already provided by Angular Material as described [here](https://material.angular.io/guide/theming) along with guidelines to make a custom theme.

**Comment by bkimminich** [comment]
Theming is working with Material default mechanisms now. Multiple light and dark color schemes will be provided out of the box, currently `teal` and `brown` are available for testing.
