### ISSUE TITLE
Customer Loyalty Program

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#636]
_As a_ regular Juice Shop customer
_I want_ to earn bonus points in a loyalty progam
_so that_ I can get free swag or extra discounts on my orders.

---

_As an_ attacker of the Juice Shop
_I want_ to steal other peoples bonus points
_so that_ I can get free swag or extra discounts on my orders.

**Comment by aaryan01** [comment]
Hi @bkimminich,
What factors according to you would define customer loyalty?
According to me, there are 2 parameters which would define loyalty to Juice Shop:
1. Number of times a person has visited Juice Shop in a given time interval (the time factor)
2. What item that  person has purchased (the cost factor)

Ways to implement this:

**1st Way**
One way of awarding bonus points would be to award points depending on what a person has purchased, for example, 1 point for OWASP Juice Shop Mug, 2 points for OWASP Juice Shop Hoodie, etc.  These points then can then earn them discounts or free swag. The shortcoming of this way is that the number of times a customer visits Juice Shop won't be taken into account. The advantage is that it is not very difficult to implement right away, and the time factor can be taken into consideration after some point of time. 

**2nd Way**
Another way would be to track the order frequency of a customer, that is, how frequently a customer purchase something from juice shop. It's advantage is that it is a more accurate way to define a customer's loyalty. But there is an issue here, let's say person _X_ has purchased items 3 times in a month, and person _Y_ has purchased items over a span of one year. We'll have to take all this in account which seems complex to implement in the beginning.

Stealing bonus points from other users can be a challenge in itself and seems like a great idea! Would love to have your suggestions.
Thanks!

**Comment by aaryan01** [comment]
@bkimminich  @J12934  Any suggestions on how I should proceed?

**Comment by J12934** [comment]
The first suggestion sounds great 👍
The amount of bonus points could simply be determined by the price of the order / product.

The time factor would make the suggestion harder to use, especially for users who use JuiceShop during trainings which only last for a couple of hours days. Unless we also add a challenge in which you are able to change the time of the server 😂

**Comment by aaryan01** [comment]
I completely agree with you :smiley: 
I'll start working on the first suggestion right away then.
Thanks

**Comment by aaryan01** [comment]
Hi @bkimminich @J12934 
I have opened a PR for this issue. Kindly review.
The total bonus points for the user are not being stored yet (though they could be calculated by looping through each order) - I'll be working on it next. Do we want to display the total bonus points in the profile section?
Thanks :)

**Comment by jurrewolff** [comment]
Hello @aaryan01,

We're working on a school project and decided the customer loyalty program would be a suitable subject for us to work on. Now we see that you've been working on this as well. 

Our question right now: How far are you on the functional part (back-end, database, etc.) of the loyalty system? If you haven't started on this yet, we'd like to build this part of the system if that is okay with you?

When you don't feel comfortable with this or if you've made significant progress already: Is it possible for us to implement the challenge associated with the loyalty program?

**Comment by bkimminich** [comment]
Hi @jurrewolff, the Customer Loyalty Program is currently implemented in a very simple way where points are assigned to each product and you see the sum of those in a user's orders. Not much else going on at the moment, so as far as I am concerned you are free to build something on top of that. Posting your design/implementation ideas here would be nice before you start submitting PRs. Thanks!

**Comment by aaryan01** [comment]
Hey @jurrewolff ,
As @bkimminich  said, it is currently implemented in a very simple manner. You can discuss your ideas and possible modifications here.
Thanks!

**Comment by jurrewolff** [comment]
Hey @bkimminich, @aaryan01. Thanks for the quick reply. 

Currently we're designing a formula for the amount of points earned at checkout. We'll merge the contributions made by @aaryan01 with ours and build a back-end around it. 

After this is done we'll start on an associated challenge.

We will keep posting updates and questions here!

**Comment by bkimminich** [comment]
Hi @jurrewolff! Do you have anything to review already? Feel free to send rather a couple smaller PR than "saving" everything for a single huge one... 😉

**Comment by jurrewolff** [comment]
Hello @bkimminich. Thanks for checking in. We definitely have code for review. This week we will have time to work on it again and I'll try to form some smaller chunks to upload.

You should know that we don't have too much time for the project anymore so when code should be refined or improved, we might not be able to fully support that. Of course we will deliver a functional system (this is almost completed)!

**Comment by jurrewolff** [comment]
Hey @bkimminich. We have currently finished our version of the Customer Loyalty Program. Because of a lack of time due to school deadlines we haven't been able to find the opportunity to push small chunks intermittently and we're sorry for that. Since the project is now over and we have to focus on other subjects we can't do this in the future either. We still have a working version of the loyalty program though, and can be found at the fork on my account.

This, of course, is not really a professional way of contributing to an open-source project, but again because of school constraints this is all we will be able to do.

We still hope some of our code might be useful to the project, but if not the Juice-Shop has allowed us to learn a lot nonetheless and we want to thank you for that!

One thing we can still do is to create PR's for the branches our team has worked on. These branches each have a specific set of functionality. Some of them however are not quite "small chunks". But I suppose it's better than merging the entire fork.
