### ISSUE TITLE
SSRF Challenge

### ISSUE THREAD

**Issue by shoebpate1** [juice-shop/juice-shop#638]
Right now, Juice-shop is lacking a very essential vulnerability, i.e. Serve side request forgery. Juice-shop doesn't have functionality to include it yet.

Here’s the unordered top 5 features that are often prone to SSRF vulnerabilities:

1. Webhooks: look for services that make HTTP requests when certain events happen. In most webhook features, the end user can choose their own endpoint and hostname. Try to send HTTP requests to internal services.

2. PDF generators: try injecting <iframe>,"<img>", <base> or <script> elements or CSS url() functions pointing to internal services.

3. Document parsers: try to discover how the document is parsed. In case it’s an XML document, use the PDF generator approach. For all other documents, see if there’s a way to reference external resources and let the server make requests to an internal service.

4. Link expansion: kudos to Mark Litchfield(https://twitter.com/BugBountyHQ/status/868242771617792000) for uncovering a vulnerability in Twitter’s link expansion recently.

5. File uploads: instead of uploading a file, try sending a URL and see if it downloads the content of the URL. Here’s an example. (https://hackerone.com/reports/713)

@J12934 @wurstbrot @bkimminich Please suggest the one,that will be fit for juice-shop.

**Comment by mdulin2** [comment]
Also, could be could be request splitting on a specific API call. 

Here's a good article to reference it: https://www.rfk.id.au/blog/entry/security-bugs-ssrf-via-request-splitting/

**Comment by janmasarik** [comment]
So no SSRF chall? 😞
