### ISSUE TITLE
Frisby API Tests fail with HTTP 500 error

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#640]
API tests often run into `500` errors without any functional reason. Maybe the server dies during test execution. Can probably not be tracked back via Git history as Frisby tests were failing on Travis-CI for a long time already but did not break the build.

**Comment by bkimminich** [comment]
Except for ~25 all of the >160 failing API tests pass again when removing the following change: https://github.com/bkimminich/juice-shop/blob/develop/server.js#L123-L130

The `JSON.parse(req.body)` is the culprit here as it runs into a `SyntaxError: Unexpected token o in JSON at position 1` which indicates that we are trying to parse something that already is an `Object`.

@CaptainFreak, can you remember the reason for this change? If not, I'll remove it locally and see which e2e tests fail from doing so.

**Comment by bkimminich** [comment]
CC/ @J12934 @wurstbrot

**Comment by J12934** [comment]
If i remember correctly this was made to access the raw body instead of the body parsed by body parser.
This was required to implement the parameter pollution challenge.

> The JSON.parse(req.body) is the culprit here as it runs into a SyntaxError: Unexpected token o in JSON at position 1 which indicates that we are trying to parse something that already is an Object.

Mhhh this is weird that this apparently only happens in the api tests. Could this possibly something specific to frisby?

**Comment by bkimminich** [comment]
Maybe it's the way frisby sends its requests compared to how Angular does it? If Angular sends them stringified and frisby does not but sends plain JSON objects, that would explain the error only occuring during API testing. Just guessing, though, needs some actual fact checking...

**Comment by bkimminich** [comment]
I added `if (req.body !== Object(req.body))` to prevent parsing an already JSON object request. This is kind of costly for every request, so it should only serve as a workaround until the actual problem has been found.

**Comment by bkimminich** [comment]
With some crazy HTTP request comparison I found the culprit for the remaining failing file upload tests: https://github.com/vlucas/frisby/issues/493. With a workaround in place, there are now just two more tests failing which I `xit`'ed for now:

```
  xit('POST zip file with directory traversal payload', done => {
    file = path.resolve(__dirname, '../files/arbitraryFileWrite.zip')
    form = frisby.formData()
    form.append('file', fs.createReadStream(file))

    frisby.post(URL + '/file-upload', { headers: { 'Content-Type': form.getHeaders()['content-type'] }, body: form })
      .expect('status', 204)
      .done(done)
  })
```

@CaptainFreak @J12934 could you please check why this one is failing? The error occuring is

```
error opening file: Error: ENOENT: no such file or directory, open 'C:\tmp\arbitraryfilewrite.zip'

TypeError [ERR_INVALID_ARG_TYPE]: The "fd" argument must be of type number. Received type undefined

      18 |             console.log('error opening file: ' + err)
      19 |           }
    > 20 |           fs.write(fd, buffer, 0, buffer.length, null, function (err) {
         |              ^
      21 |             if (err) console.log('error opening file: ' + err)
      22 |             fs.close(fd, function () {
      23 |               fs.createReadStream('/tmp/' + filename)

      at routes/fileUpload.js:20:14
      at node_modules/graceful-fs/graceful-fs.js:241:16
```

---

Also this one fails from an empty `{ }` being returned:

```
  xit('GET own user id and email on who-am-i request', done => {
    frisby.post(REST_URL + '/user/login', {
      headers: jsonHeader,
      body: {
        email: 'bjoern.kimminich@googlemail.com',
        password: 'YmpvZXJuLmtpbW1pbmljaEBnb29nbGVtYWlsLmNvbQ=='
      }
    })
      .expect('status', 200)
      .then(({ json }) => frisby.get(REST_URL + '/user/whoami', { headers: { 'Authorization': 'Bearer ' + json.authentication.token } })
        .expect('status', 200)
        .expect('header', 'content-type', /application\/json/)
        .expect('jsonTypes', 'user', {
          id: Joi.number()
        })
        .expect('json', 'user', {
          email: 'bjoern.kimminich@googlemail.com'
        }))
      .done(done)
  })
```
