### ISSUE TITLE
Un-Solve challenges

### ISSUE THREAD

**Issue by hackern0v1c3** [juice-shop/juice-shop#641]
I inadvertently completed a challenge while working on another one.  Since I didn't know what I did to cause the challenge to be marked as solved I wanted to un-mark the challenge so I could complete it later deliberately.  I didn't want to reset my whole scroreboard.  It's a very low priority request obviously but might be a nice feature.  Thanks for the fantastic work that you've done!

**Comment by bkimminich** [comment]
Hi @hackern0v1c3! Can you please add which challenge you solved inadvertently? My preferred fix would be to try and make the challenge verification more specific to avoid accidental solves.

The only challenge I am aware of where this happens regularly is _Provoke an error that is not very gracefully handled_, because not everyone has their JS-console open all the time and might miss some failed backend calls.

**Comment by hackern0v1c3** [comment]
It was a couple of days ago and I have the memory of a gold fish but I'll describe what happened the best that I can.

I was just starting to go through the 1 star challenges in firefox.  I forget exactly which challenge I was working on.  I think maybe I was looking for the DOM XSS attack.  I was logged into a juiceshop user account that I had registered in firefox.  I opened chrome while still having juiceshop open in firefox and received a notification that I had accessed someone elses basket.

I'm sure whatever I did isn't something that going to cause most people any headache.  I just thought it might be good to be able to un-solve an item in case it was done by mistake or you wanted to show someone else how to complete it or something.  I wouldn't waste too much of your time on it.

**Comment by bkimminich** [comment]
Okay, got it. The _Basket Access_ challenge is also one that occasionally solves "on its own" ... I'll check if we can improve it's verification condition a bit: #644

Undoing challenges would probably be a very rarely used feature, and with the filtering and planned hide-solved-feature plus notification re-send in CTF mode, I think the Score Board might get too confusing when adding even more functionality.
