### ISSUE TITLE
Avoid accidental solves of Basket Access challenge

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#644]
As reported in https://github.com/bkimminich/juice-shop/issues/641#issuecomment-405579185 the _Access someone else's shopping basket_ challenge sometimes solves unintentionally.

The scenario(s) when this happens need to be identified and the solution verification has to be made more resistant against such accidental solves.

**Comment by d80ep08th** [comment]
May I take up this issue?

**Comment by bkimminich** [comment]
Of course you may!
