### ISSUE TITLE
Segfault on XML upload

### ISSUE THREAD

**Issue by JGillam** [juice-shop/juice-shop#658]
I'm getting a segfault running in a Docker container, Juice Shop 7.4.1.

This occurs whenever I submit a malformed XML file (e.g. such as a blank file or one with a syntax error in it).

```
Segmentation fault (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! juice-shop@7.4.1 start: `node app`
npm ERR! Exit status 139
npm ERR! 
npm ERR! Failed at the juice-shop@7.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/juicer/.npm/_logs/2018-07-26T09_36_04_021Z-debug.log
```

When I restart the container, the folder /home/juicer/.npm/ appears to be missing, so I'm not sure if there is a way to recover that debug log.

**Comment by bkimminich** [comment]
(Reoccurence of #449 and #610)

**Comment by JGillam** [comment]
One more piece of info in case it matters: I'm currently running the docker container inside a VirtualBox VM.

**Comment by bkimminich** [comment]
Could you please pull the `snapshot` image (`v7.5.0-SNAPSHOT`) and see if you still get this error there? Thanks & sorry for the inconvenience!

**Comment by JGillam** [comment]
No luck, something is still causing it to crash while running the snapshot.  I will have to follow up with additional detail later this weekend (it's been a busy week), but please don't close the issue yet.

**Comment by bkimminich** [comment]
For some weird reason this does not occur on native Win or Linux, at least not my Win10 machine or the Travis-CI build. This seems to only bother Docker.

Is there some way to tweak memory allocation? Maybe it's a bit too little for Docker container to "survive" 2 seconds of attempted XML Bomb parsing?

**Comment by bkimminich** [comment]
I'm building a new `snapshot` image which uses default `node` base image instead of `node-alpine`. Could you please check if it this solves the problem for you?

**Comment by bkimminich** [comment]
Just checked that this doesn't solve the segfault issues...

**Comment by bkimminich** [comment]
Expert question: Is there any way for the application to determine at runtime that it's running in a Docker container? I think disabling the XXE challenges (and grey out on Score Board with some note about Docker issue replacing the hover hint) is the safest way to address this for now.

**Comment by bkimminich** [comment]
Looking for a `.dockerenv` file sounds reasonably easy... (from https://stackoverflow.com/a/25518345)

**Comment by bkimminich** [comment]
Issue solved by disabling XXE challenges on Docker. The challenges are marked as _unavailable_ on the Score Board with a fixed `hint` stating the incompatibility with Docker independent of any configured hint settings.

PS: I really hate this change, but I see no alternative. It might even come in handy for some other Docker-unfriendly challenges (@CaptainFreak?) later for 8.x ...

**Comment by JGillam** [comment]
I concur - sorry I didn't get a chance to dig into this earlier.  When I get some spare cycles I'll run some more tests but I believe for now this option is better than crashing.

**Comment by eeeschwartz** [comment]
FWIW I'm able to execute the XML file upload on Docker for Mac `18.06.1-ce-mac73 (26764)` running juice-shop 7.4.1 release. No segfaults for me.

**Comment by eeeschwartz** [comment]
Spoke too soon. It seems to depend on the xml payload.

This crashes the app for me:

```
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE foo [<!ELEMENT foo ANY >
        <!ENTITY xxe SYSTEM "file:///etc/passwd" >]>
```

This does not 

```
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE foo [<!ELEMENT foo ANY >
        <!ENTITY xxe SYSTEM "file:///etc/passwd" >]>

<trades>
    <metadata>
        <name>Apple Juice</name>
        <trader>
            <foo>&xxe;</foo>
            <name>B. Kimminich</name>
        </trader>
        <units>1500</units>
        <price>106</price>
        <name>Lemon Juice</name>
        <trader>
            <name>B. Kimminich</name>
        </trader>
        <units>4500</units>
        <price>195</price>
    </metadata>
</trades>
```

**Comment by bkimminich** [comment]
7.4.1 still has XML. parsing enabled on Docker, so crashes can happen. Use 7.5.x to have the safety on for XXE in Docker / Heroku.
