### ISSUE TITLE
Standard init_linux.go:185 exec user process caused "exec format error"

### ISSUE THREAD

**Issue by guyenko** [juice-shop/juice-shop#663]
Steps taken:
Run docker pull bkimminich/juice-shop 
Run docker run --rm -p 3000:3000 bkimminich/juice-shop
**Results:**
Standard init_linux.go:185 exec user process caused "exec format error"

OS= Kali linux 
pip version= 18

**Attempted to run with docker-compose**
standard init_linux_go:185 exec user process caused "exec format error"
Error - Service 'owtf' failed to build: the command 'bin/sh -c apt-get -y update && apt-get clean' returned a non-zero code:1 

Any assistance will be greatly appreciated.

**Comment by bkimminich** [comment]
@guyenko, I've been asking my fabulous pentester-buddies from https://7ms.us/slack to try reproduce your problem.

Also I am wondering why the `owtf` service complains in your setup. Is this https://github.com/owtf/owtf or https://www.owasp.org/index.php/OWASP_OWTF or something completely different? Neither OWTF mentioned before has anything to do with the Juice Shop nor is either used by it...

**Comment by bkimminich** [comment]
I have confirmation by someone from 7MS channel who just ran `docker run --rm -p 3000:3000 bkimminich/juice-shop` on Kali 2018.2 and it worked out of the box.

So, unfortunately the issue must be somewhere on your end. Updating your OS and installing the latest Docker version, that is the best recommendation I can provide at this point.

**Comment by guyenko** [comment]
No worries. I am running the app in Heroku. Last week this was not launching and now it is.
