### ISSUE TITLE
Juice Shop themed wallpaper

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#706]
_As a_ fan of the OWASP Juice Shop
_I want_ a wallpaper for my PC
_and_ a wallpaper for my mobile phone/tablet
_so that_ I always feel warm and cozy when watching my screen.

Bonus: (Part of a) Wallpaper might be used as a cover image for Facebook and Twitter.

**Comment by renegadejade** [comment]
Image sizes based on devices I have access to - MacBook Pro and iPhone 8.
![juiceshopdark2880x1800](https://user-images.githubusercontent.com/5083989/47532528-99a4e680-d87e-11e8-959e-6a5bc0ebcff3.png)
![juiceshoplight2880x1800](https://user-images.githubusercontent.com/5083989/47532534-9c074080-d87e-11e8-8443-db674e8a9276.png)
![juiceshopdark750x1334](https://user-images.githubusercontent.com/5083989/47532539-9e699a80-d87e-11e8-8c69-165dca5ed02f.png)
![juiceshoplight750x1334](https://user-images.githubusercontent.com/5083989/47532552-a4f81200-d87e-11e8-9a2f-efb605aa057c.png)

**Comment by qwhiz** [comment]
How do you want this issue resolved?  Create a directory in project for wallpapers and submit pull request?  Post images in comments to this issue like above comment?

**Comment by qwhiz** [comment]
Here you go!


![facebook event](https://user-images.githubusercontent.com/16926914/48852595-92300a80-ed62-11e8-8e01-52985a73d8df.jpg)
![mobile](https://user-images.githubusercontent.com/16926914/48852603-952afb00-ed62-11e8-95a9-de1c9153ed0a.jpg)
![twitter](https://user-images.githubusercontent.com/16926914/48852609-98be8200-ed62-11e8-8436-4ef2f2305a0f.jpg)
![mobile-lg](https://user-images.githubusercontent.com/16926914/48852614-9b20dc00-ed62-11e8-8894-a1478d5e7cdc.jpg)
![hd desktop](https://user-images.githubusercontent.com/16926914/48852623-9d833600-ed62-11e8-8f48-3c92bd3d11bb.jpg)

**Comment by bkimminich** [comment]
Amazing work! Big thanks to your designers, @dmqpdx!
