### ISSUE TITLE
Install failing

### ISSUE THREAD

**Issue by h-gupta** [juice-shop/juice-shop#710]
Sys Details : Linux ubuntu 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Node Version 8.X

Tried 6.X version earlier but failed

Error logs::

npm install

> juice-shop@5.0.1 postinstall /home/cuckoo/juiceshop
> bower install && grunt minify && grunt docker

Illegal instruction (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 132
npm ERR! juice-shop@5.0.1 postinstall: `bower install && grunt minify && grunt docker`
npm ERR! Exit status 132
npm ERR! 
npm ERR! Failed at the juice-shop@5.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Debug log : 
[2018-10-04T10_54_51_215Z-debug.log](https://github.com/bkimminich/juice-shop/files/2446045/2018-10-04T10_54_51_215Z-debug.log)

**Comment by bkimminich** [comment]
v5.0.1 is a very old Juice Shop version. Any reason why you download that? Please get v7.5.1 and try again on Node 8 or higher. If it doesn't work, please reopen and post error log.

**Comment by h-gupta** [comment]
Ohh....didin't realise there was a more current version available ..was just following a blog post....Must be an old one ..Thanks working now
