### ISSUE TITLE
Improvements User Profile

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#729]
* [x] Customize `title`
* [x] Based on selected `application.theme`, read colors from `frontend` _or_ pick from a redundant color definition file
* [x] Actually display user avatar somewhere in the application (e.g. instead of FontAwesome user-icon in navbar)
* [x] Email should not be changable (might mess up several of the "Login as"-challenges when emails were changed before trying those)
* [x] Add Favicon
* [x] Change UI labels to imply that a Gravatar URL could be used instead of picture upload

**Comment by aaryan01** [comment]
@bkimminich I'd like to work on this issue but I'm not sure from where to import the image of all the users. For the OAuth users, we can get the image URL through an API call. Are we storing images of other users on server?
