### ISSUE TITLE
Username XSS Challenge

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#730]
Username in User Profile is susceptible to XSS. This could simply become a Stored XSS-challenge in totally insecure legacy code or could be made harder with e.g. having to beat a weak Whitelist Input-Validation.

## Possible Flow

1. You expect payload with `<script>` tag for this challenge and state so in the description.
2. Your RegEx blocks sending `<script>` directly.
3. If attacker sends `<scr ipt>` where the spaces are actually a Tabstop character...
4. ...your RegEx would let is pass...
5. ...and the Browsers might actually "repair" that into a valid XSS and show the alert
6. Similar to `localXssChallenge` the _effective_ payload is submitted back to the server and if it matches the expected payload, the challenge is marked solved

**Comment by supra08** [comment]
@bkimminich can I take up this issue or it is on the verge of completion?

**Comment by bkimminich** [comment]
It's not being worked on yet, at least not by me, so feel free to do it!

Please don't forget to check out the contributors guide before starting.

**Comment by supra08** [comment]
Alright @bkimminich :+1:

**Comment by supra08** [comment]
@bkimminich, continuing from the gitter chat, I was thinking of making a set of regex rules for validation. I was also planning on sanitizing script tags and onload keywords in case of html attack. But couldn't figure out where to start.

**Comment by bkimminich** [comment]
Challenges are defined in `challenges.yml` and are given a `key` by which they are referred to in the backend code. If you search for all occurences of `reflectedXssChallenge` in the code, you should get a good idea how challenges are included and verified for being solved.

**Comment by bkimminich** [comment]
Challenge is merged, undergone a little refactoring and test repairs and should go live with 8.4.0! Thanks, @supra08! Please send me your address via email and I'll make sure some stickers find their way to you! :+1:
