### ISSUE TITLE
Build of v8 fails on Raspberry Pi

### ISSUE THREAD

**Issue by battletux** [juice-shop/juice-shop#742]
Trying to update the Raspi docker image to v8 and I've come across an issue at the post install stage, I've only a very bad photo of the issue (sorry about that, was not able to do this over shh).

[Docker issue](https://imgur.com/a/qgvBlL1)

Any obvious pointers on where this is going wrong? my Dockerfile only contains changes to the base images used, arm32v7/node:10, for both stages of the build.

Thanks.

**Comment by bkimminich** [comment]
Hm, the error message does not reveal anything more than the `132` error code? That is really not a lot to work with... :disappointed:

**Comment by battletux** [comment]
Yeah, what would happen if I changed the max-old-space-size variable? It seems to be 8gig but is that disk or ram? If ram then that might be a cause for not enough memory?

**Comment by bkimminich** [comment]
It would make the compile process a lot slower, but that should be it...

**Comment by battletux** [comment]
@bkimminich Where can I find that variable? I've had a look around the frontend folder and at various files but I can not seem to find it.

**Comment by battletux** [comment]
Nevermind, found it.

**Comment by bkimminich** [comment]
Did it help?

**Comment by battletux** [comment]
@bkimminich nope, a whole new load of errors:

`../src/node_sqlite3.cc:54:5: note: in expansion of macro 'DEFINE_CONSTANT_INTEGER'
../src/macros.h:63:5: warning: 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at ../node_modules/nan/nan_maybe_43_inl.h:130) [-Wdeprecated-declarations]
../src/node_sqlite3.cc:54:5: note: in expansion of macro 'DEFINE_CONSTANT_INTEGER'
../src/macros.h:59:10: warning: 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at ../node_modules/nan/nan_maybe_43_inl.h:130) [-Wdeprecated-declarations]
../src/node_sqlite3.cc:55:5: note: in expansion of macro 'DEFINE_CONSTANT_INTEGER'
../src/macros.h:63:5: warning: 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at ../node_modules/nan/nan_maybe_43_inl.h:130) [-Wdeprecated-declarations]
../src/node_sqlite3.cc:55:5: note: in expansion of macro 'DEFINE_CONSTANT_INTEGER'
../src/macros.h:59:10: warning: 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at ../node_modules/nan/nan_maybe_43_inl.h:130) [-Wdeprecated-declarations]
../src/node_sqlite3.cc:56:5: note: in expansion of macro 'DEFINE_CONSTANT_INTEGER'
../src/macros.h:63:5: warning: 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at ../node_modules/nan/nan_maybe_43_inl.h:130) [-Wdeprecated-declarations]
../src/node_sqlite3.cc:56:5: note: in expansion of macro 'DEFINE_CONSTANT_INTEGER'
../src/macros.h:59:10: warning: 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at ../node_modules/nan/nan_maybe_43_inl.h:130) [-Wdeprecated-declarations]
../src/node_sqlite3.cc:57:5: note: in expansion of macro 'DEFINE_CONSTANT_INTEGER'
../src/macros.h:63:5: warning: 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at ../node_modules/nan/nan_maybe_43_inl.h:130) [-Wdeprecated-declarations]
../src/node_sqlite3.cc:57:5: note: in expansion of macro 'DEFINE_CONSTANT_INTEGER'
In file included from ../node_modules/nan/nan.h:51:0,
                 from ../src/database.h:10,
                 from ../src/node_sqlite3.cc:8:
../src/node_sqlite3.cc: At global scope:
/root/.node-gyp/10.13.0/include/node/node.h:574:3: fatal error: opening dependency file ./Release/.deps/Release/obj.target/node_sqlite3/src/node_sqlite3.o.d.raw: No such file or directory
   }
   ^
/root/.node-gyp/10.13.0/include/node/node.h:599:3: note: in expansion of macro 'NODE_MODULE_X'
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^
../src/node_sqlite3.cc:106:1: note: in expansion of macro 'NODE_MODULE'
compilation terminated.
make: *** [Release/obj.target/node_sqlite3/src/node_sqlite3.o] Error 1
node_sqlite3.target.mk:119: recipe for target 'Release/obj.target/node_sqlite3/src/node_sqlite3.o' failed
make: Leaving directory '/juice-shop/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.14.71-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/juice-shop/node_modules/sqlite3/lib/binding/node-v64-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/juice-shop/node_modules/sqlite3/lib/binding/node-v64-linux-arm" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /juice-shop/node_modules/sqlite3
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN acorn-jsx@5.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-13T20_33_02_860Z-debug.log
The command '/bin/sh -c npm install --production --unsafe-perm' returned a non-zero code: 1
`

**Comment by battletux** [comment]
Where is the debug log it mentions? I do not appear to have a .npm folder in /root. Is it in the container?

**Comment by battletux** [comment]
So I've tried again and dumped the terminal output to a file, the full output is here:

[Juice-shop_arm version 8 issues - PasteBin](https://pastebin.com/6bEbcJKC)

I set the max-old-space-size variable to 512 (so there was some headroom).\\Going over the output and it seems that it may be NPM dependencies causing the issues now.

**Comment by bkimminich** [comment]
It seems to fail finding a pre-built SQLite3 version for you and then fails at building one from source. The older images you have, did they download `sqlite3` and also `libxmljs` or did they build them successfully from source?

**Comment by battletux** [comment]
I'm going to totally jinx this but so far building with arm32v7/node:8 seems to be working, in that I've got to 

```
> juice-shop@8.0.1 postinstall /juice-shop
> cd frontend && npm install && cd .. && npm run build
```

So am hoping sqlite3 built fine. I *think* the issue is due to node-pre-gyp, node 10 and arm. Something about that combo is not working and I'm not sure what. Some google fu shows others with this issue.

Are there any issues that you can foresee with this on node 8 vs node 10?

**Comment by battletux** [comment]
Ah, I knew I would jinx it:

```
Step 12/15 : RUN addgroup juicer &&     adduser -D -G juicer juicer &&     chown -R juicer /juice-shop &&     chgrp -R 0 /juice-shop/ &&     chmod -R g=u /juice-shop/
 ---> Running in 1c20fd1235c4
Adding group `juicer' (GID 1001) ...
Done.
Option d is ambiguous (debug, disabled-login, disabled-password)
Option g is ambiguous (gecos, gid, group)
adduser [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--firstuid ID] [--lastuid ID] [--gecos GECOS] [--ingroup GROUP | --gid ID]
[--disabled-password] [--disabled-login] USER
   Add a normal user

adduser --system [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--gecos GECOS] [--group | --ingroup GROUP | --gid ID] [--disabled-password]
[--disabled-login] USER
   Add a system user

adduser --group [--gid ID] GROUP
addgroup [--gid ID] GROUP
   Add a user group

addgroup --system [--gid ID] GROUP
   Add a system group

adduser USER GROUP
   Add an existing user to an existing group

general options:
  --quiet | -q      don't give process information to stdout
  --force-badname   allow usernames which do not match the
                    NAME_REGEX configuration variable
  --help | -h       usage message
  --version | -v    version number and copyright
  --conf | -c FILE  use FILE as configuration file
```
So I need to sort the user creation bit and hopefully that will mean it will build...

**Comment by bkimminich** [comment]
I don't plan to abandon Node 8 any time soon. Not before it goes EOL or starts failing to build... 😉

**Comment by bkimminich** [comment]
@battletux, all good with your ARM-based image as long as you stick to Node 8? Can we close this issue?
Are there any manual steps you are making to build this that couldn't be automated? I'm not really good with Docker, but maybe we can make an automated build out of it in the long run?

**Comment by battletux** [comment]
Sorry, not had a chance to finish this yet.
