### ISSUE TITLE
reflected XSS not registering on score board

### ISSUE THREAD

**Issue by EMCain** [juice-shop/juice-shop#744]
Hello, 

I thought I successfully performed a reflected XSS attack by visiting the following URL: 

http://localhost:3000/#/search?q=%3Ciframe%20src%3D%22javascript:alert(%60xss%60)%22%3E

However, it is not showing up as completed on the score board. 

If this is not enough to complete the challenge, maybe a note could be added to the [book](https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part2/xss.html) about what does qualify. 

Thanks!

**Comment by bkimminich** [comment]
Hi! I just started my server and your link gives me exactly _the expected_ solved notification... Small hint: "Where does everything after `#` in any URL _never_ go?" ;-)
