### ISSUE TITLE
Server shut down after upload of pw secured zip in Complaint form

### ISSUE THREAD

**Issue by Cord-Friemel** [juice-shop/juice-shop#750]
if i try to upload a pw secured zip on the complain form the system throws several errors and shutdown i can reproduce this error which different zip archives.

i use the version juice-shop-8.0.2_node8_linux_x64 of the juice-shop

This are two of the zip files with throws the errors
[Plain Text.txtpw.zip](https://github.com/bkimminich/juice-shop/files/2607679/Plain.Text.txtpw.zip)
which contains ownly a txt file and uses the pw test

and
[42.zip](https://github.com/bkimminich/juice-shop/files/2607687/42.zip)
which contains a zip bomb with pw 42

message in Terminal:

> juice-shop@8.0.2 start /home/tux/Software/juice-shop_8.0.2
> node app

Detected Node.js version v8.10.0 (OK)
Configuration quiet validated (OK)

Server listening on port 3000

Solved challenge Score Board (Find the carefully hidden 'Score Board' page.)
Solved challenge Error Handling (Provoke an error that is not very gracefully handled.)
Solved challenge Login Admin (Log in with the administrator's user account.)
Solved challenge Login Jim (Log in with Jim's user account.)
Solved challenge Login Bender (Log in with Bender's user account.)
Solved challenge Password Strength (Log in with the administrator's user credentials without previously changing them or applying SQL Injection.)
Solved challenge Five-Star Feedback (Get rid of all 5-star customer feedback.)
Solved challenge Basket Access Tier 1 (View another user's shopping basket.)
Solved challenge Payback Time (Place an order that makes you rich.)
Solved challenge Confidential Document (Access a confidential document.)
Solved challenge Forgotten Sales Backup (Access a salesman's forgotten backup file.)
Solved challenge Admin Section (Access the administration section of the store.)
Solved challenge NoSQL Injection Tier 1 (Let the server sleep for some time. (It has done more than enough hard work for you))
Solved challenge Deprecated Interface (Use a deprecated B2B interface that was not properly shut down.)
Solved challenge Security Policy (Behave like any "white-hat" should.)
Solved challenge Christmas Special (Order the Christmas special offer of 2014.)
Solved challenge XSS Tier 0 (Perform a reflected XSS attack with <iframe src="javascript:alert(`xss`)">.)
Solved challenge XSS Tier 1 (Perform a DOM XSS attack with <iframe src="javascript:alert(`xss`)">.)
/home/tux/Software/juice-shop_8.0.2/uploads/complaints/Plain Text.txt
{ Error: ENOENT: no such file or directory, open 'uploads/complaints/Plain Text.txt'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'uploads/complaints/Plain Text.txt' }
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: invalid block type
    at InflateRaw.zlibOnError (zlib.js:153:15)

npm ERR! Linux 4.15.0-39-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! juice-shop@8.0.2 start: `node app`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the juice-shop@8.0.2 start script 'node app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the juice-shop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs juice-shop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls juice-shop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tux/Software/juice-shop_8.0.2/npm-debug.log

**Comment by Cord-Friemel** [comment]
i forget to attach the given debug file so
[npm-debug.log](https://github.com/bkimminich/juice-shop/files/2607722/npm-debug.log)

**Comment by bkimminich** [comment]
I tested on my Windows machine and it does not crash the process when I upload a pw-protected ZIP file. I also added an API test that does the same and will let you know how the (Linux) CI server behaves.

**Comment by bkimminich** [comment]
`Error: invalid block type` will be gone with version 8.1.0. If you want to test, please run `develop` branch or Docker tag `snapshot`.
