### ISSUE TITLE
Real-world path traversal challenge?

### ISSUE THREAD

**Issue by oleksiireshetnik** [juice-shop/juice-shop#767]
I saw that there some challenges for file retrieval exists already [[1]](https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/appendix/solutions.html#access-a-developers-forgotten-backup-file), [[2]](https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/appendix/solutions.html#access-a-salesmans-forgotten-backup-file), but this challenges are limited to .md files and are not a very obvious/real-world example from the architectural point of view. Is there challenge/functionality for arbitrary file retrieval (e.g. /etc/passwd), or do you plan to make one in near future?

**Comment by bkimminich** [comment]
There is also [\[3\]](https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/appendix/solutions.html#retrieve-the-content-of-cwindowssystemini-or-etcpasswd-from-the-server) but that's about it at the moment. We are lacking a "normal" path traversal vulnerability at the moment. We tried it some years back, but it messed with the `serve-index` module too much.

So, any ideas on a different way and a place to put path traversal into would be welcome!
