### ISSUE TITLE
Obfuscate tracking image names

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#768]
Currently the tracking image names are challenge-related, so they show up when searching for obvious keywords in the `main.js` file, somewhat allowing easy cheating by just opening them. Example:

Searching for `tokensale` in yields only two hits, one is the tracking image URL:
![image](https://user-images.githubusercontent.com/3531020/50345591-e7149b80-052f-11e9-9ad6-fc7d8662051a.png)

While obfuscating the folder name `tracking` and also the image names themselves, this would not be as obvious and easy any more. Affected are:
![image](https://user-images.githubusercontent.com/3531020/50345649-1d521b00-0530-11e9-8537-3e5943950d9c.png)

**Comment by rratliff** [comment]
I solved the token sale challenge by accessing the tracking image.

It would not have occurred to me to peruse the minified JS in order to figure out which angular component mapped to which route.
