### ISSUE TITLE
Pastebin-related challenges

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#770]
In the _Sensitive Data Exposure_ category there could be several challenges where data is to be harvested from PasteBin, simulating a typical developer mistake of exchanging data over that platform e.g. with external consultants off-site.

Multiple tiers would be possible, e.g.
* a very simple data leakage which is easy to find via keyword search and solved by reporting via _Contact Us_
* a key or similar secret leakage which is harder to find and required for solving another challenge

For extra realism, the data should of course be leaked on Pastebin from either an anonymous account or an account of an actual developer (i.e. my own or someone from the contributors list).

---

Kudos to @braimee for indirectly giving me this idea when recommending a Pastebin PRO-account and mentioning its alerting capabilities!

**Comment by supra08** [comment]
@bkimminich, can I take up this issue?

**Comment by bkimminich** [comment]
@supra08, did you check my remarks on #771 where there still is one fundamental change necessary to make that challenge work as expected? I'd be happier if you wrap that up instead of starting something different in parallel. Thanks!

As for the PasteBin challenges, of course feel free to put _your ideas_ into the comments to this issue at any time!

**Comment by supra08** [comment]
@bkimminich, for the implementation I was thinking of the first approach, i.e. simple data leakage. I have the following flow in my mind:
* The user is in the products page and is referred to a particular product in the challenge description.
* He finds a wierd word regading the fruit in the description and searches over the internet.
* He gets a pastebin related result. 
* The paste is actually a XML or JSON file consisting of some data related to that keyword, along with mistakenly entered user details, like password or stuff.
* It can be submitted in the Contact Us section and then we can check for the successful completion.
I agree that the flow is still straightforward, so I need a bit of help with that.

Besides, can you suggest a flow for the 2nd approach, if it is to implemented?
