### ISSUE TITLE
Basket Access Tier 2, doesn't trigger when manipulating quantity

### ISSUE THREAD

**Issue by rratliff** [juice-shop/juice-shop#773]
### Challenge: 
Basket Access Tier 2
Manipulate another user's basket.

### Steps to reproduce:

1. Log in using an account.
2. Update "bid" value in session storage to a valid basket id of a different user.
3. Click "Your basket"
4. Notice at this point it is actually the other user's basket.
5. Increment or decrement the quantity of one of the items using buttons in the UI.

### Expected:

I should trigger the "Basket Access tier 2" challenge.

### Actual:

Nothing happens... I was able to trigger this challenge using the POST action by doubling up the "BasketId" field in the json request, but definitely got stumped that modifying the quantity did not count.

**Comment by bkimminich** [comment]
Tier 2 assumes you do the manipulation in one step, if I'm not mistaken. Maybe the description needs to be a bit more specific. Have to check the implementation though and also update the ebook accordingly. Thanks for noticing!

**Comment by bkimminich** [comment]
Challenge will be rephrased with 8.3.0 release.
