### ISSUE TITLE
IsAdmin:1 Should work for challenge register admin user.

### ISSUE THREAD

**Issue by ardalis** [juice-shop/juice-shop#777]
If you register a user via /api/Users and add IsAdmin:true it works, but if you use IsAdmin:1 it still creates an admin user but it doesn't unlock the challenge.

**Comment by aaryan01** [comment]
I'd like to work on this.

**Comment by bkimminich** [comment]
This is already solved with #778, it just not closed yet.

**Comment by aaryan01** [comment]
Oh ok
