### ISSUE TITLE
Score-board status buttons don't work in firefox

### ISSUE THREAD

**Issue by Andrew-Stubbs** [juice-shop/juice-shop#778]
The buttons don't do anything when clicked, and the tooltips don't appear on hover for the status buttons:

![image](https://user-images.githubusercontent.com/11270059/50971257-78e24980-14db-11e9-9705-cfaf080e4d6c.png)

This is an [issue with firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=843003), [captured by the angular material](https://github.com/angular/material2/issues/6886) team with a workaround.

**Comment by bkimminich** [comment]
Wow, I wonder how this didn't get reported until now... Lot's of Chrome users (like myself...) out there probably... ;-) ... ... Thanks @Andrew-Stubbs for not only reporting but also fixing this! Please send me your address via email or Twitter DM and I'll send you our _1st-time-contributor-swag-pack_!
