### ISSUE TITLE
Misspelt language title - Hebrew

### ISSUE THREAD

**Issue by PeledEldan** [juice-shop/juice-shop#801]
The Hebrew title in the navigation bar is misspelt.

Now:
{ key: 'he_IL', icons: [ 'il' ], lang: 'עברי', isFlask: true }
![screen shot 2019-02-10 at 11 11 47](https://user-images.githubusercontent.com/7409721/52531871-f8567900-2d24-11e9-95ec-6917ce591ae2.png)

Should be:
{ key: 'he_IL', icons: [ 'il' ], lang: 'עברית', isFlask: true }
![screen shot 2019-02-10 at 11 10 31](https://user-images.githubusercontent.com/7409721/52531870-f1c80180-2d24-11e9-8c08-3f8541cfeebc.png)

**Comment by bkimminich** [comment]
Thanks! Will be fixed with next release!
