### ISSUE TITLE
Pwning OWASP Juice Shop documentation needs updating

### ISSUE THREAD

**Issue by jaybobo** [juice-shop/juice-shop#802]
In a meetup we held yesterday for new and intermediate developers, we had attendees follow the challenge guide hints and solutions listed here: https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/appendix/solutions.html

**Unfortunately, attendees were unable to locate the `main.js` file in their Chrome Dev Tools as noted in the solutions.** 

<img width="806" alt="screen shot 2019-02-10 at 12 04 34 pm" src="https://user-images.githubusercontent.com/5685984/52536700-0b207c00-2d2c-11e9-8b14-b25e4f81e85f.png">

**We had deployed v7.5.1 to Heroku and our attendees saw this file hierarchy under "Sources" instead.**

<img width="420" alt="screen shot 2019-02-10 at 12 06 04 pm" src="https://user-images.githubusercontent.com/5685984/52536740-8bdf7800-2d2c-11e9-895f-c75cffe94a3d.png">

Should we have some language that directs people to update their version? Or that the documentation only covers a specific version of JuiceShop.

Love what you folks are doing with JuiceShop. Keep up the good work!

**Comment by bkimminich** [comment]
Hi @jaybobo! The eBook's latest version is for the 8.x release of the Juice Shop, which is based on Angular, while the previous major version 7.x was still AngularJS. That's when the client-side JS file name changed from `juice-shop.min.js` into `main.js`.
