### ISSUE TITLE
XSS Tier 5 challenge description unclear/misleading

### ISSUE THREAD

**Issue by ZeddYu** [juice-shop/juice-shop#804]
I am playing shop's challs  recently. This is a chall I am more confused about. I haven't seen a question like this. According to the chall's description `Perform a *persisted* XSS attack with <iframe src="javascript:alert('xss')"> through an HTTP header.`, I think it is more likely perfrom a reflected xss through an HTTP header.

**Comment by bkimminich** [comment]
@CaptainFreak @J12934 What do you think we should do to improve the challenge description and hint?

**Comment by J12934** [comment]
Mhhh i think the client side implementation got lost in in the angular upgrade.

The challenge can still be solved if you know what you are supposed to to, but it is pretty much impossible to find.

**Comment by J12934** [comment]
**:godmode: Warning Spoilers:**


The challenge is about a `lastLoginIp` value which gets displayed back to the user to check that nobody else has logged in with their account. (The feature was initially added here: https://github.com/bkimminich/juice-shop/commit/6c48d9a0cd10889980c301dc199395ac6a7bb313#diff-b26e7266ea5838968bf3df2af0e1126a)

To fix this we should add the display back into the application. We should find a fitting place for it, it was previously displayed in the navbar, but that doesnt seem fitting for it anymore with the latest navbar tweeks.

**Comment by bkimminich** [comment]
How about the "Change Password" or "User Profile" screens? Where will 2FA setup be done later?

Am 21. Februar 2019 18:35:43 MEZ schrieb Jannik Hollenbach <notifications@github.com>:

**Comment by J12934** [comment]
I was thinking of adding something like a „Privacy and Security“ screen with a sidenav (like github settings) for the related setting like:
- change password
- 2FA
- request data export
- Access log

**Comment by ZeddYu** [comment]
Yes. When I am playing juice-shop, I find all the description in the pwning-juiceshop book that is not displayed in the juice-shop. For example, the chall [Log in with Amy's original user credentials](https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/appendix/solutions.html#log-in-with-amys-original-user-credentials) displayed in the pwning-juiceshop is attached with a picture. But I don't find the picture in the juice-shop. So I have to read the hints of this chall.

Maybe the picture is well-known. Just I don't know the picture. : )

**Comment by bkimminich** [comment]
Do you mean the picture of the character Amy from the Futurama TV show? That is not in the Juice Shop, true. It's part of the challenge to get the Futurama reference.

But actually we could add her picture to her profile page to make it a bit easier.

**Comment by ZeddYu** [comment]
@bkimminich Yes. I'm sorry for my bad expression. I suggest it is better to add some  description in the pwning-juiceshop to the juice-shop. It is more understandable.

**Comment by bkimminich** [comment]
Opened #867 to fix the missing client-side of _XSS Tier5_.
