### ISSUE TITLE
Owasp and Burp Suite

### ISSUE THREAD

**Issue by A1vinSmith** [juice-shop/juice-shop#807]
![screen shot 2019-02-14 at 2 24 12 pm](https://user-images.githubusercontent.com/24937594/52755941-93708b00-3064-11e9-8b7a-01eb574e6b9b.png)

Running juice-shop locally by npm start.
Using Firefox and FoxyProxy (also settled the firefox Network proxy).
Green one is working for Owasp only.
Blue and Red are working for Burp Suite only.

Zap 2.7.0 Burp Suite Community 1.7.35

Is the difference between them caused?

**Comment by bkimminich** [comment]
Can you please help me connect the dots between your question and the Juice Shop? 😉 Juice Shop doesn't do anything to purposefully block or hinder proxies, if that's what you're asking.

**Comment by A1vinSmith** [comment]
Good to know that, thank you.
