### ISSUE TITLE
JuicyRedditBot avatar

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#825]
Are you less artistically impaired than I am? Maybe you would consider contributing a more appropriate avatar for our friendly JuicyRedditBot? :robot: :heart:

![image](https://user-images.githubusercontent.com/3531020/53356662-2f837780-392c-11e9-9e82-52cbb8e7aa4c.png)

## Concept Ideas (not mandatory)
* It should look a bit more like a robot than my own cheap version of [Clippy](https://en.wikipedia.org/wiki/Office_Assistant) ... :grin:
* ...maybe by attaching robot arms/legs to the juice box and have it stand in the classic juice puddle...
* ...that could in some ([SFW](https://www.urbandictionary.com/define.php?term=SFW)) way "leak" out of the robot?

## Requirements (mandatory)
* It must somehow include the entirety of or recognizable parts of the original Juice Shop logo
* It cannot include any copyright-protected other logos (e.g. that of Reddit)

## Resources
All Juice Shop artwork is available at https://github.com/OWASP/owasp-swag/tree/master/projects/juice-shop for your convenience, logos even in `SVG` and `AI` format.

**Comment by aaryan01** [comment]
@bkimminich Can I make an attempt? I know design tickets were to be avoided but is this available? I apologise if it's not available I was just a little curious :sweat_smile: . Thanks !

**Comment by bkimminich** [comment]
This is more a "for fun" ticket anyway, so feel free! :+1:

**Comment by aaryan01** [comment]
![untitled](https://user-images.githubusercontent.com/31697449/53494334-83749480-3ac3-11e9-998f-8416d312def2.png)
@bkimminich I was trying to work on something along these lines. It's looking a little unusual right now 😅 but I'm working on it. Open to changes and suggestions from everyone out there!

**Comment by bkimminich** [comment]
> It's looking a little unusual right now

Yeah, slightly like a vacuum cleaner... :rofl:

**Comment by cookiemoon** [comment]
![JuiceShop_8bit_Logo](https://user-images.githubusercontent.com/43241956/54864653-0d75ed00-4d52-11e9-804b-5b87d8c0eac8.png)
