### ISSUE TITLE
Behave like any white hat should challenge not working

### ISSUE THREAD

**Issue by conniepocky** [juice-shop/juice-shop#827]
I went to http://localhost:3000/.well-known/security.txt/ but all it loaded was a  large picture of the juice shop logo. Can anyone help me?

**Comment by bkimminich** [comment]
On the demo instance it works just fine... http://juice-shop.herokuapp.com/.well-known/security.txt/ ... I'll verify on my own local machine later.

**Comment by bkimminich** [comment]
Just verified that http://localhost:3000/.well-known/security.txt/ also works for a locally started Juice Shop. Are you sure you did not have a typo or server-side error from some previous attack or anything?

**Comment by agrawalarpit14** [comment]
It works fine on my machine too.
