### ISSUE TITLE
Login error message not being displayed

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#830]
Probably since merging #826 the `/#/login` screen does not show its error message any more when logging in with invalid credentials.

**Comment by aaryan01** [comment]
@bkimminich  Are you referring to this particular error? 
![screenshot from 2019-02-28 16-38-09](https://user-images.githubusercontent.com/31697449/53562499-8c26a280-3b77-11e9-92d6-b4308028195a.png)

**Comment by bkimminich** [comment]
Exactly, that ones seems to have gone missing on `develop` branch, probably since #826 was merged.

**Comment by aaryan01** [comment]
@bkimminich Okay, I am looking into it :)

**Comment by J12934** [comment]
Whoops my bad.
Changed the data type of the error.
It was previously an obejct containing an property `error` which was a string. Changed it to only be a string by destructuring the object. Forgot to fix the template to relflect that change.



https://github.com/bkimminich/juice-shop/blob/549d6604bcd7c77ec4dbee24d95e79dde1ac23f7/frontend/src/app/login/login.component.html#L6

Should be changed to something like this:

```html
<div class="error" ngIf="error">{{error}}</div>
```

**Comment by aaryan01** [comment]
Hi @J12934 ! Will it be *ngIf or ngIf ? Shall I submit a PR for it or would you like to do so?
Thanks

**Comment by J12934** [comment]
Should be `*ngIf`, see https://angular.io/api/common/NgIf
Yup please submit a PR 👍
