### ISSUE TITLE
Privacy & Security screen

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#831]
Picking up the idea of @J12934 a new screen "Security & Privacy" might incorporate (or link to) features such as
* Change password
* 2FA setup
* Request data export (#660)
* Last login IP
* Privacy policy (#581)

**Comment by agrawalarpit14** [comment]
@bkimminich Can I take up the issue? I was thinking to make it in the manner that there will be a list on the left side of the screen(approx 20%) and selecting a particular section will show the options corresponding to it. I will soon share a screenshot of what I mean. Please let me know if you have something specific in mind.🙂

**Comment by bkimminich** [comment]
Can you please get in touch with @J12934 about this? I'm not sure if he might already started working on it or had some more specific ideas, as this came up while he implemented the 2FA challenge. Thanks!

**Comment by agrawalarpit14** [comment]
> Can you please get in touch with @J12934 about this? I'm not sure if he might already started working on it or had some more specific ideas, as this came up while he implemented the 2FA challenge. Thanks!

Yeah Sure. Thanks

**Comment by agrawalarpit14** [comment]
@J12934 Can I take up the issue if you haven't already started working on it?

**Comment by J12934** [comment]
Nope didn’t start working on it. Would be really nice if you would take this up.

Your plan sounds pretty similar to what I imagined 👌
Do you have a Plan how to do the sidenav responsivly so that it could also work nicely on mobile?

**Comment by agrawalarpit14** [comment]
Yeah, if it is opened on mobile a toggle switch appears on the corner, clicking which will lead to options appearing from side of the screen covering the whole screen, after clicking on an option, corresponding settings appear. About the toggle switch I think having it on right side of the screen will be a good idea?

**Comment by agrawalarpit14** [comment]
@bkimminich @J12934 Can you please let me know what exactly is needed to be added for the 2FA setup. I will work on this?

**Comment by J12934** [comment]
Hi Arpit
I'll implement this myself over the next couple of weeks.

**Comment by agrawalarpit14** [comment]
Yeah sure. Let me know if you want me to do something.
Thank You!!
