### ISSUE TITLE
User Profile Picture handling

### ISSUE THREAD

**Issue by agrawalarpit14** [juice-shop/juice-shop#833]
When a user uploads a profile picture, the profile picture stays in the frontend of the app. A malicious user can steal the profile pictures of the user by routing to the path localhost:3000/assets/public/images/uploads/2.jpg

An example can be seen here: https://juice-shop.herokuapp.com/assets/public/images/uploads/2.jpg
This is presently the profile pic of `jim@juice-sh.op`

**Comment by agrawalarpit14** [comment]
@bkimminich How about a challenge which asks us to obtain profile picture of a user in the above way. Although to find the name of the image the attacker needs to know the name which can be only obtained by decoding the JWT of the user of which the profile picture is asked for or otherwise try random_number.jpg. If this sounds good, I will think of a proper challenge and comment here?

**Comment by agrawalarpit14** [comment]
And also, the username field is vulnerable to script injection attack

**Comment by bkimminich** [comment]
I would not consider the user profile pictures a sensitive information worth stealing. They're kind of public - okay, they can be enumerated more easily then e.g. Twitter avatars, but I don't see this as a separate challenge really. Other opinions, @wurstbrot @J12934 @CaptainFreak?

PS: The username vulnerability is already a challenge.
