### ISSUE TITLE
Complete Captcha Bypass

### ISSUE THREAD

**Issue by ghost** [juice-shop/juice-shop#835]
Hey I think i successfully bypassed Captcha  .
I uses the same CaptchaID and its answer plus I did Bruteforce with different messages It seems to submit many forms successfully within seconds .

**Comment by bkimminich** [comment]
It actually is one to the hacking challenges to beat the CAPTCHA exactly that way... If you thought it's a bug, I'll close this issue right away, ok?

**Comment by ghost** [comment]
I ain't got any notification in browser if 
Challenge is completed 
You are really sure?

**Comment by bkimminich** [comment]
I am sure... 😀
![image](https://user-images.githubusercontent.com/3531020/53693159-c624be00-3d9c-11e9-9e15-1eb2fcfd73d3.png)
Are you sure you successfully made 10 feedback comments in 10 seconds?

**Comment by ghost** [comment]
You mean I am the first one one even to discover the issue
As I can see no one has yet tried it

**Comment by ghost** [comment]
I tried using Burp suite and I know that I didn't tried all 10 requests .

**Comment by bkimminich** [comment]
> You mean I am the first one one even to discover the issue

I'm pretty sure there is no "issue" with this challenge ... send 10+ feedback comments in 10 seconds and you'll get the challenge solved... 😉
