### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by Sasanrf** [juice-shop/juice-shop#843]
I remotely connected to a virtual machine (ubuntu 16), and I want to run Juice-shop there. Everything works well but when I want to run npm in the juice-shop folder, I have this error that I couldn't find a solution for that.
![image](https://user-images.githubusercontent.com/28947996/53990996-d5ec2b80-4129-11e9-99e0-74f8eaaf724c.png)

**Comment by agrawalarpit14** [comment]
@Sasanrf Did you try running `npm install` first.

**Comment by bkimminich** [comment]
Did you clone the repo, then try what @agrawalarpit14 said. Otherwise please let us know how you installed it. Thanks!

**Comment by Sasanrf** [comment]
@agrawalarpit14 Yes, I installed npm. I did everything step by step that is needed to run as the instruction:
![image](https://user-images.githubusercontent.com/28947996/54016381-fb595380-4182-11e9-926e-73ea21d89833.png)
@bkimminich  Yes I cloned it and also I tried to remove npm and install it again but I have the same problem.

**Comment by bkimminich** [comment]
Can you please attach the log of your entire `npm install` run? Optimally in a freshly cloned directory. On Linux Node.js is always a bit tricky. You could  try https://github.com/bkimminich/juice-shop/releases/download/v8.4.0/juice-shop-8.4.0_node11_linux_x64.tgz alternatively or switch to Docker.

**Comment by username1001** [comment]
I think your problem may have to do with your version of node, as well as the version of juice shop. You have `juice-shop@8.3.0` and it appears the newest version of `node@11.10.1`. I'm not too familiar with the project yet, but my current version of juice-shop is `8.4.0`, which wouldn't work with `node@11.x`, so I switched to `node@10.x` (I'm sure I downloaded the wrong link). 

`juice-shop@8.3.0` may be an earlier version, not compatable with your version of node. You can try downgrading your node version with the `nvm` package, or downloading juice-shop again at `8.4.0_node11`.

**Comment by Sasanrf** [comment]
@bkimminich This is the log file, I will try that file too Thanks.
[log.txt](https://github.com/bkimminich/juice-shop/files/2946118/log.txt)

@username1001 I think the problem is not the version, because I tried also the node@10.x

**Comment by bkimminich** [comment]
@username1001 All 8.x versions of Juice Shop work on node.js 10. X and 11.x

**Comment by bkimminich** [comment]
```
npm WARN lifecycle juice-shop@8.3.0~postinstall: cannot run in wd juice-shop@8.3.0 cd frontend && npm install && cd .. && npm run build (wd=/root/juice-shop)
```

That's the culprit. The frontend part of the installation just never happens.

**Comment by Sasanrf** [comment]
> ```
> npm WARN lifecycle juice-shop@8.3.0~postinstall: cannot run in wd juice-shop@8.3.0 cd frontend && npm install && cd .. && npm run build (wd=/root/juice-shop)
> ```
> That's the culprit. The frontend part of the installation just never happens.

How can I solve it?

**Comment by bkimminich** [comment]
I assume it's some folder permissions thing? Definitely not a bug in Juice Shop, though.

**Comment by Sasanrf** [comment]
> I assume it's some folder permissions thing? Definitely not a bug in Juice Shop, though.

Thank you

**Comment by bkimminich** [comment]
Fall back to a pre-packaged archive would be my recommendation if it's not solvable otherwise.

**Comment by Sasanrf** [comment]
> Fall back to a pre-packaged archive would be my recommendation if it's not solvable otherwise.

Thank you so much, with pre-packed archive is working now
