### ISSUE TITLE
Similiar "Zero Stars" challenge on /recycle

### ISSUE THREAD

**Issue by username1001** [juice-shop/juice-shop#844]
Within http://localhost:3000/#/recycle, you are able to bypass the disabled button, submitting large chunks of text, or nothing at all, beating the limits of the form. I didn't see this within the score board, maybe it's minor... thanks!

**Comment by bkimminich** [comment]
I think I'd rather fix this by enforcing the same limits on the database-side as on the client, because "Recycling" will be part of a new CAPTCHA bypass challenge soon. Another client-side validation bypass challenge would be a bit too similar to existing ones.
