### ISSUE TITLE
XSS Tier 1 "DOM XSS" not acknowledged as done

### ISSUE THREAD

**Issue by tomasmlcoch** [juice-shop/juice-shop#845]
Juice-shop version 8.3.0
The score board doesn't acknowledge not green tile is displayed even if I passed XSS Tier 1 "DOM XSS" challenge.

**Comment by bkimminich** [comment]
Did you get the green notification box telling you it was solved? Was it logged as solved on the server?

**Comment by tomasmlcoch** [comment]
No green notification box. I haven't checked the server side yet. I'll do
tomorrow.
Tomas

**Comment by bkimminich** [comment]
Please make sure you are using the correct payload listed on the Score Board. All tests indicate the challenge works fine.
