### ISSUE TITLE
Uncaught [object Object] thrown in frontend unit tests [$10]

### ISSUE THREAD

**Issue by bkimminich** [juice-shop/juice-shop#846]
The following problem appears frequently on Travis-CI (and only there - never locally) during build runs:

```
HeadlessChrome 72.0.3626 (Linux 0.0.0) ChangePasswordComponent should create FAILED
	Uncaught [object Object] thrown
HeadlessChrome 72.0.3626 (Linux 0.0.0) ChangePasswordComponent should create FAILED
	Uncaught [object Object] thrown
HeadlessChrome 72.0.3626 (Linux 0.0.0): Executed 104 of 312 (1 FAILED) (skipped 4) (0 secs / 44.073 secs)
HeadlessChrome 72.0.3626 (Linux 0.0.0) ChangePasswordComponent should create FAILED
	Uncaught [object Object] thrown
e 72.0.3626 (Linux 0.0.0): Executed 105 of 312 (1 FAILED) (skipped 4) (0 secs / 44.3 secs)
```

This occurs frequently but not always and happens seemingly randomly in all Node.js versions:
![image](https://user-images.githubusercontent.com/3531020/54035233-28c0f400-41b9-11e9-8fd2-748db7b41067.png)

Restarting the build several times will eventually yield one run where all jobs pass fine. So it is probably some kind of race condition or timeout...

Disabling the unit test of `ChangePasswordComponent` does not fix the issue, as it will simply appear on a different component later. It was not investigated yet if _all components_ have this problem or only a subset. Finding such a subset might help narrowing down the issue by understanding the similarities between those components.

**Comment by agrawalarpit14** [comment]
Hi @bkimminich I feel [this](https://stackoverflow.com/questions/48101519/karma-start-fails-headlesschrome-error-uncaught-object-object?rq=1) is likely to resolve the issue. I am trying the same, will let you know.

**Comment by bkimminich** [comment]
Go for it, mate! 👍

**Comment by bkimminich** [comment]
Issue resolved due to awesome Stackoverflow-skillz of @agrawalarpit14! Please request bounty via Bountysource.com and I'll approve it asap. Cheers! 🍾
