### ISSUE TITLE
Duplicate solves of the Error Handling Challenge

### ISSUE THREAD

**Issue by supra08** [juice-shop/juice-shop#856]
This usually happens when the server is restarted. A minor issue automatically triggers the Error handling challenge to solve and but due to some reason it is not marked as a solved challenge until later when the iteration stops.
![Screenshot from 2019-02-14 23-53-45](https://user-images.githubusercontent.com/30755453/54210707-022af200-4506-11e9-93f0-973358a5b395.png)

**Comment by bkimminich** [comment]
The _Score Board_ challenge is also sometimes solved 2-3 times when restarting the server.
