### ISSUE TITLE
Cookies not cleared after running e2e tests

### ISSUE THREAD

**Issue by supra08** [juice-shop/juice-shop#857]
Cookies not being removed after tests result in the challenges being automatically being solved on subsequent runs of the server.
Steps to reproduce:
* Run `npm run protractor` to run the e2e tests. Wait for it to end.
* As soon as the server is started again, most of the challenges are solved automatically and we need to restart the server after clearing the cookies.

A function could be included in `e2eTests.js` to delete all the cookies after the completion of the tests.

**Comment by bkimminich** [comment]
As running e2e test is a "developer only" use case, I do not think this really needs to be fixed. Either way it would mess with your ongoing challenge progress, either by deleting all or solving all, no?

**Comment by supra08** [comment]
Yes it will do, I missed that part. Would using different cookies just for testing purposes is a viable solution?

**Comment by bkimminich** [comment]
Having different behavior for test and prod usage is typically a recipe for sad evenings of debugging... 😁

**Comment by supra08** [comment]
Alright, so I guess it's better to leave it as it is. Should I close the issue?
