### ISSUE TITLE
User Profile icon a bit displaced from the svg

### ISSUE THREAD

**Issue by supra08** [juice-shop/juice-shop#863]
User profile icon is a bit displaced from the svg. This is particularly visible when we hover over the icon.
![Screenshot from 2019-03-14 11-15-25](https://user-images.githubusercontent.com/30755453/54342813-7038fb80-4663-11e9-848a-ee7e7eaf33ef.png)

**Comment by bkimminich** [comment]
You have no idea how long it took me to at least get it _this close_ to overlap with the underlying button... :rofl:

**Comment by bkimminich** [comment]
Should become obsolete once the `facelift` branch is merged back.
