### ISSUE TITLE
Increase number of listening ports in Juice-Shop

### ISSUE THREAD

**Issue by lorentinoooo** [juice-shop/juice-shop#866]
I really need to make some changes in the code for a competition. I need to put the code up in a single machine. I need to adapt the listening ports of the software in order to listen in different ports. For instance, if there are 5 participants, I need 5 different ports where every single player can be connected by using VPN or something like that. Could someone help me to do that modification? or can someone tell me if it is feasible making those changes? and how?

I already know that the app is only for using individually.

Thanks in advance.

**Comment by bkimminich** [comment]
You can just start the application multiple times on the same machine passing in a different port each time via the `PORT` environment variable, like `PORT=3001 npm start` and so forth.

**Comment by bkimminich** [comment]
From https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/appendix/trainers.html#classroom-hints here's how you could launch 10 instances as Docker containers with ports from `4010` to `4019`:

```
for i in {10..19}; do docker run -d -p 40$i:3000 bkimminich/juice-shop; done
```

**Comment by J3ntH4ck** [comment]
How can the juice-shop be opened in 127.0.01 ??
