### ISSUE TITLE
Can't find index.html

### ISSUE THREAD

**Issue by junathanadi** [juice-shop/juice-shop#868]
![Screenshot from 2019-03-15 10-53-15](https://user-images.githubusercontent.com/48578048/54407489-9e284980-4710-11e9-90df-26247c9e5795.png)

I didn't about this error. Can you help me to fix it?
So I got this error notification when I'm running npm start at my terminal.

(node:14046) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat 'frontend/dist/frontend/index.html'
    at Object.lstatSync (fs.js:861:3)
    at replacizeFileSync (/root/juice-shop/node_modules/replace/replace.js:135:22)
    at module.exports (/root/juice-shop/node_modules/replace/replace.js:76:17)
    at customizeTheme (/root/juice-shop/lib/startup/customizeApplication.js:39:3)
    at customizeApplication (/root/juice-shop/lib/startup/customizeApplication.js:13:5)
    at Object.exports.start (/root/juice-shop/server.js:316:48)
(node:14046) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14046) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2ttt Error: ENOENT: no such file or directory, stat '/root/juice-shop/frontend/dist/frontend/index.html'
info: Solved challenge Error Handling (Provoke an error that is not very gracefully handled.)
Error: ENOENT: no such file or directory, stat '/root/juice-shop/frontend/dist/frontend/index.html'
Error: ENOENT: no such file or directory, stat '/root/juice-shop/frontend/dist/frontend/index.html'

**Comment by supra08** [comment]
Check once to see if `index.html` is actually present in the `root/juice-shop/frontend/src` directory and is generated in the `dist/` directory while performing npm start. If not, maybe the repo is not properly cloned.

**Comment by bkimminich** [comment]
Did you clone the repo and run `npm install`? Are you on Linux and might have permission errors during install script (see #843)?

Without more specific information there's not much we could help you with.
