### ISSUE TITLE
Empty product review

### ISSUE THREAD

**Issue by aaryan01** [juice-shop/juice-shop#871]
User is allowed to submit an empty product review.
<img width="1440" alt="Screenshot 2019-03-17 at 5 48 47 PM" src="https://user-images.githubusercontent.com/31697449/54490572-f7dd6f00-48dc-11e9-9b89-5a9c9963ebfd.png">

Working on this. :)

**Comment by bkimminich** [comment]
Thanks for finding and fixing this!!!
