### ISSUE TITLE
Track Order doesn't show error if order doesn't exist

### ISSUE THREAD

**Issue by aaryan01** [juice-shop/juice-shop#872]
Track order allows for spaces to enable the track button
![Screenshot from 2019-03-17 20-38-19](https://user-images.githubusercontent.com/31697449/54493328-bc4e9f00-48f4-11e9-96c8-16dadddc460b.png)
Shows no error when order doesn't exist
![Screenshot from 2019-03-17 20-38-22](https://user-images.githubusercontent.com/31697449/54493330-be186280-48f4-11e9-8772-d564552db63a.png)

Working on it :+1:

**Comment by bkimminich** [comment]
_Track order_ actually is supposed to not properly validate the user input. It's part of one of the easiest challenges.
