### ISSUE TITLE
Doesn't show error when registering with existing email 

### ISSUE THREAD

**Issue by aaryan01** [juice-shop/juice-shop#879]
The error is logged in console but isn't displayed to the user when I try to register again with an email I registered with before.

![Screenshot from 2019-03-19 00-29-39](https://user-images.githubusercontent.com/31697449/54556409-d369bb80-49de-11e9-96f5-cecf326b36c0.png)

**Comment by bkimminich** [comment]
Oh, wow, I'm wondering why nobody noticed that for all those years! Thanks!!!
