### ISSUE TITLE
No error when 'password' value and 'repeat password' value are different

### ISSUE THREAD

**Issue by aaryan01** [juice-shop/juice-shop#882]
Hi! @bkimminich @J12934 
When I try to sign up, if I enter different values for Password and Repeat Password, it shows no error. Also, it signs me up with the password I enter in the 'Password' field. Is this a bug or a part of a challenge. I wasn't able to find any.
Thanks!

**Comment by bkimminich** [comment]
I'm not exactly sure, it might have been validated in the old UI and this check got lost? It's not really worth a challenge, I think. So we could just fix it and add the error.

**Comment by aaryan01** [comment]
Sure! I'll get to work :+1:  asap.

**Comment by bkimminich** [comment]
You can just make it client side validation, but please similar to other form validations, ok? Thanks! 👌

**Comment by aaryan01** [comment]
I'll keep that in mind :+1:

**Comment by bkimminich** [comment]
I checked implementation options today, and it seems there is nothing out of the box in Angular for this. Probably needs a custom `Validator` or some 3rd party directive that works with `FormControl` fields.

**Comment by aaryan01** [comment]
Hey @bkimminich !
I tried implementing something earlier too and wasn't able to find an optimal solution as well. I apologise for the delay, I got a little busy with the proposal. Thanks for your suggestions :smiley: , I'll start working on them.

**Comment by supra08** [comment]
Hi! @aaryan01, are you working on it presently? If not, I can take this issue up? @bkimminich

**Comment by aaryan01** [comment]
Hi @supra08 , go ahead, I am currently working on another issue so you can take this if you want.
Thanks

**Comment by bkimminich** [comment]
@supra08 I played with the registration a bit, and found a case when the equal check doesn't work as expected:
1. Type in `aaaaa` as password
2. Type in `aaaaa` as repeat password
3. _"Do not match" error vanishes when you hit the fifth `a` as expected_
4. Go back to password field and add a `b` to the password
5. _The error "Do not match" does **not** appear as would be expected._

**Comment by bkimminich** [comment]
We could either fix this or make it a :star: challenge asking "Register without repeating yourself." ... 😁

**Comment by supra08** [comment]
Aah!, I should have seen it coming, the validator is subscribing to `repeatPasswordControl` only, therefore the bug. The :star: challenge looks a cool idea for this :grin: .
