### ISSUE TITLE
Need buttons to toggle all-select in score-board

### ISSUE THREAD

**Issue by supra08** [juice-shop/juice-shop#883]
Currently, we have to select the relevant challenge categories one by one to view the challenges. The same applies to select the levels of the challenges. This makes it a cumbersome some task if the user needs to select a large number of options.
A button to toggle all select both for the categories and the levels would be helpful and make it more user-friendly.

**Comment by bkimminich** [comment]
That's a very good idea! 👍

**Comment by bkimminich** [comment]
### Requirements (from #883)
* Use an icon or translatable text on the button
* Do not implement as "flip all button states" but "deselect all" if over 50% are currently selected or "select all" if under 50% are currently selected.
* Make sure select state is correctly flipped for the button when normally selecting/deselecting depending on which of the above state is currently given
