### ISSUE TITLE
Deal of the Day Challenge

### ISSUE THREAD

**Issue by agrawalarpit14** [juice-shop/juice-shop#898]
The challenge includes addition of "Notification Bell" as a feature:
- There will be an admin API to post and delete notifications.
- The notifications will be stored in the database on server side.
- On the client side a bell lies in the navigation bar, clicking on which a user can see notifications posted by the admins of the shop(such as "Welcome to Juice Shop"). Example can be seen below:
<img width="502" alt="Screenshot 2019-03-26 at 9 36 19 AM" src="https://user-images.githubusercontent.com/35000671/54971055-c171b500-4faa-11e9-9b56-8137e890c4ca.png">

- Clicking on the bell will always show newest of the two notifications.

For the challenge:

- If a user checks the API response(for notifications), they will find out that actually many notification messages are returned by the server(of which the newest are shown by the notification bell).
- Reading through the messages the user will find out that juice shop came with an offer on the occasion of "International Carrot Day, ie. Thursday 4 April".
- Knowing which the user will go on the offer route. But, will be restricted by a forbidden error. 
- When the attacker modifies the clock, they will be able to see the offer.
- They can then buy the carrot juice at reduced price to solve the challenge. 
A very basic implementation of the challenge can be seen [here](https://drive.google.com/file/d/1Q4-PlKBNLZN8vpvv1Lk505XkC9gpCpJP/view?usp=sharing).
@bkimminich @J12934 @CaptainFreak
Please let me know your suggestions.
Thank You!!

**Comment by bkimminich** [comment]
I love the _International Carrot Day_ storyline... :carrot: ... That's just hilarious! :rabbit2:

Having something like an extra `Deals` table also makes sense. The support for deals should actually be implemented completely and not with a singular fake just for the carrot juice-based challenge. The table should have a `validFrom` and `validTo` column as well as a `discount`. Anything else?

The idea with the notification bell is also very nice but seems kind of unrelated or at least unnecessary. How about this instead: The frontend uses a filtered API call via `epilogue` to retrieve only the `Deals` which are valid today. Calling the API directly will give you all deals and then a clock change allows to actually order those ahead of/behind schedule?

Visualization should just happen on the frontend by having a little marker (with countdown maybe) in the row of the product(s) for which a deal is available and then in the product details overlay the countdown and maybe deal title could be displayed along with the discounted price.

Does that make sense?

**Comment by agrawalarpit14** [comment]
Yeah it sounds awesome this way. 

And maybe, we can then add a way for the users to click and upload pictures with the products on offers that they purchased "Saying that the juice shop will post these images on the Juice Shop wall" and build challenges around that too. As these images will be rendered on the frontend.

Presently, I will start working on the challenge by forming a separate table for `Deals` as you said?
Thank You!!😆

**Comment by bkimminich** [comment]
Don't you think now that GSoC applications are opened, this one would be a nice addition to your proposal there? 😉

**Comment by agrawalarpit14** [comment]
Yes, actually. I will add it there.😆
Thank You for your suggestion.

Just to clarify you meant it for the second comment right, `Deal of the day` should be outside my proposal?

**Comment by bkimminich** [comment]
I think both the Deal of the Day and the Photo Wall could well be in a proposal for the "Feature Pack" project! 👍👍

**Comment by agrawalarpit14** [comment]
> I think both the Deal of the Day and the Photo Wall could well be in a proposal for the "Feature Pack" project! 👍👍

Ahh that way. Sure that's an awesome idea.
I will add them to the proposal.
Thank You!!

**Comment by agrawalarpit14** [comment]
Hi @bkimminich If you feel implementing `notification bell` is a good idea. Should we open an issue for it?🙂

**Comment by bkimminich** [comment]
We're currently undergoing a major UI facelift and I would prefer to avoid new UI features for the time being. We can pick this up when facelift is over.

**Comment by bkimminich** [comment]
With special deal prices for deluxe members as well as the campaign offers I suppose another kind of deal would be a bit of overkill.
