### ISSUE TITLE
Cannot find module 'libxmljs' while connecting to localhost:3000

### ISSUE THREAD

**Issue by parulpriyedarshani** [juice-shop/juice-shop#900]
While running the localhost: 3000; the server site cannot be reached due to the missing module 'libxmljs'. Hence the cloned project is not opening on the localhost. I tried to solve this problem by running the command "npm install libxmljs" but still getting lots of errors and could not run the juice-shop project on my laptop.
 Looking forward for your help!

**Comment by bkimminich** [comment]
Can you paste your console output of `npm install` and `npm start` please? Also which versions of node.js and npm are you using?

**Comment by parulpriyedarshani** [comment]
For node it's 
v11.6.0
And for npm it is
6.9.0

**Comment by parulpriyedarshani** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/47082288/55019355-f5040d80-4fb1-11e9-82d4-2a82c70754ff.png)
![Screenshot (8)](https://user-images.githubusercontent.com/47082288/55019443-24b31580-4fb2-11e9-924c-2b738c460a30.png)

**Comment by bkimminich** [comment]
Your `npm install` already failed to install `libxmljs@0.19.5` unfortunately. Please try this zipped version. Just unpack and run `npm start` and it should work: https://github.com/bkimminich/juice-shop/releases/download/v8.4.1/juice-shop-8.4.1_node11_windows_x64.zip

**Comment by parulpriyedarshani** [comment]
Yes, Now it's working perfectly.
![Screenshot (9)](https://user-images.githubusercontent.com/47082288/55028792-d871d080-4fc5-11e9-8717-c22c80b091e3.png)
![Screenshot (10)](https://user-images.githubusercontent.com/47082288/55028802-dc9dee00-4fc5-11e9-8885-2d36c2cdd6b0.png)

Thank you so much, sir.

**Comment by parulpriyedarshani** [comment]
@bkimminich I couldn't find the src folder in the source code of the link mentioned above that is juice-shop_8.2.1 . Could you please tell me where is it located?

**Comment by bkimminich** [comment]
The ZIP distributables don't contain all the source code, only what is needed at runtime.

**Comment by parulpriyedarshani** [comment]
Okay. Thank you, sir.
