### ISSUE TITLE
Should signing up with a fake email domain be an error? 

### ISSUE THREAD

**Issue by allina606** [juice-shop/juice-shop#908]
I registered with the email "candy@gmail" which is not a valid email format, but was still able to be registered as a new user.

**Comment by bkimminich** [comment]
We're using an official validator baked into Angular, and it seems that one is not very good at its job. But as we are never actually sending any mails this is not really a problem. Couldn't be validated stronger on the backend as challenges rely on the fact we don't do that... 😁

```
public emailControl: FormControl = new FormControl('', [Validators.required, Validators.email])
```
