### ISSUE TITLE
Last Login IP Address IPv6 or IPv4

### ISSUE THREAD

**Issue by agrawalarpit14** [juice-shop/juice-shop#909]
Presently on `/#/privacy-security/last-login-ip` the adress is returned in IPv6 form. Is it a desirable thing?

**Comment by bkimminich** [comment]
Should be fixed now by stripping `ipv4` addresses of their static `::ffff:` prefix.

**Comment by agrawalarpit14** [comment]
Hi @bkimminich I was wondering, this might not work if the `loopback` address is returned, i.e, `::1`(when the user access the application by `http://localhost:3000/#/`)?

**Comment by bkimminich** [comment]
Thanks, @agrawalarpit14!

**Comment by agrawalarpit14** [comment]
> Thanks, @agrawalarpit14!

Your Welcome!!
