### ISSUE TITLE
Addition of Pre-Push Hook to test linting

### ISSUE THREAD

**Issue by supra08** [juice-shop/juice-shop#921]
Currently, the linting tests are performed after the pull request. On the occasion of failing these tests, new commits to fix linting are to be made.
This can be improved by the addition of a `pre-push hook` to test the linting before actually pushing. Failing it would suggest fixing the linting in the local.

**Comment by agrawalarpit14** [comment]
Hi @supra08 Presently `standard` for backend and `npm run lint` for frontend exist right? Did I not understand the issue properly?
Please let me know
Thank You!!

**Comment by supra08** [comment]
@agrawalarpit14, these tests are to be run manually. If someone forgets `npm run lint`, the push is still accepted, but later fails in Travis. I guess, it would be better if a hook is provided to prevent pushing without proper lint. 
Your views in this @bkimminich?

**Comment by bkimminich** [comment]
No hooks for me, thanks! I'd keep it running on Travis regardless just to be sure it _really_ ran once.

**Comment by bkimminich** [comment]
Also, I'm not even sure it wouldn't break, e.g. when I'm pushing from my phone which cannot run anything.
