### ISSUE TITLE
npm install failed in amazon ec2

### ISSUE THREAD

**Issue by mendickxiao** [juice-shop/juice-shop#929]
[root@lin-0aff6d83 ec2-user]# npm -v
6.4.1
[root@lin-0aff6d83 ec2-user]# node -v
v10.15.3
[root@lin-0aff6d83 ec2-user]# cd juice-shop/
[root@lin-0aff6d83 juice-shop]# npm install

> iltorb@1.3.10 install /home/ec2-user/juice-shop/node_modules/iltorb
> detect-libc prebuild-install || node-gyp rebuild

sh: detect-libc: command not found
sh: node-gyp: command not found

> libxmljs@0.19.5 install /home/ec2-user/juice-shop/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

sh: node-pre-gyp: command not found
npm WARN acorn-jsx@5.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sinon-chai@3.2.0 requires a peer of sinon@>=4.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iltorb@1.3.10 (node_modules/iltorb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iltorb@1.3.10 install: `detect-libc prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! libxmljs@0.19.5 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the libxmljs@0.19.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-09T07_58_26_442Z-debug.log

1127 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
1127 verbose stack     at ChildProcess.emit (events.js:189:13)
1127 verbose stack     at maybeClose (internal/child_process.js:970:16)
1127 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
1128 verbose pkgid libxmljs@0.19.5
1129 verbose cwd /home/ec2-user/juice-shop
1130 verbose Linux 4.14.88-72.73.amzn1.x86_64
1131 verbose argv "/root/.nvm/versions/node/v10.15.3/bin/node" "/root/.nvm/versions/node/v10.15.3/bin/npm" "install"
1132 verbose node v10.15.3
1133 verbose npm  v6.4.1
1134 error file sh
1135 error code ELIFECYCLE
1136 error errno ENOENT
1137 error syscall spawn
1138 error libxmljs@0.19.5 install: `node-pre-gyp install --fallback-to-build --loglevel http`
1138 error spawn ENOENT
1139 error Failed at the libxmljs@0.19.5 install script.
1139 error This is probably not a problem with npm. There is likely additional logging output above.
1140 verbose exit [ 1, true ]

**Comment by bkimminich** [comment]
The same problem with `libxmljs` currently occurs in our GitLab pipeline for the Gemnasium dependency checks. It does not occur on Travis-CI, AppVeyor, Docker or Heroku.

**Comment by bkimminich** [comment]
@mendickxiao, maybe you can use a Docker container on AWS as a workaround? Installation instructions for this are in the README.

**Comment by bkimminich** [comment]
On Travis-CI this is the installation part of `libxmljs` which successfully pull the latest binary:
```
> libxmljs@0.19.5 install /home/travis/build/bkimminich/juice-shop/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v64-linux-x64.tar.gz
node-pre-gyp http 200 https://github.com/libxmljs/libxmljs/releases/download/v0.19.5/node-v64-linux-x64.tar.gz
[libxmljs] Success: "/home/travis/build/bkimminich/juice-shop/node_modules/libxmljs/build/Release/xmljs.node" is installed via remote
```

**Comment by bkimminich** [comment]
It seems `libxmljs 0.19.5` is not available for Node.js 11.x and on GitLab it is subsequently unable to build from source due to missing Python installation. On Travis-CI this works fine for the Node.js 11.x job as Python seems to be installed there.

@mendickxiao, for you (on Node.js 10.x) the added direct dependency on `node-pre-gyp` might fix the issue. Please let me know if it works for you now!

**Comment by bkimminich** [comment]
Ticket for missing pre-built `libxmljs` for Node 11.x: https://github.com/libxmljs/libxmljs/issues/544
