### ISSUE TITLE
JavaScript Function Redefinition Challenge

### ISSUE THREAD

**Issue by agrawalarpit14** [juice-shop/juice-shop#931]
In the integration tests of #859 I wrote a script to redefine the javascript function for `Date`. Will it be useful to build a challenge around this which can be solved by modifying the functionality of a function in browser console which is expected to be used by the juice shop.

Example:

<img width="572" alt="Screenshot 2019-04-10 at 11 37 21 PM" src="https://user-images.githubusercontent.com/35000671/55902645-9a8dc280-5be9-11e9-9fec-456888e283bc.png">

@bkimminich @J12934 @CaptainFreak 
Please let me know of your views and suggestions.
Thank You!!

**Comment by J12934** [comment]
I don't see how this would be a security vuln in itself.

This would basically just be another case of putting too much trust in the client, like only validating inputs on the client.

The easier solution to abuse these vuln would be for an attacker to just send the tampered requests directly via curl than to mess with the client side javascript.

**Comment by agrawalarpit14** [comment]
> I don't see how this would be a security vuln in itself.
> 
> This would basically just be another case of putting too much trust in the client, like only validating inputs on the client.
> 
> The easier solution to abuse these vuln would be for an attacker to just send the tampered requests directly via curl than to mess with the client side javascript.

Yeah, I get it. I didn't think in this manner.
Now I think, I understand what kind of challenges would make sense.
Thank You!! for your feedback.
I will think more this time.😁😁😆😆
