### ISSUE TITLE
No captcha in data-export for the first time

### ISSUE THREAD

**Issue by supra08** [juice-shop/juice-shop#944]
When a newly registered user tries to export data, the captcha doesn't show up and he is able to export in the desired format without the captcha.

### Steps to reproduce:
* Register a new user.
* Click on `Request Data Export`.
* No captcha appears.

**Comment by bkimminich** [comment]
That's happening for all users and it's intentional. CAPTCHA is only appearing when the user demands another export <5min after the initial one.
